const fs=require('fs');
const file='src/data/packs/ai-product-management-llm-products-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));
const FF={LLM:'Large Language Model',RAG:'Retrieval-Augmented Generation',PRD:'Product Requirements Document',MVP:'Minimum Viable Product',UX:'User Experience',API:'Application Programming Interface',KPI:'Key Performance Indicator',ROI:'Return on Investment',SaaS:'Software as a Service',SDK:'Software Development Kit',NLP:'Natural Language Processing',RLHF:'Reinforcement Learning from Human Feedback',GDPR:'General Data Protection Regulation',SLA:'Service Level Agreement',SOC:'System and Organization Controls'};

const newItems=[];let id=data.length+1,added=0,skipped=0;

function add(t,pos,sm,sis,topic,stage,work,ex,ez,diff,tg,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  newItems.push({id:'ai-product-management-llm-products-1000-'+String(id).padStart(4,'0'),packId:'ai-product-management-llm-products-1000',term:t,type:type||'word',partOfSpeech:pos,topic,productStage:stage||'',workIntent:work||'',shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'workplace',difficulty:diff||2,sourceType:'ai_product_style_original',sourceTitle:'Original AI product management learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||['ai-pm'],fullForm:FF[t]||undefined});
  id++;added++;return true;
}

// ===== VERBS (35+) =====
add('prioritize','verb','排优先级','put in order','PRD / Requirement / Roadmap','requirement','plan','We need to prioritize the backlog based on user impact not just engineering effort.','我们需要根据用户影响而不仅仅是工程工作来 prioritize backlog。',2,['pm','verb']);
add('scope','verb','界定范围','define boundaries','AI Product Strategy / Use Case Discovery','discovery','define','We scoped the MVP down to a single use case so we can launch in six weeks.','我们把 MVP scope 到单个 use case 以便能在六周内发布。',2,['pm','verb']);
add('validate','verb','验证','check correctness','Evaluation / Quality / Benchmark','evaluation','verify','We need to validate the model output against a ground truth dataset before launching.','在发布之前我们需要对照 ground truth dataset 来 validate 模型输出。',2,['eval','verb']);
add('evaluate','verb','评估','assess quality','Evaluation / Quality / Benchmark','evaluation','measure','We evaluate every model update against a fixed set of 200 questions.','我们 evaluate 每次模型更新对照 200 个固定问题。',2,['eval','verb']);
add('iterate','verb','迭代','improve in cycles','PRD / Requirement / Roadmap','implementation','improve','Ship a simple version first and iterate based on real user feedback.','先发布一个简单版本然后基于真实用户反馈 iterate。',2,['pm','verb']);
add('deploy','verb','部署','push to production','Engineering Collaboration / Debugging','implementation','release','We deployed the new RAG pipeline behind a feature flag for five percent of users.','我们用 feature flag 向百分之五的用户 deploy 了新的 RAG pipeline。',3,['engineering','verb']);
add('compare','verb','对比','check against','Evaluation / Quality / Benchmark','evaluation','measure','We compared the new prompt against the old one and saw a twelve percent improvement in accuracy.','我们 compare 了新旧 prompt 准确率提高了百分之十二。',2,['eval','verb']);
add('benchmark','verb','基准测试','test against standard','Evaluation / Quality / Benchmark','evaluation','measure','We benchmark the model every week to make sure quality is not degrading.','我们每周 benchmark 模型以确保质量没有下降。',3,['eval','verb']);
add('rewrite','verb','重写','write again','Prompt / Context / Instruction Design','design','improve','The prompt needs to be rewritten because it is too long and the model ignores parts of it.','prompt 需要 rewrite 因为它太长了模型会忽略其中的一部分。',2,['prompt','verb']);
add('simplify','verb','简化','make simpler','UX / Conversation Design','design','improve','We simplified the onboarding flow from five steps to three and completion went up.','我们把 onboarding flow 从五步 simplify 到三步完成率上升了。',1,['ux','verb']);
add('detect','verb','检测','find automatically','Safety / Privacy / Compliance','implementation','prevent','The system should detect and block any prompt injection attempts in real time.','系统应该实时 detect 并阻止任何 prompt injection 尝试。',3,['safety','verb']);
add('filter','verb','过滤','remove unwanted','Safety / Privacy / Compliance','implementation','prevent','We filter out personally identifiable information from the chat logs automatically.','我们自动 filter 聊天记录中的个人身份信息。',2,['safety','verb']);
add('rank','verb','排名','order by relevance','RAG / Knowledge Base / Retrieval','implementation','improve','The retrieval step ranks documents by relevance and returns the top five.','retrieval 步骤按相关性 rank 文档并返回前五名。',2,['rag','verb']);
add('retrieve','verb','检索','fetch','RAG / Knowledge Base / Retrieval','implementation','get data','The system retrieves relevant documents before generating the answer.','系统在生成答案之前 retrieve 相关文档。',2,['rag','verb']);
add('generate','verb','生成','produce','LLM Basics / Model Capabilities','implementation','output','The model generates a response based on the retrieved documents and the user query.','模型基于检索到的文档和用户查询 generate 回复。',2,['llm','verb']);
add('cite','verb','引用','reference source','RAG / Knowledge Base / Retrieval','design','build trust','Every answer should cite the source document so users can verify the information.','每个答案都应该 cite source document 这样用户可以核实信息。',2,['rag','verb']);
add('moderate','verb','审核','review for safety','Safety / Privacy / Compliance','implementation','prevent','We moderate all user-generated content before it goes into the knowledge base.','在内容进入知识库之前我们 moderate 所有用户生成的内容。',3,['safety','verb']);
add('flag','verb','标记','mark for review','Safety / Privacy / Compliance','implementation','identify','The system flagged this response because it contains potentially harmful medical advice.','系统 flag 了这个回复因为它包含潜在有害的医疗建议。',2,['safety','verb']);
add('retry','verb','重试','try again','Engineering Collaboration / Debugging','implementation','handle errors','If the API call fails the system should retry up to three times before returning an error.','如果 API 调用失败系统应该 retry 最多三次再返回错误。',2,['engineering','verb']);
add('triage','verb','分流','sort by urgency','Agent / Workflow / Automation','implementation','automate','The agent triages incoming tickets and routes urgent ones to a human immediately.','agent triage 进来的工单并立即将紧急的 route 给人工。',3,['agent','verb']);
add('reduce','verb','降低','bring down','Pricing / Token Cost / Monetization','growth','optimize','We reduced the average token consumption per query by using shorter system prompts.','我们通过使用更短的 system prompt 来 reduce 每次查询的平均 token 消耗。',2,['cost','verb']);
add('improve','verb','改进','make better','Evaluation / Quality / Benchmark','evaluation','enhance','The RAG pipeline improved the factual accuracy from 82 percent to 94 percent.','RAG pipeline 把事实准确率从百分之八十二 improve 到百分之九十四。',2,['eval','verb']);
add('handoff','verb','移交','pass to human','Agent / Workflow / Automation','implementation','design','When the confidence score is below 0.7 the agent should handoff to a human agent.','当 confidence score 低于 0.7 时 agent 应该 handoff 给人工。',2,['agent','verb']);
add('activate','verb','激活','turn on','Launch / GTM / Customer Success','customer success','enable','We activate new enterprise accounts within one business day of signing the contract.','我们在签署合同后一个工作日内 activate 新企业账户。',1,['customer','verb']);
add('retain','verb','留存','keep','Data / Analytics / Product Metrics','growth','measure','Our goal is to retain at least sixty percent of free users after the first month.','我们的目标是在第一个月后 retain 至少百分之六十的免费用户。',2,['metrics','verb']);
add('collect','verb','收集','gather','User Research / Customer Feedback','discovery','learn','We collected feedback from fifty beta users before deciding on the next feature.','在决定下一个 feature 之前我们从五十位 beta 用户那里 collect 了反馈。',1,['research','verb']);
add('personalize','verb','个性化','tailor','UX / Conversation Design','implementation','improve','The assistant can personalize responses based on the user role and past conversations.','助手可以根据用户角色和历史对话 personalize 回复。',2,['ux','verb']);
add('classify','verb','分类','sort into groups','Agent / Workflow / Automation','implementation','automate','The triage model classifies incoming queries into urgent high medium and low priority.','triage 模型把 incoming query classify 为紧急高中低优先级。',2,['agent','verb']);
add('summarize','verb','总结','give summary','LLM Basics / Model Capabilities','implementation','output','The model can summarize a ten-page document into three bullet points.','模型可以把一份十页的文档 summarize 成三个要点。',2,['llm','verb']);
add('ground','verb','基于事实','base on source','RAG / Knowledge Base / Retrieval','design','build trust','Every response should be grounded in the retrieved documents not the model training data.','每个回复都应该 grounded 在检索到的文档中而不是模型的 training data。',3,['rag','verb']);
add('log','verb','记录','record','Engineering Collaboration / Debugging','implementation','debug','We log every failed query so we can review patterns and improve the system.','我们 log 每次失败的查询以便 review 模式并改进系统。',1,['engineering','verb']);
add('optimize','verb','优化','make faster','Engineering Collaboration / Debugging','implementation','improve','We optimized the embedding step and cut the latency by nearly half.','我们 optimize 了 embedding 步骤延迟几乎缩短了一半。',3,['engineering','verb']);
add('compare','verb','比较','check differences','Evaluation / Quality / Benchmark','evaluation','measure','Can you compare the output from model A and model B on the same eval set.','你能 compare 模型 A 和模型 B 在同一个 eval set 上的输出吗。',2,['eval','verb']);
add('approve','verb','批准','give OK','Safety / Privacy / Compliance','risk review','validate','Legal needs to approve the data processing terms before we can onboard EU customers.','法务需要 approve data processing terms 才能 onboard EU 客户。',2,['safety','verb']);
add('reject','verb','拒绝','turn down','Evaluation / Quality / Benchmark','evaluation','decide','The model should reject requests that fall outside its defined scope.','模型应该 reject 超出其定义范围的请求。',2,['safety','verb']);

// ===== PHRASAL VERBS (15+) =====
add('roll out','phrasal_verb','推出','release','Launch / GTM / Customer Success','launch','release','We plan to roll out the new model to all users by the end of the month.','我们计划在月底前向所有用户 roll out 新模型。',2,['launch','phrasal_verb'],'phrase');
add('scale up','phrasal_verb','扩容','grow capacity','Engineering Collaboration / Debugging','growth','expand','We need to scale up the inference infrastructure before the holiday traffic hits.','在假日流量到来之前我们需要 scale up 推理基础设施。',3,['engineering','phrasal_verb'],'phrase');
add('hand off','phrasal_verb','移交','pass to','Agent / Workflow / Automation','implementation','design','The agent should hand off complex queries to a human when confidence is low.','当 confidence 低时 agent 应该 hand off complex queries 给人工。',2,['agent','phrasal_verb'],'phrase');
add('fall back','phrasal_verb','回退','use backup','Agent / Workflow / Automation','implementation','design','If the retrieval returns nothing relevant the system should fall back to a predefined answer.','如果检索没有返回相关内容系统应该 fall back 到预定义的答案。',2,['agent','phrasal_verb'],'phrase');
add('follow up','phrasal_verb','跟进','check back','Launch / GTM / Customer Success','customer success','engage','We follow up with every enterprise trial user after the first week.','我们在第一周后 follow up 每个企业试用用户。',1,['customer','phrasal_verb'],'phrase');
add('phase out','phrasal_verb','逐步淘汰','gradually remove','Launch / GTM / Customer Success','launch','manage','We will phase out the old API version over six months with migration support.','我们将在六个月内 phase out 旧版 API 并提供迁移支持。',3,['launch','phrasal_verb'],'phrase');
add('break down','phrasal_verb','分解','split into parts','Agent / Workflow / Automation','design','design','The workflow breaks down a complex task into smaller steps the agent can handle.','workflow 把复杂任务 break down 成 agent 可以处理的小步骤。',2,['agent','phrasal_verb'],'phrase');
add('try out','phrasal_verb','试用','test','User Research / Customer Feedback','discovery','learn','We should try out the new prompt with a small group of users before the full rollout.','在全面 rollout 之前我们应该用一小群用户 try out 新的 prompt。',1,['research','phrasal_verb'],'phrase');
add('cut down','phrasal_verb','削减','reduce','Pricing / Token Cost / Monetization','growth','optimize','We cut down the average token count per query by shortening the system prompt.','我们通过缩短 system prompt 来 cut down 每次查询的平均 token 数。',2,['cost','phrasal_verb'],'phrase');
add('speed up','phrasal_verb','加速','make faster','Engineering Collaboration / Debugging','implementation','improve','We sped up the retrieval step by switching to a smaller faster embedding model.','我们通过切换到更小更快的 embedding model 来 speed up retrieval 步骤。',2,['engineering','phrasal_verb'],'phrase');
add('sign up','phrasal_verb','注册','register','Launch / GTM / Customer Success','launch','acquire','We had over 500 users sign up for the beta within the first 48 hours.','在头 48 小时内超过 500 个用户 sign up 了 beta。',1,['launch','phrasal_verb'],'phrase');
add('opt in','phrasal_verb','选择加入','choose to participate','Safety / Privacy / Compliance','implementation','comply','Users must opt in before we can use their conversation data for model training.','用户必须 opt in 我们才能使用他们的对话数据进行模型训练。',2,['safety','phrasal_verb'],'phrase');
add('opt out','phrasal_verb','选择退出','choose not','Safety / Privacy / Compliance','implementation','comply','Users can opt out of data collection at any time from their account settings.','用户可以随时从账户设置中 opt out 数据收集。',1,['safety','phrasal_verb'],'phrase');
add('route to','phrasal_verb','路由到','send to','Agent / Workflow / Automation','implementation','automate','The agent routes billing questions to the finance team and tech questions to engineering.','agent route billing question 给财务团队将 tech question route 给工程团队。',2,['agent','phrasal_verb'],'phrase');
add('slow down','phrasal_verb','减慢','become slower','Engineering Collaboration / Debugging','implementation','diagnose','The retrieval step slows down significantly when the knowledge base has more than 10000 documents.','当知识库有超过 10000 个文档时 retrieval 步骤会 significantly slow down。',2,['engineering','phrasal_verb'],'phrase');
add('test with','phrasal_verb','用……测试','try using','User Research / Customer Feedback','discovery','learn','We tested the new flow with five enterprise customers before making it the default.','在将其设为默认之前我们与五家企业客户 test with 了新流程。',1,['research','phrasal_verb'],'phrase');
add('track down','phrasal_verb','追查','find root cause','Engineering Collaboration / Debugging','implementation','debug','We need to track down why the hallucination rate spiked after the last model update.','我们需要 track down 为什么 hallucination rate 在上次模型更新后飙升了。',2,['engineering','phrasal_verb'],'phrase');

// ===== ADJECTIVES (25+) =====
add('actionable','adjective','可执行的','can be acted on','Data / Analytics / Product Metrics','growth','measure','The metric is only useful if it is actionable meaning the team can do something to improve it.','这个指标只有在 actionable 时才有用意味着团队可以采取具体行动来改善它。',2,['metrics','adjective']);
add('measurable','adjective','可衡量的','can be measured','Data / Analytics / Product Metrics','growth','measure','We need a measurable success metric not just a vague feeling that the model is better.','我们需要一个 measurable success metric 而不仅仅是模型更好的模糊感觉。',2,['metrics','adjective']);
add('unreliable','adjective','不可靠的','not dependable','Evaluation / Quality / Benchmark','evaluation','identify','The output is unreliable when the input contains tables or long numerical data.','当输入包含表格或长数字数据时输出是 unreliable 的。',2,['quality','adjective']);
add('scalable','adjective','可扩展的','can grow','AI Product Strategy / Use Case Discovery','design','plan','The architecture needs to be scalable to thousands of queries per minute without a cost spike.','架构需要 scalable 到每分钟数千次查询而不会出现成本飙升。',2,['strategy','adjective']);
add('risky','adjective','有风险的','dangerous','Safety / Privacy / Compliance','risk review','assess','Launching without a fallback response is too risky for a customer-facing product.','没有 fallback response 就发布对 customer-facing 产品来说太 risky 了。',2,['safety','adjective']);
add('unclear','adjective','不清楚的','not clear','UX / Conversation Design','design','identify','The error message is unclear and does not tell the user what to do next.','错误消息 unclear 没有告诉用户接下来该做什么。',1,['ux','adjective']);
add('ambiguous','adjective','模糊的','open to interpretation','Prompt / Context / Instruction Design','design','identify','The prompt is too ambiguous and the model keeps interpreting the same input differently.','prompt 太 ambiguous 了模型一直对相同的输入做出不同的解释。',2,['prompt','adjective']);
add('irrelevant','adjective','不相关的','not related','RAG / Knowledge Base / Retrieval','evaluation','identify','The retrieval returned several irrelevant documents that had the keyword but missed the context.','检索返回了几个 irrelevant 文档有关键词但没有上下文。',2,['rag','adjective']);
add('inaccurate','adjective','不准确的','wrong','Evaluation / Quality / Benchmark','evaluation','identify','The summary was inaccurate and missed two key points from the original document.','总结 inaccurate 并且遗漏了原始文档中的两个关键点。',2,['quality','adjective']);
add('customer-facing','adjective','面向客户的','seen by users','UX / Conversation Design','design','plan','Every customer-facing response should be reviewed for tone and accuracy before launch.','每个 customer-facing 回复都应该在发布前审查语气和准确性。',2,['ux','adjective']);
add('enterprise-ready','adjective','企业就绪的','ready for business','Launch / GTM / Customer Success','enterprise deployment','assess','The feature is not enterprise-ready because it lacks role-based access control.','这个功能不是 enterprise-ready 因为它缺乏基于角色的访问控制。',2,['launch','adjective']);
add('cost-effective','adjective','划算的','good value for money','Pricing / Token Cost / Monetization','growth','optimize','Using a smaller model for simple queries is more cost-effective than running everything through the large model.','对简单查询使用较小的模型比把所有东西都通过大模型运行更 cost-effective。',2,['cost','adjective']);
add('low-latency','adjective','低延迟的','fast response','Engineering Collaboration / Debugging','implementation','measure','The system needs a low-latency retrieval step because users expect answers in under two seconds.','系统需要一个 low-latency retrieval 步骤因为用户期望在两秒内得到答案。',3,['engineering','adjective']);
add('context-aware','adjective','上下文感知的','understands context','UX / Conversation Design','design','plan','The assistant should be context-aware and remember what the user said earlier in the conversation.','助手应该是 context-aware 的记住用户在对话前面说过的话。',2,['ux','adjective']);
add('source-backed','adjective','有来源支撑的','has citations','RAG / Knowledge Base / Retrieval','design','plan','Every answer must be source-backed so users can verify the information themselves.','每个答案都必须 source-backed 这样用户可以自己核实信息。',2,['rag','adjective']);
add('hard to measure','adjective','难以衡量的','difficult to quantify','Data / Analytics / Product Metrics','evaluation','identify','User satisfaction is hard to measure without a structured feedback mechanism.','没有结构化的反馈机制用户满意度是 hard to measure 的。',2,['metrics','adjective'],'phrase');
add('ready for beta','adjective','准备好测试了','beta-ready','Launch / GTM / Customer Success','launch','assess','The core flow is stable and we are ready for beta with fifty external testers.','核心流程稳定我们已经 ready for beta 有五十个外部测试者。',1,['launch','adjective'],'phrase');
add('safe to launch','adjective','可以安全发布','ok to release','Safety / Privacy / Compliance','risk review','assess','The legal review is done and the feature is safe to launch in the EU market.','法律审查已完成该功能 safe to launch 在欧盟市场。',2,['safety','adjective'],'phrase');
add('easy to test','adjective','易于测试','simple to verify','Evaluation / Quality / Benchmark','evaluation','plan','The eval set makes the model easy to test because every question has a known correct answer.','eval set 使模型 easy to test 因为每个问题都有已知的正确答案。',1,['eval','adjective'],'phrase');
add('privacy-safe','adjective','隐私安全的','protects data','Safety / Privacy / Compliance','implementation','plan','All analytics must be privacy-safe and not expose individual user conversations.','所有分析必须 privacy-safe 且不暴露单个用户的对话。',2,['safety','adjective']);
add('high-confidence','adjective','高置信度的','very sure','Evaluation / Quality / Benchmark','evaluation','measure','Only high-confidence responses should be shown directly without a confidence warning.','只有 high-confidence 回复才应直接显示而不带置信度警告。',2,['quality','adjective']);
add('low-confidence','adjective','低置信度的','not sure','Evaluation / Quality / Benchmark','evaluation','measure','Low-confidence responses should include a disclaimer that the answer may not be accurate.','low-confidence 回复应包含答案可能不准确的免责声明。',2,['quality','adjective']);

// ===== COLLOCATIONS (25+) =====
add('prioritize the use case','collocation','对用例排优先级','rank use cases','AI Product Strategy / Use Case Discovery','discovery','plan','We need to prioritize the use case based on user demand and technical feasibility.','我们需要根据用户需求和技术可行性来 prioritize the use case。',2,['strategy','collocation'],'phrase');
add('scope the MVP','collocation','界定 MVP 范围','define minimum','AI Product Strategy / Use Case Discovery','discovery','define','We scoped the MVP to a single knowledge base and a chat interface.','我们把 scope the MVP 限定为一个知识库和一个聊天界面。',2,['strategy','collocation'],'phrase');
add('define success metrics','collocation','定义成功指标','set KPIs','Data / Analytics / Product Metrics','requirement','measure','We need to define success metrics before we start building anything.','在我们开始构建任何东西之前需要 define success metrics。',2,['metrics','collocation'],'phrase');
add('validate the workflow','collocation','验证工作流','test flow','Agent / Workflow / Automation','evaluation','verify','We validated the workflow with internal users before rolling it out to customers.','在向客户推出之前我们用内部用户 validate the workflow。',2,['agent','collocation'],'phrase');
add('measure response quality','collocation','衡量回复质量','assess output','Evaluation / Quality / Benchmark','evaluation','measure','We measure response quality across five dimensions including accuracy tone and completeness.','我们跨越五个维度 measure response quality 包括准确性语气和完整度。',2,['quality','collocation'],'phrase');
add('track user feedback','collocation','追踪用户反馈','follow opinions','User Research / Customer Feedback','growth','learn','We track user feedback through in-app ratings and weekly surveys.','我们通过应用内评分和每周调查来 track user feedback。',1,['research','collocation'],'phrase');
add('review model output','collocation','审查模型输出','check responses','Evaluation / Quality / Benchmark','evaluation','verify','We review model output on a random sample of 100 queries every week.','我们每周 review model output 随机抽样 100 个查询。',2,['quality','collocation'],'phrase');
add('reduce hallucination','collocation','减少幻觉','lower false output','RAG / Knowledge Base / Retrieval','evaluation','improve','Adding RAG reduced hallucination from eight percent to under two percent.','添加 RAG 把 hallucination 从百分之八 reduce 到百分之二以下。',3,['rag','collocation'],'phrase');
add('improve retrieval quality','collocation','提高检索质量','better search','RAG / Knowledge Base / Retrieval','evaluation','improve','We improved retrieval quality by switching to a hybrid search approach.','我们通过切换到混合搜索方法来 improve retrieval quality。',3,['rag','collocation'],'phrase');
add('cite the source document','collocation','引用源文档','reference source','RAG / Knowledge Base / Retrieval','design','plan','Every answer should cite the source document so users can verify the information.','每个答案都应该 cite the source document 这样用户可以核实信息。',2,['rag','collocation'],'phrase');
add('add a fallback response','collocation','添加兜底回复','create backup','UX / Conversation Design','design','plan','We added a fallback response for when the model cannot find relevant information.','当模型找不到相关信息时我们 add a fallback response。',2,['ux','collocation'],'phrase');
add('handoff to a human','collocation','移交人工','pass to person','Agent / Workflow / Automation','design','plan','The workflow should handoff to a human when the confidence score drops below threshold.','当 confidence score 低于阈值时 workflow 应该 handoff to a human。',2,['agent','collocation'],'phrase');
add('monitor token cost','collocation','监控 token 成本','track spending','Pricing / Token Cost / Monetization','growth','measure','We monitor token cost per user daily and alert if anyone exceeds the fair-use limit.','我们每天 monitor token cost 每个用户如果有人超过 fair-use limit 就 alert。',2,['cost','collocation'],'phrase');
add('test with real users','collocation','用真实用户测试','user test','User Research / Customer Feedback','discovery','learn','We tested with real users and found that the onboarding flow was confusing.','我们 test with real users 发现 onboarding flow 令人困惑。',1,['research','collocation'],'phrase');
add('segment power users','collocation','分群重度用户','group heavy users','Data / Analytics / Product Metrics','growth','analyse','We segment power users who send over fifty queries per day for special pricing.','我们把每天发送超过五十次查询的 power user segment 出来给特殊定价。',2,['metrics','collocation'],'phrase');
add('launch the beta','collocation','发布测试版','release beta','Launch / GTM / Customer Success','launch','release','We plan to launch the beta with 100 invited users next Monday.','我们计划下周一 launch the beta 邀请 100 个用户。',1,['launch','collocation'],'phrase');
add('collect user feedback','collocation','收集用户反馈','gather opinions','User Research / Customer Feedback','discovery','learn','We collected user feedback through a post-conversation rating prompt.','我们通过对话后的评分提示 collect user feedback。',1,['research','collocation'],'phrase');
add('compare model performance','collocation','比较模型表现','benchmark models','Evaluation / Quality / Benchmark','evaluation','measure','We compare model performance weekly to catch any regression early.','我们每周 compare model performance 以便尽早发现任何 regression。',2,['eval','collocation'],'phrase');
add('review failed queries','collocation','审查失败查询','check errors','Engineering Collaboration / Debugging','evaluation','debug','We review failed queries every Friday to find patterns and improve the system.','我们每周五 review failed queries 以找出模式并改进系统。',2,['engineering','collocation'],'phrase');
add('update the system prompt','collocation','更新系统提示','change instruction','Prompt / Context / Instruction Design','design','improve','We updated the system prompt to include clearer safety guidelines.','我们 update the system prompt 加入了更清晰的安全指南。',2,['prompt','collocation'],'phrase');
add('simplify the onboarding flow','collocation','简化引导流程','make easier','UX / Conversation Design','design','improve','We simplified the onboarding flow from six steps to three and signups increased.','我们把 onboarding flow 从六步 simplify 到三步注册量增加了。',1,['ux','collocation'],'phrase');
add('set usage limits','collocation','设置用量限制','cap consumption','Pricing / Token Cost / Monetization','growth','manage','We set usage limits on the free tier to prevent abuse and control costs.','我们在免费版 set usage limits 以防止滥用并控制成本。',1,['cost','collocation'],'phrase');
add('protect user privacy','collocation','保护用户隐私','keep data safe','Safety / Privacy / Compliance','implementation','design','Every feature we build must protect user privacy by design not as an afterthought.','我们构建的每个功能都必须 protect user privacy 从设计开始而不是事后补救。',2,['safety','collocation'],'phrase');
add('log failed queries','collocation','记录失败查询','record errors','Engineering Collaboration / Debugging','implementation','debug','We log failed queries to analyse patterns and improve the retrieval pipeline.','我们 log failed queries 以分析模式并改进 retrieval pipeline。',2,['engineering','collocation'],'phrase');
add('route the ticket','collocation','路由工单','send to right team','Agent / Workflow / Automation','implementation','automate','The system routes the ticket to the right team based on the query category.','系统根据查询类别 route the ticket 给正确的团队。',2,['agent','collocation'],'phrase');

// ===== SENTENCE PATTERNS (20+) =====
add('Can we test this with real users?','sentence_pattern','能用真实用户测吗？','user test ask','User Research / Customer Feedback','discovery','propose','Can we test this with real users before we spend more time polishing the interface.','我们能在花更多时间打磨界面之前用真实用户测一下这个吗。',1,['research','sentence_pattern'],'sentence_pattern');
add('The output is not reliable enough.','sentence_pattern','输出不够可靠','quality issue','Evaluation / Quality / Benchmark','evaluation','identify','The output is not reliable enough for customer-facing use because it still makes factual errors.','输出对于客户使用来说不够可靠因为它仍然存在事实性错误。',2,['quality','sentence_pattern'],'sentence_pattern');
add('We need a clearer success metric.','sentence_pattern','我们需要更清晰的成功指标','define KPI','Data / Analytics / Product Metrics','requirement','propose','We need a clearer success metric than just counting how many queries the assistant handles.','我们需要一个比仅仅统计助手处理了多少查询更清晰的成功指标。',1,['metrics','sentence_pattern'],'sentence_pattern');
add('The model should ask a follow-up question.','sentence_pattern','模型应该问跟进问题','clarify intent','UX / Conversation Design','design','propose','The model should ask a follow-up question when the user request is vague.','当用户请求模糊时模型应该问一个跟进问题。',1,['ux','sentence_pattern'],'sentence_pattern');
add('This feature is not ready yet.','sentence_pattern','这个功能还没准备好','status update','PRD / Requirement / Roadmap','implementation','communicate','This feature is not ready yet because the accuracy on edge cases is still below target.','这个功能还没准备好因为边缘案例的准确率仍低于目标。',1,['pm','sentence_pattern'],'sentence_pattern');
add('The workflow needs human review.','sentence_pattern','工作流需要人工审查','human in loop','Agent / Workflow / Automation','design','propose','The workflow needs human review before sending any customer-facing email.','在发送任何客户邮件之前工作流需要人工审查。',1,['agent','sentence_pattern'],'sentence_pattern');
add('The cost is too high for this plan.','sentence_pattern','这个计划的成本太高了','cost concern','Pricing / Token Cost / Monetization','growth','identify','The cost is too high for this plan because the average query uses over 5000 tokens.','这个计划的成本太高了因为平均每次查询使用超过 5000 个 token。',2,['cost','sentence_pattern'],'sentence_pattern');
add('Users want a shorter answer.','sentence_pattern','用户想要更短的答案','user preference','UX / Conversation Design','discovery','learn','Users want a shorter answer and the feedback shows they skip long responses.','用户想要更短的答案反馈显示他们会跳过长的回复。',1,['ux','sentence_pattern'],'sentence_pattern');
add('The prompt is too vague.','sentence_pattern','提示太模糊了','clarity issue','Prompt / Context / Instruction Design','design','identify','The prompt is too vague and the model keeps switching between different response formats.','提示太模糊了模型一直在不同的回复格式之间切换。',1,['prompt','sentence_pattern'],'sentence_pattern');
add('The response should cite sources.','sentence_pattern','回复应引用来源','cite requirement','RAG / Knowledge Base / Retrieval','design','propose','The response should cite sources so users can verify the information themselves.','回复应引用来源这样用户可以自己核实信息。',1,['rag','sentence_pattern'],'sentence_pattern');
add('Can we reduce the token cost?','sentence_pattern','能降低 token 成本吗？','cost ask','Pricing / Token Cost / Monetization','growth','propose','Can we reduce the token cost by using a smaller model for simple factual queries.','我们能否通过用较小的模型处理简单的事实查询来降低 token 成本。',2,['cost','sentence_pattern'],'sentence_pattern');
add('The model missed the user intent.','sentence_pattern','模型没理解用户意图','intent failure','UX / Conversation Design','evaluation','identify','The model missed the user intent and answered a different question than what was asked.','模型没理解用户意图回答了一个与所问不同的问题。',2,['ux','sentence_pattern'],'sentence_pattern');
add('The fallback feels too generic.','sentence_pattern','兜底回复感觉太泛了','generic response','UX / Conversation Design','design','identify','The fallback feels too generic and users are frustrated because it does not help them.','兜底回复感觉太泛了用户很沮丧因为它没有帮助到他们。',1,['ux','sentence_pattern'],'sentence_pattern');
add('We should log failed queries.','sentence_pattern','我们应该记录失败查询','log proposal','Engineering Collaboration / Debugging','implementation','propose','We should log failed queries so we can review them and find common patterns.','我们应该记录失败查询以便审查它们并找出常见模式。',1,['engineering','sentence_pattern'],'sentence_pattern');
add('This use case is too broad.','sentence_pattern','这个用例太宽泛了','scope concern','AI Product Strategy / Use Case Discovery','discovery','identify','This use case is too broad and the model struggles because there are too many possible answers.','这个用例太宽泛了模型很难应对因为可能的答案太多了。',1,['strategy','sentence_pattern'],'sentence_pattern');
add('Can we narrow the scope?','sentence_pattern','能缩小范围吗？','scope proposal','AI Product Strategy / Use Case Discovery','discovery','propose','Can we narrow the scope to just one type of document for the first version.','我们能缩小范围到第一版只处理一种类型的文档吗。',1,['strategy','sentence_pattern'],'sentence_pattern');
add('The answer needs better grounding.','sentence_pattern','答案需要更好的事实基础','grounding need','RAG / Knowledge Base / Retrieval','evaluation','identify','The answer needs better grounding because some claims are not supported by the retrieved documents.','答案需要更好的事实基础因为有些说法没有被检索到的文档支持。',2,['rag','sentence_pattern'],'sentence_pattern');
add('The beta feedback is mostly positive.','sentence_pattern','测试反馈基本上是正面的','beta feedback','Launch / GTM / Customer Success','launch','communicate','The beta feedback is mostly positive but users want more control over the output format.','测试反馈基本上是正面的但用户希望对输出格式有更多控制。',1,['launch','sentence_pattern'],'sentence_pattern');
add('This flow needs a human handoff.','sentence_pattern','这个流程需要人工移交','handoff need','Agent / Workflow / Automation','design','propose','This flow needs a human handoff because the model cannot handle refund requests reliably.','这个流程需要人工移交因为模型无法可靠地处理退款请求。',2,['agent','sentence_pattern'],'sentence_pattern');
add('We need to test edge cases.','sentence_pattern','我们需要测试边缘案例','edge case need','Evaluation / Quality / Benchmark','evaluation','propose','We need to test edge cases like empty input very long queries and mixed languages.','我们需要测试边缘案例如空输入超长查询和混合语言。',2,['eval','sentence_pattern'],'sentence_pattern');

const updated=data.concat(newItems);
fs.writeFileSync(file,JSON.stringify(updated));
console.log('AI PM POS: Added',added,'| Skipped:',skipped,'| New total:',updated.length);
console.log('  Verbs:',newItems.filter(x=>x.partOfSpeech==='verb').length);
console.log('  Phrasal:',newItems.filter(x=>x.partOfSpeech==='phrasal_verb').length);
console.log('  Adj:',newItems.filter(x=>x.partOfSpeech==='adjective').length);
console.log('  Colloc:',newItems.filter(x=>x.partOfSpeech==='collocation').length);
console.log('  SentPatt:',newItems.filter(x=>x.partOfSpeech==='sentence_pattern').length);
