const fs=require('fs');

const PACKS=[
  {file:'src/data/packs/ielts-exam-context-2000.json',pack:'ielts-exam-context-2000',pre:'ielts-exam-context-2000'},
  {file:'src/data/packs/foreign-trade-crowdfunding-dtc-operations-1000.json',pack:'foreign-trade-crowdfunding-dtc-operations-1000',pre:'foreign-trade-crowdfunding-dtc-operations-1000'},
  {file:'src/data/packs/robotics-rd-engineering-research-1000.json',pack:'robotics-rd-engineering-research-1000',pre:'robotics-rd-engineering-research-1000'},
  {file:'src/data/packs/ai-product-management-llm-products-1000.json',pack:'ai-product-management-llm-products-1000',pre:'ai-product-management-llm-products-1000'},
  {file:'src/data/packs/robotics-maintenance-troubleshooting-1000.json',pack:'robotics-maintenance-troubleshooting-1000',pre:'robotics-maintenance-troubleshooting-1000'},
  {file:'src/data/packs/smart-hardware-overseas-channel-sales-core.json',pack:'smart-hardware-overseas-channel-sales-core',pre:'smart-hardware-overseas-channel-sales-core'},
];

const FF={RLHF:'Reinforcement Learning from Human Feedback',GDPR:'General Data Protection Regulation',SLA:'Service Level Agreement',SOC:'System and Organization Controls',DDS:'Data Distribution Service',PID:'Proportional Integral Derivative',MSRP:'Manufacturer Suggested Retail Price',FCC:'Federal Communications Commission',CE:'Conformité Européenne',RoHS:'Restriction of Hazardous Substances',UKCA:'UK Conformity Assessed',B2B:'Business to Business',PLC:'Programmable Logic Controller','I/O':'Input/Output',IP:'Internet Protocol',UPS:'Uninterruptible Power Supply',HMI:'Human Machine Interface',DO:'Digital Output',DI:'Digital Input','3PL':'Third-Party Logistics',KPI:'Key Performance Indicator',ROI:'Return on Investment',ROAS:'Return on Ad Spend',CTR:'Click-Through Rate',CPC:'Cost Per Click',CPA:'Cost Per Acquisition',AOV:'Average Order Value',MOQ:'Minimum Order Quantity',EXW:'Ex Works',FOB:'Free On Board',CIF:'Cost Insurance Freight',DDP:'Delivered Duty Paid'};

for(const P of PACKS){
  const data=JSON.parse(fs.readFileSync(P.file,'utf-8'));
  const existing=new Set(data.map(d=>d.term.toLowerCase()));
  const newItems=[];let id=data.length+1,added=0,skipped=0;

  function add(t,pos,sm,sis,topic,ex,ez,diff,tg,type,reg,extras){
    if(existing.has(t.toLowerCase())){skipped++;return false;}
    existing.add(t.toLowerCase());
    const item={id:P.pre+'-'+String(id).padStart(4,'0'),packId:P.pack,term:t,type:type||'word',partOfSpeech:pos,topic,shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'neutral',difficulty:diff||2,sourceType:'ielts_style_original',sourceTitle:'Original learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||[],fullForm:FF[t]||undefined};
    if(extras)Object.assign(item,extras);
    newItems.push(item);id++;added++;return true;
  }

  const isIELTS=P.pack.includes('ielts');
  const isFT=P.pack.includes('foreign');
  const isRD=P.pack.includes('robotics-rd');
  const isMaint=P.pack.includes('robotics-maintenance');
  const isAI=P.pack.includes('ai');
  const isHW=P.pack.includes('smart');

  if(isIELTS){
    // Practical academic + exam vocabulary
    add('justify','verb','证明合理','give reasons for','Argument and Logic','The government must justify spending public money on space exploration when basic services are underfunded.','当基本服务资金不足时政府必须 justify 在太空探索上投入公共资金。',3,['academic','verb'],'word','formal',{examSkill:'Writing',examUse:'Task 2 argumentation'});
    add('predict','verb','预测','say what will happen','Trend and Comparison','Experts predict that the global population will reach its peak around the middle of this century.','专家 predict 全球人口将在本世纪中叶左右达到峰值。',3,['academic','verb'],'word','formal',{examSkill:'Writing',examUse:'Task 1 trends'});
    add('assess','verb','评估','evaluate','Argument and Logic','The report assesses the environmental impact of the proposed highway project.','该报告 assess 了拟建高速公路项目的环境影响。',3,['academic','verb'],'word','formal',{examSkill:'Reading',examUse:'academic reading'});
    add('worsen','verb','恶化','make worse','Argument and Logic','Air pollution is expected to worsen if no action is taken to reduce vehicle emissions.','如果不采取措施减少车辆排放空气污染预计将 worsen。',3,['academic','verb'],'word','semi-formal',{examSkill:'Writing',examUse:'cause and effect'});
    add('shape','verb','塑造','influence development','Argument and Logic','Early experiences can shape a child personality and future learning ability.','早期经历可以 shape 孩子的性格和未来的学习能力。',2,['academic','verb'],'word','semi-formal',{examSkill:'Speaking',examUse:'discussing influences'});
    add('arise from','phrasal_verb','产生于','come from','Argument and Logic','Most conflicts arise from a lack of clear communication between the parties involved.','大多数冲突 arise from 当事方之间缺乏清晰的沟通。',3,['academic','phrasal_verb'],'phrase','formal',{examSkill:'Reading',examUse:'cause and effect'});
    add('relevant','adjective','相关的','connected to topic','Argument and Logic','Make sure all the examples in your essay are directly relevant to the main argument.','确保 essay 中的所有例子都直接 relevant 于主要论点。',2,['academic','adjective'],'word','semi-formal',{examSkill:'Writing',examUse:'coherence'});
    add('ineffective','adjective','无效的','not working','Argument and Logic','The current policy has proven ineffective because it does not address the root causes of the problem.','当前政策已被证明是 ineffective 的因为它没有解决问题的根本原因。',3,['academic','adjective'],'word','formal',{examSkill:'Writing',examUse:'evaluation'});
    add('worthwhile','adjective','值得的','worth the effort','Argument and Logic','Studying abroad can be expensive but most students find it a worthwhile experience.','出国留学可能很贵但大多数学生觉得这是 worthwhile 的经历。',2,['academic','adjective'],'word','neutral',{examSkill:'Speaking',examUse:'personal opinion'});
    add('largely','adverb','主要地','mostly','Trend and Comparison','The increase in life expectancy is largely due to improvements in sanitation and healthcare.','寿命的延长 largely 归功于卫生和医疗的改善。',2,['academic','adverb'],'word','formal',{examSkill:'Writing',examUse:'qualifying statements'});
    add('roughly','adverb','大致','approximately','Trend and Comparison','Roughly half of the respondents said they would consider switching to an electric vehicle.','roughly 一半的受访者表示他们会考虑换成电动汽车。',2,['academic','adverb'],'word','neutral',{examSkill:'Listening',examUse:'approximation'});
    add('In my opinion','sentence_pattern','在我看来','personal view','Argument and Logic','In my opinion the benefits of technology in education outweigh the potential drawbacks.','in my opinion 技术在教育中的好处超过了潜在的弊端。',1,['speaking','opinion'],'sentence_pattern','neutral',{examSkill:'Speaking',examUse:'expressing opinion'});
    add('A good example is','sentence_pattern','一个很好的例子是','give example','Argument and Logic','A good example is the way public transport has transformed city life in Singapore.','a good example is 公共交通改变了新加坡的城市生活。',1,['speaking','example'],'sentence_pattern','neutral',{examSkill:'Speaking',examUse:'giving examples'});
  }
  else if(isFT){
    // Practical DTC work vocabulary
    add('update','verb','更新','refresh info','Customer Support','Please update the tracking number once the label is generated.','标签生成后请 update tracking number。',1,['support','verb'],'word','workplace',{businessStage:'logistics',workIntent:'communicate'});
    add('reply','verb','回复','respond','Customer Support','The customer sent a message two hours ago and we have not replied yet.','客户两小时前发了消息我们还没有 reply。',1,['support','verb'],'word','workplace',{businessStage:'customer support',workIntent:'resolve'});
    add('send out','phrasal_verb','发出','dispatch','Fulfillment / Logistics','We send out the first batch of reward surveys to backers this Friday.','我们本周五 send out 第一批 reward survey 给支持者。',1,['logistics','phrasal_verb'],'phrase','workplace',{businessStage:'post-campaign fulfillment',workIntent:'dispatch'});
    add('push back','phrasal_verb','推迟','delay','Supplier / Foreign Trade','The supplier pushed back the delivery date by three weeks because of a material shortage.','由于原材料短缺 supplier 把交货日期 push back 了三周。',2,['supplier','phrasal_verb'],'phrase','workplace',{businessStage:'supplier communication',workIntent:'manage delays'});
    add('sell out','phrasal_verb','卖光','all sold','Shopify / DTC Store','The blue variant sold out in two days so we need to restock it faster than planned.','蓝色款两天就 sell out 了所以我们需要比计划更快地补货。',1,['dtc','phrasal_verb'],'phrase','workplace',{businessStage:'dtc store operation',workIntent:'manage stock'});
    add('missing','adjective','缺失的','not there','Customer Support','The customer received the package but one item was missing from the bundle.','客户收到了包裹但 bundle 中有一个 item missing。',1,['support','adjective'],'word','workplace',{businessStage:'customer support',workIntent:'resolve issues'});
    add('unavailable','adjective','不可用的','not available','Shopify / DTC Store','This variant is currently unavailable because the supplier is waiting for a key component.','这个变体目前 unavailable 因为供应商在等一个关键组件。',1,['dtc','adjective'],'word','workplace',{businessStage:'dtc store operation',workIntent:'manage stock'});
    add('Please follow up today','sentence_pattern','请今天跟进','follow-up reminder','Outbound Sales / Cold Call / Email Outreach','Please follow up today because the customer said they need a decision by the end of the week.','Please follow up today 因为客户说他们需要在周末之前做出决定。',1,['communication','reminder'],'sentence_pattern','workplace',{businessStage:'cold call',workIntent:'maintain contact'});
    add('The customer asked for a replacement','sentence_pattern','客户要求换货','replacement request','Customer Support','The customer asked for a replacement because the unit arrived with a cracked screen.','The customer asked for a replacement 因为收到的产品屏幕碎裂了。',1,['support','complaint'],'sentence_pattern','workplace',{businessStage:'customer support',workIntent:'resolve issues'});
  }
  else if(isRD){
    // Practical R&D verbs, adjectives, phrases
    add('fail','verb','失败','not succeed','Research and Evaluation','The navigation stack fails when the robot enters a room with large glass walls.','当机器人进入有大玻璃墙的房间时 navigation stack 会 fail。',1,['engineering','verb'],'word','technical',{researchArea:'navigation',usageScene:'debugging',workIntent:'identify failure'});
    add('lag','verb','延迟','delay behind','Kinematics and Control','The visual feed lags behind the real robot by about 200 milliseconds which makes teleoperation difficult.','视觉画面 lag 了真实机器人约 200 毫秒使得远程操作困难。',2,['control','verb'],'word','technical',{researchArea:'control',usageScene:'debugging',workIntent:'measure latency'});
    add('outdated','adjective','过时的','no longer current','ROS2 Core','The documentation is outdated and still refers to the Humble release which was deprecated last year.','文档已经 outdated 仍然引用去年已弃用的 Humble 发行版。',1,['ros2','adjective'],'word','technical',{researchArea:'system architecture',usageScene:'code review',workIntent:'update'});
    add('The topic is not publishing','sentence_pattern','topic 没有发布','pub issue','ROS2 Core','The topic is not publishing which means the node either crashed or never started correctly.','The topic is not publishing 这意味着节点要么崩溃了要么从未正确启动。',2,['ros2','diagnostic'],'sentence_pattern','technical',{researchArea:'system architecture',usageScene:'debugging',workIntent:'diagnose'});
    add('The transform is missing','sentence_pattern','transform 缺失','TF issue','Navigation','The transform is missing between the base link and the map frame so the planner cannot start.','base link 和 map frame 之间 The transform is missing 所以 planner 无法启动。',2,['navigation','diagnostic'],'sentence_pattern','technical',{researchArea:'navigation',usageScene:'debugging',workIntent:'diagnose'});
    add('Can you reproduce the issue','sentence_pattern','能复现吗','repro question','Engineering Collaboration and Debugging','Can you reproduce the issue on the real robot because it only happens in simulation so far.','Can you reproduce the issue 在真实机器人上因为目前只在仿真中出现。',2,['engineering','diagnostic'],'sentence_pattern','technical',{researchArea:'evaluation',usageScene:'debugging',workIntent:'verify'});
    add('The log shows a timing issue','sentence_pattern','日志显示时序问题','timing problem','Engineering Collaboration and Debugging','The log shows a timing issue between the sensor callback and the controller update loop.','The log shows a timing issue 在传感器回调和控制器更新循环之间。',3,['engineering','diagnostic'],'sentence_pattern','technical',{researchArea:'system architecture',usageScene:'debugging',workIntent:'diagnose'});
  }
  else if(isMaint){
    // Practical maintenance spoken vocabulary
    add('check','verb','检查','look at','Fault Diagnosis','Please check the encoder cable before we start swapping expensive components.','在开始更换昂贵组件之前请 check encoder cable。',1,['maintenance','verb'],'word','workplace',{workIntent:'diagnose',scene:'remote support',role:'service engineer'});
    add('verify','verb','核实','confirm','Fault Diagnosis','Can you verify the voltage at the motor drive terminals with a multimeter?','你能用万用表 verify 电机驱动端子上的电压吗？',2,['diagnosis','verb'],'word','workplace',{workIntent:'diagnose',scene:'remote support',role:'service engineer'});
    add('clean','verb','清洁','remove dirt','Preventive Maintenance','Clean the optical sensor with a lint-free cloth because dust is causing false readings.','用无绒布 clean 光学传感器因为灰尘导致了错误读数。',1,['maintenance','verb'],'word','workplace',{workIntent:'maintain',scene:'onsite visit',role:'maintenance technician'});
    add('unplug','verb','拔掉','remove plug','Electrical and Wiring','Unplug the motor connector before you touch any of the terminals on the drive.','在你接触驱动器上的任何端子之前先 unplug 电机连接器。',1,['electrical','verb'],'word','workplace',{workIntent:'safety',scene:'onsite visit',role:'service engineer'});
    add('turn off','phrasal_verb','关闭','switch off','Electrical and Wiring','Turn off the main power before you open the control cabinet.','在你打开控制柜之前先 turn off 主电源。',1,['safety','phrasal_verb'],'phrase','workplace',{workIntent:'safety',scene:'onsite visit',role:'maintenance technician'});
    add('shut down','phrasal_verb','关闭','full power off','Power and Electrical','The robot shut down unexpectedly during the night shift and the operator did not log the event.','机器人在夜班期间 unexpectedly shut down 操作员没有记录该事件。',2,['power','phrasal_verb'],'phrase','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'service engineer'});
    add('hot','adjective','过热','too hot','Sensors and Actuators','The motor on axis one feels too hot to touch which is definitely not normal after only an hour of running.','一轴的电机摸起来太 hot 了运行仅一小时后这绝对不正常。',1,['diagnosis','adjective'],'word','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'service engineer'});
    add('noisy','adjective','噪音','making sound','Mechanical Repair','The gearbox on axis three is getting noisy which usually means the bearings are starting to wear.','三轴的齿轮箱变得 noisy 了这通常意味着轴承开始磨损。',1,['mechanical','adjective'],'word','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'maintenance technician'});
    add('The fault came back again','sentence_pattern','故障又回来了','fault recurring','Fault Diagnosis','The fault came back again after we replaced the cable so it must be the drive itself.','我们更换 cable 之后 The fault came back again 所以一定是驱动器本身的问题。',2,['diagnosis','diagnostic'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'service engineer'});
    add('The sensor is not responding','sentence_pattern','传感器无响应','sensor dead','Sensors and Actuators','The sensor is not responding at all so check the power supply first before replacing it.','The sensor is not responding 所以先检查电源再考虑更换。',1,['diagnosis','diagnostic'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'remote support',role:'service engineer'});
    add('The cable looks loose','sentence_pattern','线缆看起来松了','loose wire','Electrical and Wiring','The cable looks loose where it enters the connector so try pushing it in firmly first.','The cable looks loose 在进入连接器的地方所以先试着用力推入。',1,['electrical','diagnostic'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'maintenance technician'});
    add('The motor is too hot','sentence_pattern','电机太热了','overheating','Sensors and Actuators','The motor is too hot after just twenty minutes of running so the cooling fan may have failed.','仅运行二十分钟后 The motor is too hot 所以散热风扇可能坏了。',1,['motor','diagnostic'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'service engineer'});
    add('We replaced the fuse','sentence_pattern','我们换了保险丝','fuse swap','Power and Electrical','We replaced the fuse but it blew again after ten minutes which means there is a short somewhere.','我们 replaced the fuse 但十分钟后它又 blew 了这说明某处有短路。',2,['electrical','diagnostic'],'sentence_pattern','workplace',{workIntent:'repair',scene:'onsite visit',role:'maintenance technician'});
    add('Try to power cycle it first','sentence_pattern','先试试断电重启','basic fix','Power and Electrical','Try to power cycle it first before we go through the full troubleshooting procedure.','在我们进行完整的故障排查程序之前先试试 power cycle it first。',1,['electrical','advice'],'sentence_pattern','workplace',{workIntent:'troubleshoot',scene:'remote support',role:'service engineer'});
    add('The alarm cleared after reset','sentence_pattern','复位后报警清除了','alarm gone','Fault Diagnosis','The alarm cleared after reset and the robot has been running fine for the last hour.','The alarm cleared after reset 机器人过去一小时一直运行正常。',1,['diagnosis','observation'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'onsite visit',role:'service engineer'});
    add('Please send the error code','sentence_pattern','请发一下错误代码','ask for code','Fault Diagnosis','Please send the error code so I can look it up in the manual before our call.','请 send the error code 这样我可以在我们通话之前查手册。',1,['diagnosis','request'],'sentence_pattern','workplace',{workIntent:'diagnose',scene:'remote support',role:'service engineer'});
  }
  else if(isAI){
    // Practical AI PM spoken vocabulary
    add('clarify','verb','澄清','make clear','UX / Conversation Design','The assistant should ask a follow-up question when the user request is too vague to clarify the intent.','当用户请求太模糊时助手应该问一个跟进问题来 clarify 意图。',2,['ux','verb'],'word','workplace',{productStage:'design',workIntent:'improve UX'});
    add('summarize','verb','总结','give summary','LLM Basics / Model Capabilities','The model can summarize long documents but sometimes misses key numbers and dates.','模型可以 summarize 长文档但有时会漏掉关键数字和日期。',2,['llm','verb'],'word','technical',{productStage:'evaluation',workIntent:'test capability'});
    add('classify','verb','分类','sort into groups','Agent / Workflow / Automation','The triage agent needs to classify incoming tickets as urgent high medium or low before routing.','分流 agent 需要在 routing 之前将 incoming ticket classify 为紧急高中低。',2,['agent','verb'],'word','technical',{productStage:'implementation',workIntent:'automate'});
    add('unreliable','adjective','不可靠的','not dependable','Evaluation / Quality / Benchmark','The output is unreliable when the input text contains tables or complex formatting.','当输入文本包含表格或复杂格式时输出是 unreliable 的。',2,['quality','adjective'],'word','workplace',{productStage:'evaluation',workIntent:'identify issues'});
    add('unclear','adjective','不清楚的','not clear','UX / Conversation Design','The error message is unclear and does not tell the user what they should do next.','错误消息 unclear 没有告诉用户接下来该做什么。',1,['ux','adjective'],'word','workplace',{productStage:'design',workIntent:'improve UX'});
    add('irrelevant','adjective','无关的','not related','RAG / Knowledge Base / Retrieval','The retrieval returned several irrelevant documents that had the keyword but not the right context.','检索返回了几个 irrelevant 文档有关键词但没有正确的上下文。',2,['rag','adjective'],'word','workplace',{productStage:'evaluation',workIntent:'improve quality'});
    add('The output is not reliable enough','sentence_pattern','输出不够可靠','quality issue','Evaluation / Quality / Benchmark','The output is not reliable enough for customer-facing use because it still makes factual errors about once every twenty queries.','The output is not reliable enough 用于面向客户因为大约每二十次查询仍有一次事实错误。',2,['quality','concern'],'sentence_pattern','workplace',{productStage:'evaluation',workIntent:'assess quality'});
    add('The prompt is too vague','sentence_pattern','提示太模糊了','needs clarity','Prompt / Context / Instruction Design','The prompt is too vague and the model keeps switching between different formats in the same response.','The prompt is too vague 模型在同一回复中不断在不同的格式之间切换。',2,['prompt','issue'],'sentence_pattern','workplace',{productStage:'design',workIntent:'improve'});
    add('The response should cite sources','sentence_pattern','回复应引用来源','cite requirement','RAG / Knowledge Base / Retrieval','The response should cite sources so that users can verify the information themselves.','The response should cite sources 这样用户可以自己核实信息。',2,['rag','requirement'],'sentence_pattern','workplace',{productStage:'design',workIntent:'build trust'});
    add('This feature is not ready yet','sentence_pattern','这个功能还没准备好','not ready','PRD / Requirement / Roadmap','This feature is not ready yet because the accuracy on edge cases is still below eighty percent.','This feature is not ready yet 因为边缘案例的准确率仍低于百分之八十。',1,['pm','status'],'sentence_pattern','workplace',{productStage:'implementation',workIntent:'communicate status'});
  }
  else if(isHW){
    // Practical channel sales spoken vocabulary
    add('introduce','verb','介绍','present','Outbound Sales / Cold Call / Email Outreach','Let me introduce our new product line which is designed specifically for the European retail market.','让我 introduce 我们的新产品线专为欧洲零售市场设计。',1,['sales','verb'],'word','workplace',{salesStage:'cold call',channelType:'direct sales',workIntent:'pitch'});
    add('present','verb','展示','show','Trade Show / Exhibition / Follow-up','I will present the product features and the margin structure at the meeting next Tuesday.','我会在下周二的会议上 present 产品特点和利润结构。',1,['sales','verb'],'word','workplace',{salesStage:'demo',channelType:'trade show',workIntent:'showcase'});
    add('discount','verb','打折','reduce price','B2B Negotiation / Pricing / Payment','Can you discount the first batch so we can test the market with a lower retail price?','你能 discount 第一批吗这样我们可以用更低的零售价 test 市场。',1,['pricing','verb'],'word','workplace',{salesStage:'pricing negotiation',channelType:'B2B customer',workIntent:'negotiate'});
    add('expand','verb','扩展','grow','Channel Strategy / Sales Model','We plan to expand into two new countries next quarter once the certification is complete.','一旦认证完成我们计划下个季度 expand 到两个新国家。',2,['channel','verb'],'word','workplace',{salesStage:'partner negotiation',channelType:'distributor',workIntent:'grow'});
    add('sign up','phrasal_verb','签约','register','Distributor / Agent Development','The new dealer signed up after seeing our product demo at the trade show.','新经销商在展会上看到我们的产品演示后 sign up 了。',1,['channel','phrasal_verb'],'phrase','workplace',{salesStage:'partner negotiation',channelType:'dealer',workIntent:'onboard'});
    add('set up','phrasal_verb','建立','establish','Distributor / Agent Development','We need to set up a local service center before the distributor will commit to a large first order.','在分销商承诺大额 first order 之前我们需要 set up 一个当地服务中心。',2,['channel','phrasal_verb'],'phrase','workplace',{salesStage:'partner negotiation',channelType:'distributor',workIntent:'prepare'});
    add('premium','adjective','高端的','high-end','Product Positioning / Value Proposition','The premium version has a metal casing and a longer battery life for business users.','premium 版有金属外壳和更长的电池续航面向商务用户。',1,['positioning','adjective'],'word','workplace',{salesStage:'pitch',channelType:'direct sales',workIntent:'position'});
    add('entry-level','adjective','入门级的','basic','Product Positioning / Value Proposition','The entry-level model is priced to compete with local brands and still leave a healthy margin for dealers.','entry-level 型号的定价可以与当地品牌竞争同时仍为经销商留下 healthy margin。',1,['positioning','adjective'],'word','workplace',{salesStage:'pitch',channelType:'dealer',workIntent:'position'});
    add('Can we schedule a sales call','sentence_pattern','能约个销售电话吗','book meeting','Outbound Sales / Cold Call / Email Outreach','Can we schedule a sales call for next week to discuss the distributor opportunity in your region.','Can we schedule a sales call 下周讨论你所在地区的分销商机会。',1,['sales','request'],'sentence_pattern','workplace',{salesStage:'cold call',channelType:'direct sales',workIntent:'schedule'});
    add('The margin is too low','sentence_pattern','利润太低了','margin complaint','B2B Negotiation / Pricing / Payment','The margin is too low and the dealer cannot compete with similar products that offer thirty percent.','The margin is too low 经销商无法与提供百分之三十的同类产品竞争。',1,['pricing','complaint'],'sentence_pattern','workplace',{salesStage:'pricing negotiation',channelType:'dealer',workIntent:'negotiate'});
    add('Can we start with a small order','sentence_pattern','能从小单开始吗','trial request','Trial / Pilot / First Order','Can we start with a small order of fifty units to test the market before committing to a container.','Can we start with a small order 五十台在承诺整柜之前先测试市场。',1,['order','request'],'sentence_pattern','workplace',{salesStage:'pricing negotiation',channelType:'B2B customer',workIntent:'test'});
    add('Please send the price list','sentence_pattern','请发价格表','request pricing','B2B Negotiation / Pricing / Payment','Please send the price list with the wholesale and recommended retail prices for all models.','Please send the price list 包含所有型号的 wholesale 和建议零售价。',1,['pricing','request'],'sentence_pattern','workplace',{salesStage:'pricing negotiation',channelType:'B2B customer',workIntent:'request info'});
    add('We can support your first demo','sentence_pattern','我们可以支持你们的第一次演示','demo support','Trade Show / Exhibition / Follow-up','We can support your first demo by sending a demo unit and a product trainer for the event.','We can support your first demo 为活动寄送一台 demo unit 和一名产品培训师。',1,['demo','offer'],'sentence_pattern','workplace',{salesStage:'demo',channelType:'trade show',workIntent:'support partner'});
    add('The product is ready for retail','sentence_pattern','产品已准备好进入零售','retail ready','Retail / Supermarket / Channel Expansion','The product is ready for retail with all the packaging compliance labels and a retail-ready display box.','The product is ready for retail 包含所有包装合规标签和零售展示盒。',2,['retail','status'],'sentence_pattern','workplace',{salesStage:'retail onboarding',channelType:'retail chain',workIntent:'launch'});
    add('The buyer asked for a lower price','sentence_pattern','采购要求更低的价格','price pushback','B2B Negotiation / Pricing / Payment','The buyer asked for a lower price so we need to review the volume discount structure.','The buyer asked for a lower price 所以我们需要重新审视批量折扣结构。',2,['pricing','feedback'],'sentence_pattern','workplace',{salesStage:'pricing negotiation',channelType:'B2B customer',workIntent:'respond'});
    add('We need certification before launch','sentence_pattern','我们发布前需要认证','cert requirement','Certification / Market Access / Compliance','We need certification before launch in that market because the local regulation requires a separate safety approval.','在那个市场发布之前 We need certification before launch 因为当地法规要求单独的安全审批。',3,['compliance','requirement'],'sentence_pattern','workplace',{salesStage:'market access',channelType:'B2B customer',workIntent:'comply'});
  }

  const updated=data.concat(newItems);
  fs.writeFileSync(P.file,JSON.stringify(updated));
  console.log(P.pre.split('-').slice(-2).join('-')+': +'+added+' = '+updated.length);
}
