const fs=require('fs');
const file='src/data/packs/robotics-maintenance-troubleshooting-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));

const FF={PLC:'Programmable Logic Controller','I/O':'Input/Output',IP:'Internet Protocol',EtherCAT:'Ethernet for Control Automation Technology',PROFINET:'Process Field Net',UPS:'Uninterruptible Power Supply',HMI:'Human Machine Interface',VFD:'Variable Frequency Drive',PCB:'Printed Circuit Board'};

const newItems=[];let id=data.length+1,added=0,skipped=0;

function add(t,pos,sm,sis,topic,work,scene,role,ex,ez,diff,tg,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  newItems.push({id:'robotics-maintenance-troubleshooting-1000-'+String(id).padStart(4,'0'),packId:'robotics-maintenance-troubleshooting-1000',term:t,type:type||'word',partOfSpeech:pos,topic,workIntent:work||'',scene:scene||'',role:role||'',shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'workplace',difficulty:diff||1,sourceType:'robotics_maintenance_style_original',sourceTitle:'Original robotics maintenance learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||['maintenance'],fullForm:FF[t]||undefined});
  id++;added++;return true;
}

// ===== VERBS (40+) =====
add('measure','verb','测量','take a reading','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Measure the voltage at the motor drive terminals before we replace anything.','在更换任何东西之前先 measure 电机驱动端子上的电压。',1,['electrical','verb']);
add('restart','verb','重启','start again','Robot Controller','troubleshoot','remote support','support engineer','Restart the robot controller after the power dip and see if the alarm clears.','电压骤降后 restart robot controller 看看报警是否清除。',1,['controller','verb']);
add('clean','verb','清洁','remove dirt','Sensors and I/O','maintain','preventive maintenance','robot technician','Clean the optical sensor with a lint-free cloth before re-installing it.','在重新安装之前用无绒布 clean 光学传感器。',1,['sensor','verb']);
add('lubricate','verb','润滑','apply grease','Mechanical Wear','maintain','preventive maintenance','robot technician','Lubricate all six axis joints according to the schedule in the maintenance manual.','根据 maintenance manual 中的计划 lubricate 所有六个轴关节。',2,['mechanical','verb']);
add('reseat','verb','重新插拔','unplug and replug','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Try reseating the encoder connector before we order a new cable.','在订购新线缆之前试试 reseat 编码器连接器。',1,['electrical','verb']);
add('unplug','verb','拔掉','remove plug','Electrical Cabinet','safety check','onsite troubleshooting','robot technician','Unplug the motor power cable before you touch any terminals on the drive.','在接触驱动器上的任何端子之前先 unplug 电机电源线。',1,['safety','verb']);
add('plug in','verb','插上','connect plug','Electrical Cabinet','safety check','onsite troubleshooting','robot technician','Plug in the encoder cable firmly until you hear the locking tab click.','plug in 编码器线缆直到听到锁扣咔嗒一声。',1,['electrical','verb']);
add('turn on','verb','开启','switch on','Robot Controller','troubleshoot','remote support','support engineer','Turn on the main power and wait for the controller to finish its boot sequence.','turn on 主电源等待控制器完成启动序列。',1,['power','verb']);
add('turn off','verb','关闭','switch off','Robot Controller','safety check','onsite troubleshooting','robot technician','Turn off the robot before you enter the cell to inspect the gripper.','在你进入工作间检查 gripper 之前先 turn off 机器人。',1,['safety','verb']);
add('trace','verb','追踪','follow the path','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','We need to trace the cable from the encoder back to the controller to find the break.','我们需要从编码器 trace 线缆回到控制器以找到断点。',2,['electrical','verb']);
add('ground','verb','接地','earth','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','All metal parts of the cabinet must be properly grounded to avoid noise on the signal lines.','柜子的所有金属部件必须正确 ground 以避免信号线上的 noise。',2,['electrical','verb']);
add('shield','verb','屏蔽','protect from noise','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','Make sure to shield the encoder cable because it runs right next to the motor power line.','确保 shield encoder cable 因为它就在 motor power line 旁边走线。',2,['electrical','verb']);
add('reconnect','verb','重新连接','connect again','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Reconnect the network cable and wait for the fieldbus to re-establish communication.','reconnect 网线等待 fieldbus 重新建立通信。',1,['electrical','verb']);
add('acknowledge','verb','确认','accept alert','Robot Controller','alarm diagnosis','onsite troubleshooting','field service engineer','You need to acknowledge the alarm before the robot will allow any axis movement.','在机器人允许任何轴运动之前你需要 acknowledge alarm。',1,['controller','verb']);
add('monitor','verb','监控','watch continuously','Robot Controller','diagnose issue','remote support','support engineer','Monitor the current draw on axis two while the robot runs at full speed for ten minutes.','在机器人全速运行十分钟时 monitor 二号轴的电流。',2,['controller','verb']);
add('record','verb','记录','write down','Robot Controller','diagnose issue','remote support','support engineer','Record the error code and the exact time it appeared so we can check the log.','record error code 和它出现的确切时间以便我们检查 log。',1,['controller','verb']);
add('adjust','verb','调整','change slightly','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','We need to adjust the zero position on axis five because it is off by about 0.2 degrees.','我们需要 adjust 五轴的零点因为偏移了大约 0.2 度。',2,['calibration','verb']);
add('level','verb','调平','make flat','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','Level the robot base before you start the mastering procedure.','在开始 mastering 程序之前 level 机器人底座。',2,['calibration','verb']);
add('secure','verb','固定','fasten tight','Mechanical Wear','mechanical inspection','part replacement','robot technician','Secure all the bolts on the base frame before the robot goes back into production.','在机器人恢复生产之前 secure 底座框架上的所有螺栓。',1,['mechanical','verb']);
add('fasten','verb','紧固','tighten firmly','Mechanical Wear','mechanical inspection','part replacement','robot technician','Fasten the gripper mounting screws to the torque specified on the label.','按照标签上指定的扭矩 fasten 夹爪安装螺丝。',1,['mechanical','verb']);
add('remove','verb','拆下','take off','Mechanical Wear','part replacement','onsite troubleshooting','field service engineer','Remove the old gearbox carefully because the oil inside is still hot.','小心 remove 旧齿轮箱因为里面的油还很热。',1,['mechanical','verb']);
add('install','verb','安装','put in place','Mechanical Wear','part replacement','onsite troubleshooting','field service engineer','Install the new motor and make sure the shaft is aligned before tightening the bolts.','install 新电机确保在拧紧螺栓之前轴已对准。',1,['mechanical','verb']);
add('restore','verb','恢复','bring back','Robot Controller','diagnose issue','remote support','support engineer','We restored the robot parameters from the backup and the fault disappeared.','我们从 backup restore 了机器人参数故障消失了。',2,['controller','verb']);
add('isolate','verb','隔离','separate from system','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','maintenance engineer','We need to isolate whether the problem is in the drive the cable or the motor itself.','我们需要 isolate 问题是出在驱动器线缆还是电机本身。',2,['method','verb']);
add('bypass','verb','旁路','skip around','Safety and Interlock','diagnose issue','onsite troubleshooting','field service engineer','Do not bypass the safety interlock even for testing unless you have written approval.','即使为了测试也不要 bypass safety interlock 除非你有书面批准。',2,['safety','verb']);
add('repair','verb','修复','fix','Replacement and Spare Parts','part replacement','onsite troubleshooting','field service engineer','We repaired the drive by replacing the failed capacitor on the power board.','我们通过更换电源板上的 failed capacitor 来 repair 驱动器。',2,['repair','verb']);
add('confirm','verb','确认','verify','Troubleshooting Workflow','diagnose issue','remote support','support engineer','Can you confirm the fault only appears when the robot runs above 80 percent speed.','你能 confirm 故障只在机器人运行超过百分之八十速度时出现吗。',1,['method','verb']);
add('test','verb','测试','try','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','field service engineer','Test the limit switch by manually triggering it and watching the I/O status on the pendant.','通过手动触发 limit switch 并在 pendant 上观察 I/O 状态来 test 它。',1,['sensor','verb']);
add('trace back','phrasal_verb','回溯','follow backwards','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','We traced back the encoder signal and found a break in the cable near the robot wrist.','我们 trace back 了编码器信号在靠近机器人手腕处的线缆中发现了一处断路。',2,['electrical','verb'],'phrase');
add('look for','phrasal_verb','寻找','search','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','maintenance engineer','Look for any signs of rubbing on the cable harness where it passes through the cable chain.','在 cable harness 经过 cable chain 的地方 look for 摩擦痕迹。',1,['method','verb'],'phrase');
add('go back','phrasal_verb','回到','return to','Troubleshooting Workflow','diagnose issue','remote support','support engineer','Go back to the original settings and see if the problem disappears.','回到原始设置 go back 看看问题是否消失。',1,['method','verb'],'phrase');

// ===== PHRASAL VERBS (20+) =====
add('power cycle','phrasal_verb','断电重启','turn off and on','Robot Controller','troubleshoot','remote support','support engineer','Please power cycle the controller and let me know if the alarm clears after reboot.','请 power cycle 控制器让我知道重启后报警是否清除。',1,['power','phrasal_verb'],'phrase');
add('shut down','phrasal_verb','关闭','full power off','Robot Controller','safety check','onsite troubleshooting','robot technician','The robot shut down unexpectedly during the night shift and the operator did not log the event.','机器人在夜班期间 unexpectedly shut down 操作员没有记录。',1,['power','phrasal_verb'],'phrase');
add('drop out','phrasal_verb','信号丢失','lose connection','Encoder and Feedback','diagnose issue','remote support','support engineer','The encoder signal keeps dropping out for a few milliseconds which is enough to trigger a stop.','编码器信号持续 drop out 几毫秒足以触发停机。',2,['encoder','phrasal_verb'],'phrase');
add('come back','phrasal_verb','复发','return','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','field service engineer','The fault came back after the robot had been running for about three hours.','机器人运行约三小时后故障 come back 了。',1,['diagnosis','phrasal_verb'],'phrase');
add('clear up','phrasal_verb','消失','go away','Troubleshooting Workflow','diagnose issue','remote support','support engineer','The alarm cleared up after we replaced the encoder cable which confirms the cable was the issue.','更换了编码器线缆后 alarm clear up 了这确认线缆就是问题所在。',1,['diagnosis','phrasal_verb'],'phrase');
add('cool down','phrasal_verb','冷却','become cooler','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','Let the motor cool down for at least thirty minutes before you touch it.','在你触摸电机之前让 motor cool down 至少三十分钟。',1,['motor','phrasal_verb'],'phrase');
add('start up','phrasal_verb','启动','begin running','Robot Controller','troubleshoot','onsite troubleshooting','field service engineer','The controller starts up normally but then throws an error about two minutes later.','控制器正常 start up 但大约两分钟后抛出一个错误。',1,['controller','phrasal_verb'],'phrase');
add('boot up','phrasal_verb','开机','power-on sequence','Robot Controller','troubleshoot','remote support','support engineer','Let the pendant boot up completely before you press the reset button.','让 pendant 完全 boot up 再按 reset 按钮。',1,['controller','phrasal_verb'],'phrase');
add('swap out','phrasal_verb','更换','exchange','Replacement and Spare Parts','part replacement','onsite troubleshooting','field service engineer','We swapped out the servo drive and the fault disappeared immediately.','我们 swap out 了伺服驱动器故障立即消失了。',1,['repair','phrasal_verb'],'phrase');
add('back up','phrasal_verb','备份','save copy','Robot Controller','maintain','preventive maintenance','field service engineer','Always back up the robot parameters before making any changes to the configuration.','在对配置做任何更改之前总是 back up 机器人参数。',1,['service','phrasal_verb'],'phrase');
add('lock out','phrasal_verb','锁定','safety lock','Safety and Interlock','safety check','onsite troubleshooting','maintenance engineer','Lock out the main power before you open the control cabinet.','在打开控制柜之前 lock out 主电源。',1,['safety','phrasal_verb'],'phrase');
add('tag out','phrasal_verb','挂牌','safety tag','Safety and Interlock','safety check','onsite troubleshooting','maintenance engineer','Tag out the machine with your name and the time so nobody turns it on while you are inside.','用你的名字和时间 tag out 机器这样你在里面时没人会开机。',1,['safety','phrasal_verb'],'phrase');
add('pull out','phrasal_verb','拔出','remove','Electrical Cabinet','diagnose issue','onsite troubleshooting','robot technician','Pull out the connector gently and check if any of the pins are bent.','轻轻 pull out 连接器检查是否有任何针脚弯曲。',1,['electrical','phrasal_verb'],'phrase');
add('check out','phrasal_verb','检查','inspect','Troubleshooting Workflow','diagnose issue','remote support','support engineer','Check out the alarm history first before we start ordering replacement parts.','在我们开始订购替换部件之前先 check out alarm history。',1,['method','phrasal_verb'],'phrase');
add('plug in','phrasal_verb','插上','connect','Electrical Cabinet','safety check','onsite troubleshooting','robot technician','Plug in the network cable and wait for the green link light on the switch.','plug in 网线等待交换机上的绿色 link 灯。',1,['electrical','phrasal_verb'],'phrase');
add('pull off','phrasal_verb','拔下','disconnect','Electrical Cabinet','diagnose issue','onsite troubleshooting','robot technician','Pull off the connector cover and check for moisture inside.','pull off 连接器盖检查内部是否有湿气。',1,['electrical','phrasal_verb'],'phrase');
add('hold down','phrasal_verb','按住','press and keep','Robot Controller','diagnose issue','onsite troubleshooting','field service engineer','Hold down the reset button for five seconds until the pendant beeps.','hold down reset 按钮五秒直到 pendant 发出哔声。',1,['controller','phrasal_verb'],'phrase');
add('warm up','phrasal_verb','预热','heat up','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','Let the robot warm up for ten minutes before you run the calibration routine.','让机器人 warm up 十分钟再运行校准程序。',1,['calibration','phrasal_verb'],'phrase');
add('run through','phrasal_verb','跑一遍','go through','Troubleshooting Workflow','diagnose issue','remote support','support engineer','Let us run through the checklist together so we do not miss anything obvious.','让我们一起 run through 清单以免遗漏任何明显的问题。',1,['method','phrasal_verb'],'phrase');
add('burn out','phrasal_verb','烧毁','destroy by heat','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The fuse burnt out because of a short circuit on the I/O board.','由于 I/O board 上的 short circuit fuse burn out 了。',2,['electrical','phrasal_verb'],'phrase');

// ===== ADJECTIVES (25+) =====
add('loose','adjective','松动的','not tight','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The connector feels loose so push it in until you hear the click.','连接器感觉 loose 所以推入直到听到咔嗒声。',1,['electrical','adjective']);
add('broken','adjective','损坏的','not working','Mechanical Wear','diagnose issue','onsite troubleshooting','field service engineer','The bearing is broken and you can hear it grinding when the axis moves.','bearing broken 了当轴移动时你能听到 grinding。',1,['mechanical','adjective']);
add('dirty','adjective','脏的','contaminated','Sensors and I/O','diagnose issue','onsite troubleshooting','robot technician','The encoder disc is dirty which is causing erratic position readings.','编码器盘 dirty 了导致位置读数 erratic。',1,['sensor','adjective']);
add('blocked','adjective','堵塞的','obstructed','Pneumatics and Vacuum','diagnose issue','onsite troubleshooting','maintenance engineer','The air line to the gripper is blocked which is why the vacuum level is too low.','到 gripper 的 air line blocked 了这就是真空水平太低的原因。',1,['pneumatic','adjective']);
add('stuck','adjective','卡住的','cannot move','Mechanical Wear','diagnose issue','onsite troubleshooting','field service engineer','The joint is stuck and will not move even when we release the brake manually.','joint stuck 了即使我们手动释放制动器也不动。',1,['mechanical','adjective']);
add('hot','adjective','过热','too hot','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','The motor on axis one feels too hot to touch after only twenty minutes.','一号轴的 motor 运行仅二十分钟后就感觉太 hot 了。',1,['motor','adjective']);
add('noisy','adjective','噪音大','making sound','Mechanical Wear','diagnose issue','onsite troubleshooting','field service engineer','The gearbox on axis three is getting noisy so the bearings are probably starting to go.','三轴的齿轮箱变得 noisy 了所以轴承可能开始出问题了。',1,['mechanical','adjective']);
add('worn','adjective','磨损的','used down','Mechanical Wear','diagnose issue','preventive maintenance','field service engineer','The gripper pads are worn and need to be replaced before the next production run.','夹爪垫 worn 了需要在下一轮生产前更换。',1,['mechanical','adjective']);
add('jammed','adjective','卡死的','completely stuck','Mechanical Wear','diagnose issue','onsite troubleshooting','maintenance engineer','The tool changer is jammed and the robot cannot release the current end effector.','tool changer jammed 了机器人无法释放当前的 end effector。',1,['mechanical','adjective']);
add('unstable','adjective','不稳定的','not steady','Servo Motor and Drive','diagnose issue','remote support','support engineer','The motor speed is unstable at low RPM which could be a feedback issue.','电机速度在低 RPM 时 unstable 可能是 feedback 的问题。',2,['motor','adjective']);
add('misaligned','adjective','未对准的','not aligned','Calibration and Homing','diagnose issue','calibration','field service engineer','The motor shaft is misaligned with the gearbox which is causing the vibration.','电机轴与齿轮箱 misaligned 导致了振动。',2,['mechanical','adjective']);
add('intermittent','adjective','间歇性的','comes and goes','Troubleshooting Workflow','diagnose issue','remote support','support engineer','The fault is intermittent so it is hard to catch but it usually happens after the robot runs for an hour.','故障是 intermittent 的所以很难捕捉但通常在机器人运行一小时后发生。',2,['diagnosis','adjective']);
add('overheated','adjective','过热的','too hot too long','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','The drive shut down because it was overheated so check the cooling fan first.','驱动器因为 overheated 而关闭了所以先检查冷却风扇。',2,['motor','adjective']);
add('burnt','adjective','烧焦的','damaged by heat','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The fuse looks burnt and there is a strong smell of burnt plastic near the terminal block.','保险丝看起来 burnt 了端子排附近有强烈的塑料焦味。',1,['electrical','adjective']);
add('corroded','adjective','腐蚀的','rusty','Electrical Cabinet','diagnose issue','preventive maintenance','maintenance engineer','The terminals are corroded because of moisture inside the cabinet so we need to fix the seal.','端子 corroded 了因为柜子内有湿气所以我们需要修好密封。',2,['electrical','adjective']);
add('disconnected','adjective','断开连接的','unplugged','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The ground wire is disconnected which explains the noise on the encoder signals.','地线 disconnected 了这解释了编码器信号上的 noise。',1,['electrical','adjective']);
add('grounded','adjective','已接地的','earthed','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','Make sure the cabinet frame is properly grounded before powering it on.','在通电之前确保 cabinet frame 正确 grounded。',1,['electrical','adjective']);
add('shielded','adjective','已屏蔽的','noise protected','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','The signal cable must be shielded to prevent interference from the adjacent power cables.','signal cable 必须 shielded 以防止来自相邻 power cable 的干扰。',2,['electrical','adjective']);
add('safe','adjective','安全的','not dangerous','Safety and Interlock','safety check','onsite troubleshooting','maintenance engineer','The area is safe to enter now because the robot is in a full stop state.','现在进入区域是 safe 的因为机器人处于完全停止状态。',1,['safety','adjective']);
add('unsafe','adjective','不安全的','dangerous','Safety and Interlock','safety check','onsite troubleshooting','maintenance engineer','Do not enter the cell while the light curtain is triggered because the safety circuit is unsafe in this state.','在 light curtain 触发时不要进入 cell 因为安全电路在这种状态下 unsafe。',1,['safety','adjective']);
add('manual','adjective','手动的','by hand','Robot Controller','diagnose issue','onsite troubleshooting','field service engineer','Put the robot in manual mode before you try to jog any axis.','在尝试 jog 任何轴之前将机器人置于 manual 模式。',1,['controller','adjective']);
add('automatic','adjective','自动的','self-running','Robot Controller','safety check','onsite troubleshooting','field service engineer','The robot is in automatic mode so keep the safety gate closed.','机器人在 automatic 模式所以保持 safety gate 关闭。',1,['controller','adjective']);
add('onsite','adjective','现场的','at location','Field Service Report','diagnose issue','onsite troubleshooting','field service engineer','This is an onsite repair so bring the spare drive and the calibration tools.','这是 onsite repair 所以带上备用驱动器和校准工具。',1,['service','adjective']);
add('underpowered','adjective','功率不足的','not enough power','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','The motor feels underpowered and struggles to lift the rated payload.','电机感觉 underpowered 很难举起额定 payload。',2,['motor','adjective']);

// ===== COLLOCATIONS (20+) =====
add('check the cable','collocation','检查线缆','inspect wire','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Please check the cable on axis four because the encoder reading jumps when it moves fast.','请 check the cable 四轴因为快速移动时编码器读数跳动。',1,['electrical','collocation'],'phrase');
add('tighten the connector','collocation','拧紧连接器','secure plug','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Tighten the connector on the motor drive because a loose connection can cause intermittent faults.','tighten the connector 电机驱动上因为 loose connection 可能导致 intermittent fault。',1,['electrical','collocation'],'phrase');
add('replace the fuse','collocation','更换保险丝','swap fuse','Electrical Cabinet','part replacement','onsite troubleshooting','robot technician','Replace the fuse with the same rating and check if the new one holds.','用相同额定值 replace the fuse 检查新的是否能保持。',1,['electrical','collocation'],'phrase');
add('reset the alarm','collocation','复位报警','clear alert','Robot Controller','diagnose issue','remote support','support engineer','First reset the alarm and then observe if the fault comes back immediately or after some time.','先 reset the alarm 然后观察故障是立即回来还是过一段时间才回来。',1,['controller','collocation'],'phrase');
add('restart the controller','collocation','重启控制器','reboot','Robot Controller','troubleshoot','remote support','support engineer','Please restart the controller and tell me if the pendant shows any error during boot.','请 restart the controller 告诉我 pendant 在启动过程中是否显示任何 error。',1,['controller','collocation'],'phrase');
add('measure the voltage','collocation','测量电压','check volts','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Measure the voltage at the input terminals and compare it with the label on the drive.','在输入端子上 measure the voltage 并与驱动器标签上的值比较。',1,['electrical','collocation'],'phrase');
add('inspect the harness','collocation','检查线束','look at wiring','Electrical Cabinet','electrical inspection','preventive maintenance','maintenance engineer','Inspect the harness for any signs of rubbing against the robot frame.','inspect the harness 有没有与机器人框架摩擦的迹象。',1,['electrical','collocation'],'phrase');
add('clean the sensor','collocation','清洁传感器','remove dirt','Sensors and I/O','maintain','preventive maintenance','robot technician','Clean the sensor with compressed air first and then with a lint-free cloth.','先用压缩空气再用无绒布 clean the sensor。',1,['sensor','collocation'],'phrase');
add('swap the drive','collocation','更换驱动器','exchange motor controller','Servo Motor and Drive','part replacement','onsite troubleshooting','field service engineer','We swapped the drive and the fault disappeared so the old drive was the problem.','我们 swap the drive 故障消失了所以旧的驱动器是问题所在。',2,['motor','collocation'],'phrase');
add('reseat the connector','collocation','重新插拔连接器','unplug and replug','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Reseat the connector before ordering a new cable because the pins might just be dirty.','在订购新线缆之前 reseat the connector 因为针脚可能只是脏了。',1,['electrical','collocation'],'phrase');
add('clear the alarm','collocation','清除报警','remove alert','Robot Controller','diagnose issue','remote support','support engineer','Clear the alarm and try to jog the axis slowly to see if the fault reappears.','clear the alarm 然后尝试慢慢 jog 轴看看故障是否重新出现。',1,['controller','collocation'],'phrase');
add('record the error code','collocation','记录错误代码','write fault number','Robot Controller','diagnose issue','remote support','support engineer','Please record the error code and send it to me so I can look it up in the manual.','请 record the error code 发给我这样我可以在手册中查找。',1,['controller','collocation'],'phrase');
add('send the alarm history','collocation','发送报警历史','share fault log','Robot Controller','diagnose issue','remote support','support engineer','Can you send the alarm history from the last 24 hours so we can see the sequence.','你能 send the alarm history 过去 24 小时的吗这样我们可以看序列。',1,['controller','collocation'],'phrase');
add('verify the signal','collocation','验证信号','check waveform','Encoder and Feedback','diagnose issue','onsite troubleshooting','field service engineer','Verify the signal with an oscilloscope because the multimeter will not catch a brief dropout.','用示波器 verify the signal 因为万用表捕捉不到短暂的 dropout。',2,['encoder','collocation'],'phrase');
add('test the limit switch','collocation','测试限位开关','check end stop','Sensors and I/O','diagnose issue','onsite troubleshooting','maintenance engineer','Test the limit switch by pressing it manually while watching the I/O monitor on the pendant.','在 pendant 上观察 I/O monitor 的同时手动按压来 test the limit switch。',1,['sensor','collocation'],'phrase');
add('align the axis','collocation','对中轴','adjust position','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','We need to align the axis after replacing the motor because the zero position has shifted.','更换电机后我们需要 align the axis 因为零点偏移了。',2,['calibration','collocation'],'phrase');
add('calibrate the robot','collocation','校准机器人','set zero positions','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','Calibrate the robot after replacing any mechanical component in the drive train.','在更换传动链中任何机械组件后 calibrate the robot。',2,['calibration','collocation'],'phrase');
add('isolate the fault','collocation','隔离故障','narrow down','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','field service engineer','We need to isolate the fault to a single component before we can be sure what to replace.','在确定要更换什么之前我们需要 isolate the fault 到单个组件。',2,['method','collocation'],'phrase');
add('restore the power','collocation','恢复电源','bring back electricity','Robot Controller','diagnose issue','remote support','support engineer','Restore the power after confirming all safety gates are closed and the area is clear.','在确认所有 safety gate 关闭且区域清空后 restore the power。',1,['power','collocation'],'phrase');
add('check the grounding','collocation','检查接地','verify earth','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','Check the grounding on the control cabinet because poor grounding causes erratic encoder readings.','check the grounding 控制柜因为 poor grounding 会导致 erratic encoder reading。',1,['electrical','collocation'],'phrase');
add('back up the parameters','collocation','备份参数','save config','Robot Controller','maintain','preventive maintenance','field service engineer','Back up the parameters before you start any troubleshooting so we can always restore them.','在开始任何故障排查之前 back up the parameters 这样我们随时可以 restore。',1,['controller','collocation'],'phrase');

// ===== SENTENCE PATTERNS (15+) =====
add('Please send the error code.','sentence_pattern','请发送错误代码','ask for code','Robot Controller','diagnose issue','remote support','support engineer','Please send the error code so I can look it up in the service manual before our call.','请 send the error code 这样我可以在通话前在服务手册中查找。',1,['controller','sentence_pattern'],'sentence_pattern');
add('The sensor is not responding.','sentence_pattern','传感器没有响应','sensor dead','Sensors and I/O','diagnose issue','onsite troubleshooting','maintenance engineer','The sensor is not responding at all so check the power supply before replacing it.','传感器完全没有响应所以先检查电源再考虑更换。',1,['sensor','sentence_pattern'],'sentence_pattern');
add('The cable looks loose.','sentence_pattern','线缆看起来松了','loose wire','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The cable looks loose where it enters the connector so push it in until it clicks.','在进入连接器的地方线缆看起来松了所以推入直到听到咔嗒声。',1,['electrical','sentence_pattern'],'sentence_pattern');
add('The motor is too hot.','sentence_pattern','电机太热了','overheating','Servo Motor and Drive','diagnose issue','onsite troubleshooting','maintenance engineer','The motor is too hot after just twenty minutes of running so the cooling fan may have failed.','仅运行二十分钟后电机就太热了所以冷却风扇可能坏了。',1,['motor','sentence_pattern'],'sentence_pattern');
add('We replaced the fuse.','sentence_pattern','我们换了保险丝','fuse swap','Electrical Cabinet','part replacement','onsite troubleshooting','robot technician','We replaced the fuse but it blew again after ten minutes which means there is a short circuit somewhere.','我们换了保险丝但十分钟后又烧了说明某处有短路。',2,['electrical','sentence_pattern'],'sentence_pattern');
add('Try to power cycle it first.','sentence_pattern','先试着断电重启','basic fix','Robot Controller','troubleshoot','remote support','support engineer','Try to power cycle it first before we go through the full troubleshooting procedure.','先试试断电重启再走完整的故障排查程序。',1,['controller','sentence_pattern'],'sentence_pattern');
add('The alarm cleared after reset.','sentence_pattern','复位后报警清除了','alarm gone','Robot Controller','diagnose issue','onsite troubleshooting','field service engineer','The alarm cleared after reset and the robot has been running fine for the last hour.','复位后报警清除了机器人过去一小时一直运行正常。',1,['controller','sentence_pattern'],'sentence_pattern');
add('The connector may be loose.','sentence_pattern','连接器可能松了','possible loose','Electrical Cabinet','diagnose issue','remote support','support engineer','The connector may be loose because the fault only appears when the robot runs at high speed.','连接器可能松了因为故障只在机器人高速运行时出现。',1,['electrical','sentence_pattern'],'sentence_pattern');
add('The voltage looks too low.','sentence_pattern','电压看起来太低了','low volts','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The voltage looks too low on the 24-volt supply so check the power supply module.','24 伏电源上的电压看起来太低了所以检查电源模块。',1,['electrical','sentence_pattern'],'sentence_pattern');
add('The robot stops near the gate.','sentence_pattern','机器人在门附近停下了','stops at gate','Safety and Interlock','diagnose issue','onsite troubleshooting','field service engineer','The robot stops near the gate every time which suggests an issue with the safety zone setup.','机器人每次都在门附近停下说明安全区域设置有问题。',2,['safety','sentence_pattern'],'sentence_pattern');
add('The drive is not enabled.','sentence_pattern','驱动器没有被启用','drive off','Servo Motor and Drive','diagnose issue','remote support','support engineer','The drive is not enabled so check the enable signal from the safety PLC.','驱动器没有被启用所以检查来自安全 PLC 的启用信号。',2,['motor','sentence_pattern'],'sentence_pattern');
add('The sensor keeps dropping out.','sentence_pattern','传感器一直断信号','sensor intermittent','Sensors and I/O','diagnose issue','remote support','support engineer','The sensor keeps dropping out for a few milliseconds which is enough to stop the robot.','传感器一直断信号几毫秒足以停止机器人。',2,['sensor','sentence_pattern'],'sentence_pattern');
add('The gripper loses vacuum.','sentence_pattern','夹爪失去真空了','vacuum loss','Pneumatics and Vacuum','diagnose issue','onsite troubleshooting','maintenance engineer','The gripper loses vacuum after a few cycles so check the air line for a leak.','夹爪运行几个循环后失去真空所以检查气管是否有泄漏。',2,['pneumatic','sentence_pattern'],'sentence_pattern');
add('The alarm came back after reboot.','sentence_pattern','重启后报警又回来了','recurring alarm','Robot Controller','diagnose issue','remote support','support engineer','The alarm came back after reboot which means the fault is not a one-time glitch.','重启后报警又回来了说明故障不是一次性的。',2,['controller','sentence_pattern'],'sentence_pattern');
add('Can you check the grounding?','sentence_pattern','能检查一下接地吗？','verify earth','Electrical Cabinet','diagnose issue','remote support','support engineer','Can you check the grounding on the controller because we are seeing noise on all encoder channels.','能检查一下控制器上的接地吗因为我们在所有编码器通道上都看到了噪声。',2,['electrical','sentence_pattern'],'sentence_pattern');

// === EXTRA VERBS ===
add('calibrate','verb','校准','set zero','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','We need to calibrate the robot after replacing the encoder on axis three.','更换三轴编码器后我们需要 calibrate 机器人。',2,['calibration','verb']);
add('align','verb','对中','adjust position','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','Align the motor shaft with the gearbox input before tightening the mounting bolts.','在拧紧安装螺栓之前 align 电机轴与齿轮箱输入。',2,['calibration','verb']);
add('replace','verb','更换','swap out','Replacement and Spare Parts','part replacement','onsite troubleshooting','field service engineer','Replace the worn gearbox before it fails completely and causes a production stop.','在完全失效并导致停产之前 replace worn gearbox。',1,['repair','verb']);
add('swap','verb','更换','exchange','Replacement and Spare Parts','part replacement','onsite troubleshooting','field service engineer','We swapped the encoder and the fault cleared so we will send the old one for testing.','我们 swap 了编码器故障清除了所以我们会把旧的那个送去检测。',1,['repair','verb']);
add('tighten','verb','拧紧','make tight','Mechanical Wear','maintain','preventive maintenance','robot technician','Tighten all the mounting bolts on the robot base every six months.','每六个月 tighten 机器人底座上的所有安装螺栓。',1,['mechanical','verb']);
add('inspect','verb','检查','look closely','Troubleshooting Workflow','diagnose issue','preventive maintenance','maintenance engineer','Inspect the cable chain for any signs of wear where the cables bend repeatedly.','inspect cable chain 线缆反复弯曲处是否有磨损迹象。',1,['maintenance','verb']);
add('reset','verb','复位','clear','Robot Controller','troubleshoot','remote support','support engineer','Reset the controller and see if the fault clears before we start replacing parts.','在我们开始更换部件之前 reset 控制器看看故障是否清除。',1,['controller','verb']);
add('reboot','verb','重新启动','restart fully','Robot Controller','troubleshoot','remote support','support engineer','Reboot the entire robot system including the safety PLC and the pendant.','reboot 整个机器人系统包括安全 PLC 和 pendant。',1,['controller','verb']);
add('mount','verb','安装','attach firmly','Mechanical Wear','part replacement','onsite troubleshooting','field service engineer','Mount the new motor carefully and make sure the flange sits flush against the gearbox.','小心地 mount 新电机确保法兰与齿轮箱平齐。',1,['mechanical','verb']);
add('disconnect','verb','断开','remove connection','Electrical Cabinet','safety check','onsite troubleshooting','robot technician','Disconnect the main power before you open the panel door.','在你打开 panel 门之前 disconnect 主电源。',1,['safety','verb']);
add('reconnect','verb','重新连接','connect again','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','Reconnect all the cables and power on the system to see if the fault is gone.','reconnect 所有线缆并通电看看故障是否消失。',1,['electrical','verb']);
add('power on','verb','通电','apply power','Robot Controller','troubleshoot','onsite troubleshooting','field service engineer','Power on the controller and watch the pendant for any error messages during the boot sequence.','power on 控制器在启动过程中观察 pendant 是否有 error 消息。',1,['power','verb'],'phrase');
add('shut off','verb','关闭','turn off','Robot Controller','safety check','onsite troubleshooting','robot technician','Shut off the robot before performing any mechanical work inside the cell.','在 cell 内进行任何机械工作之前 shut off 机器人。',1,['safety','verb'],'phrase');

// === EXTRA ADJECTIVES ===
add('damaged','adjective','损坏的','broken','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The cable insulation is damaged where it rubs against the frame so it needs replacing.','线缆绝缘层在摩擦框架的地方 damaged 了所以需要更换。',1,['electrical','adjective']);
add('corroded','adjective','腐蚀的','rusty','Electrical Cabinet','diagnose issue','preventive maintenance','maintenance engineer','The terminal block is corroded from moisture so we need to replace it and fix the seal.','端子排因湿气 corroded 了所以我们需要更换它并修复密封。',2,['electrical','adjective']);
add('disconnected','adjective','断开状态的','not connected','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The ground wire is disconnected from the cabinet frame which is a safety hazard.','地线从 cabinet frame 上 disconnected 了这是一个安全隐患。',1,['electrical','adjective']);
add('shielded','adjective','屏蔽的','noise protected','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','The encoder cable must be shielded to prevent interference from the adjacent motor cables.','编码器线缆必须 shielded 以防止来自相邻电机线缆的干扰。',2,['electrical','adjective']);
add('grounded','adjective','接地的','earthed','Electrical Cabinet','electrical inspection','onsite troubleshooting','maintenance engineer','Make sure the cabinet is properly grounded before turning on the main breaker.','在打开 main breaker 之前确保柜子正确 grounded。',1,['electrical','adjective']);
add('burnt','adjective','烧毁的','destroyed by heat','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The contactor coil looks burnt and there is a strong smell near the panel.','contactor coil 看起来 burnt 了面板附近有强烈的味道。',1,['electrical','adjective']);
add('manual','adjective','手动的','by hand','Robot Controller','diagnose issue','onsite troubleshooting','field service engineer','Put the controller in manual mode before you try to move any axis.','在尝试移动任何轴之前将控制器置于 manual 模式。',1,['controller','adjective']);
add('automatic','adjective','自动的','self-running','Robot Controller','safety check','onsite troubleshooting','field service engineer','The cell is running in automatic mode so keep the safety gate closed at all times.','cell 在 automatic 模式下运行所以始终保持 safety gate 关闭。',1,['controller','adjective']);
add('onsite','adjective','现场的','at location','Field Service Report','diagnose issue','onsite troubleshooting','field service engineer','We need an onsite visit because the fault cannot be diagnosed remotely.','我们需要 onsite visit 因为故障无法远程诊断。',1,['service','adjective']);
add('remote','adjective','远程的','from distance','Field Service Report','diagnose issue','remote support','support engineer','The remote diagnostic tool shows that the controller has been running for 12000 hours.','remote diagnostic tool 显示控制器已经运行了 12000 小时。',1,['service','adjective']);

// === BATCH 2: MORE UNIQUE VERBS AND ADJECTIVES ===
add('cycle','verb','循环通断电','power off and on','Robot Controller','troubleshoot','remote support','support engineer','Cycle the power to the controller and see if the fault clears after reboot.','cycle 控制器电源看看重启后故障是否清除。',1,['controller','verb']);
add('diagnose','verb','诊断','find the problem','Troubleshooting Workflow','diagnose issue','onsite troubleshooting','field service engineer','We need to diagnose whether the fault is in the drive or the motor before ordering parts.','在订购部件之前我们需要 diagnose 故障是在驱动器还是电机。',2,['method','verb']);
add('jog','verb','点动','move slowly','Robot Controller','diagnose issue','onsite troubleshooting','field service engineer','Jog the axis slowly and watch the position feedback for any jumps.','慢慢 jog 轴观察位置反馈是否有跳动。',1,['controller','verb']);
add('home','verb','回零','return to zero','Calibration and Homing','calibration','onsite troubleshooting','field service engineer','Home all axes after the mastering procedure is complete.','在 mastering 程序完成后 home 所有轴。',2,['calibration','verb']);
add('override','verb','超控','bypass safety','Safety and Interlock','diagnose issue','onsite troubleshooting','field service engineer','You can override the safety signal with a key switch but only for maintenance mode.','你可以用钥匙开关 override 安全信号但只能在 maintenance 模式下。',2,['safety','verb']);
add('release brake','verb','释放制动器','free the brake','Servo Motor and Drive','diagnose issue','onsite troubleshooting','field service engineer','Release the brake manually and check if the axis moves freely by hand.','手动 release brake 检查轴是否可以手动自由移动。',2,['motor','verb'],'phrase');
add('log event','verb','记录事件','record occurrence','Troubleshooting Workflow','diagnose issue','remote support','support engineer','Log every alarm event with the exact time and axis number for later analysis.','log event 每个报警记录准确的时间和轴号以备后续分析。',1,['method','verb'],'phrase');
add('check parameter','verb','检查参数','verify config','Robot Controller','diagnose issue','remote support','support engineer','Check the parameter settings on the drive because the maximum speed might have been changed accidentally.','check parameter 驱动器上的设置因为最大速度可能被意外更改了。',1,['controller','verb'],'phrase');
add('tune gain','verb','调整增益','adjust PID','Servo Motor and Drive','diagnose issue','onsite troubleshooting','field service engineer','We need to tune the gain on axis two because the robot is oscillating at high speed.','我们需要 tune gain 二号轴因为机器人在高速时在振荡。',3,['motor','verb'],'phrase');
add('replace belt','verb','更换皮带','swap timing belt','Mechanical Wear','part replacement','onsite troubleshooting','field service engineer','Replace the timing belt on axis four because it shows signs of cracking.','replace belt 四号轴的同步带因为它显示出开裂的迹象。',2,['mechanical','verb'],'phrase');
add('drain oil','verb','排油','remove old oil','Mechanical Wear','maintain','preventive maintenance','robot technician','Drain the old gearbox oil before you refill it with fresh lubricant.','在用新鲜润滑油重新加注之前 drain oil 旧齿轮箱油。',2,['mechanical','verb'],'phrase');
add('clean fan','verb','清洁风扇','remove dust','Electrical Cabinet','maintain','preventive maintenance','robot technician','Clean the cooling fan on the drive because dust buildup is causing it to overheat.','clean fan 驱动器上的因为灰尘积聚导致过热。',1,['electrical','verb'],'phrase');

add('balanced','adjective','平衡的','even','Calibration and Homing','diagnose issue','calibration','field service engineer','The load must be balanced before the robot can run at full speed.','负载必须 balanced 才能让机器人全速运行。',2,['calibration','adjective']);
add('bent','adjective','弯曲的','not straight','Mechanical Wear','diagnose issue','onsite troubleshooting','maintenance engineer','One of the pins in the connector is bent so the signal is intermittent.','连接器中的一个针脚 bent 了所以信号是 intermittent 的。',1,['electrical','adjective']);
add('cracked','adjective','开裂的','split','Mechanical Wear','diagnose issue','preventive maintenance','maintenance engineer','The timing belt is cracked in several places and needs to be replaced immediately.','同步带在好几处 cracked 了需要立即更换。',1,['mechanical','adjective']);
add('leaking','adjective','漏的','fluid escaping','Mechanical Wear','diagnose issue','onsite troubleshooting','maintenance engineer','The gearbox is leaking oil from the input shaft seal.','齿轮箱从输入轴密封处 leaking 油。',1,['mechanical','adjective']);
add('tripped','adjective','跳闸的','safety triggered','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The main breaker is tripped so check if anything shorted in the cabinet.','主断路器 tripped 了所以检查柜子里是否有短路。',1,['electrical','adjective']);
add('seized','adjective','卡死的','cannot move','Mechanical Wear','diagnose issue','onsite troubleshooting','field service engineer','The bearing is seized and the axis cannot turn at all even with the brake released.','轴承 seized 了即使制动器释放了轴也完全无法转动。',2,['mechanical','adjective']);
add('flat','adjective','扁平的','not round','Mechanical Wear','diagnose issue','preventive maintenance','maintenance engineer','The roller has a flat spot from wear which causes vibration at high speed.','滚轮有一个 flat spot 由磨损引起导致高速时振动。',1,['mechanical','adjective']);
add('cracked','adjective','开裂的','broken surface','Electrical Cabinet','diagnose issue','onsite troubleshooting','maintenance engineer','The fuse holder is cracked so replace it before it causes an intermittent connection.','保险丝座 cracked 了所以更换它以免导致 intermittent connection。',1,['electrical','adjective']);

const updated=data.concat(newItems);
fs.writeFileSync(file,JSON.stringify(updated));
console.log('Maint POS: Added',added,'| Skipped:',skipped,'| New total:',updated.length);
console.log('  Verbs:',newItems.filter(x=>x.partOfSpeech==='verb').length);
console.log('  Phrasal verbs:',newItems.filter(x=>x.partOfSpeech==='phrasal_verb').length);
console.log('  Adjectives:',newItems.filter(x=>x.partOfSpeech==='adjective').length);
console.log('  Collocations:',newItems.filter(x=>x.partOfSpeech==='collocation').length);
console.log('  Sentence patterns:',newItems.filter(x=>x.partOfSpeech==='sentence_pattern').length);
