const fs=require('fs');
const file='src/data/packs/robotics-rd-engineering-research-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));
const newItems=[];let id=data.length+1,added=0,skipped=0;

function add(t,pos,sm,sis,topic,ra,us,work,ex,ez,diff,tg,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  const item={
    id:'robotics-rd-engineering-research-1000-'+String(id).padStart(4,'0'),
    packId:'robotics-rd-engineering-research-1000',
    term:t,
    type:type||'word',
    partOfSpeech:pos,
    topic,researchArea:ra||'',usageScene:us||'',
    workIntent:work||'',
    shortMeaning:sm,
    shortMeaningInSentence:sis,
    example:ex,exampleZh:ez,
    register:reg||'workplace',
    difficulty:diff||2,
    sourceType:'robotics_rd_style_original',
    sourceTitle:'Original robotics R&D learning sentence',
    sourceUrl:'',sourceDate:'',
    isRealSourceSentence:false,
    tags:tg||['robotics-rd']
  };
  newItems.push(item);
  id++;added++;return true;
}

// ===== VERBS (40+) =====
add('build','verb','构建','compile','ROS2 / Middleware / System Architecture','system architecture','system design','build','Build the workspace with colcon before launching any node.','在启动任何节点之前先用 colcon build workspace。',2,['ros2','verb']);
add('run','verb','运行','start','ROS2 / Middleware / System Architecture','system architecture','system design','execute','Run the node with verbose logging to see if any callbacks are being dropped.','用 verbose logging run 节点看看是否有 callback 被丢弃。',1,['ros2','verb']);
add('configure','verb','配置','set up','ROS2 / Middleware / System Architecture','system architecture','system design','configure','Configure the QoS profile to use reliable transport for the scan topic.','Configure scan topic 的 QoS profile 使用 reliable transport。',2,['ros2','verb']);
add('initialize','verb','初始化','start up','Control / ros2_control / Real-time Systems','control','system design','initialize','Initialize the controller after the hardware interface reports that all motors are ready.','在 hardware interface 报告所有 motor 就绪后 initialize controller。',2,['control','verb']);
add('restart','verb','重启','start again','ROS2 / Middleware / System Architecture','system architecture','debugging','restart','If the node stops publishing we restart the lifecycle manager automatically.','如果节点停止 publish 我们自动 restart lifecycle manager。',1,['ros2','verb']);
add('publish','verb','发布','send','ROS2 / Middleware / System Architecture','system architecture','code review','publish','Publish the odometry at 50 Hz or the EKF will complain about stale data.','以 50 Hz publish odometry 否则 EKF 会报 stale data。',2,['ros2','verb']);
add('subscribe','verb','订阅','listen to','ROS2 / Middleware / System Architecture','system architecture','code review','subscribe','Subscribe to the joint states so the planner always has the latest arm configuration.','Subscribe to joint states 这样 planner 始终有最新的 arm 配置。',2,['ros2','verb']);
add('broadcast','verb','广播','send wider','Control / ros2_control / Real-time Systems','system architecture','system design','broadcast','Broadcast the updated TF tree after the robot re-localizes.','在 robot re-localize 后 broadcast 更新后的 TF tree。',2,['ros2','verb']);
add('trigger','verb','触发','cause','ROS2 / Middleware / System Architecture','system architecture','debugging','trigger','The watchdog timer triggers a safety stop if no message arrives within 100 milliseconds.','如果在 100 毫秒内没有 message 到达 watchdog timer 会 trigger safety stop。',2,['ros2','verb']);
add('throttle','verb','限速','limit rate','ROS2 / Middleware / System Architecture','system architecture','system design','optimize','We throttled the point cloud publishing to 10 Hz to reduce network load.','我们把 point cloud 的 publish Throttle 到 10 Hz 以减少网络负载。',3,['ros2','verb']);
add('interpolate','verb','插值','fill between','Motion Planning / Trajectory Optimization','planning','system design','improve','Interpolate waypoints with a cubic spline to get smoother motion.','用 cubic spline interpolate waypoints 以获得更平滑的运动。',3,['planning','verb']);
add('clamp','verb','限幅','limit range','Control / ros2_control / Real-time Systems','control','system design','constrain','Clamp the velocity command to prevent the robot from exceeding the safety limit.','Clamp velocity command 以防止 robot 超过 safety limit。',2,['control','verb']);
add('normalize','verb','归一化','scale to 1','Perception / Sensor Fusion / 3D Vision','perception','code review','preprocess','Normalize the intensity values before feeding them into the detection model.','在送入 detection model 之前 normalize intensity values。',2,['perception','verb']);
add('fuse','verb','融合','combine','Perception / Sensor Fusion / 3D Vision','perception','system design','integrate','We fuse lidar and camera data to get both depth and semantic labels.','我们 fuse lidar 和 camera data 以获得 depth 和 semantic labels。',3,['perception','verb']);
add('project','verb','投影','map 3D to 2D','Perception / Sensor Fusion / 3D Vision','perception','system design','transform','Project the 3D bounding box into the image plane to check alignment.','把 3D bounding box project 到 image plane 上以检查 alignment。',3,['perception','verb']);
add('infer','verb','推理','run model','Robot Learning / Embodied AI / Policy Learning','robot learning','experiment report','run','Infer the action from the observation in under 5 milliseconds on the onboard GPU.','在 onboard GPU 上在 5 毫秒内 infer action from observation。',3,['robot learning','verb']);
add('render','verb','渲染','draw','Simulation / Gazebo / Digital Twin','simulation','simulation test','visualize','Render the occupancy grid in RViz so we can visually check the inflation layer.','在 RViz 中 render occupancy grid 以便视觉检查 inflation layer。',2,['simulation','verb']);
add('parse','verb','解析','read','ROS2 / Middleware / System Architecture','system architecture','code review','parse','Parse the URDF to extract joint limits and load them into the controller config.','Parse URDF 提取 joint limits 并加载到 controller config 中。',2,['ros2','verb']);
add('serialize','verb','序列化','convert to bytes','ROS2 / Middleware / System Architecture','system architecture','code review','format','Serialize the custom message and check its size before sending it over DDS.','在通过 DDS 发送之前 serialize custom message 并检查其大小。',3,['ros2','verb']);
add('resolve','verb','解析','find','ROS2 / Middleware / System Architecture','system architecture','debugging','solve','The node failed to start because it could not resolve the dependency at runtime.','节点启动失败因为在 runtime 无法 resolve dependency。',2,['ros2','verb']);
add('probe','verb','探测','check','Hardware / Actuator / Sensor / Mechanical','hardware','real robot test','measure','Probe the CAN bus to verify that the motor driver is receiving torque commands.','Probe CAN bus 以验证 motor driver 是否收到 torque commands。',3,['hardware','verb']);
add('mount','verb','挂载','attach to','Hardware / Actuator / Sensor / Mechanical','hardware','real robot test','attach','Mount the lidar on top of the robot and remeasure the extrinsic calibration.','把 lidar mount 在 robot 顶部然后重新测量 extrinsic calibration。',1,['hardware','verb']);
add('detach','verb','分离','remove','Hardware / Actuator / Sensor / Mechanical','hardware','real robot test','detach','Detach the gripper before running the torque test on the wrist joint.','在 wrist joint 上运行 torque test 之前 detach gripper。',2,['hardware','verb']);
add('calibrate','verb','标定','adjust','Perception / Sensor Fusion / 3D Vision','perception','real robot test','calibrate','Calibrate the camera with a checkerboard before running any visual SLAM.','在运行任何 visual SLAM 之前用 checkerboard calibrate camera。',2,['perception','verb']);
add('tune','verb','调参','adjust values','Control / ros2_control / Real-time Systems','control','experiment report','improve','We tuned the PID gains with Ziegler-Nichols and then fine-tuned manually on the real robot.','我们用 Ziegler-Nichols tune PID gains 然后在 real robot 上手动 fine-tune。',3,['control','verb']);
add('estimate','verb','估计','compute','SLAM / Localization / Mapping','slam','experiment report','compute','Estimate the robot pose by fusing wheel odometry with IMU and lidar data.','通过融合 wheel odometry 与 IMU 和 lidar data 来 estimate robot pose。',2,['slam','verb']);
add('localize','verb','定位','find position','SLAM / Localization / Mapping','slam','real robot test','locate','The robot localizes against a prior map using lidar scan matching.','Robot 使用 lidar scan matching localize against a prior map。',2,['slam','verb']);
add('plan','verb','规划','compute path','Motion Planning / Trajectory Optimization','planning','experiment report','compute','Plan a collision-free path from the current pose to the target waypoint.','从当前 pose 到 target waypoint plan 一条 collision-free path。',2,['planning','verb']);
add('detect','verb','检测','find','Perception / Sensor Fusion / 3D Vision','perception','experiment report','detect','Detect dynamic obstacles with a Kalman filter tracker on the clustered point cloud.','在 clustered point cloud 上用 Kalman filter tracker detect dynamic obstacles。',2,['perception','verb']);
add('classify','verb','分类','label','Perception / Sensor Fusion / 3D Vision','perception','experiment report','classify','Classify each cluster as pedestrian vehicle or static background.','把每个 cluster classify 为 pedestrian vehicle 或 static background。',2,['perception','verb']);
add('segment','verb','分割','split','Perception / Sensor Fusion / 3D Vision','perception','experiment report','process','Segment the ground plane first before clustering the remaining points.','在聚类剩余点之前先 segment ground plane。',2,['perception','verb']);
add('align','verb','对齐','match','Perception / Sensor Fusion / 3D Vision','perception','code review','match','Align the two point clouds with ICP and compute the RMS error.','用 ICP align 两个 point cloud 并计算 RMS error。',3,['perception','verb']);
add('register','verb','配准','align','Perception / Sensor Fusion / 3D Vision','perception','experiment report','match','Register the current scan to the global map to correct the odometry drift.','把 current scan register 到 global map 以纠正 odometry drift。',3,['slam','verb']);
add('smooth','verb','平滑','make smooth','Motion Planning / Trajectory Optimization','planning','code review','improve','Smooth the trajectory with a quadratic programming optimizer to reduce jerk.','用 quadratic programming optimizer smooth trajectory 以减少 jerk。',3,['planning','verb']);
add('optimize','verb','优化','make better','Motion Planning / Trajectory Optimization','planning','benchmark analysis','improve','We optimized the planner to finish within 50 ms on a 100-by-100-meter map.','我们 optimize planner 使其在 100x100 米地图上在 50 毫秒内完成。',3,['planning','verb']);
add('visualize','verb','可视化','show','Simulation / Gazebo / Digital Twin','simulation','simulation test','observe','Visualize the planned path and the actual trajectory to spot the overshoot.','Visualize planned path 和 actual trajectory 以发现 overshoot。',1,['simulation','verb']);
add('record','verb','录制','save','Experiment / Benchmark / Evaluation','system architecture','benchmark analysis','collect','Record a rosbag of all topics during the field test so we can replay and analyse later.','在场测期间 record 所有 topic 的 rosbag 以便后续 replay 和分析。',1,['ros2','verb']);
add('replay','verb','回放','play back','Experiment / Benchmark / Evaluation','system architecture','debugging','reproduce','Replay the recorded bag file to check if the detection pipeline drops frames.','Replay 录制的 bag file 以检查 detection pipeline 是否丢帧。',2,['ros2','verb']);
add('reproduce','verb','复现','make happen again','Experiment / Benchmark / Evaluation','system architecture','debugging','verify','We cannot reproduce the crash on the bench but it happens every time on the real robot.','我们在 bench 上无法 reproduce crash 但 real robot 上每次都发生。',2,['ros2','verb']);
add('deploy','verb','部署','put on robot','ROS2 / Middleware / System Architecture','system architecture','system design','release','Deploy the updated planner to the robot and run the regression tests before the demo.','在 demo 前把更新后的 planner deploy 到 robot 上并运行 regression tests。',2,['ros2','verb']);
add('monitor','verb','监控','watch','ROS2 / Middleware / System Architecture','system architecture','debugging','observe','Monitor the CPU temperature during the stress test because throttling kicks in above 80 degrees.','在 stress test 期间 monitor CPU temperature 因为超过 80 度会 throttling。',2,['hardware','verb']);
add('profile','verb','性能分析','measure perf','Engineering Collaboration / Debugging','system architecture','debugging','measure','Profile the callback execution time to find which subscriber is blocking the executor.','Profile callback execution time 以找出哪个 subscriber 在 block executor。',3,['ros2','verb']);
add('compare','verb','对比','check against','Experiment / Benchmark / Evaluation','planning','benchmark analysis','evaluate','We compared three planners on the same benchmark and MPPI had the lowest path cost.','我们在同一个 benchmark 上 compare 三个 planner MPPI 的 path cost 最低。',1,['planning','verb']);
add('evaluate','verb','评估','assess','Experiment / Benchmark / Evaluation','planning','benchmark analysis','measure','Evaluate the planner across 500 randomized scenes and report the success rate.','在 500 个随机场景中 evaluate planner 并报告 success rate。',2,['planning','verb']);
add('iterate','verb','迭代','refine','Engineering Collaboration / Debugging','system architecture','experiment report','improve','We iterate on the controller gains daily during the tuning phase and track every change.','在 tuning 阶段我们每天 iterate controller gains 并 tracking 每次改动。',2,['control','verb']);
add('approximate','verb','近似','rough compute','Motion Planning / Trajectory Optimization','planning','system design','compute','Approximate the robot footprint as a circle to speed up collision checking.','把 robot footprint approximate 成圆形以加速 collision checking。',2,['planning','verb']);
add('constrain','verb','约束','limit','Motion Planning / Trajectory Optimization','planning','system design','constrain','Constrain the search space to the known free regions from the static map.','把 search space Constrain 到 static map 中的 known free regions。',2,['planning','verb']);
add('preempt','verb','抢先','interrupt','Navigation / Nav2 / Behavior Trees','navigation','system design','handle','The recovery behavior preempts the current plan and moves to a clear area.','recovery behavior preempt 当前 plan 并移动到一个 clear area。',3,['navigation','verb']);
add('traverse','verb','穿越','move through','Navigation / Nav2 / Behavior Trees','navigation','experiment report','navigate','The robot traverses the narrow corridor at half speed using a tighter costmap.','Robot 以 half speed traverse narrow corridor 使用 tighter costmap。',2,['navigation','verb']);
add('approach','verb','接近','move toward','Navigation / Nav2 / Behavior Trees','navigation','experiment report','navigate','Approach the docking station from the front and stop 30 centimeters away.','从正前方 approach docking station 并停在 30 厘米处。',1,['navigation','verb']);
add('recover','verb','恢复','get back','Navigation / Nav2 / Behavior Trees','navigation','system design','recover','If the robot gets stuck it should recover by backing up and replanning.','如果 robot 卡住了应该通过后退并 replan 来 recover。',2,['navigation','verb']);
add('abort','verb','中止','stop','Navigation / Nav2 / Behavior Trees','navigation','system design','stop','The planner aborts the goal if no valid path is found within the time limit.','如果在 time limit 内没有找到 valid path planner 会 abort goal。',2,['navigation','verb']);
add('cancel','verb','取消','stop','Navigation / Nav2 / Behavior Trees','navigation','code review','stop','The user sends a cancel request and the action server terminates the current goal.','User sends a cancel request action server 终止 current goal。',1,['navigation','verb']);

// ===== PHRASAL VERBS (18+) =====
add('spin up','phrasal_verb','启动','start','ROS2 / Middleware / System Architecture','system architecture','debugging','start','Spin up a second node to act as a mock sensor so we can test without hardware.','Spin up 一个 second node 作为 mock sensor 这样我们可以不用 hardware 测试。',1,['ros2','phrasal_verb'],'phrase');
add('shut down','phrasal_verb','关闭','stop','ROS2 / Middleware / System Architecture','system architecture','system design','stop','Shut down all nodes gracefully by calling the lifecycle shutdown transition.','通过调用 lifecycle shutdown transition gracefully shut down 所有 node。',2,['ros2','phrasal_verb'],'phrase');
add('bring up','phrasal_verb','启动系统','launch','ROS2 / Middleware / System Architecture','system architecture','system design','start','Bring up the full navigation stack with a single launch file.','用一个 launch file bring up 完整的 navigation stack。',1,['ros2','phrasal_verb'],'phrase');
add('break down','phrasal_verb','分解','split','Engineering Collaboration / Debugging','system architecture','code review','analyse','Break down the monolithic node into smaller components that we can test independently.','把 monolithic node break down 成可以 independently test 的 smaller components。',2,['ros2','phrasal_verb'],'phrase');
add('slow down','phrasal_verb','减速','reduce speed','Navigation / Nav2 / Behavior Trees','navigation','real robot test','navigate','The robot slows down when entering narrow spaces because the costmap inflation increases.','当进入窄空间时 robot slow down 因为 costmap inflation 增加了。',1,['navigation','phrasal_verb'],'phrase');
add('fall back','phrasal_verb','回退','use backup','Navigation / Nav2 / Behavior Trees','navigation','system design','handle','If the primary planner fails the system falls back to a simple reactive controller.','如果 primary planner 失败系统 fall back 到 simple reactive controller。',2,['navigation','phrasal_verb'],'phrase');
add('time out','phrasal_verb','超时','exceed limit','ROS2 / Middleware / System Architecture','system architecture','debugging','fail','The service call times out after five seconds because the action server is not responding.','service call time out 在五秒后因为 action server 没有响应。',2,['ros2','phrasal_verb'],'phrase');
add('drop out','phrasal_verb','丢失','disappear','Perception / Sensor Fusion / 3D Vision','perception','debugging','fail','Lidar points drop out beyond eight meters when the surface is dark and non-reflective.','当表面是 dark and non-reflective 时 lidar points 在八米外 drop out。',2,['perception','phrasal_verb'],'phrase');
add('start up','phrasal_verb','启动','begin','ROS2 / Middleware / System Architecture','system architecture','real robot test','start','The robot starts up in under thirty seconds from power-on to ready-for-navigation.','Robot 从 power-on 到 ready-for-navigation 在不到三十秒内 start up。',1,['ros2','phrasal_verb'],'phrase');
add('switch to','phrasal_verb','切换到','change to','Navigation / Nav2 / Behavior Trees','navigation','code review','switch','Switch to the conservative planner when the robot moves through crowded areas.','当 robot 通过拥挤区域时 switch to conservative planner。',1,['navigation','phrasal_verb'],'phrase');
add('fall behind','phrasal_verb','落后','lag','Perception / Sensor Fusion / 3D Vision','perception','debugging','fail','The tracker falls behind when the person moves faster than two meters per second.','当人移动速度快于 2 m/s 时 tracker fall behind。',2,['perception','phrasal_verb'],'phrase');
add('catch up','phrasal_verb','赶上','recover','Navigation / Nav2 / Behavior Trees','navigation','debugging','recover','The planner catches up after the short freeze and replans from the latest pose.','在短暂的 freeze 后 planner catch up 并从 latest pose replan。',2,['navigation','phrasal_verb'],'phrase');
add('pipe into','phrasal_verb','输入到','feed into','ROS2 / Middleware / System Architecture','system architecture','system design','connect','Pipe the raw lidar output directly into the obstacle detection node.','把 raw lidar output 直接 pipe into obstacle detection node。',2,['ros2','phrasal_verb'],'phrase');
add('feed into','phrasal_verb','传入','input to','Perception / Sensor Fusion / 3D Vision','perception','system design','connect','The depth image feeds into the segmentation model which outputs labeled masks.','depth image feed into segmentation model output labeled masks。',2,['perception','phrasal_verb'],'phrase');
add('roll back','phrasal_verb','回滚','revert','Engineering Collaboration / Debugging','system architecture','debugging','revert','We rolled back the controller update after the regression tests showed a higher failure rate.','在 regression tests 显示 higher failure rate 后我们 roll back 了 controller update。',2,['ros2','phrasal_verb'],'phrase');
add('ramp up','phrasal_verb','逐步增加','increase gradually','Control / ros2_control / Real-time Systems','control','system design','control','Ramp up the motor torque over 500 milliseconds to avoid jerk on the gearbox.','在 500 毫秒内 ramp up motor torque 以避免 gearbox jerk。',3,['control','phrasal_verb'],'phrase');
add('back off','phrasal_verb','后退','move back','Navigation / Nav2 / Behavior Trees','navigation','system design','navigate','The robot backs off when the safety lidar detects an object within the stop zone.','当 safety lidar 在 stop zone 内 detect 到 object 时 robot back off。',1,['navigation','phrasal_verb'],'phrase');
add('wake up','phrasal_verb','唤醒','resume','ROS2 / Middleware / System Architecture','system architecture','system design','start','The node wakes up every 100 milliseconds to check for new commands on the action server.','node 每 100 毫秒 wake up 检查 action server 上的 new commands。',1,['ros2','phrasal_verb'],'phrase');

// ===== ADJECTIVES (28+) =====
add('noisy','adjective','有噪声的','with noise','Perception / Sensor Fusion / 3D Vision','perception','debugging','diagnose','The point cloud is too noisy near the edges because the lidar beam scatters on rough surfaces.','point cloud 在边缘处太 noisy 因为 lidar beam 在 rough surfaces 上散射。',1,['perception','adjective']);
add('deterministic','adjective','确定性的','always same','Control / ros2_control / Real-time Systems','control','code review','ensure','The controller must be deterministic so the same input always produces the same output.','controller 必须是 deterministic 的这样相同输入总是产生相同输出。',3,['control','adjective']);
add('modular','adjective','模块化的','plug-in style','ROS2 / Middleware / System Architecture','system architecture','code review','design','We kept the pipeline modular so swapping the planner does not touch the perception layer.','我们保持 pipeline modular 这样更换 planner 不会影响 perception layer。',2,['ros2','adjective']);
add('reproducible','adjective','可复现的','same every time','Experiment / Benchmark / Evaluation','system architecture','experiment report','ensure','The bug is reproducible only when the CPU is under heavy load which took days to figure out.','这个 bug 只有在 CPU heavy load 时才 reproducible 花了几天才发现。',2,['ros2','adjective']);
add('misaligned','adjective','未对齐的','offset','Perception / Sensor Fusion / 3D Vision','perception','debugging','diagnose','The misaligned camera caused the depth map to be off by two pixels in the image center.','misaligned camera 导致 depth map 在 image center 偏移了两像素。',2,['perception','adjective']);
add('asynchronous','adjective','异步的','not waiting','ROS2 / Middleware / System Architecture','system architecture','code review','design','The asynchronous service call returns immediately and the result arrives in a callback.','asynchronous service call 立即返回结果在 callback 中到达。',3,['ros2','adjective']);
add('synchronous','adjective','同步的','blocking','ROS2 / Middleware / System Architecture','system architecture','code review','design','We switched from synchronous to async processing because the sensor callback was blocking.','我们从 synchronous 切换到 async processing 因为 sensor callback 在 blocking。',2,['ros2','adjective']);
add('lightweight','adjective','轻量的','few resources','Engineering Collaboration / Debugging','system architecture','benchmark analysis','optimize','The lightweight node uses under 10 MB of RAM and runs on the embedded board fine.','lightweight node 只用了不到 10 MB RAM 在 embedded board 上运行良好。',1,['ros2','adjective']);
add('sparse','adjective','稀疏的','few points','Perception / Sensor Fusion / 3D Vision','perception','debugging','diagnose','The sparse point cloud from the stereo camera has fewer points than the lidar scan.','stereo camera 的 sparse point cloud 比 lidar scan 的 point 少。',2,['perception','adjective']);
add('dense','adjective','稠密的','many points','Perception / Sensor Fusion / 3D Vision','perception','benchmark analysis','describe','We use a dense depth image for training but a sparse representation at runtime.','我们在训练时使用 dense depth image 但在 runtime 使用 sparse representation。',2,['perception','adjective']);
add('dynamic','adjective','动态的','changing','Perception / Sensor Fusion / 3D Vision','perception','system design','describe','The dynamic obstacle filter removes moving pedestrians from the static map used for localization.','dynamic obstacle filter 把 moving pedestrians 从用于 localization 的 static map 中移除。',2,['perception','adjective']);
add('static','adjective','静态的','unchanging','SLAM / Localization / Mapping','slam','system design','describe','The static map is built offline and only updated during planned maintenance cycles.','static map 是 offline build 的只在 planned maintenance cycles 期间更新。',1,['slam','adjective']);
add('occluded','adjective','被遮挡的','blocked','Perception / Sensor Fusion / 3D Vision','perception','debugging','diagnose','Part of the target is occluded by a pillar so the detector only sees half of the object.','目标的一部分被 pillar occluded 所以 detector 只看到 object 的一半。',2,['perception','adjective']);
add('cluttered','adjective','杂乱的','messy','Navigation / Nav2 / Behavior Trees','navigation','experiment report','describe','The environment is too cluttered for the global planner to find a path in reasonable time.','environment 太 cluttered 了 global planner 无法在合理时间内找到 path。',2,['navigation','adjective']);
add('jerky','adjective','颠簸的','not smooth','Motion Planning / Trajectory Optimization','planning','real robot test','diagnose','The motion is jerky because the controller is sending velocity commands with too-large time gaps.','motion 是 jerky 因为 controller 发送 velocity commands 的 time gaps 太大。',2,['planning','adjective']);
add('overfitted','adjective','过拟合的','too specific','Robot Learning / Embodied AI / Policy Learning','robot learning','benchmark analysis','diagnose','The policy is overfitted to the training scenes and fails when the lighting changes slightly.','policy overfitted 在 training scenes 上当 lighting 轻微改变就会 fail。',3,['robot learning','adjective']);
add('under-tuned','adjective','欠调的','not enough','Control / ros2_control / Real-time Systems','control','debugging','diagnose','The controller is under-tuned and overshoots by about 20 centimeters on every sharp turn.','controller under-tuned 在每次 sharp turn 时 overshoot 大约 20 厘米。',2,['control','adjective']);
add('well-tuned','adjective','调好的','properly set','Control / ros2_control / Real-time Systems','control','benchmark analysis','describe','A well-tuned PID tracks the setpoint within two percent error across the speed range.','well-tuned PID 在整个 speed range 内 tracking setpoint 误差在百分之二以内。',2,['control','adjective']);
add('drift-prone','adjective','容易漂移的','drifts easily','SLAM / Localization / Mapping','slam','experiment report','diagnose','Wheel odometry alone is drift-prone on slippery floors so we always fuse it with lidar.','单独的 wheel odometry 在 slippery floors 上是 drift-prone 的所以我们总是与 lidar fuse。',3,['slam','adjective']);
add('frame-accurate','adjective','帧精确的','exact timing','Perception / Sensor Fusion / 3D Vision','perception','technical meeting','describe','The timestamp must be frame-accurate or the sensor fusion will produce ghost objects.','timestamp 必须是 frame-accurate 的否则 sensor fusion 会产生 ghost objects。',3,['perception','adjective']);
add('run-time','adjective','运行时的','during execution','ROS2 / Middleware / System Architecture','system architecture','code review','describe','The run-time error only appears when the CPU usage is above 90 percent.','run-time error 只在 CPU usage 高于百分之九十时出现。',2,['ros2','adjective']);
add('hard-coded','adjective','硬编码的','fixed in code','Engineering Collaboration / Debugging','system architecture','code review','identify','The hard-coded timeout of three seconds is too short for the planner on large maps.','hard-coded timeout 三秒对 large maps 上的 planner 来说太短了。',2,['ros2','adjective']);
add('off-by-one','adjective','差一错误','index error','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','An off-by-one error in the waypoint index made the robot skip the second-last point.','waypoint index 中的 off-by-one error 导致 robot skip 了倒数第二个 point。',3,['ros2','adjective']);
add('thread-safe','adjective','线程安全的','concurrent','ROS2 / Middleware / System Architecture','system architecture','code review','ensure','The callback must be thread-safe because the executor runs multiple threads concurrently.','callback 必须是 thread-safe 因为 executor 会 concurrently 运行 multiple threads。',3,['ros2','adjective']);
add('sub-optimal','adjective','次优的','not best','Motion Planning / Trajectory Optimization','planning','benchmark analysis','evaluate','The planner found a sub-optimal path that is about 15 percent longer than the shortest route.','planner 找到了 sub-optimal path 比 shortest route 长约百分之十五。',2,['planning','adjective']);
add('well-defined','adjective','明确定义的','clearly specified','ROS2 / Middleware / System Architecture','system architecture','code review','describe','Make sure the interface is well-defined so that the perception and planning teams can work in parallel.','确保 interface 是 well-defined 的这样 perception 和 planning 团队可以并行工作。',2,['ros2','adjective']);
add('safe-to-deploy','adjective','可安全部署的','ready','Engineering Collaboration / Debugging','system architecture','technical meeting','assess','The planner is safe-to-deploy after passing all 300 benchmark scenarios without a single collision.','在通过所有 300 个 benchmark scenarios 且零碰撞后 planner 是 safe-to-deploy 的。',2,['planning','adjective'],'phrase');

// ===== COLLOCATIONS (25+) =====
add('build the workspace','collocation','构建工作空间','compile workspace','ROS2 / Middleware / System Architecture','system architecture','code review','build','Build the workspace with colcon build and check for any dependency errors.','用 colcon build build the workspace 并检查 dependency errors。',1,['ros2','collocation'],'phrase');
add('publish a topic','collocation','发布话题','send topic','ROS2 / Middleware / System Architecture','system architecture','code review','publish','Publish a topic at exactly 30 Hz or the controller will reject the stale odometry.','以精确 30 Hz publish a topic 否则 controller 会 reject stale odometry。',2,['ros2','collocation'],'phrase');
add('subscribe to a topic','collocation','订阅话题','listen to','ROS2 / Middleware / System Architecture','system architecture','code review','subscribe','Subscribe to a topic in a separate callback group so it does not block the main loop.','在一个 separate callback group 中 subscribe to a topic 这样不会阻塞 main loop。',2,['ros2','collocation'],'phrase');
add('tune the controller','collocation','调控制器','adjust controller','Control / ros2_control / Real-time Systems','control','experiment report','improve','We tuned the controller step by step first the feedforward then the PID feedback.','我们逐步 tune the controller 先 feedforward 然后 PID feedback。',2,['control','collocation'],'phrase');
add('calibrate the sensor','collocation','标定传感器','calibrate sensor','Perception / Sensor Fusion / 3D Vision','perception','real robot test','calibrate','Calibrate the sensor before every field deployment because vibrations throw off the alignment.','每次 field deployment 前 calibrate the sensor 因为 vibration 会让 alignment 偏移。',2,['perception','collocation'],'phrase');
add('transform the point cloud','collocation','变换点云','apply tf','Perception / Sensor Fusion / 3D Vision','perception','code review','transform','Transform the point cloud from sensor frame to base link before feeding it to the planner.','在送入 planner 之前把 point cloud 从 sensor frame transform the point cloud 到 base link。',2,['perception','collocation'],'phrase');
add('filter noisy data','collocation','过滤噪声数据','clean data','Perception / Sensor Fusion / 3D Vision','perception','code review','process','Filter noisy data with a statistical outlier removal before running the segmentation node.','在运行 segmentation node 之前用 statistical outlier removal filter noisy data。',2,['perception','collocation'],'phrase');
add('estimate the pose','collocation','估计位姿','compute pose','SLAM / Localization / Mapping','slam','experiment report','compute','We estimate the pose by fusing lidar odometry with IMU in an extended Kalman filter.','我们通过在 extended Kalman filter 中融合 lidar odometry 与 IMU 来 estimate the pose。',3,['slam','collocation'],'phrase');
add('localize on the map','collocation','在地图上定位','find pose','SLAM / Localization / Mapping','slam','real robot test','locate','The robot localizes on the map within two seconds after waking up using lidar scan matching.','使用 lidar scan matching robot 在唤醒后两秒内 localize on the map。',2,['slam','collocation'],'phrase');
add('plan a collision-free path','collocation','规划无碰撞路径','find safe path','Motion Planning / Trajectory Optimization','planning','experiment report','plan','Plan a collision-free path that keeps at least 20 centimeters from every obstacle.','Plan a collision-free path 与每个 obstacle 保持至少 20 厘米距离。',2,['planning','collocation'],'phrase');
add('smooth the trajectory','collocation','平滑轨迹','make smooth','Motion Planning / Trajectory Optimization','planning','code review','improve','Smooth the trajectory to reduce the maximum curvature so the robot does not slow down too much.','Smooth the trajectory 以减少 maximum curvature 这样 robot 不会过度减速。',3,['planning','collocation'],'phrase');
add('validate the result','collocation','验证结果','check output','Experiment / Benchmark / Evaluation','system architecture','benchmark analysis','verify','Validate the result against ground truth from the motion capture system.','用 motion capture system 的 ground truth 来 validate the result。',2,['planning','collocation'],'phrase');
add('reproduce the issue','collocation','复现问题','recreate bug','Engineering Collaboration / Debugging','system architecture','debugging','debug','We cannot reproduce the issue in simulation because the rendering pipeline does not match real lidar noise.','我们在 simulation 中无法 reproduce the issue 因为 rendering pipeline 不匹配 real lidar noise。',2,['ros2','collocation'],'phrase');
add('reset the controller','collocation','重置控制器','restart controller','Control / ros2_control / Real-time Systems','control','debugging','reset','Reset the controller after the emergency stop clears or it will stay in the fault state.','在 emergency stop 清除后 reset the controller 否则它会保持在 fault state。',2,['control','collocation'],'phrase');
add('launch the stack','collocation','启动技术栈','start full system','ROS2 / Middleware / System Architecture','system architecture','real robot test','start','Launch the stack with a single command and wait for all nodes to report active.','用一个命令 launch the stack 等待所有 node report active。',1,['ros2','collocation'],'phrase');
add('benchmark the planner','collocation','基准测试规划器','test planner','Experiment / Benchmark / Evaluation','planning','benchmark analysis','evaluate','We benchmark the planner across five difficulty levels from empty rooms to crowded mazes.','我们从 empty rooms 到 crowded mazes 共五个难度级别 benchmark the planner。',2,['planning','collocation'],'phrase');
add('record a bag file','collocation','录制 rosbag','save rosbag','Experiment / Benchmark / Evaluation','system architecture','debugging','collect','Record a bag file during the demo so we can check what the robot saw if anything goes wrong.','在 demo 期间 record a bag file 这样如果出了问题我们可以 check robot 看到了什么。',1,['ros2','collocation'],'phrase');
add('replay the dataset','collocation','回放数据','play back','Experiment / Benchmark / Evaluation','system architecture','benchmark analysis','test','Replay the dataset on the updated pipeline and compare the detection recall against the old version.','在 updated pipeline 上 replay the dataset 并 compare detection recall 与 old version。',2,['ros2','collocation'],'phrase');
add('check the timestamp','collocation','检查时间戳','verify time','Perception / Sensor Fusion / 3D Vision','perception','debugging','verify','Check the timestamp of the lidar message against the system clock because it is drifting.','Check the timestamp of lidar message 对照 system clock 因为它正在 drift。',2,['perception','collocation'],'phrase');
add('align the frames','collocation','对齐坐标系','match frames','Perception / Sensor Fusion / 3D Vision','perception','code review','match','Align the frames by publishing a static transform from base link to lidar frame.','通过 publish 从 base link 到 lidar frame 的 static transform 来 align the frames。',2,['perception','collocation'],'phrase');
add('profile the latency','collocation','分析延迟','measure latency','Engineering Collaboration / Debugging','system architecture','debugging','measure','Profile the latency of each stage in the pipeline to find the bottleneck.','Profile the latency 每个 pipeline 阶段以找出 bottleneck。',3,['ros2','collocation'],'phrase');
add('integrate the sensor','collocation','集成传感器','connect sensor','Hardware / Actuator / Sensor / Mechanical','hardware','system design','integrate','Integrate the sensor by wiring it to the CAN bus and configuring the driver.','通过连接到 CAN bus 并 configure driver 来 integrate the sensor。',2,['hardware','collocation'],'phrase');
add('compare against baseline','collocation','对照基线对比','compare w/ baseline','Experiment / Benchmark / Evaluation','planning','benchmark analysis','evaluate','We compare against baseline for every planner update and flag any regression.','每次 planner update 我们 compare against baseline 并 flag 任何 regression。',2,['planning','collocation'],'phrase');
add('scan for obstacles','collocation','扫描障碍物','detect obstacles','Navigation / Nav2 / Behavior Trees','navigation','real robot test','detect','The robot scans for obstacles continuously and updates the costmap before every planning cycle.','Robot 在每次 planning cycle 前 continuously scan for obstacles 并 update costmap。',1,['navigation','collocation'],'phrase');
add('track the object','collocation','跟踪目标','follow object','Perception / Sensor Fusion / 3D Vision','perception','experiment report','track','Track the object in 3D space and maintain the same ID across consecutive frames.','在 3D 空间中 track the object 并在 consecutive frames 之间保持相同的 ID。',2,['perception','collocation'],'phrase');
add('visualize the trajectory','collocation','可视化轨迹','show path','Simulation / Gazebo / Digital Twin','simulation','debugging','observe','Visualize the trajectory in RViz and overlay the planned path to check how close they are.','在 RViz 中 visualize the trajectory 并 overlay planned path 以检查它们有多接近。',1,['simulation','collocation'],'phrase');
add('simulate the world','collocation','仿真环境','run simulation','Simulation / Gazebo / Digital Twin','simulation','simulation test','test','We simulated the world with custom friction parameters to match the real floor material.','我们用 custom friction parameters simulate the world 以匹配 real floor material。',2,['simulation','collocation'],'phrase');

// ===== SENTENCE PATTERNS (20+) =====
add('The node crashes during startup.','sentence_pattern','节点启动时崩溃','crash at start','ROS2 / Middleware / System Architecture','system architecture','debugging','report','The node crashes during startup because it tries to load a parameter before the parameter server is ready.','节点在启动时 crash 因为它试图在 parameter server 就绪之前 load parameter。',2,['ros2','sentence_pattern'],'sentence_pattern');
add('The transform is not available.','sentence_pattern','变换不可用','missing tf','Perception / Sensor Fusion / 3D Vision','perception','debugging','report','The transform is not available and the point cloud frame is stuck at the origin.','transform 不可用 point cloud frame 卡在 origin。',2,['perception','sentence_pattern'],'sentence_pattern');
add('The planner fails near corners.','sentence_pattern','规划器在转角附近失败','corner failure','Motion Planning / Trajectory Optimization','planning','debugging','report','The planner fails near corners because the costmap does not inflate enough for the robot footprint.','planner 在 corner 附近 fail 因为 costmap 没有针对 robot footprint 充分 inflate。',2,['planning','sentence_pattern'],'sentence_pattern');
add('The controller overshoots the target.','sentence_pattern','控制器超过目标','overshoot issue','Control / ros2_control / Real-time Systems','control','debugging','report','The controller overshoots the target by about ten centimeters after every sharp turn.','controller 在每次 sharp turn 后 overshoot target 大约十厘米。',2,['control','sentence_pattern'],'sentence_pattern');
add('The robot drifts after rotating.','sentence_pattern','机器人旋转后漂移','rotation drift','SLAM / Localization / Mapping','slam','debugging','report','The robot drifts after rotating in place because the wheel encoders slip on the polished floor.','robot 在原地 rotate 后 drift 因为 wheel encoders 在 polished floor 上 slip。',2,['slam','sentence_pattern'],'sentence_pattern');
add('The point cloud looks too sparse.','sentence_pattern','点云看起来太稀疏','sparse cloud','Perception / Sensor Fusion / 3D Vision','perception','debugging','report','The point cloud looks too sparse at this range and the detector cannot segment small objects.','point cloud 在这个 range 看起来 too sparse detector 无法 segment small objects。',1,['perception','sentence_pattern'],'sentence_pattern');
add('The camera calibration is off.','sentence_pattern','相机标定偏了','bad calibration','Perception / Sensor Fusion / 3D Vision','perception','debugging','report','The camera calibration is off by about two pixels which causes the depth reprojection error.','camera calibration 偏了大约两像素这导致 depth reprojection error。',2,['perception','sentence_pattern'],'sentence_pattern');
add('The pose estimate keeps diverging.','sentence_pattern','位姿估计一直发散','pose divergence','SLAM / Localization / Mapping','slam','debugging','report','The pose estimate keeps diverging after the robot enters the feature-poor corridor.','在 robot 进入 feature-poor corridor 后 pose estimate 一直 diverge。',3,['slam','sentence_pattern'],'sentence_pattern');
add('The controller misses the waypoint.','sentence_pattern','控制器未到航点','missed waypoint','Control / ros2_control / Real-time Systems','control','debugging','report','The controller misses the waypoint because the lookahead distance is set too short.','controller miss waypoint 因为 lookahead distance 设置得太短。',2,['control','sentence_pattern'],'sentence_pattern');
add('The planner gets stuck in narrow spaces.','sentence_pattern','规划器卡在狭窄空间','stuck planner','Motion Planning / Trajectory Optimization','planning','debugging','report','The planner gets stuck in narrow spaces and keeps replanning without finding a way out.','planner 在 narrow spaces 中 stuck 不断 replan 但找不到出路。',2,['planning','sentence_pattern'],'sentence_pattern');
add('The sensor timestamp drifts over time.','sentence_pattern','传感器时间戳渐渐漂移','timestamp drift','Perception / Sensor Fusion / 3D Vision','perception','debugging','report','The sensor timestamp drifts over time because the internal clock is not synchronized with the system clock.','sensor timestamp 渐渐 drift 因为 internal clock 没有与 system clock synchronized。',3,['perception','sentence_pattern'],'sentence_pattern');
add('The robot moves too slowly for the test.','sentence_pattern','测试中机器人走太慢','too slow','Navigation / Nav2 / Behavior Trees','navigation','benchmark analysis','report','The robot moves too slowly for the test because the safety lidar zone is set to one meter.','robot 对 test 来说 move too slowly 因为 safety lidar zone 设置为一米。',1,['navigation','sentence_pattern'],'sentence_pattern');
add('The trajectory is too jerky for the payload.','sentence_pattern','轨迹太颠簸不适合负载','jerky path','Motion Planning / Trajectory Optimization','planning','real robot test','report','The trajectory is too jerky for the payload because the max acceleration is set too high.','trajectory 对 payload 来说 too jerky 因为 max acceleration 设置得太高。',2,['planning','sentence_pattern'],'sentence_pattern');
add('The baseline fails in this scene.','sentence_pattern','基线在此场景失败','baseline fail','Experiment / Benchmark / Evaluation','planning','benchmark analysis','report','The baseline fails in this scene because the narrow gap is not modeled in the costmap.','baseline 在这个 scene 中 fail 因为 narrow gap 没有在 costmap 中建模。',2,['planning','sentence_pattern'],'sentence_pattern');
add('We should replay the rosbag to check.','sentence_pattern','我们应该回放rosbag','replay suggestion','Engineering Collaboration / Debugging','system architecture','debugging','propose','We should replay the rosbag to check whether the delay is in perception or in planning.','我们应该 replay rosbag 以查看 delay 是在 perception 还是 planning 中。',1,['ros2','sentence_pattern'],'sentence_pattern');
add('The simulation works but the hardware fails.','sentence_pattern','仿真可以但硬件不行','sim-to-real gap','Simulation / Gazebo / Digital Twin','simulation','debugging','report','The simulation works but the hardware fails because the real motor has backlash not modeled in the sim.','simulation works 但 hardware fail 因为 real motor 有 backlash 没有在 sim 中建模。',2,['simulation','sentence_pattern'],'sentence_pattern');
add('We need to patch the controller config.','sentence_pattern','我们需要修改控制器配置','config change','Control / ros2_control / Real-time Systems','control','code review','propose','We need to patch the controller config because the joint limit is too conservative for this workspace.','我们需要 patch controller config 因为 joint limit 对这个 workspace 太保守了。',2,['control','sentence_pattern'],'sentence_pattern');
add('The node is dropping messages under load.','sentence_pattern','节点在高负载下丢消息','message drop','ROS2 / Middleware / System Architecture','system architecture','debugging','report','The node is dropping messages under load and the queue size is already set to 100.','node 在高负载下 dropping messages queue size 已经设为 100。',2,['ros2','sentence_pattern'],'sentence_pattern');
add('Can we merge the two callback groups?','sentence_pattern','能否合并两个回调组？','merge proposal','ROS2 / Middleware / System Architecture','system architecture','code review','propose','Can we merge the two callback groups into one to reduce thread switching overhead.','能否合并两个 callback group 成一个以减少 thread switching overhead。',3,['ros2','sentence_pattern'],'sentence_pattern');
add('The odometry reset after the collision.','sentence_pattern','碰撞后里程计重置了','odom reset','SLAM / Localization / Mapping','slam','debugging','report','The odometry reset after the collision and the robot lost its localization for about five seconds.','collision 后 odometry reset robot 大约五秒钟 lost localization。',2,['slam','sentence_pattern'],'sentence_pattern');
add('The workspace is not clean.','sentence_pattern','工作空间不干净','build issue','ROS2 / Middleware / System Architecture','system architecture','debugging','report','The workspace is not clean and stale build artifacts are causing symbol lookup errors at runtime.','workspace 不干净 stale build artifacts 导致 runtime 出现 symbol lookup errors。',2,['ros2','sentence_pattern'],'sentence_pattern');

// Write updated pack
const updated=data.concat(newItems);
fs.writeFileSync(file,JSON.stringify(updated));
console.log('Robotics R&D POS: Added',added,'| Skipped:',skipped,'| New total:',updated.length);
console.log('  Verbs:',newItems.filter(x=>x.partOfSpeech==='verb').length);
console.log('  Phrasal:',newItems.filter(x=>x.partOfSpeech==='phrasal_verb').length);
console.log('  Adj:',newItems.filter(x=>x.partOfSpeech==='adjective').length);
console.log('  Colloc:',newItems.filter(x=>x.partOfSpeech==='collocation').length);
console.log('  SentPatt:',newItems.filter(x=>x.partOfSpeech==='sentence_pattern').length);

// Update packs.ts
const packsFile='src/data/packs.ts';
let packsContent=fs.readFileSync(packsFile,'utf-8');
packsContent=packsContent.replace(
  /'robotics-rd-engineering-research-1000':\s*\{\s*id:\s*'robotics-rd-engineering-research-1000',\s*title:[^,]*,/,
  "'robotics-rd-engineering-research-1000': {\n    id: 'robotics-rd-engineering-research-1000',\n    title: 'Robotics R&D Engineering Core',"
);
packsContent=packsContent.replace(
  /('robotics-rd-engineering-research-1000'[\s\S]*?total:\s*)\d+/,
  (_,prefix)=>prefix+updated.length
);
fs.writeFileSync(packsFile,packsContent);
console.log('Updated packs.ts total to',updated.length);

// Update status
const statusFile='docs/WORD_PACK_GENERATION_STATUS.json';
const status=JSON.parse(fs.readFileSync(statusFile,'utf-8'));
const rdPack=status.packs.find(p=>p.id==='robotics-rd-engineering-research-1000');
if(rdPack){
  rdPack.total=updated.length;
  rdPack.lastUpdated=new Date().toISOString().split('T')[0];
}
fs.writeFileSync(statusFile,JSON.stringify(status,null,2));
console.log('Updated status file.');
