const fs=require('fs');
const file='src/data/packs/foreign-trade-crowdfunding-dtc-operations-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));

const FF={ROAS:'Return on Ad Spend',CPC:'Cost Per Click',CTR:'Click-Through Rate',CPA:'Cost Per Acquisition',CPM:'Cost Per Mille',AOV:'Average Order Value',MOQ:'Minimum Order Quantity','3PL':'Third-Party Logistics',CRM:'Customer Relationship Management',KPI:'Key Performance Indicator',ROI:'Return on Investment',EXW:'Ex Works',FOB:'Free On Board',CIF:'Cost Insurance Freight',DDP:'Delivered Duty Paid',HS:'Harmonised System',B2B:'Business to Business'};

const newItems=[];let id=data.length+1,added=0,skipped=0;

function add(t,pos,sm,sis,topic,biz,work,ex,ez,diff,tg,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  newItems.push({id:'foreign-trade-crowdfunding-dtc-operations-1000-'+String(id).padStart(4,'0'),packId:'foreign-trade-crowdfunding-dtc-operations-1000',term:t,type:type||'word',partOfSpeech:pos,topic,businessStage:biz||'',workIntent:work||'',shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'workplace',difficulty:diff||2,sourceType:'foreign_trade_dtc_style_original',sourceTitle:'Original foreign trade DTC learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||['dtc'],fullForm:FF[t]||undefined});
  id++;added++;return true;
}

// ===== VERBS (40+) =====
add('quote','verb','报价','give a price','B2B Negotiation / Pricing / Payment','pricing negotiation','provide pricing','Can you quote the wholesale price for 500 units delivered to our warehouse in Hamburg?','你能 quote 500 台发到我们汉堡仓库的批发价吗？',1,['pricing','verb']);
add('deliver','verb','送达','bring to customer','Fulfillment / Logistics','logistics','complete order','We delivered all the rewards to backers in North America by the end of November.','我们在十一月底前 deliver 了所有北美支持者的 rewards。',1,['logistics','verb']);
add('restock','verb','补货','refill inventory','Fulfillment / Logistics','logistics','maintain supply','We need to restock the best-selling variant because it sold out in the first week.','最畅销的变体第一周就卖光了我们需要 restock。',1,['logistics','verb']);
add('bundle','verb','捆绑销售','sell as combo','Shopify / DTC Store','dtc store operation','increase AOV','We bundled the main device with a carrying case and a screen protector at a slight discount.','我们把主设备和收纳盒及屏幕保护膜 bundle 在一起略微打折出售。',1,['sales','verb']);
add('segment','verb','分群','split into groups','Email / CRM','email marketing','target customers','We segmented the email list by purchase history so we can send different offers to first-time buyers.','我们按购买历史 segment 了邮件列表以便向首次购买者发送不同的优惠。',2,['email','verb']);
add('trigger','verb','触发','activate automatically','Email / CRM','email marketing','automate','The abandoned cart email is triggered one hour after the customer leaves the checkout page.','客户离开结账页面一小时后 abandon cart email 就会 trigger。',2,['email','verb']);
add('automate','verb','自动化','run automatically','Email / CRM','email marketing','save time','We automated the post-purchase flow so every customer gets a thank-you email without manual work.','我们 automate 了购后流程这样每个客户都能自动收到感谢邮件无需手动操作。',2,['email','verb']);
add('split','verb','拆分','divide into parts','Fulfillment / Logistics','logistics','manage shipments','We split the order into two shipments because the larger items are ready now but the accessories are delayed.','我们 split 了这个订单分成两批因为大件已经 ready 但配件 delay 了。',2,['logistics','verb']);
add('merge','verb','合并','combine together','Fulfillment / Logistics','logistics','manage shipments','Please merge these two orders from the same customer so we only charge shipping once.','请 merge 这个客户的两个订单这样我们只收一次运费。',2,['logistics','verb']);
add('cancel','verb','取消','call off','Customer Support','customer support','resolve issues','The customer asked to cancel the order because they found a local alternative with faster delivery.','客户要求 cancel 订单因为他们找到了本地替代品可以更快 delivery。',1,['support','verb']);
add('process','verb','处理','handle','Customer Support','customer support','resolve issues','We process returns within 48 hours of receiving the item back at the warehouse.','我们在仓库收到退货后 48 小时内 process return。',1,['support','verb']);
add('verify','verb','核实','check is correct','Customer Support','customer support','prevent errors','Please verify the shipping address before we print the label because the last order was returned.','请在打印标签前 verify 收货地址因为上一单被退回了。',1,['support','verb']);
add('prepare','verb','准备','get ready','Supplier / Foreign Trade','supplier communication','document','I will prepare the commercial invoice and the packing list before the freight forwarder arrives on Friday.','我会在货运代理周五到达之前 prepare commercial invoice 和 packing list。',1,['supplier','verb']);
add('submit','verb','提交','send in','Customer Support','customer support','file','We submitted a claim to the carrier for the lost package and expect a response within two weeks.','我们向承运商 submit 了丢失包裹的 claim 预计两周内回复。',2,['support','verb']);
add('escalate','verb','升级处理','send to higher level','Customer Support','customer support','handle complex','If the refund is over five hundred dollars we need to escalate it to the finance manager.','如果退款超过五百美元我们需要 escalate 给财务经理。',2,['support','verb']);
add('pause','verb','暂停','stop temporarily','Ads / Acquisition','paid acquisition','manage','We paused the campaign over the weekend because the conversion rate was dropping.','我们在周末 pause 了 campaign 因为转化率在下降。',1,['ads','verb']);
add('resume','verb','恢复','start again','Ads / Acquisition','paid acquisition','manage','Let us resume the campaign on Monday morning when our target audience is most active.','我们周一早上 resume campaign 当目标受众最活跃的时候。',1,['ads','verb']);
add('optimize','verb','优化','make better','Ads / Acquisition','paid acquisition','improve','We need to optimize the landing page because the bounce rate is over sixty percent.','我们需要 optimize landing page 因为跳出率超过百分之六十。',2,['ads','verb']);
add('adjust','verb','调整','change slightly','Ads / Acquisition','paid acquisition','improve','I adjusted the daily budget from 200 to 250 dollars because the CPA was trending down.','我把每日预算从 200 adjust 到 250 美元因为 CPA 在下降。',1,['ads','verb']);
add('recover','verb','挽回','get back','Shopify / DTC Store','dtc store operation','save sales','The abandoned cart flow recovered about eight percent of carts that would have been lost.','abandoned cart flow recover 了大约百分之八本来会丢失的购物车。',2,['dtc','verb']);
add('book','verb','预订','reserve','Fulfillment / Logistics','logistics','arrange','I booked the shipment for pickup on Thursday morning with the freight forwarder.','我 book 了周四早上货运代理的 shipment pickup。',1,['logistics','verb']);
add('release','verb','放行','let go','Supplier / Foreign Trade','supplier communication','approve','We cannot release the payment until the quality inspection report comes back clean.','在 quality inspection report 确认没问题之前我们不能 release payment。',2,['supplier','verb']);
add('inspect','verb','检查','look at carefully','Supplier / Foreign Trade','supplier communication','verify','We hired a third-party company to inspect the goods before they left the factory.','我们聘请了第三方公司在货物离开工厂前 inspect。',2,['supplier','verb']);
add('clear','verb','清关','pass customs','Fulfillment / Logistics','logistics','international','The shipment cleared customs this morning and is now on its way to the local distribution centre.','货物今早 clear customs 了现在正在前往当地配送中心的路上。',2,['logistics','verb']);
add('approve','verb','批准','give OK','Supplier / Foreign Trade','supplier communication','confirm','The factory needs us to approve the sample before they can start mass production.','工厂需要我们先 approve sample 才能开始量产。',1,['supplier','verb']);
add('arrange','verb','安排','organise','Fulfillment / Logistics','logistics','coordinate','Can you arrange a pickup with the carrier for tomorrow afternoon after 2pm?','你能 arrange 明天下午两点后的承运商 pickup 吗？',1,['logistics','verb']);
add('contact','verb','联系','get in touch','Supplier / Foreign Trade','supplier communication','reach out','I contacted the supplier about the delayed shipment and they promised an update by Wednesday.','我 contact 了 supplier 关于 delayed shipment 他们承诺周三前回复。',1,['supplier','verb']);
add('collect','verb','收集','gather','Crowdfunding Campaign','post-campaign fulfillment','gather info','We need to collect backer addresses through the pledge manager before we can start fulfillment.','我们需要在开始 fulfillment 之前通过 pledge manager collect backer address。',1,['crowdfunding','verb']);
add('test','verb','测试','try out','Ads / Acquisition','paid acquisition','experiment','We tested three different ad creatives and the user-generated content style performed the best.','我们 test 了三个不同的广告素材用户生成内容风格的表现最好。',1,['ads','verb']);
add('review','verb','审查','check','Ads / Acquisition','paid acquisition','evaluate','Let us review the campaign performance before we decide whether to scale the budget.','在我们决定是否扩大预算之前先 review campaign 表现。',1,['ads','verb']);
add('lock','verb','锁定','fix in place','Fulfillment / Logistics','logistics','finalize','Please lock the shipping address before the fulfillment centre starts processing the batch.','在 fulfillment centre 开始处理这批货之前请 lock shipping address。',1,['logistics','verb']);
add('export','verb','导出','pull out data','Analytics / Reporting','analytics review','get data','I exported all the orders from Shopify so we can send them to the 3PL for fulfillment.','我从 Shopify export 了所有订单以便发给 3PL 进行 fulfillment。',1,['analytics','verb']);
add('issue','verb','发出','send out','Customer Support','customer support','provide','We issued a full refund to the customer because the product arrived with a cracked screen.','我们 issue 了全额退款给客户因为产品到达时屏幕碎裂了。',1,['support','verb']);
add('request','verb','请求','ask for','Customer Support','customer support','ask','The customer requested a replacement unit because the first one stopped working after two days.','客户 request 了一个替换品因为第一台两天后就停止工作了。',1,['support','verb']);
add('check','verb','检查','look at','Fulfillment / Logistics','logistics','verify','Can you check the inventory level for the black variant before we launch the promotion?','你能在推出促销之前 check 黑色款的库存水平吗？',1,['logistics','verb']);
add('ship','verb','发货','send','Fulfillment / Logistics','logistics','deliver','We shipped all the rewards last Friday and backers should receive tracking numbers today.','我们上周五 ship 了所有 rewards backer 今天应该会收到 tracking number。',1,['logistics','verb']);
add('track','verb','追踪','follow','Fulfillment / Logistics','logistics','monitor','Can you track this package because the customer says it has not moved in five days.','你能 track 这个包裹吗客户说已经五天没有更新了。',1,['logistics','verb']);
add('schedule','verb','安排时间','set a time','Supplier / Foreign Trade','supplier communication','plan','I scheduled a call with the supplier for Wednesday morning to discuss the lead time for the next batch.','我 schedule 了周三早上与 supplier 的通话讨论下一批的 lead time。',1,['supplier','verb']);

// ===== PHRASAL VERBS (20+) =====
add('hold back','phrasal_verb','暂缓','delay release','Fulfillment / Logistics','logistics','manage','We held back the shipment for two days because the packaging was not ready.','我们 hold back 了 shipment 两天因为包装还没准备好。',1,['logistics','phrasal_verb'],'phrase');
add('check out','phrasal_verb','结账','complete purchase','Shopify / DTC Store','dtc store operation','purchase','The checkout flow is failing on mobile because customers cannot check out with Apple Pay.','checkout 流程在手机上失败因为客户无法用 Apple Pay check out。',2,['dtc','phrasal_verb'],'phrase');
add('run out','phrasal_verb','用完','use up','Fulfillment / Logistics','logistics','manage','We ran out of packaging materials and had to pause fulfillment for two days.','我们 run out 了包装材料不得不暂停 fulfillment 两天。',1,['logistics','phrasal_verb'],'phrase');
add('clear customs','phrasal_verb','清关','pass border check','Fulfillment / Logistics','logistics','international','The shipment cleared customs in Frankfurt and should reach the warehouse by Friday.','货物在法兰克福 clear customs 了应该在周五前到达仓库。',2,['logistics','phrasal_verb'],'phrase');
add('lock address','phrasal_verb','锁定地址','fix address','Fulfillment / Logistics','logistics','finalize','Please lock the address before we send the order to the fulfillment centre.','请在把订单发给 fulfillment centre 之前 lock address。',1,['logistics','phrasal_verb'],'phrase');
add('export orders','phrasal_verb','导出订单','pull orders','Analytics / Reporting','analytics review','get data','I exported orders from Shopify to send to the 3PL for processing.','我从 Shopify export orders 发给 3PL 处理。',2,['analytics','phrasal_verb'],'phrase');
add('issue refund','phrasal_verb','退款','give money back','Customer Support','customer support','resolve','We issued a refund within two hours of receiving the return at the warehouse.','我们在仓库收到退货后两小时内 issue refund。',1,['support','phrasal_verb'],'phrase');
add('approve sample','phrasal_verb','确认样品','OK the prototype','Supplier / Foreign Trade','supplier communication','confirm','The factory is waiting for us to approve the sample before they can start tooling.','工厂在等我们 approve sample 才能开始做模具。',1,['supplier','phrasal_verb'],'phrase');
add('confirm payment','phrasal_verb','确认到账','verify money','Payment / Tax / Refund','supplier communication','verify','We can release the goods once we confirm payment has arrived in our bank account.','一旦 confirm payment 到账我们就可以放行货物。',1,['payment','phrasal_verb'],'phrase');
add('collect feedback','phrasal_verb','收集反馈','gather opinions','Crowdfunding Campaign','campaign live','learn','We collected feedback from the first batch of backers and most complaints were about the user manual.','我们从第一批 backer 那里 collect feedback 大多数投诉是关于 user manual 的。',1,['crowdfunding','phrasal_verb'],'phrase');
add('update tracking','phrasal_verb','更新追踪','refresh tracking','Fulfillment / Logistics','logistics','communicate','Please update tracking for all orders in this batch because the carrier just sent the new numbers.','请 update tracking 这批所有订单因为承运商刚发来新的 tracking number。',1,['logistics','phrasal_verb'],'phrase');
add('arrange pickup','phrasal_verb','安排取件','set collection','Fulfillment / Logistics','logistics','coordinate','Can you arrange pickup with the freight forwarder for Thursday morning?','你能 arrange pickup 与货运代理安排在周四早上吗？',1,['logistics','phrasal_verb'],'phrase');
add('split shipment','phrasal_verb','拆分发货','divide delivery','Fulfillment / Logistics','logistics','manage','We split the shipment because half the order is ready now and the rest will take two more weeks.','我们 split shipment 因为一半订单现在 ready 其余还要两周。',2,['logistics','phrasal_verb'],'phrase');
add('merge orders','phrasal_verb','合并订单','combine','Fulfillment / Logistics','logistics','manage','Can you merge these orders from the same customer so they only pay shipping once?','你能 merge orders 这个客户的多笔订单吗这样他们只付一次运费。',2,['logistics','phrasal_verb'],'phrase');
add('cancel order','phrasal_verb','取消订单','call off','Customer Support','customer support','resolve','The customer asked us to cancel the order before it shipped because they found a better deal.','客户要求在发货前 cancel order 因为他们找到了更好的交易。',1,['support','phrasal_verb'],'phrase');
add('process return','phrasal_verb','处理退货','handle return','Customer Support','customer support','resolve','We process returns within three business days of receiving the item back.','我们在收到退货后三个工作日内 process return。',1,['support','phrasal_verb'],'phrase');
add('handle chargeback','phrasal_verb','处理拒付','deal with dispute','Customer Support','customer support','resolve','The finance team needs to handle this chargeback before the deadline or we lose the case automatically.','财务团队需要在截止日期前 handle this chargeback 否则我们自动败诉。',3,['payment','phrasal_verb'],'phrase');
add('verify address','phrasal_verb','核实地址','check address','Fulfillment / Logistics','logistics','prevent error','We verify the address before shipping because wrong addresses are the number one cause of returns.','我们在发货前 verify address 因为错误地址是退货的头号原因。',1,['logistics','phrasal_verb'],'phrase');
add('prepare invoice','phrasal_verb','准备发票','make bill','Supplier / Foreign Trade','supplier communication','document','I will prepare the commercial invoice before the shipment leaves the factory.','我会在货物离开工厂之前 prepare commercial invoice。',1,['supplier','phrasal_verb'],'phrase');
add('submit claim','phrasal_verb','提交索赔','file complaint','Customer Support','customer support','file','We submitted a claim to the carrier for the damaged package and attached photos as evidence.','我们向承运商 submit claim 损坏包裹并附上了照片作为证据。',2,['support','phrasal_verb'],'phrase');
add('push back','phrasal_verb','推迟','delay','Supplier / Foreign Trade','supplier communication','manage','The supplier pushed back the delivery date by two weeks because one component is stuck in customs.','supplier 把交货日期 push back 了两周因为有一个组件卡在 customs 了。',2,['supplier','phrasal_verb'],'phrase');
add('sell out','phrasal_verb','售罄','completely gone','Shopify / DTC Store','dtc store operation','sell','The limited edition sold out in less than 24 hours and we are getting messages asking for a restock.','限量版在不到 24 小时内 sell out 我们收到很多消息要求补货。',1,['dtc','phrasal_verb'],'phrase');

// ===== ADJECTIVES (25+) =====
add('low-stock','adjective','库存低的','running out','Fulfillment / Logistics','logistics','monitor','The blue variant is showing as low-stock so we should pause the ad for that colour.','蓝色款显示为 low-stock 所以我们应该暂停该颜色的广告。',1,['logistics','adjective']);
add('backordered','adjective','缺货中的','on backorder','Fulfillment / Logistics','logistics','manage','This item is currently backordered and will ship approximately three weeks from today.','这个商品目前 backordered 大约三周后发货。',2,['logistics','adjective']);
add('customizable','adjective','可定制的','can be changed','Shopify / DTC Store','dtc store operation','offer','The product page should show that the colour and engraving are customizable.','产品页应该显示颜色和刻字是 customizable 的。',1,['dtc','adjective']);
add('prepaid','adjective','预付的','paid in advance','Payment / Tax / Refund','supplier communication','finance','The shipping label is prepaid so the customer does not need to pay anything at delivery.','shipping label 是 prepaid 的所以客户在 delivery 时不需要付任何费用。',1,['payment','adjective']);
add('unpaid','adjective','未付的','not yet paid','Payment / Tax / Refund','supplier communication','finance','There are three unpaid invoices from this distributor that are now over 60 days overdue.','这个 distributor 有三张 unpaid invoice 已经逾期超过 60 天了。',1,['payment','adjective']);
add('fulfilled','adjective','已履约的','completed','Fulfillment / Logistics','logistics','track','All fulfilled orders from this batch have tracking numbers updated in Shopify.','这批所有 fulfilled order 在 Shopify 中都已更新 tracking number。',1,['logistics','adjective']);
add('unfulfilled','adjective','未履约的','not yet done','Fulfillment / Logistics','logistics','track','We have about 200 unfulfilled orders from the weekend that need to go out by Tuesday.','我们有大约 200 个周末的 unfulfilled order 需要在周二前发出。',1,['logistics','adjective']);
add('defective','adjective','有缺陷的','faulty','Customer Support','customer support','resolve','The customer sent photos of the defective unit with a cracked screen straight out of the box.','客户发来了 defective unit 的照片开箱即屏幕碎裂。',2,['support','adjective']);
add('partial','adjective','部分的','not full','Payment / Tax / Refund','customer support','handle','We offered a partial refund of 30 percent because the product had minor cosmetic damage.','我们提供了百分之三十的 partial refund 因为产品有轻微外观损伤。',2,['payment','adjective']);
add('bulk','adjective','批量的','large quantity','Fulfillment / Logistics','logistics','manage','The bulk shipment of 2000 units arrived at the warehouse yesterday afternoon.','2000 台的 bulk shipment 昨天下午到达了仓库。',1,['logistics','adjective']);
add('duty-free','adjective','免税的','no import tax','Payment / Tax / Refund','supplier communication','international','This product qualifies as duty-free under the trade agreement between the two countries.','根据两国之间的贸易协定这款产品属于 duty-free。',3,['payment','adjective']);
add('taxable','adjective','应税的','subject to tax','Payment / Tax / Refund','supplier communication','international','The value of the shipment exceeds the de minimis threshold so it is fully taxable in the destination country.','货值超过了最低限额所以在目的国全额 taxable。',3,['payment','adjective']);
add('time-sensitive','adjective','时效敏感的','urgent timing','Crowdfunding Campaign','post-campaign fulfillment','manage','The backer addresses are time-sensitive because the fulfillment centre needs them by Friday.','backer address 是 time-sensitive 的因为 fulfillment centre 周五前需要它们。',2,['crowdfunding','adjective']);
add('price-sensitive','adjective','价格敏感的','cares about cost','Ads / Acquisition','paid acquisition','target','Our audience on Facebook is more price-sensitive than the one on Google so we adjusted the messaging.','我们在 Facebook 上的受众比 Google 上的更 price-sensitive 所以我们调整了信息传达。',2,['ads','adjective']);
add('customer-facing','adjective','面向客户的','seen by customers','Shopify / DTC Store','dtc store operation','design','The customer-facing page needs to show the shipping policy clearly before checkout.','customer-facing 页面需要在结账前清楚地显示 shipping policy。',1,['dtc','adjective']);
add('refundable','adjective','可退款的','can get money back','Payment / Tax / Refund','customer support','policy','The deposit is fully refundable if the order is cancelled at least seven days before the shipment date.','如果在发货日期前至少七天取消订单订金全额 refundable。',1,['payment','adjective']);
add('overdue','adjective','逾期的','past deadline','Payment / Tax / Refund','supplier communication','track','The overdue payment from this distributor is now over 90 days and we need to escalate.','这个 distributor 的 overdue payment 已经超过 90 天了我们需要 escalate。',2,['payment','adjective']);
add('trackable','adjective','可追踪的','can be followed','Fulfillment / Logistics','logistics','monitor','All shipments are fully trackable from the factory to the customer doorstep.','所有 shipment 从工厂到客户门口都完全 trackable。',1,['logistics','adjective']);
add('retail-ready','adjective','零售就绪的','ready for store','Retail / Supermarket / Channel Expansion','retail onboarding','prepare','The packaging is retail-ready with a hanging tab and a shelf-friendly display box.','包装是 retail-ready 的有挂孔和适合货架的展示盒。',2,['retail','adjective']);
add('damaged','adjective','损坏的','broken','Customer Support','customer support','resolve','The customer received a damaged unit and sent photos of the cracked casing.','客户收到了一台 damaged unit 并发了碎裂外壳的照片。',1,['support','adjective']);
add('urgent','adjective','紧急的','very important','Customer Support','customer support','prioritize','This ticket is urgent because the customer is a top-tier backer who pledged over five hundred dollars.','这个工单是 urgent 的因为客户是一位 pledging 超过五百美元的顶级 backer。',1,['support','adjective']);
add('seasonal','adjective','季节性的','varies by season','Ads / Acquisition','paid acquisition','target','The seasonal demand for our product peaks in November and drops sharply in January.','我们产品的 seasonal demand 在十一月达到峰值在 January 急剧下降。',1,['ads','adjective']);
add('late','adjective','延迟的','behind schedule','Fulfillment / Logistics','logistics','track','The late shipment from the supplier is now affecting at least 50 customer orders.','来自 supplier 的 late shipment 现在至少影响了 50 个客户订单。',1,['logistics','adjective']);
add('international','adjective','国际的','cross-border','Fulfillment / Logistics','logistics','manage','International shipping takes about two weeks but domestic delivery is usually under three days.','international shipping 大约需要两周但 domestic delivery 通常在三天以内。',1,['logistics','adjective']);

// ===== COLLOCATIONS (26+) =====
add('confirm the lead time','collocation','确认交货周期','verify production time','Supplier / Foreign Trade','supplier communication','verify','Can you confirm the lead time for the next batch because the last order took six weeks instead of four.','你能 confirm the lead time 吗因为上一批花了六周而不是四周。',2,['supplier','collocation'],'phrase');
add('issue a partial refund','collocation','发放部分退款','give partial money','Payment / Tax / Refund','customer support','resolve','We decided to issue a partial refund of 20 percent because the packaging was damaged but the product works.','我们决定 issue a partial refund 百分之二十因为包装损坏但产品功能正常。',2,['payment','collocation'],'phrase');
add('update the tracking number','collocation','更新追踪号','refresh tracking','Fulfillment / Logistics','logistics','communicate','Please update the tracking number in Shopify so the customer can follow their package.','请在 Shopify 中 update the tracking number 这样客户可以追踪包裹。',1,['logistics','collocation'],'phrase');
add('lock the shipping address','collocation','锁定收货地址','finalize address','Fulfillment / Logistics','logistics','finalize','We need to lock the shipping address before sending the batch to the fulfillment centre.','在把批次发给 fulfillment centre 之前我们需要 lock the shipping address。',1,['logistics','collocation'],'phrase');
add('export the order file','collocation','导出订单文件','pull order data','Analytics / Reporting','analytics review','get data','I export the order file every Monday morning and send it to the 3PL for processing.','我每周一早上 export the order file 并发给 3PL 处理。',2,['analytics','collocation'],'phrase');
add('split the shipment','collocation','拆分发货','divide delivery','Fulfillment / Logistics','logistics','manage','We had to split the shipment because half the inventory was ready but the accessories were delayed.','我们不得不 split the shipment 因为一半库存 ready 但配件 delay 了。',2,['logistics','collocation'],'phrase');
add('merge duplicate orders','collocation','合并重复订单','combine same-customer','Fulfillment / Logistics','logistics','manage','Please merge duplicate orders from the same customer so they do not pay shipping twice.','请 merge duplicate orders 这个客户的多笔订单这样他们不用付两次运费。',2,['logistics','collocation'],'phrase');
add('process a return','collocation','处理退货','handle return','Customer Support','customer support','resolve','We process a return within 48 hours of receiving the item back at our warehouse.','我们在仓库收到退货后 48 小时内 process a return。',1,['support','collocation'],'phrase');
add('handle a chargeback','collocation','处理拒付','deal with dispute','Customer Support','customer support','resolve','The finance team needs to handle this chargeback before the 7-day response window closes.','财务团队需要在 7 天回复窗口关闭前 handle this chargeback。',3,['payment','collocation'],'phrase');
add('approve the sample','collocation','确认样品','OK prototype','Supplier / Foreign Trade','supplier communication','confirm','The factory is waiting for us to approve the sample before they can start mass production.','工厂在等我们 approve the sample 才能开始量产。',1,['supplier','collocation'],'phrase');
add('confirm the payment terms','collocation','确认付款条款','verify terms','Supplier / Foreign Trade','supplier communication','negotiate','We need to confirm the payment terms before signing the purchase order for this batch.','在签署这批的 purchase order 之前我们需要 confirm the payment terms。',2,['supplier','collocation'],'phrase');
add('prepare the commercial invoice','collocation','准备商业发票','make trade bill','Supplier / Foreign Trade','supplier communication','document','I will prepare the commercial invoice after the goods pass the final quality inspection.','货物通过最终 quality inspection 后我会 prepare the commercial invoice。',2,['supplier','collocation'],'phrase');
add('check the inventory level','collocation','检查库存水平','verify stock','Fulfillment / Logistics','logistics','monitor','Can you check the inventory level for the black variant because the ad is driving a lot of traffic.','你能 check the inventory level 黑色款吗因为广告正在带来大量流量。',1,['logistics','collocation'],'phrase');
add('pause the ad campaign','collocation','暂停广告活动','stop campaign','Ads / Acquisition','paid acquisition','manage','We paused the ad campaign over the weekend because the conversion rate was dropping sharply.','我们周末 pause the ad campaign 因为转化率在急剧下降。',1,['ads','collocation'],'phrase');
add('resume the email flow','collocation','恢复邮件流程','restart email','Email / CRM','email marketing','manage','Let us resume the email flow on Monday after we fix the broken link in the second email.','我们修复第二封邮件中的 broken link 后周一 resume the email flow。',2,['email','collocation'],'phrase');
add('recover abandoned carts','collocation','挽回弃购车','save lost carts','Shopify / DTC Store','dtc store operation','save sales','The abandoned cart flow recovers about ten percent of abandoned carts on average.','abandoned cart flow 平均 recover abandoned carts 大约百分之十。',2,['dtc','collocation'],'phrase');
add('review the product page','collocation','审查产品页','check listing','Shopify / DTC Store','dtc store operation','improve','We need to review the product page because the bounce rate is over seventy percent.','我们需要 review the product page 因为跳出率超过百分之七十。',1,['dtc','collocation'],'phrase');
add('optimize the checkout page','collocation','优化结账页','improve checkout','Shopify / DTC Store','dtc store operation','improve','We optimized the checkout page by removing the account creation requirement and conversions improved.','我们通过移除创建账户的要求来 optimize the checkout page 转化率提高了。',2,['dtc','collocation'],'phrase');
add('contact the freight forwarder','collocation','联系货运代理','reach shipper','Fulfillment / Logistics','logistics','communicate','Can you contact the freight forwarder and ask why the shipment has been sitting at the port for three days.','你能 contact the freight forwarder 问一下为什么货物在港口放了三天。',1,['logistics','collocation'],'phrase');
add('book the shipment','collocation','预订发货','reserve transport','Fulfillment / Logistics','logistics','arrange','I booked the shipment for next Tuesday morning with the freight forwarder.','我跟货运代理 book the shipment 下周二早上。',1,['logistics','collocation'],'phrase');
add('send a campaign update','collocation','发送活动更新','notify backers','Crowdfunding Campaign','campaign live','communicate','We send a campaign update every Friday with photos from the production line and the shipping timeline.','我们每周五 send a campaign update 附上产线照片和 shipping timeline。',1,['crowdfunding','collocation'],'phrase');
add('collect backer feedback','collocation','收集支持者反馈','gather opinions','Crowdfunding Campaign','post-campaign fulfillment','learn','We collected backer feedback through the survey and most people wanted a longer battery life.','我们通过 survey collect backer feedback 大多数人想要更长的电池续航。',1,['crowdfunding','collocation'],'phrase');
add('confirm the delivery timeline','collocation','确认交付时间','verify schedule','Crowdfunding Campaign','post-campaign fulfillment','communicate','Please confirm the delivery timeline before we post the next campaign update.','在我们发布下一个 campaign update 之前请 confirm the delivery timeline。',1,['crowdfunding','collocation'],'phrase');
add('check the payment status','collocation','检查付款状态','verify payment','Payment / Tax / Refund','supplier communication','verify','Can you check the payment status for invoice number 2047 because the supplier says they have not received it.','你能 check the payment status invoice 2047 吗 supplier 说他们还没收到。',1,['payment','collocation'],'phrase');
add('adjust the pricing','collocation','调整价格','change prices','B2B Negotiation / Pricing / Payment','pricing negotiation','improve','We adjusted the pricing for volume orders because the supplier gave us a better rate on components.','我们 adjust the pricing 批量订单因为 supplier 给了我们更好的 component 价格。',2,['pricing','collocation'],'phrase');
add('request a replacement','collocation','请求更换','ask for new','Customer Support','customer support','resolve','The customer requested a replacement because the unit arrived with the wrong power adapter.','客户 request a replacement 因为收到的产品带有错误的电源适配器。',1,['support','collocation'],'phrase');

// ===== SENTENCE PATTERNS (15+) =====
add('Can you confirm the lead time?','sentence_pattern','能确认交货周期吗？','ask for timeline','Supplier / Foreign Trade','supplier communication','ask','Can you confirm the lead time because the last order took nearly twice as long as estimated.','Can you confirm the lead time 因为上一次订单花了几乎是预计时间的两倍。',1,['supplier','sentence_pattern'],'sentence_pattern');
add('The shipment has been delayed.','sentence_pattern','发货已延迟','delayed delivery','Fulfillment / Logistics','logistics','communicate','The shipment has been delayed because of a customs hold at the port of entry.','由于入境口岸的 customs hold the shipment has been delayed。',2,['logistics','sentence_pattern'],'sentence_pattern');
add('The item is out of stock.','sentence_pattern','该商品已缺货','no stock','Shopify / DTC Store','dtc store operation','communicate','The item is out of stock in the blue variant but we have the black and silver available now.','蓝色款 the item is out of stock 但我们有黑色和银色现货。',1,['dtc','sentence_pattern'],'sentence_pattern');
add('We need to refund this customer.','sentence_pattern','我们需要给这个客户退款','must refund','Customer Support','customer support','resolve','We need to refund this customer because the package was lost and the carrier accepted the claim.','We need to refund this customer 因为包裹丢失且承运商接受了 claim。',1,['support','sentence_pattern'],'sentence_pattern');
add('The tracking has not updated yet.','sentence_pattern','追踪还没更新','no tracking','Fulfillment / Logistics','logistics','communicate','The tracking has not updated yet since the package left the warehouse three days ago.','自从包裹三天前离开仓库以来 the tracking has not updated yet。',1,['logistics','sentence_pattern'],'sentence_pattern');
add('The supplier pushed back the delivery.','sentence_pattern','供应商推迟了交货','supplier delay','Supplier / Foreign Trade','supplier communication','communicate','The supplier pushed back the delivery by two weeks and we need to update all affected backers.','supplier pushed back the delivery 两周我们需要通知所有受影响的 backer。',2,['supplier','sentence_pattern'],'sentence_pattern');
add('The discount ends this week.','sentence_pattern','折扣本周结束','promo ending','Shopify / DTC Store','dtc store operation','communicate','The discount ends this week so we should send a reminder email to the people who viewed the product.','The discount ends this week 所以我们应该给看过产品的人发提醒邮件。',1,['dtc','sentence_pattern'],'sentence_pattern');
add('The customer asked for a replacement.','sentence_pattern','客户要求换货','wants swap','Customer Support','customer support','communicate','The customer asked for a replacement because the screen had a dead pixel right in the centre.','The customer asked for a replacement 因为屏幕正中央有一个坏点。',1,['support','sentence_pattern'],'sentence_pattern');
add('The checkout failed again.','sentence_pattern','结账又失败了','payment fail','Shopify / DTC Store','dtc store operation','investigate','The checkout failed again for the third time this week and we need to escalate to the payment processor.','这周第三次 The checkout failed again 我们需要 escalat 给支付处理器。',2,['dtc','sentence_pattern'],'sentence_pattern');
add('Can we split this shipment?','sentence_pattern','能拆分这个发货吗？','divide delivery','Fulfillment / Logistics','logistics','ask','Can we split this shipment so the ready items go out now and the rest follow in two weeks.','Can we split this shipment 让 ready 的物品现在发出其余的 two weeks 后跟进。',1,['logistics','sentence_pattern'],'sentence_pattern');
add('The abandoned cart flow did not trigger.','sentence_pattern','弃购车流程没有触发','flow fail','Email / CRM','email marketing','investigate','The abandoned cart flow did not trigger for the last ten carts and we need to debug the integration.','最近十个购物车 The abandoned cart flow did not trigger 我们需要 debug integration。',3,['email','sentence_pattern'],'sentence_pattern');
add('Please lock the address before fulfillment.','sentence_pattern','请在履约前锁定地址','finalize','Fulfillment / Logistics','logistics','instruct','Please lock the address before fulfillment because we cannot change it after the label is printed.','请在打印标签之前 lock the address before fulfillment 因为之后无法更改。',1,['logistics','sentence_pattern'],'sentence_pattern');
add('We need to export the order file today.','sentence_pattern','今天需要导出订单文件','urgent data','Analytics / Reporting','analytics review','instruct','We need to export the order file today because the 3PL needs it by 5pm for Monday processing.','We need to export the order file today 因为 3PL 需要在下午五点前收到以便周一处理。',1,['analytics','sentence_pattern'],'sentence_pattern');
add('The backer asked for a shipping update.','sentence_pattern','支持者要求物流更新','backer inquiry','Crowdfunding Campaign','campaign live','communicate','The backer asked for a shipping update and I promised we would reply with an ETA by tomorrow.','The backer asked for a shipping update 我承诺明天前回复预计到达时间。',1,['crowdfunding','sentence_pattern'],'sentence_pattern');
add('Please check the inventory before launch.','sentence_pattern','发布前请检查库存','verify stock','Shopify / DTC Store','dtc store operation','instruct','Please check the inventory before launch because we cannot afford to sell out in the first hour.','Please check the inventory before launch 因为我们不能承受第一个小时就卖光。',1,['dtc','sentence_pattern'],'sentence_pattern');
add('Can we pause this campaign?','sentence_pattern','能暂停这个广告活动吗？','stop campaign','Ads / Acquisition','paid acquisition','ask','Can we pause this campaign because the CPA has been rising for three days straight.','Can we pause this campaign 因为 CPA 已经连续三天在上升。',1,['ads','sentence_pattern'],'sentence_pattern');
add('We should review the product page first.','sentence_pattern','我们应该先审查产品页','check page','Shopify / DTC Store','dtc store operation','suggest','We should review the product page first before we spend more on ads because the conversion rate is too low.','We should review the product page first 因为在 conversion rate 太低的页面上多投广告没有意义。',1,['dtc','sentence_pattern'],'sentence_pattern');
add('The customs clearance is taking longer.','sentence_pattern','清关比预期时间长','customs slow','Fulfillment / Logistics','logistics','communicate','The customs clearance is taking longer than expected because the paperwork was missing a product description.','The customs clearance is taking longer 因为 paperwork 缺少 product description。',2,['logistics','sentence_pattern'],'sentence_pattern');
add('Please prepare the commercial invoice.','sentence_pattern','请准备商业发票','make invoice','Supplier / Foreign Trade','supplier communication','instruct','Please prepare the commercial invoice before the goods leave the factory so we can clear customs faster.','请在货物离开工厂前 prepare the commercial invoice 这样我们可以更快清关。',1,['supplier','sentence_pattern'],'sentence_pattern');

const updated=data.concat(newItems);
fs.writeFileSync(file,JSON.stringify(updated));
console.log('FT POS: Added',added,'| Skipped:',skipped,'| New total:',updated.length);
console.log('  Verbs:',newItems.filter(x=>x.partOfSpeech==='verb').length);
console.log('  Phrasal verbs:',newItems.filter(x=>x.partOfSpeech==='phrasal_verb').length);
console.log('  Adjectives:',newItems.filter(x=>x.partOfSpeech==='adjective').length);
console.log('  Collocations:',newItems.filter(x=>x.partOfSpeech==='collocation').length);
console.log('  Sentence patterns:',newItems.filter(x=>x.partOfSpeech==='sentence_pattern').length);
