const fs=require('fs');

const PACKS=[
  {file:'src/data/packs/ielts-exam-context-2000.json',pack:'ielts-exam-context-2000',pre:'ielts-exam-context-2000'},
  {file:'src/data/packs/foreign-trade-crowdfunding-dtc-operations-1000.json',pack:'foreign-trade-crowdfunding-dtc-operations-1000',pre:'foreign-trade-crowdfunding-dtc-operations-1000'},
  {file:'src/data/packs/robotics-rd-engineering-research-1000.json',pack:'robotics-rd-engineering-research-1000',pre:'robotics-rd-engineering-research-1000'},
  {file:'src/data/packs/ai-product-management-llm-products-1000.json',pack:'ai-product-management-llm-products-1000',pre:'ai-product-management-llm-products-1000'},
  {file:'src/data/packs/robotics-maintenance-troubleshooting-1000.json',pack:'robotics-maintenance-troubleshooting-1000',pre:'robotics-maintenance-troubleshooting-1000'},
  {file:'src/data/packs/smart-hardware-overseas-channel-sales-core.json',pack:'smart-hardware-overseas-channel-sales-core',pre:'smart-hardware-overseas-channel-sales-core'},
];

const FF={RLHF:'Reinforcement Learning from Human Feedback',GDPR:'General Data Protection Regulation',SLA:'Service Level Agreement',SOC:'System and Organization Controls',DDS:'Data Distribution Service',PID:'Proportional Integral Derivative',MSRP:'Manufacturer Suggested Retail Price',FCC:'Federal Communications Commission',CE:'Conformité Européenne',RoHS:'Restriction of Hazardous Substances',UKCA:'UK Conformity Assessed',B2B:'Business to Business'};

for(const P of PACKS){
  const data=JSON.parse(fs.readFileSync(P.file,'utf-8'));
  const existing=new Set(data.map(d=>d.term.toLowerCase()));
  const newItems=[];let id=data.length+1,added=0,skipped=0;

  function add(t,pos,sm,sis,topic,ex,ez,diff,tg,type,reg,extras){
    if(existing.has(t.toLowerCase())){skipped++;return false;}
    existing.add(t.toLowerCase());
    const item={id:P.pre+'-'+String(id).padStart(4,'0'),packId:P.pack,term:t,type:type||'word',partOfSpeech:pos,topic,shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'neutral',difficulty:diff||2,sourceType:(P.pack.includes('ielts')?'ielts_style_original':P.pack.includes('foreign')?'foreign_trade_dtc_style_original':P.pack.includes('robotics-maintenance')?'robotics_maintenance_style_original':P.pack.includes('robotics-rd')?'robotics_rd_style_original':P.pack.includes('ai')?'ai_product_style_original':'smart_hardware_channel_sales_style_original'),sourceTitle:'Original learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||[],fullForm:FF[t]||undefined};
    if(extras)Object.assign(item,extras);
    newItems.push(item);id++;added++;return true;
  }

  const isIELTS=P.pack.includes('ielts');
  const isFT=P.pack.includes('foreign');
  const isRD=P.pack.includes('robotics-rd');
  const isMaint=P.pack.includes('robotics-maintenance');
  const isAI=P.pack.includes('ai');
  const isHW=P.pack.includes('smart');

  // Common verb/adjective/adverb/sentence_pattern items per pack
  if(isIELTS){
    add('evaluate','verb','评估','judge carefully','Argument and Logic','The study evaluates the long-term impact of early childhood education on career outcomes.','该研究 evaluate 了早期儿童教育对职业成果的长期影响。',3,['academic','verb']);
    add('illustrate','verb','说明','show with example','Trend and Comparison','The graph illustrates the changes in consumer spending patterns over a ten-year period.','该图表 illustrate 了十年间消费者支出模式的变化。',3,['academic','verb']);
    add('prioritize','verb','优先处理','put first','Argument and Logic','Governments must prioritize spending on healthcare and education over military expansion.','政府必须 prioritize 在医疗和教育上的支出优先于军事扩张。',3,['academic','verb']);
    add('address','verb','应对','deal with','Argument and Logic','The government needs to address the growing problem of youth unemployment in rural areas.','政府需要 address 农村地区日益严重的青年失业问题。',2,['academic','verb']);
    add('contribute to','phrasal_verb','有助于','help bring about','Argument and Logic','Regular exercise can contribute to better mental health and reduced stress levels.','定期锻炼可以 contribute to 更好的心理健康和降低压力水平。',2,['academic','phrasal_verb']);
    add('depend on','phrasal_verb','取决于','rely on','Argument and Logic','The success of the project will depend on how well the team communicates with stakeholders.','项目的成功将 depend on 团队与利益相关者的沟通效果。',2,['academic','phrasal_verb']);
    add('result in','phrasal_verb','导致','cause','Argument and Logic','Rising temperatures could result in more frequent and severe droughts in many regions.','气温升高可能 result in 许多地区更频繁和更严重的干旱。',2,['academic','phrasal_verb']);
    add('noticeable','adjective','明显的','easy to see','Trend and Comparison','There has been a noticeable improvement in air quality since the new regulations came into effect.','自新规生效以来空气质量有了 noticeable 的改善。',3,['academic','adjective']);
    add('substantial','adjective','大量的','large in amount','Trend and Comparison','A substantial number of students now choose to study abroad for at least one semester.','substantial 数量的学生现在选择至少到国外学习一个学期。',3,['academic','adjective']);
    add('gradually','adverb','逐渐地','little by little','Trend and Comparison','The population of rural villages has been gradually declining as young people move to cities.','随着年轻人迁往城市农村人口 gradually 在下降。',2,['academic','adverb']);
    add('The main reason is that','sentence_pattern','主要原因是','cause phrase','Argument and Logic','The main reason is that most households now have access to high-speed internet.','the main reason is that 大多数家庭现在都能接入高速互联网。',2,['writing','sentence_pattern']);
    add('This can be attributed to','sentence_pattern','这可以归因于','cause attribution','Argument and Logic','This can be attributed to the increased investment in renewable energy over the past decade.','this can be attributed to 过去十年对可再生能源的投资增加。',3,['writing','sentence_pattern']);
  }
  else if(isFT){
    add('negotiate','verb','谈判','discuss terms','B2B Negotiation / Pricing / Payment','We need to negotiate the payment terms before signing the purchase order.','在签署采购订单之前我们需要 negotiate 付款条款。',2,['business','verb'],'word','workplace',{businessStage:'pricing negotiation',workIntent:'agree terms'});
    add('confirm','verb','确认','verify','B2B Negotiation / Pricing / Payment','Please confirm the shipping address before we dispatch the order.','请在我们发货之前 confirm 收货地址。',1,['business','verb'],'word','workplace',{businessStage:'pricing negotiation',workIntent:'verify details'});
    add('fulfill','verb','完成履约','complete order','Fulfillment / Logistics','The warehouse can fulfill up to 500 orders per day during the holiday season.','仓库在假日期间每天最多可以 fulfill 500 个订单。',2,['logistics','verb'],'word','workplace',{businessStage:'logistics',workIntent:'process orders'});
    add('follow up','phrasal_verb','跟进','check back','Outbound Sales / Cold Call / Email Outreach','I will follow up with the supplier on Monday to get an update on the lead time.','我周一会 follow up 供应商以获取交货周期的最新信息。',1,['communication','phrasal_verb'],'phrasal_verb','workplace',{businessStage:'cold call',workIntent:'maintain contact'});
    add('sell through','phrasal_verb','售罄','all sold','Retail / Supermarket / Channel Expansion','The first batch sold through within two weeks so the retailer placed a reorder immediately.','第一批在两周内 sell through 所以零售商立即下了复购订单。',2,['retail','phrasal_verb'],'phrasal_verb','workplace',{businessStage:'retail onboarding',workIntent:'measure performance'});
    add('run out','phrasal_verb','卖光','use up','Fulfillment / Logistics','We ran out of stock on the most popular variant and had to pause the ad campaign.','最受欢迎的变体我们 run out 了库存不得不暂停广告活动。',1,['logistics','phrasal_verb'],'phrasal_verb','workplace',{businessStage:'logistics',workIntent:'manage stock'});
    add('refundable','adjective','可退款的','can get money back','Customer Support','The deposit is fully refundable if you cancel the order at least 48 hours before production starts.','如果你在生产开始前至少 48 小时取消订单订金全额 refundable。',2,['support','adjective'],'word','workplace',{businessStage:'customer support',workIntent:'set policy'});
    add('overdue','adjective','逾期的','past deadline','Fulfillment / Logistics','The overdue shipment from the supplier is causing a delay for at least three customer orders.','来自供应商的 overdue shipment 导致至少三个客户订单延迟。',2,['logistics','adjective'],'word','workplace',{businessStage:'logistics',workIntent:'track issues'});
    add('Can you confirm the lead time','sentence_pattern','能确认交货周期吗','ask for timeline','Supplier / Foreign Trade','Can you confirm the lead time because the last order took nearly twice as long as promised.','你能 confirm the lead time 吗因为上次订单花了承诺时间的近两倍。',1,['supplier','sentence_pattern'],'sentence_pattern','workplace',{businessStage:'supplier communication',workIntent:'plan production'});
    add('The shipment has been delayed','sentence_pattern','发货已延迟','delivery late','Fulfillment / Logistics','The shipment has been delayed due to customs clearance taking longer than expected.','由于清关时间比预期长 the shipment has been delayed。',2,['logistics','sentence_pattern'],'sentence_pattern','workplace',{businessStage:'logistics',workIntent:'communicate issues'});
  }
  else if(isRD){
    add('debug','verb','调试','find and fix','Engineering Collaboration and Debugging','It took two hours to debug the issue because the error log was not clear about which node failed.','花了两个小时 debug 这个问题因为错误日志没有清楚指明哪个节点失败了。',2,['engineering','verb'],'word','technical',{researchArea:'system architecture',usageScene:'debugging',workIntent:'fix issues'});
    add('compile','verb','编译','build from source','ROS2 Core','The package failed to compile because of a missing dependency in the CMakeLists file.','由于 CMakeLists 文件中缺少依赖 package 无法 compile。',2,['ros2','verb'],'word','technical',{researchArea:'system architecture',usageScene:'code review',workIntent:'build code'});
    add('simulate','verb','仿真','run virtually','Simulation','We need to simulate the robot in Gazebo before deploying to the real hardware.','在部署到真实硬件之前我们需要在 Gazebo 中 simulate 机器人。',2,['simulation','verb'],'word','technical',{researchArea:'simulation',usageScene:'system design',workIntent:'test virtually'});
    add('crash','verb','崩溃','stop working suddenly','Engineering Collaboration and Debugging','The node crashes during startup because it tries to read a parameter that has not been set.','该节点在启动时 crash 因为它试图读取一个尚未设置的参数。',2,['engineering','verb'],'word','technical',{researchArea:'system architecture',usageScene:'debugging',workIntent:'identify failure'});
    add('validate','verb','验证','check correctness','Research and Evaluation','We need to validate the results on the real robot before publishing the paper.','在发表论文之前我们需要在真实机器人上 validate 结果。',2,['research','verb'],'word','technical',{researchArea:'evaluation',usageScene:'benchmark analysis',workIntent:'verify results'});
    add('unstable','adjective','不稳定的','not steady','Research and Evaluation','The controller is still unstable at high speeds so we need to tune the gains more carefully.','控制器在高速下仍然 unstable 所以我们需要更仔细地调整增益。',2,['research','adjective'],'word','technical',{researchArea:'control',usageScene:'debugging',workIntent:'find issues'});
    add('reproducible','adjective','可复现的','same result each time','Research and Evaluation','The results need to be reproducible across at least five test runs before we can trust them.','结果需要在至少五次测试运行中 reproducible 我们才能信任它们。',3,['research','adjective'],'word','technical',{researchArea:'evaluation',usageScene:'benchmark analysis',workIntent:'verify consistency'});
    add('consistently','adverb','一致地','every time','Research and Evaluation','The robot consistently fails to navigate through the narrow corridor in the real world.','机器人在真实世界中 consistently 无法通过狭窄走廊。',2,['research','adverb'],'word','technical',{researchArea:'evaluation',usageScene:'debugging',workIntent:'measure reliability'});
    add('The simulation works but the real robot fails','sentence_pattern','仿真行但真机不行','sim-real gap','Research and Evaluation','The simulation works but the real robot fails which suggests a modelling issue in the URDF.','simulation 可以但 real robot 不行这表明 URDF 中存在建模问题。',3,['research','sentence_pattern'],'sentence_pattern','technical',{researchArea:'evaluation',usageScene:'debugging',workIntent:'identify gaps'});
    add('We need to tune this parameter','sentence_pattern','需要调参数','adjust config','Kinematics and Control','We need to tune this parameter because the robot overshoots every waypoint by about ten centimetres.','我们需要 tune this parameter 因为机器人每个航点都超调大约十厘米。',2,['control','sentence_pattern'],'sentence_pattern','technical',{researchArea:'control',usageScene:'debugging',workIntent:'optimise performance'});
  }
  else if(isMaint){
    add('inspect','verb','检查','look at carefully','Preventive Maintenance','Inspect the cable harness on axis three because the error log shows intermittent communication faults.','检查三轴的 cable harness 因为错误日志显示间歇性通信故障。',1,['maintenance','verb'],'word','workplace',{workIntent:'diagnose issue',scene:'onsite visit',role:'service engineer'});
    add('tighten','verb','拧紧','make tight','Mechanical Repair','Tighten all the bolts on the robot base because vibration can loosen them over time.','拧紧机器人底座上的所有螺栓因为振动会随时间使其松动。',1,['mechanical','verb'],'word','workplace',{workIntent:'adjust',scene:'onsite visit',role:'maintenance technician'});
    add('swap','verb','更换','exchange','Mechanical Repair','We swapped the encoder cable and the fault disappeared immediately.','我们 swap 了编码器线缆故障立即消失了。',1,['mechanical','verb'],'word','workplace',{workIntent:'replace',scene:'onsite visit',role:'service engineer'});
    add('isolate','verb','隔离','separate','Fault Diagnosis','We need to isolate the problem to a specific component before ordering replacement parts.','在订购替换部件之前我们需要把问题 isolate 到特定组件。',2,['diagnosis','verb'],'word','workplace',{workIntent:'diagnose issue',scene:'onsite visit',role:'service engineer'});
    add('reseat','verb','重新插拔','unplug and replug','Electrical and Wiring','Try reseating the connector before replacing the entire cable because the contacts might just be dirty.','在更换整条线缆之前试试 reseat 连接器因为触点可能只是脏了。',2,['electrical','verb'],'word','workplace',{workIntent:'diagnose issue',scene:'onsite visit',role:'maintenance technician'});
    add('power cycle','phrasal_verb','断电重启','turn off and on','Power and Electrical','The fault came back after a simple power cycle so we will need to investigate further.','简单的 power cycle 之后故障又回来了所以我们需要进一步调查。',1,['electrical','phrasal_verb'],'phrasal_verb','workplace',{workIntent:'troubleshoot',scene:'remote support',role:'service engineer'});
    add('come back','phrasal_verb','复发','return','Fault Diagnosis','The fault came back after the robot had been running for about three hours.','机器人运行了大约三小时后故障 come back 了。',1,['diagnosis','phrasal_verb'],'phrasal_verb','workplace',{workIntent:'diagnose issue',scene:'onsite visit',role:'service engineer'});
    add('misaligned','adjective','未对准的','not aligned','Mechanical Repair','The motor shaft is misaligned with the gearbox input which causes excess vibration at high speed.','电机轴与齿轮箱输入 misaligned 在高速时导致过度振动。',2,['mechanical','adjective'],'word','workplace',{workIntent:'diagnose issue',scene:'onsite visit',role:'service engineer'});
    add('intermittently','adverb','间歇性地','now and then','Fault Diagnosis','The sensor signal drops intermittently for just a few milliseconds which is enough to trigger a stop.','传感器信号 intermittently 中断仅几毫秒就足以触发停机。',2,['diagnosis','adverb'],'word','workplace',{workIntent:'diagnose issue',scene:'remote support',role:'service engineer'});
    add('Try to power cycle the controller first','sentence_pattern','先试试断电重启','basic troubleshooting','Power and Electrical','Try to power cycle the controller first before we start swapping hardware components.','在我们开始更换硬件组件之前先试试 power cycle the controller first。',1,['electrical','sentence_pattern'],'sentence_pattern','workplace',{workIntent:'troubleshoot',scene:'remote support',role:'service engineer'});
  }
  else if(isAI){
    add('prioritize','verb','排优先级','put in order','PRD / Requirement / Roadmap','We need to prioritize the backlog based on user impact not just engineering effort.','我们需要根据用户影响而不仅仅是工程工作量来 prioritize backlog。',2,['pm','verb'],'word','workplace',{productStage:'requirement',workIntent:'plan'});
    add('iterate','verb','迭代','improve in cycles','PRD / Requirement / Roadmap','Ship a simple version first and iterate based on real user feedback rather than guessing.','先发布一个简单版本然后基于真实用户反馈 iterate 而不是猜测。',2,['pm','verb'],'word','workplace',{productStage:'evaluation',workIntent:'improve'});
    add('approve','verb','批准','give OK','Safety / Privacy / Compliance','The legal team needs to approve the privacy policy before we can launch in the EU.','法律团队需要 approve 隐私政策才能在欧洲发布。',2,['safety','verb'],'word','workplace',{productStage:'risk review',workIntent:'validate'});
    add('route','verb','路由','send to right place','Agent / Workflow / Automation','The agent needs to route complex queries to a human when the confidence score is below the threshold.','当置信度得分低于阈值时 agent 需要把复杂查询 route 给人工。',2,['agent','verb'],'word','technical',{productStage:'implementation',workIntent:'automate'});
    add('monitor','verb','监控','watch continuously','Evaluation / Quality / Benchmark','We monitor the hallucination rate daily and trigger an alert if it goes above two percent.','我们每天 monitor hallucination rate 如果超过百分之二就触发警报。',2,['evaluation','verb'],'word','workplace',{productStage:'evaluation',workIntent:'track'});
    add('roll out','phrasal_verb','推出','release','Launch / GTM / Customer Success','We plan to roll out the new RAG pipeline to all users by the end of the month.','我们计划在月底前将新的 RAG pipeline roll out 给所有用户。',2,['launch','phrasal_verb'],'phrasal_verb','workplace',{productStage:'launch',workIntent:'release'});
    add('phase out','phrasal_verb','逐步淘汰','gradually remove','Launch / GTM / Customer Success','We will phase out the old API version over six months with clear migration support for each customer.','我们将在六个月内 phase out 旧版 API 并为每个客户提供清晰的迁移支持。',3,['launch','phrasal_verb'],'phrasal_verb','workplace',{productStage:'launch',workIntent:'manage transition'});
    add('actionable','adjective','可执行的','can be acted on','Data / Analytics / Product Metrics','The metric is only useful if it is actionable meaning the team can do something specific to improve it.','这个指标只有在 actionable 时才有用也就是团队可以做具体的事情来改善它。',2,['analytics','adjective'],'word','workplace',{productStage:'growth',workIntent:'measure'});
    add('scalable','adjective','可扩展的','can grow','AI Product Strategy / Use Case Discovery','The architecture needs to be scalable to thousands of queries per minute without a significant cost increase.','架构需要 scalable 到每分钟数千次查询而成本不会显著增加。',2,['strategy','adjective'],'word','workplace',{productStage:'design',workIntent:'plan'});
    add('Can we test this with real users','sentence_pattern','能用真实用户测吗','user validation','User Research / Customer Feedback','Can we test this with real users before we spend another month polishing the interface.','在我们再花一个月打磨界面之前能用真实用户测一下这个吗。',1,['user-research','sentence_pattern'],'sentence_pattern','workplace',{productStage:'discovery',workIntent:'validate'});
  }
  else if(isHW){
    add('pitch','verb','推销','present persuasively','Outbound Sales / Cold Call / Email Outreach','You have about thirty seconds to pitch the product before the buyer loses interest.','你大约有三十秒来 pitch 产品否则买方就会失去兴趣。',2,['sales','verb'],'word','workplace',{salesStage:'cold call',channelType:'direct sales',workIntent:'present offer'});
    add('qualify','verb','筛选','check if worth','Outbound Sales / Cold Call / Email Outreach','We need to qualify the lead before spending time on a custom quotation.','在花时间做定制报价之前我们需要 qualify 这个线索。',2,['sales','verb'],'word','workplace',{salesStage:'qualification',channelType:'direct sales',workIntent:'assess potential'});
    add('authorize','verb','授权','give official permission','Distributor / Agent Development','We authorized them as our exclusive distributor for the Benelux region last month.','我们上个月 authorize 他们成为我们在比荷卢地区的独家分销商。',2,['channel','verb'],'word','workplace',{salesStage:'partner negotiation',channelType:'distributor',workIntent:'designate partner'});
    add('certify','verb','认证','officially confirm','Certification / Market Access / Compliance','The device needs to be certified by an accredited lab before we can apply for CE marking.','设备需要由认证实验室 certify 之后才能申请 CE 标志。',3,['compliance','verb'],'word','workplace',{salesStage:'market access',channelType:'B2B customer',workIntent:'comply'});
    add('comply','verb','合规','follow rules','Certification / Market Access / Compliance','We must comply with local electronic waste regulations in every country we sell to.','我们必须 comply 每个销售国的当地电子废物法规。',2,['compliance','verb'],'word','workplace',{salesStage:'market access',channelType:'B2B customer',workIntent:'meet requirements'});
    add('reach out','phrasal_verb','联系','make contact','Outbound Sales / Cold Call / Email Outreach','I reached out to three potential distributors this week and two responded positively.','我这周 reach out 了三个潜在分销商两个回复积极。',1,['communication','phrasal_verb'],'phrasal_verb','workplace',{salesStage:'cold call',channelType:'direct sales',workIntent:'initiate contact'});
    add('take on','phrasal_verb','接收','accept as partner','Distributor / Agent Development','We decided to take on two new dealers in the southern region to improve coverage.','我们决定在南部地区 take on 两个新经销商以改善覆盖。',1,['channel','phrasal_verb'],'phrasal_verb','workplace',{salesStage:'partner negotiation',channelType:'dealer',workIntent:'expand network'});
    add('exclusive','adjective','独家的','only for one','Exclusive Agency / Territory / Channel Policy','They are asking for exclusive rights to the territory but we are not ready to commit yet.','他们在要求该地区的 exclusive 权利但我们还没准备好承诺。',2,['channel','adjective'],'word','workplace',{salesStage:'partner negotiation',channelType:'agent',workIntent:'negotiate terms'});
    add('negotiable','adjective','可协商的','open to discussion','B2B Negotiation / Pricing / Payment','The minimum order quantity is negotiable for a first-time partner who wants to start with a trial order.','对于想从试单开始的首次合作伙伴 minimum order quantity 是 negotiable 的。',2,['pricing','adjective'],'word','workplace',{salesStage:'pricing negotiation',channelType:'B2B customer',workIntent:'discuss terms'});
    add('We are looking for a local distributor','sentence_pattern','我们在找本地分销商','partner search','Distributor / Agent Development','We are looking for a local distributor who already has relationships with electronics retailers.','我们在找一家与电子产品零售商已有关系的本地 distributor。',1,['channel','sentence_pattern'],'sentence_pattern','workplace',{salesStage:'partner negotiation',channelType:'distributor',workIntent:'find partner'});
  }

  const updated=data.concat(newItems);
  fs.writeFileSync(P.file,JSON.stringify(updated));
  console.log(P.pre+': Added',added,'| Skipped:',skipped,'| Total:',updated.length);
}
