// DEPRECATED / DO NOT RUN
// This generator may produce low-quality or over-target items.
// Use only with a manually curated candidate pool.
const fs=require('fs');
const F='src/data/packs/robotics-rd-engineering-research-1000.json';
const D=JSON.parse(fs.readFileSync(F,'utf-8'));
const X=new Set(D.map(d=>d.term.toLowerCase()));
const T=1000;let id=D.length,A=0,S=0;
function a(t,p,m,s,tp,ra,us,w,ex,ez,d,tg,ty,re){ty=ty||'phrase';re=re||'workplace';d=d||2;tg=tg||['robotics-rd'];if(X.has(t.toLowerCase())){S++;return;}X.add(t.toLowerCase());id++;D.push({id:'robotics-rd-engineering-research-1000-'+String(id).padStart(4,'0'),packId:'robotics-rd-engineering-research-1000',term:t,type:ty,partOfSpeech:p,topic:tp,researchArea:ra||'',usageScene:us||'',workIntent:w||'',shortMeaning:m,shortMeaningInSentence:s,example:ex,exampleZh:ez,register:re,difficulty:d,sourceType:'robotics_rd_style_original',sourceTitle:'Original robotics R&D learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg});A++;}
console.log('From',D.length,'need',T-D.length);

// Compact: [term,pos,sm,sis,topic,researchArea,usageScene,workIntent,example,exampleZh,diff,tags]

const L=[
// === NAVIGATION / NAV2 ===
['global costmap','noun_phrase','全局代价地图','world cost layer','Navigation / Nav2 / Behavior Trees','navigation','system design','map','The global costmap covers the entire known environment and is updated from the static map.','global costmap 覆盖整个已知环境并从 static map 更新。',3,['navigation','nav2']],
['local costmap','noun_phrase','局部代价地图','local window','Navigation / Nav2 / Behavior Trees','navigation','system design','plan','The local costmap is a sliding window around the robot that updates with sensor data.','local costmap 是 robot 周围的一个滑动窗口随 sensor data 更新。',3,['navigation','nav2']],
['dwb controller','noun_phrase','DWB控制器','DWB local planner','Navigation / Nav2 / Behavior Trees','navigation','code review','control','The DWB controller scores trajectory candidates and picks the one with the lowest cost.','DWB controller 对 trajectory candidates 打分并选出 cost 最低的那个。',4,['navigation','control']],
['regulated pure pursuit','noun_phrase','纯追踪控制器','RPP algorithm','Navigation / Nav2 / Behavior Trees','navigation','code review','implement','Regulated pure pursuit adds linear velocity regulation on top of the basic pure pursuit algorithm.','regulated pure pursuit 在 basic pure pursuit algorithm 之上添加 linear velocity regulation。',4,['navigation','planning']],
['nav2 bt navigator','noun_phrase','Nav2行为树导航器','behavior tree navigator','Navigation / Nav2 / Behavior Trees','navigation','system design','implement','The Nav2 BT navigator uses behavior trees to orchestrate the full navigation lifecycle.','Nav2 BT navigator 使用 behavior trees 来编排完整的 navigation lifecycle。',4,['navigation','nav2']],
['recovery behavior','noun_phrase','恢复行为','fault recovery','Navigation / Nav2 / Behavior Trees','navigation','system design','recover','The recovery behavior spins the robot in place and clears the local costmap before replanning.','recovery behavior 原地旋转 robot 并在 replanning 前清除 local costmap。',3,['navigation','recovery']],
['waypoint follower','noun_phrase','航点跟随器','waypoint tracker','Navigation / Nav2 / Behavior Trees','navigation','system design','navigate','The waypoint follower sends the robot through a sequence of predefined poses.','waypoint follower 引导 robot 通过一系列预定义的 poses。',3,['navigation','nav2']],
['smac planner','noun_phrase','SMAC规划器','Hybrid-A* planner','Navigation / Nav2 / Behavior Trees','planning','benchmark analysis','plan','The Smac planner uses a hybrid A-star search on a 2D costmap with a Reed-Shepp model.','Smac planner 使用 hybrid A-star search 在 2D costmap 上使用 Reed-Shepp model。',4,['planning','nav2']],
['mppi controller','noun_phrase','MPPI控制器','model predictive path integral','Navigation / Nav2 / Behavior Trees','planning','benchmark analysis','control','The MPPI controller samples thousands of trajectories and executes the weighted average action.','MPPI controller 采样数千条 trajectories 并执行 weighted average action。',5,['planning','control']],
['nav2 bringup','noun_phrase','Nav2启动配置','nav2 launch setup','Navigation / Nav2 / Behavior Trees','navigation','system design','start','The nav2 bringup launch file includes the map server planner controller and recovery servers.','nav2 bringup launch file 包含 map server planner controller 和 recovery servers。',3,['navigation','nav2']],
['goal pose','noun_phrase','目标位姿','target pose','Navigation / Nav2 / Behavior Trees','navigation','real robot test','navigate','The goal pose is set through RViz and the action server starts planning immediately.','goal pose 通过 RViz 设置 action server 立即开始 planning。',2,['navigation','nav2']],

// === SLAM / LOCALIZATION ===
['scan matching','noun_phrase','扫描匹配','align scans','SLAM / Localization / Mapping','slam','experiment report','localize','Scan matching aligns the current lidar scan with a reference map to estimate the pose.','scan matching 将当前 lidar scan 与 reference map 对齐以 estimate pose。',3,['slam','algorithm']],
['particle filter','noun_phrase','粒子滤波','Monte Carlo localization','SLAM / Localization / Mapping','slam','code review','localize','The particle filter maintains a set of pose hypotheses and resamples based on sensor likelihood.','particle filter 维护一组 pose hypotheses 并根据 sensor likelihood 进行 resample。',4,['slam','algorithm']],
['feature extraction','noun_phrase','特征提取','find landmarks','SLAM / Localization / Mapping','slam','experiment report','process','Feature extraction finds corners edges and planes in the point cloud for the SLAM backend.','feature extraction 在 point cloud 中找出 corners edges 和 planes 供 SLAM backend 使用。',3,['slam','perception']],
['graph optimization','noun_phrase','图优化','pose graph refinement','SLAM / Localization / Mapping','slam','code review','optimize','The graph optimization step adjusts all historical poses to minimise the accumulated drift.','graph optimization 步骤调整所有 historical poses 以最小化 accumulated drift。',4,['slam','algorithm']],
['submap','noun_phrase','子地图','partial map','SLAM / Localization / Mapping','slam','system design','map','Each submap covers a local area and submaps are stitched together by loop closures.','每个 submap 覆盖一个局部区域 submaps 通过 loop closures 拼接在一起。',3,['slam','mapping']],
['keyframe','noun_phrase','关键帧','important frame','SLAM / Localization / Mapping','slam','code review','select','The SLAM backend keeps only keyframes that add new information instead of every single scan.','SLAM backend 只保留添加新信息的 keyframes 而不是每一个 scan。',3,['slam','algorithm']],
['global localization','noun_phrase','全局定位','find pose from scratch','SLAM / Localization / Mapping','slam','real robot test','localize','Global localization recovers the pose without a prior estimate when the robot is kidnapped.','global localization 在 robot 被 kidnapping 且无 prior estimate 时 recover pose。',4,['slam','localization']],
['pose covariance','noun_phrase','位姿协方差','pose uncertainty','SLAM / Localization / Mapping','slam','debugging','measure','The pose covariance matrix tells us how much we can trust the estimated pose in each axis.','pose covariance matrix 告诉我们每个轴上 estimated pose 的可信度。',4,['slam','math']],
['relocalization','noun','重定位','find again','SLAM / Localization / Mapping','slam','debugging','recover','After the robot is moved manually relocalization takes about two seconds using the lidar.','robot 被手动移动后 relocalization 使用 lidar 大约需要两秒。',3,['slam','localization'],'word'],

// === PERCEPTION / SENSOR FUSION ===
['point cloud registration','noun_phrase','点云配准','align clouds','Perception / Sensor Fusion / 3D Vision','perception','experiment report','match','Point cloud registration with ICP gives a rough alignment which is refined with feature matching.','使用 ICP 进行 point cloud registration 给出粗略 alignment 然后用 feature matching 细化。',4,['perception','algorithm']],
['voxel grid','noun_phrase','体素网格','3D grid','Perception / Sensor Fusion / 3D Vision','perception','code review','process','A voxel grid downsamples the point cloud to a uniform resolution before segmentation.','voxel grid 在 segmentation 之前将 point cloud downsample 到 uniform resolution。',3,['perception','processing']],
['multi-sensor fusion','noun_phrase','多传感器融合','combine sensors','Perception / Sensor Fusion / 3D Vision','perception','system design','integrate','Multi-sensor fusion combines lidar camera and radar to get robust detection in all weather.','multi-sensor fusion 结合 lidar camera 和 radar 以在所有天气中获得 robust detection。',4,['perception','fusion']],
['depth image','noun_phrase','深度图','range image','Perception / Sensor Fusion / 3D Vision','perception','code review','process','The depth image from the stereo camera has holes where the matching confidence is low.','stereo camera 的 depth image 在 matching confidence 低的地方有空洞。',3,['perception','sensor']],
['semantic segmentation','noun_phrase','语义分割','label each pixel','Perception / Sensor Fusion / 3D Vision','perception','experiment report','classify','Semantic segmentation labels every point as ground obstacle or dynamic object.','semantic segmentation 将每个 point label 为 ground obstacle 或 dynamic object。',4,['perception','ml']],
['frustum culling','noun_phrase','视锥剔除','remove outside view','Perception / Sensor Fusion / 3D Vision','perception','code review','filter','Frustum culling removes all points outside the camera field of view before processing.','frustum culling 在处理前 remove 所有在 camera field of view 之外的 points。',3,['perception','processing']],
['point clustering','noun_phrase','点聚类','group points','Perception / Sensor Fusion / 3D Vision','perception','code review','group','Point clustering groups nearby points into distinct objects for the tracking module.','point clustering 将附近的 points group 成 distinct objects 供 tracking module 使用。',3,['perception','algorithm']],
['object tracker','noun_phrase','目标追踪器','follow objects','Perception / Sensor Fusion / 3D Vision','perception','code review','track','The object tracker assigns a persistent ID to each detected obstacle across frames.','object tracker 为每个跨帧 detected obstacle 分配一个 persistent ID。',3,['perception','tracking']],

// === MOTION PLANNING ===
['trajectory rollout','noun_phrase','轨迹展开','generate candidates','Motion Planning / Trajectory Optimization','planning','code review','generate','Trajectory rollout generates a set of candidate paths and evaluates each against the costmap.','trajectory rollout 生成一组 candidate paths 并根据 costmap 评估每个。',4,['planning','algorithm']],
['collision checker','noun_phrase','碰撞检测器','footprint tester','Motion Planning / Trajectory Optimization','planning','code review','check','The collision checker tests whether the robot footprint overlaps any obstacle cell.','collision checker 测试 robot footprint 是否 overlapping 任何 obstacle cell。',3,['planning','safety']],
['motion primitive','noun_phrase','运动基元','predefined motion','Motion Planning / Trajectory Optimization','planning','system design','define','Each motion primitive is a short feasible arc that the planner can chain together.','每个 motion primitive 是一个 short feasible arc planner 可以将它们 chain 在一起。',4,['planning','algorithm']],
['path smoothing','noun_phrase','路径平滑','make path smooth','Motion Planning / Trajectory Optimization','planning','code review','improve','Path smoothing reduces unnecessary turns and makes the trajectory easier for the controller.','path smoothing 减少不必要的转弯使 trajectory 对 controller 更 easy。',3,['planning','optimization']],
['reeds-shepp curve','noun_phrase','Reeds-Shepp曲线','optimal short path','Motion Planning / Trajectory Optimization','planning','code review','plan','The Reeds-Shepp curve gives the shortest path for a car-like robot with a bounded turning radius.','Reeds-Shepp curve 为具有 bounded turning radius 的 car-like robot 提供 shortest path。',5,['planning','math']],
['dubins path','noun_phrase','Dubins路径','forward-only curve','Motion Planning / Trajectory Optimization','planning','code review','plan','A Dubins path assumes the robot can only move forward which is true for many fixed-wing drones.','Dubins path 假设 robot 只能 forward 这对许多 fixed-wing drones 成立。',4,['planning','math']],
['kinodynamic planning','noun_phrase','运动动力学规划','velocity-aware planning','Motion Planning / Trajectory Optimization','planning','experiment report','plan','Kinodynamic planning respects velocity and acceleration limits not just geometric constraints.','kinodynamic planning 尊重 velocity 和 acceleration limits 而不仅仅是 geometric constraints。',5,['planning','algorithm']],
['footprint inflation','noun_phrase','轮廓膨胀','safety margin','Motion Planning / Trajectory Optimization','planning','system design','configure','Footprint inflation adds a safety margin around the robot to account for localization error.','footprint inflation 在 robot 周围添加 safety margin 以应对 localization error。',3,['planning','safety']],

// === CONTROL ===
['joint trajectory','noun_phrase','关节轨迹','arm path','Control / ros2_control / Real-time Systems','control','code review','plan','The joint trajectory defines position velocity and acceleration for each joint over time.','joint trajectory 定义了每个 joint 随时间变化的 position velocity 和 acceleration。',3,['control','trajectory']],
['effort control','noun_phrase','力矩控制','torque mode','Control / ros2_control / Real-time Systems','control','system design','control','Effort control sends raw torque commands to the motors and needs a safety watchdog.','effort control 向 motors 发送 raw torque commands 需要 safety watchdog。',4,['control','hardware']],
['position control','noun_phrase','位置控制','position mode','Control / ros2_control / Real-time Systems','control','system design','control','Position control uses a PID loop to track the desired joint angle from the trajectory.','position control 使用 PID loop 来 track trajectory 中的 desired joint angle。',3,['control','algorithm']],
['velocity control','noun_phrase','速度控制','speed mode','Control / ros2_control / Real-time Systems','control','system design','control','Velocity control sends speed commands and relies on the motor driver for torque regulation.','velocity control 发送 speed commands 并依靠 motor driver 进行 torque regulation。',3,['control','algorithm']],
['control update loop','noun_phrase','控制更新循环','real-time loop','Control / ros2_control / Real-time Systems','control','system design','implement','The control update loop runs at 1000 Hz and must never miss a deadline.','control update loop 以 1000 Hz 运行必须 never miss a deadline。',4,['control','real-time']],
['feedforward term','noun_phrase','前馈项','predictive input','Control / ros2_control / Real-time Systems','control','code review','improve','The feedforward term compensates for known dynamics before the feedback loop corrects the error.','feedforward term 在 feedback loop 纠正 error 之前补偿 known dynamics。',4,['control','algorithm']],
['anti-windup','noun_phrase','抗积分饱和','prevent integral buildup','Control / ros2_control / Real-time Systems','control','code review','prevent','Anti-windup stops the integral term from growing unbounded when the actuator saturates.','anti-windup 在 actuator saturates 时阻止 integral term unbounded growth。',4,['control','algorithm']],
['control frequency','noun_phrase','控制频率','loop rate','Control / ros2_control / Real-time Systems','control','debugging','measure','The control frequency dropped below 500 Hz when logging was enabled on the same core.','当 logging 在同一 core 上启用时 control frequency 降到了 500 Hz 以下。',3,['control','real-time']],

// === SIMULATION ===
['spawn model','noun_phrase','生成模型','create in sim','Simulation / Gazebo / Digital Twin','simulation','simulation test','setup','We spawn the robot model into Gazebo with the correct initial pose and joint config.','我们用正确的 initial pose 和 joint config 在 Gazebo 中 spawn robot model。',2,['simulation','gazebo']],
['physics engine','noun_phrase','物理引擎','simulation physics','Simulation / Gazebo / Digital Twin','simulation','system design','configure','The physics engine in Gazebo uses ODE by default but we switched to Bullet for better contact.','Gazebo 中的 physics engine 默认使用 ODE 但我们切换到 Bullet 以获得更好的 contact。',3,['simulation','gazebo']],
['sensor plugin','noun_phrase','传感器插件','gazebo sensor add-on','Simulation / Gazebo / Digital Twin','simulation','system design','add','The sensor plugin adds Gaussian noise to the lidar to simulate real sensor behaviour.','sensor plugin 向 lidar 添加 Gaussian noise 以模拟 real sensor behaviour。',3,['simulation','gazebo']],
['world plugin','noun_phrase','世界插件','gazebo world logic','Simulation / Gazebo / Digital Twin','simulation','system design','extend','The world plugin spawns obstacles at random positions for each simulation run.','world plugin 在每次 simulation run 时随机 spawn obstacles。',3,['simulation','gazebo']],
['sim time','noun_phrase','仿真时间','simulated clock','Simulation / Gazebo / Digital Twin','simulation','debugging','synchronize','The sim time is published on the clock topic so all nodes use the same time base.','sim time 发布在 clock topic 上这样所有 node 使用相同的 time base。',2,['simulation','ros2']],
['headless simulation','noun_phrase','无头仿真','no-GUI sim','Simulation / Gazebo / Digital Twin','simulation','benchmark analysis','run','We run headless simulation on the CI server to test the planner 24 hours a day.','我们在 CI server 上 run headless simulation 以 24 小时测试 planner。',3,['simulation','ci']],
['sim-to-real gap','noun_phrase','仿真到现实差距','sim vs real','Simulation / Gazebo / Digital Twin','simulation','experiment report','understand','The sim-to-real gap is mainly caused by inaccurate friction and sensor noise modelling.','sim-to-real gap 主要由 inaccurate friction 和 sensor noise modelling 引起。',4,['simulation','research']],

// === HARDWARE / SENSORS ===
['can bus','noun_phrase','CAN总线','CAN communication','Hardware / Actuator / Sensor / Mechanical','hardware','system design','connect','The CAN bus connects all motor drivers to the onboard computer at 1 Mbps.','CAN bus 以 1 Mbps 将所有 motor drivers 连接到 onboard computer。',3,['hardware','communication']],
['encoder resolution','noun_phrase','编码器分辨率','ticks per rev','Hardware / Actuator / Sensor / Mechanical','hardware','debugging','measure','The encoder resolution of 4096 ticks per revolution gives sub-degree accuracy at the joint.','每圈 4096 ticks 的 encoder resolution 在 joint 处提供 sub-degree accuracy。',3,['hardware','sensor']],
['motor driver','noun_phrase','电机驱动','controller board','Hardware / Actuator / Sensor / Mechanical','hardware','system design','control','The motor driver takes velocity commands from the control loop and drives the motor phases.','motor driver 从 control loop 接收 velocity commands 并驱动 motor phases。',3,['hardware','actuator']],
['power board','noun_phrase','电源板','power management','Hardware / Actuator / Sensor / Mechanical','hardware','system design','supply','The power board monitors voltage and current for each motor and shuts down on overcurrent.','power board 监控每个 motor 的 voltage 和 current 并在 overcurrent 时 shut down。',3,['hardware','power']],
['implicit joint','noun_phrase','隐式关节','fixed offset','Hardware / Actuator / Sensor / Mechanical','hardware','code review','define','We modelled the camera mount as an implicit joint so it stays at a fixed offset from the base.','我们把 camera mount model 为 implicit joint 使其与 base 保持 fixed offset。',3,['hardware','modeling']],
['gear ratio','noun_phrase','传动比','gear reduction','Hardware / Actuator / Sensor / Mechanical','hardware','system design','calculate','The gear ratio of 50 to 1 means the motor spins 50 times for one rev of the output shaft.','50:1 的 gear ratio 意味着 motor 转 50 圈 output shaft 才转一圈。',3,['hardware','mechanical']],

// === ROS2 / MIDDLEWARE ===
['spin some','noun_phrase','选择性spin','spin with timeout','ROS2 / Middleware / System Architecture','system architecture','code review','execute','We use spin_some instead of spin to process available messages without blocking indefinitely.','我们使用 spin_some 而不是 spin 来 process available messages 而不 indefinitely blocking。',3,['ros2','executor']],
['multi-threaded executor','noun_phrase','多线程执行器','parallel callback runner','ROS2 / Middleware / System Architecture','system architecture','system design','optimize','The multi-threaded executor runs callbacks in parallel across a thread pool of four threads.','multi-threaded executor 在四个线程的 thread pool 中 parallel run callbacks。',4,['ros2','executor']],
['composable node','noun_phrase','可组合节点','component-loaded node','ROS2 / Middleware / System Architecture','system architecture','system design','design','A composable node is loaded into a component container and shares the same process.','composable node 被 load 到 component container 中并共享同一 process。',3,['ros2','component']],
['rclcpp','noun','rclcpp客户端库','C++ client library','ROS2 / Middleware / System Architecture','system architecture','code review','develop','Rclcpp is the ROS2 client library for C++ and wraps the lower-level rcl layer.','rclcpp 是 ROS2 的 C++ client library 封装了 lower-level rcl layer。',4,['ros2','library'],'word'],
['rclpy','noun','rclpy客户端库','Python client library','ROS2 / Middleware / System Architecture','system architecture','code review','develop','Rclpy is the Python client library for ROS2 with an API similar to rclcpp.','rclpy 是 ROS2 的 Python client library API 与 rclcpp 类似。',4,['ros2','library'],'word'],
['ros2 bag','noun_phrase','ROS2 bag工具','record and replay','ROS2 / Middleware / System Architecture','system architecture','debugging','record','Ros2 bag records all specified topics into an SQLite database for later replay.','ros2 bag 将所有 specified topics record 到 SQLite database 中供后续 replay。',3,['ros2','tool']],
['ros2 control','noun_phrase','ros2控制框架','control framework','Control / ros2_control / Real-time Systems','control','system design','implement','Ros2 control provides a standard interface between controllers and hardware drivers.','ros2 control 在 controllers 和 hardware drivers 之间提供 standard interface。',4,['control','framework']],
['rmw layer','noun_phrase','中间件抽象层','middleware abstraction','ROS2 / Middleware / System Architecture','system architecture','system design','abstract','The rmw layer abstracts the DDS implementation so the rest of ROS2 is vendor-neutral.','rmw layer abstract DDS implementation 使 ROS2 的其他部分 vendor-neutral。',4,['ros2','middleware']],
['deadline QoS','noun_phrase','Deadline服务质量','message deadline','ROS2 / Middleware / System Architecture','system architecture','code review','configure','Deadline QoS ensures a topic receives messages within a maximum period or gets a callback.','deadline QoS 确保 topic 在最大时间内 receive messages 否则获得 callback。',4,['ros2','qos']],
['lifespan QoS','noun_phrase','Lifespan服务质量','message expiry','ROS2 / Middleware / System Architecture','system architecture','code review','configure','Lifespan QoS discards messages older than the specified duration to avoid processing stale data.','lifespan QoS 丢弃超过指定时长的 messages 以避免 processing stale data。',4,['ros2','qos']],
['rosdep','noun','rosdep依赖工具','dependency resolver','ROS2 / Middleware / System Architecture','system architecture','system design','install','Rosdep checks and installs system dependencies listed in the package.xml of every package.','rosdep 检查并安装每个 package 的 package.xml 中列出的 system dependencies。',3,['ros2','tool'],'word'],

// === ROBOT LEARNING ===
['observation space','noun_phrase','观测空间','what agent sees','Robot Learning / Embodied AI / Policy Learning','robot learning','system design','define','The observation space includes the joint positions velocities and the target pose error.','observation space 包括 joint positions velocities 和 target pose error。',3,['robot learning','rl']],
['action space','noun_phrase','动作空间','what agent can do','Robot Learning / Embodied AI / Policy Learning','robot learning','system design','define','The action space is the set of joint torque commands the policy can output at each step.','action space 是 policy 在每一步可以 output 的 joint torque commands 集合。',3,['robot learning','rl']],
['reward shaping','noun_phrase','奖励塑造','design reward','Robot Learning / Embodied AI / Policy Learning','robot learning','experiment report','design','Reward shaping adds intermediate rewards to help the agent learn faster than with sparse rewards.','reward shaping 添加 intermediate rewards 帮助 agent 比 sparse rewards 更快 learn。',4,['robot learning','rl']],
['domain randomization','noun_phrase','域随机化','vary sim params','Robot Learning / Embodied AI / Policy Learning','robot learning','experiment report','train','Domain randomization varies friction mass and lighting during training to bridge the sim-to-real gap.','domain randomization 在 training 期间 vary friction mass 和 lighting 以 bridge sim-to-real gap。',5,['robot learning','simulation']],
['isaac sim','noun_phrase','Isaac Sim平台','NVIDIA sim platform','Robot Learning / Embodied AI / Policy Learning','simulation','simulation test','train','Isaac Sim provides GPU-accelerated physics and photorealism for robot policy training.','Isaac Sim 为 robot policy training 提供 GPU-accelerated physics 和 photorealism。',4,['robot learning','nvidia']],
['checkpoint policy','noun_phrase','检查点策略','saved model','Robot Learning / Embodied AI / Policy Learning','robot learning','experiment report','save','We save a checkpoint policy every 50000 environment steps during the training run.','我们在 training run 期间每 50000 environment steps 保存一个 checkpoint policy。',3,['robot learning','training']],

// === EXPERIMENT / BENCHMARK ===
['ablation study','noun_phrase','消融实验','remove-to-test','Experiment / Benchmark / Evaluation','planning','benchmark analysis','evaluate','The ablation study showed that the inflation layer contributes more than the obstacle layer.','ablation study 显示 inflation layer 比 obstacle layer 的贡献更大。',4,['planning','research']],
['success rate','noun_phrase','成功率','win ratio','Experiment / Benchmark / Evaluation','planning','benchmark analysis','measure','The success rate drops from 95 percent to 60 percent when the map has narrow passages.','当 map 有 narrow passages 时 success rate 从百分之九十五降到了百分之六十。',2,['planning','metrics']],
['path length','noun_phrase','路径长度','travel distance','Experiment / Benchmark / Evaluation','planning','benchmark analysis','measure','The path length is about ten percent shorter with the new smoother.','使用 new smoother 后 path length 大约缩短了百分之十。',2,['planning','metrics']],
['computation time','noun_phrase','计算时间','processing time','Experiment / Benchmark / Evaluation','planning','benchmark analysis','measure','The computation time for the planner must stay under 50 milliseconds to meet the control rate.','planner 的 computation time 必须保持在 50 毫秒以下以满足 control rate。',3,['planning','metrics']],
['ground truth','noun_phrase','真值','actual value','Experiment / Benchmark / Evaluation','slam','benchmark analysis','measure','We use a motion capture system as ground truth to evaluate the localization accuracy.','我们使用 motion capture system 作为 ground truth 来 evaluate localization accuracy。',3,['slam','metrics']],
['repeat experiment','noun_phrase','重复实验','run again','Experiment / Benchmark / Evaluation','planning','benchmark analysis','verify','We repeat the experiment five times with different random seeds to get a reliable average.','我们以不同的 random seeds repeat the experiment 五次以获得 reliable average。',2,['planning','methodology']],
['performance regression','noun_phrase','性能回退','got worse','Experiment / Benchmark / Evaluation','planning','benchmark analysis','detect','The performance regression was traced to a commit that changed the costmap resolution.','performance regression 追踪到一个更改了 costmap resolution 的 commit。',3,['planning','quality']],

// === ENGINEERING / DEBUGGING ===
['debug build','noun_phrase','调试构建','non-optimized build','Engineering Collaboration / Debugging','system architecture','debugging','debug','The debug build runs much slower but gives us full stack traces when a segfault happens.','debug build 运行慢得多但在 segfault 发生时给出 full stack traces。',2,['ros2','debugging']],
['release build','noun_phrase','发布构建','optimized build','Engineering Collaboration / Debugging','system architecture','system design','deploy','The release build enables compiler optimizations and strips debug symbols for speed.','release build 启用 compiler optimizations 并 strip debug symbols 以提速。',2,['ros2','build']],
['stack trace','noun_phrase','调用栈','call stack print','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','The stack trace from the crash shows the segfault happened inside the point cloud callback.','crash 的 stack trace 显示 segfault 发生在 point cloud callback 内部。',3,['ros2','debugging']],
['core dump','noun_phrase','核心转储','memory dump','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','The core dump file from the crash is over 2 GB because of the large point cloud buffers.','来自 crash 的 core dump file 超过 2 GB 因为 large point cloud buffers。',3,['ros2','debugging']],
['regression test','noun_phrase','回归测试','change safety check','Engineering Collaboration / Debugging','planning','benchmark analysis','verify','The regression test suite runs 50 benchmark scenarios and compares against the last release.','regression test suite 运行 50 个 benchmark scenarios 并与上次 release 比较。',3,['planning','testing']],
['ci pipeline','noun_phrase','CI流水线','continuous integration','Engineering Collaboration / Debugging','system architecture','system design','automate','The CI pipeline builds the workspace runs linting and launches simulation tests on every PR.','CI pipeline build workspace run linting 并在每个 PR 上 launch simulation tests。',3,['ros2','devops']],
['merge request','noun_phrase','合并请求','pull request','Engineering Collaboration / Debugging','system architecture','code review','collaborate','The merge request adds a new feature to the planner but needs a review from the navigation team.','merge request 为 planner 添加了一个 new feature 但需要 navigation team 的 review。',2,['ros2','collaboration']],
['code review','noun_phrase','代码审查','peer review','Engineering Collaboration / Debugging','system architecture','code review','check','The code review caught a potential race condition in the callback group assignment.','code review 发现了 callback group assignment 中的一个 potential race condition。',2,['ros2','process']],
['dependency graph','noun_phrase','依赖图','package dependency visual','Engineering Collaboration / Debugging','system architecture','system design','understand','The dependency graph shows all packages and their interconnections in the workspace.','dependency graph 显示 workspace 中所有 packages 及其 interconnections。',2,['ros2','tool']],
['flaky test','noun_phrase','不稳定测试','unreliable test','Engineering Collaboration / Debugging','planning','debugging','diagnose','The flaky test passes nine out of ten times and fails only when the system load is high.','flaky test 十次中有九次通过只在 system load 高时 fail。',3,['planning','testing']],

// === VERBS ===
['namespace','verb','命名空间隔离','put in namespace','ROS2 / Middleware / System Architecture','system architecture','code review','organise','We namespace each robot instance so two robots can run the same node names without conflict.','我们 namespace 每个 robot instance 这样两个 robots 可以 run 相同的 node names 而不会 conflict。',3,['ros2','verb'],'word'],
['remap','verb','重映射','rename topic','ROS2 / Middleware / System Architecture','system architecture','code review','configure','We remap the scan topic from the default name to a robot-specific name.','我们将 scan topic 从 default name remap 到 robot-specific name。',2,['ros2','verb'],'word'],
['lint','verb','代码检查','run linter','Engineering Collaboration / Debugging','system architecture','code review','check','We lint all C++ files with ament_cpplint before every merge.','我们在每次 merge 前用 ament_cpplint lint 所有 C++ files。',2,['ros2','verb'],'word'],
['deadlock','verb','死锁','stuck in lock','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','The two callback groups deadlock when both try to acquire the same mutex in opposite order.','当两个 callback groups 以相反顺序 try to acquire 同一个 mutex 时 deadlock。',4,['ros2','verb'],'word','technical'],
['race condition','verb','竞态条件','timing-dependent bug','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','The shared variable race-conditions with the sensor callback and the control loop.','shared variable 与 sensor callback 和 control loop 之间 race condition。',4,['ros2','verb'],'word','technical'],
['teardown','verb','拆卸','shut down cleanly','ROS2 / Middleware / System Architecture','system architecture','code review','implement','We teardown the node in the destructor to make sure all publishers are closed properly.','我们在 destructor 中 teardown node 以确保所有 publishers properly closed。',3,['ros2','verb'],'word'],
['hot-swap','verb','热替换','swap while running','ROS2 / Middleware / System Architecture','system architecture','system design','upgrade','We hot-swapped the planner while the robot was running without restarting the navigation stack.','我们在 robot running 时 hot-swap planner 无需 restart navigation stack。',4,['ros2','verb'],'word'],
['double-check','verb','仔细检查','verify again','Engineering Collaboration / Debugging','planning','debugging','verify','Double-check the TF tree before running the planner because a missing frame causes silent failures.','在 run planner 前 double-check TF tree 因为 missing frame 会导致 silent failures。',1,['ros2','verb'],'word'],

// === PHRASAL VERBS ===
['spin down','phrasal_verb','停止运行','stop spinning','ROS2 / Middleware / System Architecture','system architecture','system design','stop','The node spins down gracefully when it receives a shutdown signal from the lifecycle manager.','当收到 lifecycle manager 的 shutdown signal 时 node gracefully spin down。',2,['ros2','phrasal_verb'],'phrase'],
['wire up','phrasal_verb','连接','connect','Hardware / Actuator / Sensor / Mechanical','hardware','real robot test','connect','We wired up the new IMU to the CAN bus and updated the URDF with the correct transform.','我们把新 IMU wire up 到 CAN bus 并更新了 URDF 的 correct transform。',2,['hardware','phrasal_verb'],'phrase'],
['bodge together','phrasal_verb','临时拼凑','quick hack','Engineering Collaboration / Debugging','system architecture','debugging','hack','We bodged together a quick test node to isolate whether the issue is in perception or control.','我们 bodge together 一个 quick test node 来 isolate 问题是否在 perception 还是 control。',2,['ros2','phrasal_verb'],'phrase','technical'],
['freeze up','phrasal_verb','卡住','become stuck','Navigation / Nav2 / Behavior Trees','navigation','debugging','diagnose','The robot freezes up when the planner runs out of time because the callback never returns.','当 planner 超时 callback 从不返回时 robot freeze up。',2,['navigation','phrasal_verb'],'phrase'],
['factor in','phrasal_verb','考虑进去','include in calculation','Motion Planning / Trajectory Optimization','planning','code review','consider','We factored in the acceleration limits when smoothing the trajectory to avoid overshoot.','我们在 smoothing trajectory 时 factor in acceleration limits 以避免 overshoot。',2,['planning','phrasal_verb'],'phrase'],
['tick over','phrasal_verb','持续运行','keep running','ROS2 / Middleware / System Architecture','system architecture','debugging','monitor','Let the system tick over for an hour to see if the memory leak causes a slowdown.','让 system tick over 一小时看看 memory leak 是否导致 slowdown。',1,['ros2','phrasal_verb'],'phrase','technical'],
['iron out','phrasal_verb','解决','fix problems','Engineering Collaboration / Debugging','planning','debugging','fix','We ironed out the remaining jitter in the trajectory by tuning the derivative gain.','我们通过 tuning derivative gain iron out trajectory 中剩余的 jitter。',2,['planning','phrasal_verb'],'phrase'],
['cut out','phrasal_verb','突然停止','suddenly stop','Hardware / Actuator / Sensor / Mechanical','hardware','debugging','diagnose','The motor cuts out when the temperature sensor reads above 120 degrees at the winding.','当 winding 的 temperature sensor 读数超过 120 度时 motor cut out。',2,['hardware','phrasal_verb'],'phrase'],
['plot out','phrasal_verb','绘制输出','plot data','Experiment / Benchmark / Evaluation','planning','benchmark analysis','visualize','We plotted out the planned path against the actual trajectory for the quarterly review.','我们为季度 review plot out planned path 与 actual trajectory 对比。',1,['planning','phrasal_verb'],'phrase'],
['clamp down','phrasal_verb','严格限制','enforce limit','Control / ros2_control / Real-time Systems','control','system design','constrain','We clamped down the maximum velocity to 0.5 meters per second for the indoor test.','我们把 indoor test 的 maximum velocity clamp down 到 0.5 米/秒。',2,['control','phrasal_verb'],'phrase'],

// === ADJECTIVES ===
['real-time safe','adjective','实时安全的','wont miss deadline','Control / ros2_control / Real-time Systems','control','code review','ensure','The control loop must be real-time safe meaning no dynamic memory allocation inside.','control loop 必须是 real-time safe 的意味着内部 no dynamic memory allocation。',4,['control','adjective'],'word'],
['thread-safe','adjective','线程安全的','concurrent ok','ROS2 / Middleware / System Architecture','system architecture','code review','ensure','The shared data structure must be thread-safe because multiple callbacks access it.','shared data structure 必须是 thread-safe 因为多个 callbacks access 它。',4,['ros2','adjective'],'word'],
['latency-sensitive','adjective','延迟敏感的','needs low delay','Control / ros2_control / Real-time Systems','control','system design','describe','The latency-sensitive control loop cannot tolerate delays longer than 1 millisecond.','latency-sensitive control loop 不能 tolerate 超过 1 毫秒的 delays。',3,['control','adjective'],'word'],
['compute-bound','adjective','计算受限的','limited by CPU','Experiment / Benchmark / Evaluation','planning','benchmark analysis','diagnose','The planner is compute-bound and the GPU does not help because the algorithm is mostly sequential.','planner 是 compute-bound 的 GPU 没有帮助因为 algorithm 大部分是 sequential。',3,['planning','adjective'],'word'],
['memory-bound','adjective','内存受限的','limited by RAM','Experiment / Benchmark / Evaluation','planning','benchmark analysis','diagnose','The mapping node is memory-bound because it stores the full-resolution global map in RAM.','mapping node 是 memory-bound 因为它将 full-resolution global map 存储在 RAM 中。',3,['slam','adjective'],'word'],
['sim-compatible','adjective','仿真兼容的','works in sim','Simulation / Gazebo / Digital Twin','simulation','code review','verify','The URDF is sim-compatible and includes all inertia and collision tags for the physics engine.','URDF 是 sim-compatible 的包含 physics engine 所需的所有 inertia 和 collision tags。',3,['simulation','adjective'],'word'],
['tuned-in','adjective','调好的','properly adjusted','Control / ros2_control / Real-time Systems','control','real robot test','describe','The controller is well tuned-in after the morning session and tracks within two centimetres.','经过上午的 session 后 controller 已经 tuned-in track 在两厘米以内。',2,['control','adjective'],'word'],
['lossy','adjective','有损的','dropping data','Perception / Sensor Fusion / 3D Vision','perception','debugging','diagnose','The lossy compression on the depth image discards fine details we need for small object detection.','depth image 上的 lossy compression 丢弃了 small object detection 所需的 fine details。',3,['perception','adjective'],'word'],
['backward-compatible','adjective','向后兼容的','old API still works','ROS2 / Middleware / System Architecture','system architecture','code review','maintain','The new message format is backward-compatible so old nodes can still subscribe without recompilation.','new message format 是 backward-compatible 的所以 old nodes 仍然可以 subscribe 无需 recompilation。',3,['ros2','adjective'],'word'],
['sample-efficient','adjective','样本高效的','learns fast','Robot Learning / Embodied AI / Policy Learning','robot learning','benchmark analysis','describe','The new algorithm is more sample-efficient and learns a walking gait in under 100000 steps.','新 algorithm 更 sample-efficient 在不到 100000 steps 内 learn walking gait。',4,['robot learning','adjective'],'word'],

// === COLLOCATIONS ===
['spin up a node','collocation','启动节点','start node','ROS2 / Middleware / System Architecture','system architecture','system design','start','Spin up a node for each sensor so the failure of one does not affect the others.','为每个 sensor spin up a node 这样其中一个 failure 不会影响其他。',2,['ros2','collocation'],'phrase'],
['remap a topic','collocation','重映射话题','rename topic','ROS2 / Middleware / System Architecture','system architecture','code review','configure','Remap a topic from the default name to include the robot namespace at launch time.','在 launch time 将 topic 从 default name remap a topic 以包含 robot namespace。',2,['ros2','collocation'],'phrase'],
['tune the gains','collocation','调增益','adjust PID','Control / ros2_control / Real-time Systems','control','experiment report','improve','We tuned the gains with a step response test and then verified on the real robot.','我们通过 step response test tune the gains 然后在 real robot 上 verify。',3,['control','collocation'],'phrase'],
['run the planner','collocation','运行规划器','execute planner','Motion Planning / Trajectory Optimization','planning','benchmark analysis','test','We ran the planner on 500 random maps and logged the success rate and path length.','我们在 500 个 random maps 上 run the planner 并 log success rate 和 path length。',2,['planning','collocation'],'phrase'],
['spawn the robot','collocation','生成机器人','create robot in sim','Simulation / Gazebo / Digital Twin','simulation','simulation test','setup','Spawn the robot at the origin and wait for all sensors to start publishing before testing.','在 origin 处 spawn the robot 并在 testing 前等待所有 sensors start publishing。',1,['simulation','collocation'],'phrase'],
['kill a node','collocation','终止节点','stop node','ROS2 / Middleware / System Architecture','system architecture','debugging','stop','We killed the failing node and the lifecycle manager automatically restarted it.','我们 kill the failing node lifecycle manager 自动 restart 了它。',1,['ros2','collocation'],'phrase'],
['check the logs','collocation','查看日志','inspect logs','Engineering Collaboration / Debugging','system architecture','debugging','diagnose','Check the logs from the last run to find the exact timestamp when the odometry started drifting.','check the logs 从上次 run 中找出 odometry 开始 drift 的确切 timestamp。',1,['ros2','collocation'],'phrase'],
['catkin build','collocation','catkin构建','catkin compile','ROS2 / Middleware / System Architecture','system architecture','system design','build','We use catkin build with the cmake argument to set the build type to Release.','我们用 catkin build 和 cmake argument 将 build type 设为 Release。',2,['ros2','collocation'],'phrase'],
['colcon build','collocation','colcon构建','colcon compile','ROS2 / Middleware / System Architecture','system architecture','system design','build','Colcon build compiles all packages in the workspace and resolves dependencies automatically.','colcon build compile workspace 中所有 packages 并 automatically resolve dependencies。',2,['ros2','collocation'],'phrase'],
['source the workspace','collocation','source工作空间','activate env','ROS2 / Middleware / System Architecture','system architecture','system design','configure','Source the workspace after every build to update the package path for the shell.','每次 build 后 source the workspace 以更新 shell 的 package path。',1,['ros2','collocation'],'phrase'],
['echo a topic','collocation','回显话题','print topic data','ROS2 / Middleware / System Architecture','system architecture','debugging','inspect','Echo a topic to see the raw data and check if the header timestamp matches the system clock.','echo a topic 查看 raw data 并检查 header timestamp 是否与 system clock 匹配。',1,['ros2','collocation'],'phrase'],
['run the test suite','collocation','运行测试套件','execute tests','Experiment / Benchmark / Evaluation','planning','benchmark analysis','test','We run the test suite on every PR and the merge is blocked if any test fails.','我们在每个 PR 上 run the test suite 任何 test fail 则 merge blocked。',2,['planning','collocation'],'phrase'],

// === SENTENCE PATTERNS ===
['The planner timed out on this map.','sentence_pattern','规划器在此地图超时','planning timeout','Motion Planning / Trajectory Optimization','planning','debugging','report','The planner timed out on this map after 50 milliseconds and the robot just stopped.','planner 在这张地图上 timed out 了 50 毫秒后 robot 就停了。',2,['planning','sentence_pattern'],'sentence_pattern'],
['The odometry is diverging after the turn.','sentence_pattern','转弯后里程计在发散','odom divergence','SLAM / Localization / Mapping','slam','debugging','report','The odometry is diverging after the turn because the wheel encoders slip on this floor.','转弯后 odometry 在 diverging 因为 wheel encoders 在这个地板上 slip。',2,['slam','sentence_pattern'],'sentence_pattern'],
['The node segfaulted during the callback.','sentence_pattern','节点在回调中段错误','segfault alert','Engineering Collaboration / Debugging','system architecture','debugging','report','The node segfaulted during the callback and the core dump points to a null pointer access.','node 在 callback 中 segfaulted core dump 指向一个 null pointer access。',3,['ros2','sentence_pattern'],'sentence_pattern'],
['The camera extrinsics are wrong again.','sentence_pattern','相机外参又错了','extrinsic error','Perception / Sensor Fusion / 3D Vision','perception','debugging','report','The camera extrinsics are wrong again and the point cloud is shifted by ten centimetres.','camera extrinsics 又错了 point cloud 偏移了十厘米。',2,['perception','sentence_pattern'],'sentence_pattern'],
['The controller needs retuning after the hardware change.','sentence_pattern','换硬件后控制器需重调','retune need','Control / ros2_control / Real-time Systems','control','real robot test','report','The controller needs retuning after the hardware change because the motor response is different.','换硬件后 controller 需要 retuning 因为 motor response 变了。',2,['control','sentence_pattern'],'sentence_pattern'],
['The simulation needs more realistic friction.','sentence_pattern','仿真需要更真实的摩擦','friction need','Simulation / Gazebo / Digital Twin','simulation','simulation test','report','The simulation needs more realistic friction because the robot slides unrealistically on turns.','simulation 需要更 realistic friction 因为 robot 转弯时 unrealistically slides。',2,['simulation','sentence_pattern'],'sentence_pattern'],
['Can we check the QoS profile on this publisher.','sentence_pattern','查下发布者的QoS配置','qos check','ROS2 / Middleware / System Architecture','system architecture','debugging','propose','Can we check the QoS profile on this publisher because messages might be dropped silently.','查一下这个 publisher 的 QoS profile 因为 messages 可能会 silently dropped。',2,['ros2','sentence_pattern'],'sentence_pattern'],
['The costmap is not updating fast enough.','sentence_pattern','代价地图更新不够快','costmap speed','Navigation / Nav2 / Behavior Trees','navigation','debugging','report','The costmap is not updating fast enough and the planner uses stale obstacle information.','costmap 更新不够快 planner 在使用 stale obstacle information。',2,['navigation','sentence_pattern'],'sentence_pattern'],
['The TF lookup failed in the navigation stack.','sentence_pattern','导航栈里TF查找失败','tf error','Navigation / Nav2 / Behavior Trees','navigation','debugging','report','The TF lookup failed in the navigation stack because the odom frame was not being published.','navigation stack 中的 TF lookup failed 因为 odom frame 没有被 publish。',2,['navigation','sentence_pattern'],'sentence_pattern'],
['We should log the full point cloud once per second.','sentence_pattern','应每秒记录一次完整点云','logging idea','Perception / Sensor Fusion / 3D Vision','perception','debugging','propose','We should log the full point cloud once per second to debug the clustering issue offline.','我们应该每秒 log the full point cloud 一次以 offline debug the clustering issue。',1,['perception','sentence_pattern'],'sentence_pattern'],

// === Many more nouns for coverage ===
['nav2 params','noun_phrase','Nav2参数','nav2 config','Navigation / Nav2 / Behavior Trees','navigation','code review','configure','The nav2 params file defines the planner controller and behavior tree plugin names.','nav2 params file 定义了 planner controller 和 behavior tree plugin names。',3,['navigation','nav2']],
['amcl config','noun_phrase','AMCL配置','localization config','SLAM / Localization / Mapping','slam','code review','configure','The AMCL config sets the particle count resample threshold and sensor model parameters.','AMCL config 设置了 particle count resample threshold 和 sensor model parameters。',4,['slam','config']],
['laser scan','noun_phrase','激光扫描','lidar reading','Perception / Sensor Fusion / 3D Vision','perception','code review','process','Each laser scan message contains an array of range values from the lidar sensor.','每个 laser scan message 包含来自 lidar sensor 的 range values array。',2,['perception','sensor']],
['point type','noun_phrase','点类型','point data format','Perception / Sensor Fusion / 3D Vision','perception','code review','define','The point type includes XYZ coordinates intensity and optionally RGB colour and ring index.','point type 包括 XYZ coordinates intensity 以及可选的 RGB colour 和 ring index。',3,['perception','data']],
['tf broadcaster','noun_phrase','TF广播器','tf publisher','ROS2 / Middleware / System Architecture','system architecture','code review','publish','The tf broadcaster publishes the transform between base link and the lidar frame at 50 Hz.','tf broadcaster 以 50 Hz publish base link 与 lidar frame 之间的 transform。',3,['ros2','tf']],
['joint limit','noun_phrase','关节限位','position cap','Hardware / Actuator / Sensor / Mechanical','hardware','system design','constrain','The joint limits in the URDF prevent the planner from commanding unreachable arm poses.','URDF 中的 joint limits 防止 planner command unreachable arm poses。',3,['hardware','safety']],
['base footprint','noun_phrase','底座轮廓','robot projection','Navigation / Nav2 / Behavior Trees','navigation','code review','define','The base footprint is a polygon that defines the robot shape for collision checking.','base footprint 是一个 polygon 定义了用于 collision checking 的 robot shape。',3,['navigation','geometry']],
['robot description','noun_phrase','机器人描述','URDF model','Simulation / Gazebo / Digital Twin','simulation','system design','define','The robot description loads the URDF from the parameter server for all nodes to use.','robot description 从 parameter server load URDF 供所有 nodes 使用。',2,['simulation','urdf']],
['joint state','noun_phrase','关节状态','joint reading','Control / ros2_control / Real-time Systems','control','code review','publish','The joint state message includes position velocity and effort for every actuated joint.','joint state message 包括每个 actuated joint 的 position velocity 和 effort。',3,['control','sensor']],
['imu frame','noun_phrase','IMU坐标系','IMU reference','SLAM / Localization / Mapping','slam','code review','define','The IMU frame must be aligned with the robot base link or the orientation estimate is wrong.','IMU frame 必须与 robot base link aligned 否则 orientation estimate 是错误的。',3,['slam','tf']],
['wall timer','noun_phrase','墙上时钟定时器','real-time timer','Control / ros2_control / Real-time Systems','control','code review','use','The wall timer triggers the control loop at a steady rate regardless of system load.','wall timer 以 steady rate trigger control loop regardless of system load。',3,['control','ros2']],
['slam toolbox','noun_phrase','SLAM工具箱','slam library','SLAM / Localization / Mapping','slam','system design','use','Slam Toolbox is a widely-used ROS2 SLAM package with both online and offline modes.','Slam Toolbox 是一个广泛使用的 ROS2 SLAM package 具有 online 和 offline modes。',3,['slam','tool']],
['pose array','noun_phrase','位姿数组','list of poses','Motion Planning / Trajectory Optimization','planning','code review','publish','The pose array message holds all the waypoints along the planned path.','pose array message 包含 planned path 上的所有 waypoints。',3,['planning','ros2']],
['nav2 simple commander','noun_phrase','Nav2简易命令器','nav2 demo tool','Navigation / Nav2 / Behavior Trees','navigation','simulation test','demo','The Nav2 Simple Commander lets us send goals from Python without RViz.','Nav2 Simple Commander 让我们可以在不用 RViz 的情况下从 Python send goals。',3,['navigation','tool']],
['twist message','noun_phrase','Twist消息','velocity command','Control / ros2_control / Real-time Systems','control','code review','publish','The twist message carries linear and angular velocity commands for the robot base.','twist message carries linear and angular velocity commands for the robot base。',2,['control','ros2']],
['sensor qos','noun_phrase','传感器QoS','sensor reliability','Perception / Sensor Fusion / 3D Vision','perception','code review','configure','The sensor QoS profile uses best-effort reliability to avoid blocking on old readings.','sensor QoS profile 使用 best-effort reliability 以避免在 old readings 上 blocking。',3,['perception','ros2']],
['dynamic reconfigure','noun_phrase','动态调参','runtime parameter change','Navigation / Nav2 / Behavior Trees','navigation','system design','tune','Dynamic reconfigure lets us tweak planner parameters without restarting the navigation stack.','dynamic reconfigure 让我们可以在不 restart navigation stack 的情况下 tweak planner parameters。',3,['navigation','config']],
['warehouse world','noun_phrase','仓库世界','warehouse sim env','Simulation / Gazebo / Digital Twin','simulation','simulation test','test','The warehouse world in Gazebo has shelves and pallets for testing autonomous forklift navigation.','Gazebo 中的 warehouse world 有 shelves 和 pallets 用于测试 autonomous forklift navigation。',2,['simulation','gazebo']],
['robot state','noun_phrase','机器人状态','current state','Control / ros2_control / Real-time Systems','control','code review','publish','The robot state publisher broadcasts the current joint positions from the hardware interface.','robot state publisher 从 hardware interface broadcast 当前的 joint positions。',3,['control','ros2']],
['monte carlo','noun_phrase','蒙特卡洛','random sampling','SLAM / Localization / Mapping','slam','experiment report','describe','The Monte Carlo localization approach represents the belief as a set of weighted particles.','Monte Carlo localization approach 将 belief 表示为 weighted particles 集合。',4,['slam','algorithm']],
['visual odometry','noun_phrase','视觉里程计','camera-based odom','SLAM / Localization / Mapping','slam','experiment report','track','Visual odometry estimates the camera motion by tracking features between consecutive frames.','visual odometry 通过 track consecutive frames 之间的 features 来 estimate camera motion。',4,['slam','perception']],
['ros2 doctor','noun_phrase','ROS2诊断工具','ros2 diagnosis','ROS2 / Middleware / System Architecture','system architecture','debugging','diagnose','Ros2 doctor checks the environment for common issues like missing dependencies or wrong DDS config.','ros2 doctor 检查环境中的 common issues 如 missing dependencies 或 wrong DDS config。',2,['ros2','tool']],
['behavior tree xml','noun_phrase','行为树XML','BT definition','Navigation / Nav2 / Behavior Trees','navigation','system design','define','The behavior tree XML defines the sequence of actions for navigation including recovery.','behavior tree XML 定义了 navigation 的 action sequence 包括 recovery。',3,['navigation','config']],
['obstacle layer','noun_phrase','障碍物层','dynamic obstacle data','Navigation / Nav2 / Behavior Trees','navigation','code review','process','The obstacle layer marks laser scan readings as lethal obstacles in the local costmap.','obstacle layer 将 laser scan readings mark 为 local costmap 中的 lethal obstacles。',3,['navigation','costmap']],
['inflation radius','noun_phrase','膨胀半径','safety buffer size','Navigation / Nav2 / Behavior Trees','navigation','code review','configure','The inflation radius expands each obstacle cell by the robot footprint plus a safety margin.','inflation radius 将每个 obstacle cell expand robot footprint 加上 safety margin。',3,['navigation','costmap']],
['goal distance','noun_phrase','目标距离','remaining distance','Motion Planning / Trajectory Optimization','planning','code review','measure','The goal distance is checked in every control cycle to trigger the arrival condition.','goal distance 在每个 control cycle 检查以 trigger the arrival condition。',2,['planning','nav2']],
['rviz panel','noun_phrase','RViz面板','visualization panel','Engineering Collaboration / Debugging','system architecture','debugging','visualize','The RViz panel shows the planned path costmap and robot footprint all in one view.','RViz panel 在一个视图中显示 planned path costmap 和 robot footprint。',1,['ros2','tool']],
['gazebo world','noun_phrase','Gazebo世界','sim world file','Simulation / Gazebo / Digital Twin','simulation','simulation test','setup','The Gazebo world includes a ground plane lighting and static obstacles for testing.','Gazebo world 包括 ground plane lighting 和 static obstacles 供 testing 使用。',2,['simulation','gazebo']],
['marker array','noun_phrase','标记数组','RViz markers','Engineering Collaboration / Debugging','system architecture','debugging','visualize','The marker array is used to display bounding boxes and object labels in RViz.','marker array 用于在 RViz 中 display bounding boxes 和 object labels。',2,['ros2','visualization']],
['collision body','noun_phrase','碰撞体','collision geometry','Motion Planning / Trajectory Optimization','planning','code review','define','Each collision body in the URDF defines a simplified shape for the collision checker.','URDF 中的每个 collision body 定义了 collision checker 使用的 simplified shape。',3,['planning','geometry']],
['service call','noun_phrase','服务调用','ROS2 service','ROS2 / Middleware / System Architecture','system architecture','code review','use','A service call is synchronous by default and blocks until the server responds or times out.','service call 默认是 synchronous 的会 block 直到 server responds 或 timeout。',3,['ros2','communication']],
['action client','noun_phrase','动作客户端','async task client','ROS2 / Middleware / System Architecture','system architecture','code review','use','The action client sends a goal and receives feedback and a result asynchronously.','action client 异步 send goal 并 receive feedback 和 result。',3,['ros2','communication']],
['data recorder','noun_phrase','数据录制器','data logging','Experiment / Benchmark / Evaluation','system architecture','debugging','record','The data recorder captures all specified topics during field tests for offline analysis.','data recorder 在场测期间 capture 所有指定 topics 供 offline analysis。',2,['ros2','tools']],
['nav2 collision monitor','noun_phrase','Nav2碰撞监控器','safety monitor','Navigation / Nav2 / Behavior Trees','navigation','system design','safety','The nav2 collision monitor stops the robot if the safety lidar zone is breached.','nav2 collision monitor 在 safety lidar zone 被 breached 时 stop robot。',3,['navigation','safety']],
['package xml','noun_phrase','package.xml文件','ROS package manifest','ROS2 / Middleware / System Architecture','system architecture','code review','define','The package xml file declares the package name version dependencies and build type.','package xml file 声明了 package name version dependencies 和 build type。',2,['ros2','build']],
['interface definition','noun_phrase','接口定义','msg/srv/action def','ROS2 / Middleware / System Architecture','system architecture','system design','define','The interface definitions for messages services and actions live in a separate package.','messages services 和 actions 的 interface definitions 放在一个单独的 package 中。',3,['ros2','communication']],
['cmake arguments','noun_phrase','CMake参数','build flags','ROS2 / Middleware / System Architecture','system architecture','code review','configure','The cmake arguments set the build type and compiler flags for the entire workspace.','cmake arguments 为整个 workspace 设置了 build type 和 compiler flags。',3,['ros2','build']],
['rviz marker','noun_phrase','RViz标记','visual marker','Engineering Collaboration / Debugging','system architecture','debugging','visualize','An RViz marker can be a sphere arrow cube or text displayed in the 3D view.','RViz marker 可以是在 3D view 中显示的 sphere arrow cube 或 text。',2,['ros2','viz']],
['action server','noun_phrase','动作服务器','async task handler','ROS2 / Middleware / System Architecture','system architecture','system design','implement','The action server accepts goals executes the task and sends feedback during execution.','action server 接受 goals execute task 并在 execution 期间 send feedback。',3,['ros2','communication']],
['loop rate','noun_phrase','循环频率','how often','Control / ros2_control / Real-time Systems','control','debugging','measure','The loop rate of the controller is measured with a timer and must stay above 500 Hz.','controller 的 loop rate 通过 timer measured 必须保持在 500 Hz 以上。',3,['control','real-time']],
['kinematic chain','noun_phrase','运动链','joint linkage','Manipulation / MoveIt2 / Kinematics','manipulation','code review','define','The kinematic chain from the base to the end-effector defines all joints in the arm.','从 base 到 end-effector 的 kinematic chain 定义了 arm 中的所有 joints。',3,['manipulation','kinematics']],
['singularity','noun','奇异点','unreachable config','Manipulation / MoveIt2 / Kinematics','manipulation','debugging','avoid','The arm reaches a singularity when two joint axes align and the Jacobian loses rank.','当两个 joint axes align 且 Jacobian loses rank 时 arm reaches a singularity。',4,['manipulation','kinematics'],'word','technical'],
['gripper command','noun_phrase','夹爪指令','end-effector action','Manipulation / MoveIt2 / Kinematics','manipulation','code review','control','The gripper command opens or closes the parallel fingers to a specified width.','gripper command 将 parallel fingers open 或 close 到指定 width。',3,['manipulation','hardware']],
['ik solver','noun_phrase','逆运动学求解器','IK algorithm','Manipulation / MoveIt2 / Kinematics','manipulation','code review','compute','The IK solver finds joint angles that place the end-effector at a target pose.','IK solver 找到将 end-effector 放置于 target pose 的 joint angles。',4,['manipulation','algorithm']],
['moveit setup assistant','noun_phrase','MoveIt配置助手','moveit config tool','Manipulation / MoveIt2 / Kinematics','manipulation','system design','configure','The MoveIt Setup Assistant generates the configuration package from the URDF.','MoveIt Setup Assistant 从 URDF generate the configuration package。',3,['manipulation','tool']],
['planning scene','noun_phrase','规划场景','collision environment','Manipulation / MoveIt2 / Kinematics','manipulation','system design','setup','The planning scene includes the robot model and all surrounding objects for collision checking.','planning scene 包括 robot model 和所有用于 collision checking 的 surrounding objects。',3,['manipulation','moveit']],
['move group','noun_phrase','运动组','joint group','Manipulation / MoveIt2 / Kinematics','manipulation','system design','organize','The move group for the arm includes all six joints from the shoulder to the wrist.','arm 的 move group 包括从 shoulder 到 wrist 的所有六个 joints。',3,['manipulation','moveit']],
['rrt planner','noun_phrase','RRT规划器','sampling planner','Motion Planning / Trajectory Optimization','planning','benchmark analysis','plan','The RRT planner rapidly explores the configuration space with random sampling.','RRT planner 通过 random sampling rapidly explore the configuration space。',4,['planning','algorithm']],
['linear interpolation','noun_phrase','线性插值','straight line between','Motion Planning / Trajectory Optimization','planning','code review','compute','Linear interpolation between two waypoints creates a constant-velocity straight segment.','两个 waypoints 之间的 linear interpolation 创建了一个 constant-velocity straight segment。',2,['planning','math']],
['workspace boundary','noun_phrase','工作空间边界','reachable limit','Manipulation / MoveIt2 / Kinematics','manipulation','system design','constrain','The workspace boundary limits the arm motion to a reachable volume in front of the robot.','workspace boundary 将 arm motion limit 到 robot 前方的 reachable volume。',3,['manipulation','safety']],
['speed scaling','noun_phrase','速度缩放','reduce speed factor','Control / ros2_control / Real-time Systems','control','system design','safety','Speed scaling reduces the maximum velocity when a person enters the safety zone.','当人进入 safety zone 时 speed scaling reduce the maximum velocity。',3,['control','safety']],
['state estimate','noun_phrase','状态估计','current belief','SLAM / Localization / Mapping','slam','experiment report','estimate','The state estimate fuses odometry IMU and visual data to produce a smooth pose stream.','state estimate 融合 odometry IMU 和 visual data 以产生 smooth pose stream。',3,['slam','fusion']],
['timing analysis','noun_phrase','时序分析','latency check','Engineering Collaboration / Debugging','system architecture','debugging','measure','The timing analysis shows that the perception pipeline takes 42 ms out of the 50 ms budget.','timing analysis 显示 perception pipeline 占用 50 ms budget 中的 42 ms。',4,['ros2','debugging']],
['motion model','noun_phrase','运动模型','how robot moves','SLAM / Localization / Mapping','slam','code review','define','The motion model predicts the next pose given the current pose and control input.','motion model 在给定当前 pose 和 control input 的情况下 predict 下一个 pose。',4,['slam','math']],
['observation model','noun_phrase','观测模型','sensor likelihood','SLAM / Localization / Mapping','slam','code review','define','The observation model computes the likelihood of a sensor reading given a pose hypothesis.','observation model 计算给定 pose hypothesis 下 sensor reading 的 likelihood。',4,['slam','math']],
['slam node','noun_phrase','SLAM节点','slam ros node','SLAM / Localization / Mapping','slam','system design','implement','The SLAM node subscribes to the scan topic and publishes the map and the robot pose.','SLAM node subscribe to scan topic 并 publish map 和 robot pose。',3,['slam','ros2']],
['ekf node','noun_phrase','EKF节点','extended kalman filter','SLAM / Localization / Mapping','slam','system design','estimate','The EKF node fuses wheel odometry IMU and visual odometry into a single pose output.','EKF node 融合 wheel odometry IMU 和 visual odometry 成 single pose output。',4,['slam','ros2']],
['filter chain','noun_phrase','滤波器链','sequential filters','Perception / Sensor Fusion / 3D Vision','perception','code review','process','The filter chain applies crop box voxel grid and passthrough filters to the raw cloud.','filter chain 对 raw cloud apply crop box voxel grid 和 passthrough filters。',3,['perception','pipeline']],
['robot localization','noun_phrase','机器人定位','state estimation pkg','SLAM / Localization / Mapping','slam','system design','localize','The robot localization package implements a non-linear state estimator for mobile robots.','robot localization package 为 mobile robots 实现了 non-linear state estimator。',4,['slam','ros2']],
];

for(const x of L){if(D.length>=T)break;a(...x);}
console.log('Added',A,'|Skip',S,'|Total',D.length);if(D.length<T)console.log('Short',T-D.length);
fs.writeFileSync(F,JSON.stringify(D));
let pc=fs.readFileSync('src/data/packs.ts','utf-8');pc=pc.replace(/('robotics-rd-engineering-research-1000'[\s\S]*?total:\s*)\d+/,(_,p)=>p+D.length);fs.writeFileSync('src/data/packs.ts',pc);
let st=JSON.parse(fs.readFileSync('docs/WORD_PACK_GENERATION_STATUS.json','utf-8'));if(st.packs['robotics-rd-engineering-research-1000'])st.packs['robotics-rd-engineering-research-1000'].current=D.length;st.lastAction='Extended robotics-rd pack to '+D.length+' with clean exampleZh items.';fs.writeFileSync('docs/WORD_PACK_GENERATION_STATUS.json',JSON.stringify(st,null,2));
console.log('Done:',D.length);

