// DEPRECATED / DO NOT RUN
// This generator may produce low-quality or over-target items.
// Use only with a manually curated candidate pool.
const fs=require('fs');
const file='src/data/packs/foreign-trade-crowdfunding-dtc-operations-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));
const TARGET=1000;
let id=data.length,added=0,skipped=0;

// FullForm map for abbreviations
const FF={ROAS:'Return on Ad Spend',CPC:'Cost Per Click',CTR:'Click-Through Rate',CPA:'Cost Per Acquisition',CPM:'Cost Per Mille',AOV:'Average Order Value',MOQ:'Minimum Order Quantity','3PL':'Third-Party Logistics',CRM:'Customer Relationship Management',KPI:'Key Performance Indicator',ROI:'Return on Investment',EXW:'Ex Works',FOB:'Free On Board',CIF:'Cost Insurance Freight',DDP:'Delivered Duty Paid',FAQ:'Frequently Asked Questions',LTV:'Lifetime Value',SKU:'Stock Keeping Unit',BOM:'Bill of Materials',PO:'Purchase Order',ETA:'Estimated Time of Arrival',OEM:'Original Equipment Manufacturer',ODM:'Original Design Manufacturer',FBA:'Fulfillment by Amazon',COD:'Cash on Delivery',TOS:'Terms of Service',SOP:'Standard Operating Procedure'};

// item format: [term,pos,sm,sis,topic,bizStage,workIntent,ex,ez,diff,tags,type,reg]
// exampleZh rule: only target term + allowlist in English
const newItems=[];
const items=[

// ===== CROWDFUNDING CAMPAIGN =====
['campaign video','noun_phrase','活动视频','promo video','Crowdfunding Campaign','pre-launch','engage visitors','The campaign video should show the product working within the first ten seconds.','campaign video 应该在头十秒内展示产品的实际使用情况。',1,['crowdfunding','content'],'phrase'],
['backer community','noun_phrase','支持者社群','supporter group','Crowdfunding Campaign','campaign live','build engagement','Our backer community is very active and regularly shares feedback in the comments section.','我们的 backer community 非常活跃，经常在评论区分享反馈。',1,['crowdfunding','community'],'phrase'],
['press kit','noun_phrase','媒体资料包','media package','Crowdfunding Campaign','pre-launch','earn media coverage','We sent the press kit to over fifty journalists two weeks before launch.','我们在上线前两周把 press kit 发给了五十多位记者。',2,['crowdfunding','marketing'],'phrase'],
['viral coefficient','noun_phrase','病毒系数','sharing growth rate','Crowdfunding Campaign','campaign live','measure sharing','Our viral coefficient is above one which means each backer brings in more than one new backer.','我们的 viral coefficient 超过一，意味着每个支持者平均带来超过一个新支持者。',3,['crowdfunding','growth'],'phrase'],
['campaign analytics','noun_phrase','活动分析','campaign data','Crowdfunding Campaign','campaign live','track performance','Campaign analytics show that most pledges come in between 6pm and 10pm on weekdays.','campaign analytics 显示大多数认缴发生在工作日的晚上六点到十点之间。',2,['crowdfunding','data'],'phrase'],
['social proof','noun_phrase','社会证明','customer validation','Crowdfunding Campaign','campaign live','build trust','Adding social proof like backer quotes boosted our conversion rate by over ten percent.','在页面上添加支持者引语等 social proof 后，转化率提高了超过百分之十。',2,['crowdfunding','marketing'],'phrase'],
['press release','noun_phrase','新闻稿','media announcement','Crowdfunding Campaign','pre-launch','earn media','The press release went out on the same morning the campaign went live.','press release 在活动上线的同一天早上发出。',1,['crowdfunding','marketing'],'phrase'],
['influencer outreach','noun_phrase','达人外联','influencer contact','Crowdfunding Campaign','pre-launch','earn coverage','We started influencer outreach about a month before launch and got ten product review videos.','我们在上线前大约一个月开始 influencer outreach，得到了十个产品评测视频。',2,['crowdfunding','marketing'],'phrase'],
['reward survey','noun_phrase','回报调查','reward questionnaire','Crowdfunding Campaign','post-campaign fulfillment','collect preferences','The reward survey asks backers to choose their colour and confirm their shipping address.','reward survey 让支持者选择颜色并确认收货地址。',1,['crowdfunding','communication'],'phrase'],
['project timeline','noun_phrase','项目时间线','schedule','Crowdfunding Campaign','campaign live','set expectations','The project timeline on the page shows delivery estimated for March next year.','页面上的 project timeline 显示预计明年三月交付。',1,['crowdfunding','planning'],'phrase'],
['backer update','noun_phrase','支持者更新','supporter update','Crowdfunding Campaign','post-campaign fulfillment','maintain transparency','We post a backer update every Friday with factory photos and progress notes.','我们每周五发布 backer update，附上工厂照片和进度说明。',1,['crowdfunding','communication'],'phrase'],
['campaign header','noun_phrase','活动头图','campaign banner','Crowdfunding Campaign','pre-launch','attract attention','The campaign header image should show the product in use not just a render.','campaign header 图片应展示产品的实际使用场景，而不仅仅是渲染图。',1,['crowdfunding','content'],'phrase'],
['launch timing','noun_phrase','上线时机','when to launch','Crowdfunding Campaign','pre-launch','plan schedule','The launch timing matters a lot because summer months are slow for crowdfunding.','launch timing 非常重要，因为夏季对众筹来说是淡季。',2,['crowdfunding','strategy'],'phrase'],
['pledge level','noun_phrase','认缴档位','pledge amount','Crowdfunding Campaign','campaign live','track funding','The average pledge level on this campaign is higher than our previous one.','这次活动的平均 pledge level 比我们上次的高。',1,['crowdfunding','funding'],'phrase'],
['backer referral','noun_phrase','支持者推荐','backer invite','Crowdfunding Campaign','campaign live','grow organically','We added a backer referral programme that gives credits for bringing in new supporters.','我们增加了一个 backer referral 计划，为引入新支持者提供积分。',2,['crowdfunding','growth'],'phrase'],
['campaign dashboard','noun_phrase','活动仪表盘','campaign metrics','Crowdfunding Campaign','campaign live','monitor campaign','The campaign dashboard shows real-time pledge totals and traffic sources.','campaign dashboard 显示实时的认缴总额和流量来源。',2,['crowdfunding','data'],'phrase'],
['pledge confirmation','noun_phrase','认缴确认','pledge receipt','Crowdfunding Campaign','campaign live','confirm payment','Backers receive a pledge confirmation email immediately after their payment goes through.','支持者在付款成功后立即收到 pledge confirmation 邮件。',1,['crowdfunding','communication'],'phrase'],

// ===== BACKER COMMUNICATION =====
['backer satisfaction','noun_phrase','支持者满意度','supporter happiness','Backer Communication','post-campaign fulfillment','measure sentiment','Backer satisfaction dropped after the second delay announcement so we added a live Q&A.','在第二次延迟公告后 backer satisfaction 下降了，所以我们增加了直播问答。',2,['communication','metrics'],'phrase'],
['delay notice','noun_phrase','延迟通知','delay announcement','Backer Communication','post-campaign fulfillment','manage expectations','We sent a delay notice explaining that the tooling revision will add four weeks.','我们发了一则 delay notice，解释模具修改将增加四周。',2,['communication','transparency'],'phrase'],
['backer poll','noun_phrase','支持者投票','supporter vote','Backer Communication','campaign live','involve community','We ran a backer poll to decide between two colour options for the final product.','我们发起了一次 backer poll 来决定最终产品的两种颜色选项。',1,['communication','community'],'phrase'],
['comment reply','noun_phrase','评论回复','response to comment','Backer Communication','campaign live','engage supporters','Every comment reply should be polite and factual even when the backer is upset.','每条 comment reply 都应礼貌且如实，即使支持者情绪激动。',1,['communication','support'],'phrase'],
['update frequency','noun_phrase','更新频率','how often','Backer Communication','post-campaign fulfillment','set expectations','The update frequency should be at least once every two weeks during production.','update frequency 在生产期间应至少每两周一次。',1,['communication','planning'],'phrase'],
['backer expectation','noun_phrase','支持者期望','what backers expect','Backer Communication','campaign live','understand audience','Backer expectations are high because the campaign promised delivery within six months.','backer expectation 很高，因为活动承诺六个月内交付。',2,['communication','strategy'],'phrase'],
['shipping survey','noun_phrase','发货调查','delivery questionnaire','Backer Communication','post-campaign fulfillment','collect addresses','The shipping survey must be completed before we can assign tracking numbers.','shipping survey 必须在我们分配追踪号之前完成。',1,['communication','logistics'],'phrase'],
['batch notification','noun_phrase','批次通知','batch announcement','Backer Communication','post-campaign fulfillment','inform progress','We sent a batch notification to backers in the first wave confirming their orders are shipping.','我们向第一批的 backer 发送了 batch notification，确认他们的订单正在发货。',2,['communication','logistics'],'phrase'],
['backer-only update','noun_phrase','仅支持者可见','exclusive update','Backer Communication','campaign live','reward loyalty','We posted a backer-only update with a behind-the-scenes video from the factory.','我们发布了一则 backer-only update，附有工厂的幕后视频。',1,['communication','community'],'phrase'],

// ===== SHOPIFY / DTC STORE =====
['storefront','noun_phrase','店铺门面','online store front','Shopify / DTC Store','dtc store operation','present brand','The storefront needs a cleaner design with less clutter above the fold.','storefront 需要更简洁的设计，首屏减少杂乱。',1,['dtc','design'],'phrase'],
['payment gateway','noun_phrase','支付网关','payment processor','Shopify / DTC Store','dtc store operation','accept payments','We switched the payment gateway because the old one did not support local currency in Singapore.','我们更换了 payment gateway，因为旧的在新加坡不支持当地货币。',2,['dtc','technical'],'phrase'],
['inventory sync','noun_phrase','库存同步','stock synchronisation','Shopify / DTC Store','dtc store operation','avoid overselling','The inventory sync between Shopify and the warehouse has a two-hour delay.','Shopify 和仓库之间的 inventory sync 延迟了大约两小时。',2,['dtc','operations'],'phrase'],
['product variant','noun_phrase','产品变体','product option','Shopify / DTC Store','dtc store operation','offer choices','The most popular product variant is the black one with the larger battery.','最受欢迎的 product variant 是带大电池的黑色款。',1,['dtc','product'],'phrase'],
['sales tax','noun_phrase','销售税','purchase tax','Shopify / DTC Store','dtc store operation','comply with tax','We need to configure the sales tax setting correctly for each state we ship to.','我们需要为每个发货州正确配置 sales tax 设置。',2,['dtc','finance'],'phrase'],
['order tracking','noun_phrase','订单追踪','shipment tracking','Shopify / DTC Store','dtc store operation','keep customers informed','The order tracking page should show live status from the carrier API.','order tracking 页面应该显示来自承运商 API 的实时状态。',1,['dtc','operations'],'phrase'],
['conversion funnel','noun_phrase','转化漏斗','purchase path','Shopify / DTC Store','dtc store operation','analyse flow','The conversion funnel shows a big drop between add-to-cart and checkout.','conversion funnel 显示从加购到结账之间有大量流失。',2,['dtc','analytics'],'phrase'],
['product tag','noun_phrase','产品标签','item label','Shopify / DTC Store','dtc store operation','organise products','We use product tags to automatically sort items into the right collection pages.','我们用 product tag 自动将商品归类到正确的系列页面中。',1,['dtc','operations'],'phrase'],
['shipping calculator','noun_phrase','运费计算器','delivery cost tool','Shopify / DTC Store','dtc store operation','show costs','The shipping calculator on the cart page should estimate costs before checkout.','购物车页面的 shipping calculator 应该在结账前估算费用。',1,['dtc','tools'],'phrase'],
['loyalty programme','noun_phrase','忠诚计划','reward scheme','Shopify / DTC Store','dtc store operation','retain customers','Our loyalty programme gives points for every purchase that can be redeemed for discounts.','我们的 loyalty programme 为每次购买提供可兑换折扣的积分。',1,['dtc','retention'],'phrase'],
['referral link','noun_phrase','推荐链接','share link','Shopify / DTC Store','dtc store operation','grow through word of mouth','Each customer gets a unique referral link to share with friends for credit.','每位客户获得一个唯一的 referral link 分享给朋友可获得积分。',1,['dtc','growth'],'phrase'],
['bulk discount','noun_phrase','批量折扣','volume price break','Shopify / DTC Store','dtc store operation','increase AOV','We added a bulk discount for orders of three or more and the average cart size jumped.','我们为三件及以上订单增加了 bulk discount，平均购物车金额大涨。',2,['dtc','pricing'],'phrase'],
['product bundle','noun_phrase','产品套装','item combo','Shopify / DTC Store','dtc store operation','increase order value','The product bundle pairs the main device with a case and screen protector at a slight discount.','product bundle 将主设备与保护壳和屏幕保护膜以小幅折扣组合在一起。',1,['dtc','sales'],'phrase'],
['collection page','noun_phrase','系列页面','category page','Shopify / DTC Store','dtc store operation','organise products','The collection page should have clear filtering options so customers can narrow down quickly.','collection page 应该有清晰的筛选选项，让客户能快速缩小范围。',1,['dtc','design'],'phrase'],
['homepage hero','noun_phrase','首页主图','hero banner','Shopify / DTC Store','dtc store operation','capture attention','The homepage hero banner should show our best-selling product with a clear call to action.','homepage hero 横幅应该展示我们的畅销产品并带有清晰的行动号召。',1,['dtc','design'],'phrase'],
['mobile checkout','noun_phrase','移动端结账','phone checkout','Shopify / DTC Store','dtc store operation','improve mobile','Mobile checkout conversion is lower than desktop so we need to simplify the form fields.','移动端结账转化率比桌面端低，所以我们需要简化表单字段。',2,['dtc','ux'],'phrase'],
['store speed','noun_phrase','店铺速度','page load time','Shopify / DTC Store','dtc store operation','optimise performance','Store speed affects both conversion rate and Google ranking so we compress all images.','store speed 影响转化率和 Google 排名，所以我们压缩了所有图片。',2,['dtc','technical'],'phrase'],
['product feed','noun_phrase','商品数据源','product data file','Shopify / DTC Store','dtc store operation','sync to ads','The product feed for Google Shopping needs accurate titles prices and availability.','Google Shopping 的 product feed 需要准确的标题、价格和库存状态。',3,['dtc','technical'],'phrase'],
['brand voice','noun_phrase','品牌语调','brand tone','Shopify / DTC Store','dtc store operation','define style','Our brand voice is casual and direct never corporate or salesy.','我们的 brand voice 是随意直接的，从不是企业化或推销式的。',1,['dtc','brand'],'phrase'],
['value proposition','noun_phrase','价值主张','why buy','Shopify / DTC Store','dtc store operation','communicate value','The value proposition should be clear within three seconds of landing on the page.','value proposition 应该在到达页面的三秒内清晰传达。',2,['dtc','strategy'],'phrase'],

// ===== ADS / ACQUISITION =====
['ad copy','noun_phrase','广告文案','ad text','Ads / Acquisition','paid acquisition','craft message','The ad copy should speak directly to the pain point not just describe the product.','ad copy 应该直接针对痛点，而不仅仅是描述产品。',1,['ads','content'],'phrase'],
['landing page view','noun_phrase','落地页浏览','page visit','Ads / Acquisition','paid acquisition','measure traffic','Landing page views are up but conversions are flat which suggests a page problem.','landing page view 上升了但转化持平，这说明是页面问题而不是广告问题。',2,['ads','metrics'],'phrase'],
['cost cap','noun_phrase','成本上限','spending limit','Ads / Acquisition','paid acquisition','control budget','We set a cost cap of twenty dollars per purchase to keep the campaign profitable.','我们把每次购买的 cost cap 设在二十美元以保持活动盈利。',2,['ads','strategy'],'phrase'],
['audience overlap','noun_phrase','受众重叠','audience duplication','Ads / Acquisition','paid acquisition','optimise targeting','The audience overlap between our two ad sets is over forty percent so we are wasting budget.','两个广告组之间的 audience overlap 超过百分之四十，所以我们在浪费预算。',3,['ads','optimisation'],'phrase'],
['retargeting pixel','noun_phrase','再营销像素','remarketing code','Ads / Acquisition','paid acquisition','track visitors','The retargeting pixel needs to fire on every product page not just the homepage.','retargeting pixel 需要在每个产品页触发，而不仅仅是首页。',2,['ads','technical'],'phrase'],
['ad engagement','noun_phrase','广告互动','ad interaction','Ads / Acquisition','paid acquisition','measure response','Ad engagement is up but purchases have not followed which suggests a landing page problem.','ad engagement 上升了但购买没有跟上来，说明是落地页的问题。',2,['ads','metrics'],'phrase'],
['negative feedback','noun_phrase','负面反馈','bad response','Ads / Acquisition','paid acquisition','monitor sentiment','The negative feedback score on this ad set is too high so we need to adjust the targeting.','这个广告组的 negative feedback 分数太高了，我们需要调整定向。',2,['ads','metrics'],'phrase'],
['cost per purchase','noun_phrase','每次购买成本','acquisition cost','Ads / Acquisition','paid acquisition','measure efficiency','The cost per purchase on Meta Ads dropped after we refined the lookalike audience.','我们在优化相似受众后 Meta Ads 上的 cost per purchase 下降了。',2,['ads','metrics'],'phrase'],
['ad schedule','noun_phrase','广告排期','ad timing','Ads / Acquisition','paid acquisition','control timing','The ad schedule only runs during business hours when our support team is online.','ad schedule 只在工作时间运行，因为那时我们的支持团队在线。',1,['ads','strategy'],'phrase'],
['dynamic product ad','noun_phrase','动态产品广告','personalised ad','Ads / Acquisition','paid acquisition','retarget with products','Dynamic product ads show people the exact item they viewed but did not buy.','dynamic product ad 向人们展示他们看过但没买的确切商品。',2,['ads','technical'],'phrase'],
['ad placement','noun_phrase','广告版位','where ad appears','Ads / Acquisition','paid acquisition','choose placement','The ad placement on Instagram stories has a higher CTR than feed placements.','Instagram stories 上的 ad placement 比 feed placement 有更高的 CTR。',2,['ads','strategy'],'phrase'],
['broad targeting','noun_phrase','广泛定向','wide audience','Ads / Acquisition','paid acquisition','reach more people','Broad targeting works better than narrow interest targeting for this product.','对这个产品来说 broad targeting 比 narrow interest targeting 效果更好。',2,['ads','strategy'],'phrase'],
['scaled campaign','noun_phrase','放量活动','budget-increased campaign','Ads / Acquisition','paid acquisition','increase budget','We duplicated the scaled campaign and added a new creative to fight fatigue.','我们复制了 scaled campaign 并添加了新 creative 来对抗疲劳。',2,['ads','strategy'],'phrase'],
['first-click attribution','noun_phrase','首次点击归因','credit first touch','Ads / Acquisition','paid acquisition','attribute conversions','First-click attribution overvalues awareness ads because the actual purchase often comes later.','first-click attribution 高估了 awareness ad 的价值，因为实际购买往往在之后发生。',4,['ads','analytics'],'phrase'],
['ad account audit','noun_phrase','广告账户审计','account review','Ads / Acquisition','paid acquisition','review spend','We do an ad account audit every month to spot wasted spend and test gaps.','我们每月做一次 ad account audit，以发现浪费的支出和测试盲点。',2,['ads','optimisation'],'phrase'],
['winning creative','noun_phrase','爆款素材','top-performing ad','Ads / Acquisition','paid acquisition','identify best','The winning creative has a hook in the first two seconds and shows the product immediately.','winning creative 在头两秒内有 hook 并立即展示产品。',2,['ads','content'],'phrase'],
['ad library','noun_phrase','广告库','competitor ad database','Ads / Acquisition','paid acquisition','research competitors','We check the ad library of our top three competitors every week for new angles.','我们每周检查前三名竞争对手的 ad library 以发现新角度。',1,['ads','research'],'phrase'],
['brand lift study','noun_phrase','品牌提升研究','brand awareness test','Ads / Acquisition','paid acquisition','measure brand impact','The brand lift study showed a fifteen percent increase in recall after the video campaign.','brand lift study 显示视频活动后品牌回忆度提高了百分之十五。',3,['ads','analytics'],'phrase'],
['dayparting','noun','分时投放','time-based delivery','Ads / Acquisition','paid acquisition','optimise timing','We use dayparting to increase the budget during evening hours when conversion is highest.','我们使用 dayparting 在转化率最高的晚间时段增加预算。',3,['ads','strategy'],'word'],
['ad fatigue score','noun_phrase','广告疲劳度','fatigue metric','Ads / Acquisition','paid acquisition','monitor performance','The ad fatigue score rose after the same creative ran for over three weeks.','相同的 creative 运行超过三周后 ad fatigue score 上升了。',2,['ads','metrics'],'phrase'],

// ===== EMAIL / CRM =====
['email automation','noun_phrase','邮件自动化','auto email','Email / CRM','email marketing','save time','Email automation handles the welcome flow abandoned cart and post-purchase follow-up.','email automation 处理欢迎流程、弃购流程和购后跟进。',2,['email','automation'],'phrase'],
['conversion email','noun_phrase','转化邮件','sales email','Email / CRM','email marketing','drive purchases','The conversion email is the one that actually asks for the sale with a clear call to action.','conversion email 是真正请求购买的邮件，带有明确的行动号召。',1,['email','strategy'],'phrase'],
['list growth','noun_phrase','列表增长','subscriber increase','Email / CRM','email marketing','grow audience','Our list growth slowed after we removed the pop-up from the homepage.','我们从首页移除弹窗后 list growth 放缓了。',1,['email','metrics'],'phrase'],
['spam complaint','noun_phrase','垃圾投诉','spam report','Email / CRM','email marketing','maintain reputation','A spam complaint rate above 0.1 percent can hurt your sender reputation badly.','超过百分之零点一的 spam complaint 率会严重损害你的发件人信誉。',3,['email','technical'],'phrase'],
['email deliverability','noun_phrase','邮件送达率','inbox rate','Email / CRM','email marketing','ensure delivery','Email deliverability dropped after we switched to a new sending domain without warming it up.','我们在没有预热新发送域名的情况下切换后 email deliverability 下降了。',3,['email','technical'],'phrase'],
['drip campaign','noun_phrase','滴灌式营销','timed email series','Email / CRM','email marketing','educate leads','The drip campaign sends one email per day for five days covering different product benefits.','drip campaign 每天发送一封邮件，连续五天，介绍不同的产品优势。',2,['email','strategy'],'phrase'],
['list cleaning','noun_phrase','列表清理','remove inactive','Email / CRM','email marketing','maintain deliverability','We do list cleaning every quarter to remove subscribers who have not opened in six months.','我们每季度做一次 list cleaning，删除六个月未打开邮件的订阅者。',2,['email','maintenance'],'phrase'],
['sender reputation','noun_phrase','发件人信誉','email trust score','Email / CRM','email marketing','ensure delivery','A poor sender reputation means your emails land in spam regardless of content quality.','不良的 sender reputation 意味着无论内容质量如何邮件都会被送入 spam。',3,['email','technical'],'phrase'],
['cart recovery email','noun_phrase','购物车挽回邮件','abandoned recovery mail','Email / CRM','email marketing','recover sales','The first cart recovery email goes out one hour after the cart is abandoned.','第一封 cart recovery email 在购物车被放弃一小时后发出。',2,['email','automation'],'phrase'],
['thank-you page','noun_phrase','感谢页面','post-purchase page','Email / CRM','email marketing','confirm purchase','The thank-you page is a great place to offer a one-time upsell or a referral ask.','thank-you page 是提供一次性追加销售或邀请推荐的好地方。',1,['email','conversion'],'phrase'],
['email sequence','noun_phrase','邮件序列','email chain','Email / CRM','email marketing','nurture leads','The email sequence starts with a welcome message then shares social proof then asks for the sale.','email sequence 从欢迎消息开始，然后分享社会证明，最后请求购买。',1,['email','strategy'],'phrase'],
['bounce rate','noun_phrase','退信率','email rejection rate','Email / CRM','email marketing','monitor deliverability','Our bounce rate spiked after we imported a list of old subscribers without cleaning first.','我们在没清洗旧订阅者列表就导入后 bounce rate 激增。',2,['email','metrics'],'phrase'],
['preview text','noun_phrase','预览文字','email snippet','Email / CRM','email marketing','increase opens','The preview text should complement the subject line not just repeat it.','preview text 应该补充标题而不是简单重复。',1,['email','content'],'phrase'],
['pop-up form','noun_phrase','弹窗表单','popup signup','Email / CRM','email marketing','collect emails','The pop-up form triggers after the visitor has been on the page for eight seconds.','pop-up form 在访客浏览页面八秒后触发。',1,['email','growth'],'phrase'],
['welcome offer','noun_phrase','欢迎优惠','first-purchase discount','Email / CRM','email marketing','convert new subscribers','The welcome offer gives ten percent off the first order for new email subscribers.','welcome offer 为新的邮件订阅者提供首次订单九折优惠。',1,['email','conversion'],'phrase'],
['re-engagement campaign','noun_phrase','再激活活动','win-back campaign','Email / CRM','email marketing','reactivate churned','The re-engagement campaign targets customers who have not purchased in over ninety days.','re-engagement campaign 针对超过九十天未购买的客户。',2,['email','retention'],'phrase'],
['segmentation rule','noun_phrase','分群规则','segment rule','Email / CRM','email marketing','target messaging','We created a segmentation rule that groups customers by purchase frequency and average order value.','我们创建了一条 segmentation rule，按购买频率和平均订单金额将客户分群。',2,['email','strategy'],'phrase'],
['email template','noun_phrase','邮件模板','email design','Email / CRM','email marketing','maintain consistency','All our email templates are mobile-responsive and load under two seconds.','我们所有的 email template 都适配移动端且加载时间不超过两秒。',1,['email','design'],'phrase'],

// ===== CUSTOMER SUPPORT =====
['customer feedback','noun_phrase','客户反馈','user opinions','Customer Support','customer support','gather insights','Customer feedback from the post-purchase survey showed the packaging could be improved.','购后调查中的 customer feedback 显示包装可以改进。',1,['support','feedback'],'phrase'],
['ticket volume','noun_phrase','工单量','support request count','Customer Support','customer support','measure workload','Ticket volume tripled during the campaign launch because backers had many urgent questions.','活动上线期间 ticket volume 翻了三倍，因为支持者有很多紧急问题。',1,['support','metrics'],'phrase'],
['priority support','noun_phrase','优先支持','faster help','Customer Support','customer support','serve VIP customers','We offer priority support to customers who have spent over five hundred dollars.','我们为消费超过五百美元的客户提供 priority support。',1,['support','service'],'phrase'],
['knowledge base','noun_phrase','知识库','article collection','Customer Support','customer support','enable self-help','The knowledge base now has over a hundred articles covering the most common issues.','knowledge base 现在有超过一百篇文章，涵盖了最常见的问题。',1,['support','tools'],'phrase'],
['return label','noun_phrase','退货标签','return sticker','Customer Support','customer support','simplify returns','We include a prepaid return label in every package for easy returns.','我们在每个包裹中附上 prepaid return label，方便退货。',1,['support','logistics'],'phrase'],
['refund policy','noun_phrase','退款政策','money-back rules','Customer Support','customer support','set expectations','Our refund policy allows returns within thirty days as long as the product is unused.','我们的 refund policy 允许三十天内退货，只要产品未使用。',1,['support','policy'],'phrase'],
['live chat','noun_phrase','在线聊天','real-time support','Customer Support','customer support','provide instant help','We added live chat to the website and the average response time dropped significantly.','我们在网站上添加了 live chat，平均响应时间大幅缩短。',1,['support','tools'],'phrase'],
['help centre','noun_phrase','帮助中心','support portal','Customer Support','customer support','enable self-service','The help centre has articles for the most common questions which reduces ticket volume.','help centre 有针对最常见问题的文章，这减少了工单数量。',1,['support','tools'],'phrase'],
['order confirmation','noun_phrase','订单确认','purchase verification','Customer Support','customer support','confirm transactions','The order confirmation email goes out immediately after payment is processed.','order confirmation 邮件在付款处理后立即发出。',1,['support','communication'],'phrase'],
['support team','noun_phrase','客服团队','support staff','Customer Support','customer support','staff appropriately','Our support team works across three time zones to provide nearly 24-hour coverage.','我们的 support team 跨越三个时区工作，提供近乎全天候的服务。',1,['support','team'],'phrase'],
['satisfaction survey','noun_phrase','满意度调查','CSAT survey','Customer Support','customer support','measure quality','We send a satisfaction survey after every ticket is resolved to track our support quality.','我们在每个工单解决后发送 satisfaction survey 来追踪支持质量。',1,['support','metrics'],'phrase'],
['return window','noun_phrase','退货期限','how long to return','Customer Support','customer support','set policy','The return window is thirty days from the delivery date not the order date.','return window 是从送达之日起三十天，不是下单日期。',2,['support','policy'],'phrase'],
['defective claim','noun_phrase','瑕疵索赔','quality complaint','Customer Support','customer support','process claims','We processed the defective claim within 24 hours and shipped a replacement immediately.','我们在 24 小时内处理了 defective claim 并立即发出了替换品。',2,['support','quality'],'phrase'],
['damage report','noun_phrase','损坏报告','damage documentation','Customer Support','customer support','document issues','The customer sent a damage report with photos showing the crushed corner of the box.','客户发来了一份 damage report，附有显示箱子一角被压碎的照片。',1,['support','logistics'],'phrase'],
['customer retention','noun_phrase','客户留存','keeping customers','Customer Support','customer support','build loyalty','Good customer support drives customer retention more than any discount ever could.','好的客户支持比任何折扣都更能推动 customer retention。',2,['support','strategy'],'phrase'],
['CSAT score','noun_phrase','客户满意度分','customer satisfaction','Customer Support','customer support','measure satisfaction','Our CSAT score averaged 4.7 out of 5 this month which is our best ever.','这个月我们的 CSAT score 平均达到 4.7 分（满分 5 分），是有史以来最好的一次。',2,['support','metrics'],'phrase'],

// ===== FULFILLMENT / LOGISTICS =====
['warehouse capacity','noun_phrase','仓库容量','storage space','Fulfillment / Logistics','logistics','plan storage','Warehouse capacity is nearly full so we need to ship the current batch quickly.','warehouse capacity 快满了，所以我们需要尽快发出现有批次。',2,['logistics','operations'],'phrase'],
['parcel tracking','noun_phrase','包裹追踪','package tracking','Fulfillment / Logistics','logistics','keep customers informed','Parcel tracking updates are sent automatically at every major delivery checkpoint.','parcel tracking 更新会在派送旅程的每个主要节点自动发送。',1,['logistics','communication'],'phrase'],
['stockout','noun','断货','out of stock','Fulfillment / Logistics','logistics','avoid shortages','A stockout of the best-selling variant during a promotion is a nightmare for us.','促销期间最畅销变体的 stockout 对我们来说是一场噩梦。',2,['logistics','operations'],'word'],
['customs clearance','noun_phrase','清关','border processing','Fulfillment / Logistics','logistics','clear international','Customs clearance took nearly two weeks because the paperwork was incomplete.','因为文件不完整 customs clearance 花了将近两周。',3,['logistics','international'],'phrase'],
['pick and pack','noun_phrase','拣货打包','select and box','Fulfillment / Logistics','logistics','process orders','The 3PL charges per pick and pack which adds about two dollars to each order.','3PL 按 pick and pack 收费，每个订单增加约两美元。',2,['logistics','operations'],'phrase'],
['shipping zone','noun_phrase','运输区域','delivery area','Fulfillment / Logistics','logistics','calculate cost','Our shipping zones are based on distance from the warehouse with Zone 8 costing the most.','我们的 shipping zone 基于距离仓库的远近，Zone 8 最贵。',2,['logistics','operations'],'phrase'],
['dimensional weight','noun_phrase','体积重量','size-based weight','Fulfillment / Logistics','logistics','calculate cost','The carrier charges by dimensional weight so a large light box costs more than a small heavy one.','承运商按 dimensional weight 收费，所以大而轻的箱子比小而重的更贵。',3,['logistics','operations'],'phrase'],
['proof of delivery','noun_phrase','签收证明','delivery confirmation','Fulfillment / Logistics','logistics','verify receipt','The carrier provided proof of delivery with a photo of the package at the door.','承运商提供了 proof of delivery，附有包裹在门口的照片。',2,['logistics','operations'],'phrase'],
['freight charge','noun_phrase','运费','shipping fee','Fulfillment / Logistics','logistics','manage costs','The freight charge for air shipping is nearly triple the cost of sea freight.','空运的 freight charge 几乎是海运成本的三倍。',2,['logistics','finance'],'phrase'],
['order backlog','noun_phrase','积压订单','unfulfilled orders','Fulfillment / Logistics','logistics','manage capacity','The order backlog grew during the promotion because the 3PL could not keep up.','订单积压在促销期间增加了，因为 3PL 跟不上节奏。',2,['logistics','operations'],'phrase'],
['shipping cost','noun_phrase','运费','delivery cost','Fulfillment / Logistics','logistics','manage expenses','The shipping cost dropped after we negotiated a volume discount with the carrier.','我们与承运商协商量大批发折扣后 shipping cost 降低了。',1,['logistics','finance'],'phrase'],
['delivery window','noun_phrase','派送时间窗','estimated delivery time','Fulfillment / Logistics','logistics','set expectations','The delivery window is three to seven business days depending on the shipping zone.','delivery window 为三到七个工作日，取决于 shipping zone。',1,['logistics','communication'],'phrase'],
['pallet','noun','托盘','wooden pallet','Fulfillment / Logistics','logistics','organise shipments','Each pallet holds forty cartons and weighs about three hundred kilograms.','每个 pallet 装载四十个纸箱，重约三百公斤。',2,['logistics','operations'],'word'],
['port of entry','noun_phrase','入境港','arrival port','Fulfillment / Logistics','logistics','manage international','The port of entry for this shipment is Los Angeles and customs clearance will happen there.','这批货物的 port of entry 是洛杉矶，清关将在那里进行。',3,['logistics','international'],'phrase'],
['container','noun','集装箱','shipping container','Fulfillment / Logistics','logistics','manage bulk','A full container holds about three thousand units and costs roughly four thousand dollars to ship.','一个完整的 container 装载约三千个单位，运费大约四千美元。',2,['logistics','operations'],'word'],
['air freight','noun_phrase','空运','air cargo','Fulfillment / Logistics','logistics','expedite delivery','Air freight takes about a week but costs five times more than sea freight.','air freight 大约需要一周但成本是海运的五倍。',2,['logistics','operations'],'phrase'],
['sea freight','noun_phrase','海运','ocean cargo','Fulfillment / Logistics','logistics','reduce cost','Sea freight is slower but makes economic sense for orders over a hundred units.','sea freight 较慢但对于超过一百个单位的订单来说在经济上是合理的。',1,['logistics','operations'],'phrase'],
['dispatch date','noun_phrase','发货日期','ship date','Fulfillment / Logistics','logistics','track timeline','The dispatch date is three days after the order is placed if the item is in stock.','如果有库存，dispatch date 是下单后三天。',1,['logistics','operations'],'phrase'],
['courier pickup','noun_phrase','快递取件','carrier collection','Fulfillment / Logistics','logistics','ship packages','The courier pickup is scheduled for 2pm every weekday at our warehouse dock.','courier pickup 安排在每个工作日下午两点在我们的仓库装卸口。',1,['logistics','operations'],'phrase'],
['freight insurance','noun_phrase','货运保险','cargo insurance','Fulfillment / Logistics','logistics','protect shipments','We added freight insurance after a previous shipment arrived with water damage.','我们在上一批货物到达时有水渍损坏后添加了 freight insurance。',2,['logistics','finance'],'phrase'],
['returned shipment','noun_phrase','退回的货物','sent-back order','Fulfillment / Logistics','logistics','process returns','The returned shipment goes to a separate inspection area before re-entering inventory.','returned shipment 在重新进入库存之前先进入单独的检查区。',1,['logistics','operations'],'phrase'],
['cross-docking','noun','越库配送','direct transfer','Fulfillment / Logistics','logistics','speed up flow','We use cross-docking to move goods directly from inbound to outbound without storage.','我们使用 cross-docking 将货物直接从入站转到出站而不经存储。',4,['logistics','operations'],'word'],

// ===== SUPPLIER / FOREIGN TRADE =====
['supplier audit','noun_phrase','供应商审计','factory check','Supplier / Foreign Trade','supplier communication','verify quality','We conduct a supplier audit twice a year to ensure working conditions and quality standards.','我们每年进行两次 supplier audit 以确保工作条件和质量标准。',3,['supplier','quality'],'phrase'],
['production sample','noun_phrase','生产样品','pre-production sample','Supplier / Foreign Trade','supplier communication','approve quality','The production sample must be signed off before mass production can begin.','production sample 必须在量产开始前签字确认。',2,['supplier','quality'],'phrase'],
['shipping marks','noun_phrase','唛头','box labels','Supplier / Foreign Trade','supplier communication','label correctly','The shipping marks on each carton must include the purchase order number and port.','每个纸箱上的 shipping marks 必须包含采购订单号和目的港。',3,['supplier','documentation'],'phrase'],
['incoterms','noun','国际贸易术语','trade terms','Supplier / Foreign Trade','supplier communication','agree delivery terms','We need to agree on the incoterms before signing the purchase order.','我们需要在签署采购订单之前就 incoterms 达成一致。',4,['supplier','international'],'word'],
['purchase order','noun_phrase','采购订单','buy order','Supplier / Foreign Trade','supplier communication','formalise order','The purchase order must be signed by both parties before production can begin.','purchase order 必须在生产开始前由双方签署。',2,['supplier','documentation'],'phrase'],
['payment term','noun_phrase','付款条件','pay condition','Supplier / Foreign Trade','supplier communication','agree payment','The payment term is net thirty days from the date of the commercial invoice.','payment term 是从商业发票日期起 net 30 天。',2,['supplier','finance'],'phrase'],
['production schedule','noun_phrase','生产排期','manufacturing timeline','Supplier / Foreign Trade','supplier communication','track progress','The production schedule shows the first batch completing in early November.','production schedule 显示第一批在十一月初完成。',2,['supplier','production'],'phrase'],
['factory visit','noun_phrase','工厂访问','on-site visit','Supplier / Foreign Trade','supplier communication','verify production','We did a factory visit before placing the first order and the facility looked well-organised.','我们在下第一笔订单前做了一次 factory visit，工厂看起来组织良好。',1,['supplier','quality'],'phrase'],
['material cost','noun_phrase','材料成本','raw material price','Supplier / Foreign Trade','supplier communication','calculate pricing','The material cost went up by ten percent so the supplier is asking for a price adjustment.','material cost 上涨了百分之十，所以供应商要求调整价格。',1,['supplier','finance'],'phrase'],
['unit price','noun_phrase','单价','per-unit cost','Supplier / Foreign Trade','supplier communication','negotiate pricing','The unit price drops significantly if we order more than five thousand pieces.','如果我们订购超过五千件 unit price 会显著下降。',1,['supplier','negotiation'],'phrase'],
['factory capacity','noun_phrase','工厂产能','production capacity','Supplier / Foreign Trade','supplier communication','assess capability','Factory capacity is tight during the holiday season so lead times get longer.','假日季期间 factory capacity 紧张，所以交货周期会变长。',2,['supplier','planning'],'phrase'],
['sub-supplier','noun','次级供应商','tier-two supplier','Supplier / Foreign Trade','supplier communication','trace supply chain','The sub-supplier for the battery cells had a quality issue that delayed the whole order.','电池单元的 sub-supplier 出现质量问题，延误了整个订单。',3,['supplier','sourcing'],'word'],
['material certificate','noun_phrase','材料证明','material compliance doc','Supplier / Foreign Trade','supplier communication','comply with regulations','We need a material certificate showing the fabric meets EU safety standards.','我们需要一份 material certificate 证明面料符合欧盟安全标准。',3,['supplier','documentation'],'phrase'],
['shipping window','noun_phrase','发货窗口','when goods ship','Supplier / Foreign Trade','supplier communication','schedule shipment','The shipping window is between the 15th and 20th of the month depending on factory output.','shipping window 在每月 15 日至 20 日之间，取决于工厂产量。',2,['supplier','planning'],'phrase'],
['tolerance limit','noun_phrase','公差极限','acceptable deviation','Supplier / Foreign Trade','supplier communication','define quality','The tolerance limit for the plastic casing is plus or minus 0.2 millimetres.','塑料外壳的 tolerance limit 是正负 0.2 毫米。',3,['supplier','quality'],'phrase'],
['mould fee','noun_phrase','模具费','tooling cost','Supplier / Foreign Trade','supplier communication','agree tooling cost','The mould fee is a one-time charge and the mould belongs to us after payment.','mould fee 是一次性费用，付款后模具归我们所有。',2,['supplier','finance'],'phrase'],
['contract manufacturer','noun_phrase','合同制造商','contracted factory','Supplier / Foreign Trade','supplier communication','select partner','We work with a contract manufacturer that specialises in small electronics.','我们与一家专门从事小型电子产品的 contract manufacturer 合作。',2,['supplier','sourcing'],'phrase'],
['raw material','noun_phrase','原材料','unprocessed material','Supplier / Foreign Trade','supplier communication','source materials','The raw material price for aluminium has been fluctuating a lot this quarter.','本季度铝的 raw material 价格一直波动很大。',1,['supplier','sourcing'],'phrase'],
['spec sheet','noun_phrase','规格表','specification document','Supplier / Foreign Trade','supplier communication','communicate requirements','The spec sheet lists every dimension material and finish for each component.','spec sheet 列出了每个组件的所有尺寸、材料和表面处理。',2,['supplier','documentation'],'phrase'],
['price quote','noun_phrase','报价单','price offer document','Supplier / Foreign Trade','supplier communication','compare pricing','We got a price quote from three factories and the middle one offered the best terms.','我们从三家工厂拿到了 price quote，中间那家提供的条件最好。',1,['supplier','negotiation'],'phrase'],
['manufacturing defect','noun_phrase','制造缺陷','production flaw','Supplier / Foreign Trade','supplier communication','identify quality issues','We found a manufacturing defect in about three percent of the units from the last batch.','我们在上一批大约百分之三的产品中发现了 manufacturing defect。',2,['supplier','quality'],'phrase'],
['batch inspection','noun_phrase','批次检查','per-batch quality check','Supplier / Foreign Trade','supplier communication','control quality','A batch inspection is done before each shipment leaves the factory.','每批货物离开工厂前都会进行 batch inspection。',2,['supplier','quality'],'phrase'],
['import licence','noun_phrase','进口许可证','import permit','Supplier / Foreign Trade','supplier communication','comply with regulations','We need an import licence for the electronic components before the shipment arrives.','在货物到达前我们需要为电子组件办理 import licence。',3,['supplier','international'],'phrase'],
['tariff code','noun_phrase','关税编码','customs tariff code','Supplier / Foreign Trade','supplier communication','classify correctly','The tariff code determines the duty rate so getting it right saves a lot of money.','tariff code 决定了关税率，所以准确分类可以节省大量费用。',3,['supplier','international'],'phrase'],
['shipment delay','noun_phrase','发货延迟','late dispatch','Supplier / Foreign Trade','supplier communication','manage problems','The shipment delay was caused by a shortage of a key electronic component.','shipment delay 是由于一个关键电子元件的短缺造成的。',1,['supplier','logistics'],'phrase'],

// ===== VERBS (DTC & Foreign Trade) =====
['negotiate','verb','谈判','talk terms','Supplier / Foreign Trade','supplier communication','agree terms','We negotiated the unit price down by fifteen percent by committing to a larger volume.','我们通过承诺更大的量将单价 negotiate 降低了百分之十五。',2,['supplier','verb'],'word'],
['renegotiate','verb','重新谈判','talk again','Supplier / Foreign Trade','supplier communication','adjust terms','We had to renegotiate the contract after the material cost spiked unexpectedly.','材料成本意外上涨后我们不得不 renegotiate 合同。',3,['supplier','verb'],'word'],
['upsell','verb','追加销售','suggest upgrade','Shopify / DTC Store','dtc store operation','increase order value','Can we upsell the extended warranty on the checkout page without slowing it down.','我们能在结账页面上在不拖慢速度的情况下 upsell 延长保修吗。',2,['dtc','verb'],'word'],
['cross-sell','verb','交叉销售','suggest related','Shopify / DTC Store','dtc store operation','increase breadth','The post-purchase email cross-sells accessories that match the product they just bought.','购后邮件 cross-sell 与他们刚买的产品相匹配的配件。',2,['dtc','verb'],'word'],
['restock','verb','补货','refill inventory','Fulfillment / Logistics','logistics','maintain stock','We need to restock the black variant because it sold out during the flash sale.','我们需要 restock 黑色款因为它在闪购期间卖光了。',1,['logistics','verb'],'word'],
['pre-order','verb','预售','sell before ready','Crowdfunding Campaign','pre-launch','gauge demand','We opened pre-orders to gauge demand before committing to a full production run.','在承诺全面生产之前我们开放了 pre-order 来测试需求。',1,['crowdfunding','verb'],'word'],
['remarket','verb','再营销','target again','Ads / Acquisition','paid acquisition','re-engage visitors','We remarket to people who viewed the product page but did not add to cart.','我们向浏览了产品页但未加入购物车的人 remarket。',2,['ads','verb'],'word'],
['onboard','verb','引导上手','bring onto platform','Email / CRM','email marketing','welcome users','We onboard new subscribers with a five-email welcome sequence over two weeks.','我们在两周内用五封欢迎邮件来 onboard 新订阅者。',2,['email','verb'],'word'],
['fulfil','verb','履行','complete order','Fulfillment / Logistics','logistics','process orders','The 3PL fulfils orders within 24 hours of receiving them on business days.','3PL 在工作日收到订单后 24 小时内 fulfil 订单。',2,['logistics','verb'],'word'],
['source','verb','采购','find and buy','Supplier / Foreign Trade','supplier communication','find suppliers','We source the battery cells from a supplier in Shenzhen that we have worked with for years.','我们从深圳一家合作多年的供应商那里 source 电池单元。',2,['supplier','verb'],'word'],
['dispute','verb','争议','challenge','Customer Support','customer support','resolve payment issues','The customer disputed the charge with their bank because they did not recognise the transaction.','客户因为不认得这笔交易而与银行 dispute 了这项收费。',2,['support','verb'],'word'],
['restock alert','noun','补货提醒','back-in-stock notice','Shopify / DTC Store','dtc store operation','capture demand','We set up a restock alert for the sold-out colour and collected over 200 signups.','我们为售罄的颜色设置了 restock alert，收集了超过 200 个注册。',1,['dtc','tools'],'word'],
['inspect','verb','检查','look carefully','Supplier / Foreign Trade','supplier communication','check quality','We inspect every unit from the first production batch before giving the green light.','在给绿灯之前我们 inspect 第一批量产的每个产品。',1,['supplier','verb'],'word'],
['expedite','verb','加快','speed up','Fulfillment / Logistics','logistics','speed up','We paid extra to expedite the shipment because the backers were getting impatient.','我们额外付费来 expedite 发货因为支持者越来越不耐烦了。',3,['logistics','verb'],'word'],
['refund','verb','退款','give money back','Customer Support','customer support','resolve payment','We refunded the customer within two days after they returned the defective unit.','我们在客户退回瑕疵品后的两天内 refund 了他们。',1,['support','verb'],'word'],

// ===== PHRASAL VERBS =====
['roll out','phrasal_verb','推出','release','Crowdfunding Campaign','campaign live','launch','We plan to roll out the next reward tier after the stretch goal is unlocked.','我们计划在 stretch goal 解锁后 roll out 下一个回报档位。',2,['crowdfunding','phrasal_verb'],'phrase'],
['sell out','phrasal_verb','售罄','run out','Shopify / DTC Store','dtc store operation','track inventory','The black variant sold out within three days and the next batch is still a month away.','黑色款在三天内 sell out 了下一批还要一个月。',1,['dtc','phrasal_verb'],'phrase'],
['follow up','phrasal_verb','跟进','check back','Email / CRM','email marketing','nurture leads','We follow up with every abandoned cart within one hour with a reminder email.','我们在一小时内用提醒邮件 follow up 每个弃购车。',1,['email','phrasal_verb'],'phrase'],
['set up','phrasal_verb','建立','create','Shopify / DTC Store','dtc store operation','build','We set up the Shopify store in about two weeks using a premium theme.','我们用高级主题在大约两周内 set up 了 Shopify 店铺。',1,['dtc','phrasal_verb'],'phrase'],
['ramp up','phrasal_verb','逐步增加','increase gradually','Ads / Acquisition','paid acquisition','scale budget','We ramped up the ad spend slowly over two weeks to avoid resetting the learning phase.','我们在两周内缓慢 ramp up 广告支出以避免重置学习阶段。',2,['ads','phrasal_verb'],'phrase'],
['phase out','phrasal_verb','逐步淘汰','gradually remove','Supplier / Foreign Trade','supplier communication','change supplier','We are phasing out the old packaging design and switching to the eco-friendly version.','我们正在 phase out 旧包装设计转向环保版本。',3,['supplier','phrasal_verb'],'phrase'],
['break even','phrasal_verb','收支平衡','cover costs','Ads / Acquisition','paid acquisition','measure profitability','The campaign broke even on day six and has been profitable every day since.','活动在第六天 break even 此后每天都盈利。',2,['ads','phrasal_verb'],'phrase'],
['top up','phrasal_verb','充值','add more','Fulfillment / Logistics','logistics','manage stock','We topped up the inventory in the US warehouse before the holiday rush.','我们在假日高峰前给美国仓库 top up 了库存。',1,['logistics','phrasal_verb'],'phrase'],
['ship out','phrasal_verb','发出','send','Fulfillment / Logistics','logistics','dispatch','We ship out all orders placed before 2pm on the same business day.','我们在同一工作日 ship out 所有下午两点前下的订单。',1,['logistics','phrasal_verb'],'phrase'],
['back out','phrasal_verb','退出','withdraw','Crowdfunding Campaign','campaign live','cancel support','About two percent of backers back out before the campaign ends and their cards are charged.','大约百分之二的 backer 在活动结束扣款前 back out。',2,['crowdfunding','phrasal_verb'],'phrase'],
['mark down','phrasal_verb','降价','reduce price','Shopify / DTC Store','dtc store operation','clear inventory','We marked down the older version when the new model launched to clear the remaining stock.','新版本上线时我们 mark down 了旧版以清仓。',1,['dtc','phrasal_verb'],'phrase'],
['opt in','phrasal_verb','选择加入','agree to receive','Email / CRM','email marketing','grow list','Customers must opt in before we can send them marketing emails under GDPR rules.','根据 GDPR 规定客户必须 opt in 我们才能发送营销邮件。',2,['email','phrasal_verb'],'phrase'],
['flag up','phrasal_verb','标记','raise attention','Customer Support','customer support','identify issues','The quality team flagged up a potential defect pattern in the latest batch.','质量团队 flag up 了最近批次中的一个潜在缺陷模式。',2,['support','phrasal_verb'],'phrase'],
['chase up','phrasal_verb','催促','follow urgently','Supplier / Foreign Trade','supplier communication','push for update','We chased up the supplier three times this week because the shipment is already late.','我们本周 chase up 了供应商三次因为发货已经延迟了。',1,['supplier','phrasal_verb'],'phrase'],
['strike a deal','phrasal_verb','达成协议','agree terms','Supplier / Foreign Trade','supplier communication','finalise','We struck a deal with the factory that includes a price drop after the first 5000 units.','我们与工厂 strike a deal 包括前 5000 个单位后的降价。',2,['supplier','phrasal_verb'],'phrase'],

// ===== ADJECTIVES =====
['brand-safe','adjective','品牌安全的','safe for brand image','Ads / Acquisition','paid acquisition','protect brand','We block certain placements to keep our ads brand-safe and avoid controversial content.','我们屏蔽某些版位以保持广告 brand-safe 避免有争议的内容。',2,['ads','adjective'],'word'],
['conversion-ready','adjective','可转化的','ready to convert','Shopify / DTC Store','dtc store operation','optimise','The product page is not conversion-ready because it lacks reviews and a clear call to action.','product page 还不是 conversion-ready 因为它缺少评价和明确的行动号召。',2,['dtc','adjective'],'word'],
['backer-funded','adjective','支持者出资的','funded by backers','Crowdfunding Campaign','campaign live','describe status','This is a backer-funded project so we are accountable to the community not investors.','这是一个 backer-funded 项目所以我们对社区负责而不是投资者。',1,['crowdfunding','adjective'],'word'],
['costly','adjective','昂贵的','expensive','Ads / Acquisition','paid acquisition','assess','The most costly mistake in advertising is not testing enough creatives.','广告中最 costly 的错误就是测试的素材不够多。',1,['ads','adjective'],'word'],
['time-sensitive','adjective','时间敏感的','urgent','Crowdfunding Campaign','campaign live','create urgency','The early bird offer is time-sensitive and expires in 48 hours.','early bird 优惠是 time-sensitive 的，将在 48 小时后到期。',1,['crowdfunding','adjective'],'word'],
['margin-friendly','adjective','有利可图的','profitable','Shopify / DTC Store','dtc store operation','assess','The bundle is margin-friendly because the accessory has a higher markup than the main unit.','这个 bundle 是 margin-friendly 的因为配件的加价率比主产品高。',2,['dtc','adjective'],'word'],
['shippable','adjective','可发货的','ready to ship','Fulfillment / Logistics','logistics','assess readiness','The product is shippable once it passes the final quality inspection and is packed.','产品一旦通过最终质检并包装好就是 shippable 的了。',1,['logistics','adjective'],'word'],
['customer-centric','adjective','以客户为中心的','customer-focused','Customer Support','customer support','define approach','Our customer-centric approach means we prioritise user experience over cost-cutting.','我们 customer-centric 的方法意味着用户体验优先于削减成本。',2,['support','adjective'],'word'],
['in-stock','adjective','有现货的','available','Fulfillment / Logistics','logistics','check availability','Only the blue variant is in-stock right now so we need to update the product page.','目前只有蓝色款是 in-stock 的所以我们需要更新产品页面。',1,['logistics','adjective'],'word'],
['out-of-stock','adjective','缺货的','unavailable','Fulfillment / Logistics','logistics','manage expectations','The best-selling colour is out-of-stock until the next production run finishes.','最畅销的颜色是 out-of-stock 的直到下一批量产完成。',1,['logistics','adjective'],'word'],
['duty-free','adjective','免税的','no tax','Supplier / Foreign Trade','supplier communication','clarify terms','Shipments under 800 dollars to the US are duty-free under the de minimis rule.','根据最低限额规则八百美元以下的运往美国的货物是 duty-free 的。',3,['supplier','adjective'],'word'],
['customer-ready','adjective','客户就绪的','ready for users','Customer Support','customer support','prepare launch','The help centre is customer-ready with over fifty articles covering the most common issues.','help centre 是 customer-ready 的有超过五十篇覆盖最常见问题的文章。',1,['support','adjective'],'word'],
['refundable','adjective','可退款的','can be refunded','Customer Support','customer support','set policy','The deposit is refundable within fourteen days if the customer changes their mind.','如果客户改变主意 deposit 在十四天内是 refundable 的。',1,['support','adjective'],'word'],
['pre-launch','adjective','预发布阶段的','before launch','Crowdfunding Campaign','pre-launch','describe phase','Our pre-launch email list has over five thousand subscribers ready for day one.','我们的 pre-launch 邮件列表有超过五千订阅者准备好迎接第一天。',1,['crowdfunding','adjective'],'word'],

// ===== COLLOCATIONS =====
['launch a campaign','collocation','发起活动','start campaign','Crowdfunding Campaign','pre-launch','execute','We will launch a campaign on Kickstarter in early September after the pre-launch list reaches 5000.','我们在 pre-launch 列表达到 5000 人后将于九月初在 Kickstarter launch a campaign。',2,['crowdfunding','collocation'],'phrase'],
['hit the funding goal','collocation','达成筹款目标','reach target','Crowdfunding Campaign','campaign live','achieve','We hit the funding goal in under six hours which was completely unexpected.','我们在不到六小时内 hit the funding goal 完全出乎意料。',1,['crowdfunding','collocation'],'phrase'],
['convert visitors','collocation','转化访客','turn visitors to buyers','Shopify / DTC Store','dtc store operation','increase sales','Better product images helped us convert visitors at a much higher rate.','更好的产品图片帮助我们以更高的比率 convert visitors。',1,['dtc','collocation'],'phrase'],
['drive traffic','collocation','引流','bring visitors','Ads / Acquisition','paid acquisition','acquire','We drive traffic from Meta Ads to a dedicated landing page not the homepage.','我们从 Meta Ads drive traffic 到一个专门的落地页面而不是首页。',1,['ads','collocation'],'phrase'],
['process a refund','collocation','处理退款','handle refund','Customer Support','customer support','resolve','We process a refund within 48 hours of receiving the returned item at the warehouse.','我们在仓库收到退回商品后 48 小时内 process a refund。',1,['support','collocation'],'phrase'],
['reduce churn','collocation','降低流失','keep subscribers','Email / CRM','email marketing','retain','The win-back flow helped reduce churn among customers who had not purchased in three months.','win-back flow 帮助 reduce churn 在三个月未购买的客户中。',2,['email','collocation'],'phrase'],
['clear customs','collocation','通关','pass border check','Fulfillment / Logistics','logistics','pass','The shipment was stuck for a week because the paperwork did not match and it could not clear customs.','因为文件不匹配货物被卡了一周无法 clear customs。',2,['logistics','collocation'],'phrase'],
['place an order','collocation','下单','submit order','Supplier / Foreign Trade','supplier communication','purchase','We placed an order for three thousand units with a four-week lead time.','我们 place an order 三千个单位交货周期四周。',1,['supplier','collocation'],'phrase'],
['build a list','collocation','建邮件列表','grow email list','Email / CRM','email marketing','grow','We built a list of over ten thousand subscribers before the product even launched.','我们在产品上线前 build a list 超过一万订阅者。',1,['email','collocation'],'phrase'],
['test a creative','collocation','测试素材','try an ad','Ads / Acquisition','paid acquisition','optimise','We test a creative every week with a small budget before scaling the winner.','我们每周用少量预算 test a creative 然后放量到胜出的那个。',1,['ads','collocation'],'phrase'],
['fulfil an order','collocation','完成订单','complete order','Fulfillment / Logistics','logistics','process','The 3PL can fulfil an order within 24 hours on business days.','3PL 可以在工作日 24 小时内 fulfil an order。',1,['logistics','collocation'],'phrase'],
['respond to a ticket','collocation','回复工单','answer request','Customer Support','customer support','resolve','We respond to a ticket within four hours during business hours.','我们在工作时间内四小时内 respond to a ticket。',1,['support','collocation'],'phrase'],
['segment the audience','collocation','分群受众','group audience','Email / CRM','email marketing','target','We segmented the audience by purchase history and sent each group a different offer.','我们按购买历史 segment the audience 并给每组发送了不同的优惠。',2,['email','collocation'],'phrase'],
['optimise the funnel','collocation','优化漏斗','improve flow','Shopify / DTC Store','dtc store operation','improve','We optimised the funnel by reducing the number of checkout steps from four to two.','我们通过将结账步骤从四步减少到两步来 optimise the funnel。',2,['dtc','collocation'],'phrase'],
['negotiate the price','collocation','谈判价格','talk price','Supplier / Foreign Trade','supplier communication','bargain','We negotiated the price down by ordering a larger quantity and paying earlier.','我们通过订购更大量和提前付款来 negotiate the price。',1,['supplier','collocation'],'phrase'],
['track the shipment','collocation','追踪货物','follow shipment','Fulfillment / Logistics','logistics','monitor','Customers can track the shipment on the carrier website with the number we email them.','客户可以用我们通过邮件发送的号码在承运商网站上 track the shipment。',1,['logistics','collocation'],'phrase'],
['scale the campaign','collocation','放量活动','increase budget','Ads / Acquisition','paid acquisition','grow','We scaled the campaign gradually after the pixel had enough data to optimise.','我们在 pixel 有足够数据优化后逐步 scale the campaign。',2,['ads','collocation'],'phrase'],
['manage expectations','collocation','管理预期','set realistic view','Backer Communication','post-campaign fulfillment','communicate','We need to manage expectations about the delivery timeline because delays are very common.','我们需要 manage expectations 关于交付时间线因为延迟非常常见。',2,['communication','collocation'],'phrase'],
['handle a chargeback','collocation','处理拒付','deal with dispute','Customer Support','customer support','resolve','We handle a chargeback by providing evidence that the customer received and signed for the package.','我们通过提供客户收到并签收包裹的证据来 handle a chargeback。',3,['support','collocation'],'phrase'],
['approve a sample','collocation','批准样品','ok the sample','Supplier / Foreign Trade','supplier communication','verify','We approved the sample after the third revision when the stitching was finally even.','在第三次修改后针脚终于均匀了我们 approve the sample。',1,['supplier','collocation'],'phrase'],

// ===== SENTENCE PATTERNS =====
['The tracking number has not updated.','sentence_pattern','追踪号没更新','tracking issue','Customer Support','customer support','report','The tracking number has not updated for five days and the customer is worried the package is lost.','tracking number 已经五天没有更新了，客户担心包裹丢了。',1,['support','sentence_pattern'],'sentence_pattern'],
['The shipment is stuck at customs.','sentence_pattern','货物卡在海关','customs delay','Fulfillment / Logistics','logistics','report','The shipment is stuck at customs because the commercial invoice had a wrong HS code.','货物卡在了海关因为商业发票上的 HS code 有误。',2,['logistics','sentence_pattern'],'sentence_pattern'],
['Can we offer a partial refund?','sentence_pattern','能给部分退款吗？','refund proposal','Customer Support','customer support','propose','Can we offer a partial refund to this customer since only one part of the bundle was defective.','既然 bundle 中只有一部分有缺陷我们能否给这位客户提供 partial refund。',2,['support','sentence_pattern'],'sentence_pattern'],
['The campaign slowed down in week two.','sentence_pattern','活动第二周放缓了','momentum drop','Crowdfunding Campaign','campaign live','report','The campaign slowed down in week two which is normal but we still need a boost.','活动在第二周 slowed down 了这是正常的但我们仍然需要一波推动。',1,['crowdfunding','sentence_pattern'],'sentence_pattern'],
['We need to lower the free shipping threshold.','sentence_pattern','得降低包邮门槛','shipping proposal','Shopify / DTC Store','dtc store operation','propose','We need to lower the free shipping threshold because the current one is scaring off buyers.','我们需要降低 free shipping threshold 因为目前的门槛在吓跑买家。',1,['dtc','sentence_pattern'],'sentence_pattern'],
['The supplier missed the deadline again.','sentence_pattern','供应商又逾期了','supplier delay','Supplier / Foreign Trade','supplier communication','report','The supplier missed the deadline again and this is the third time so we need to talk seriously.','supplier 又 missed the deadline 了这是第三次所以我们需要认真谈谈。',2,['supplier','sentence_pattern'],'sentence_pattern'],
['The return rate is higher than expected.','sentence_pattern','退货率高于预期','return issue','Customer Support','customer support','report','The return rate is higher than expected for the blue variant and we are investigating why.','蓝色款的 return rate 高于预期我们正在调查原因。',1,['support','sentence_pattern'],'sentence_pattern'],
['We should A/B test the headline.','sentence_pattern','标题得做 AB 测试','test proposal','Ads / Acquisition','paid acquisition','propose','We should A/B test the headline because the current one has a CTR below industry average.','我们应该对标题做 A/B test 因为目前标题的 CTR 低于行业平均水平。',1,['ads','sentence_pattern'],'sentence_pattern'],
['The cost per purchase is too high.','sentence_pattern','每次购买成本太高','cost concern','Ads / Acquisition','paid acquisition','report','The cost per purchase is too high at thirty-eight dollars and we need to bring it under thirty.','cost per purchase 三十八美元太高了我们需要把它降到三十以下。',2,['ads','sentence_pattern'],'sentence_pattern'],
['The 3PL lost another package.','sentence_pattern','三方物流又丢包了','logistics problem','Fulfillment / Logistics','logistics','report','The 3PL lost another package this month so we are considering switching providers.','3PL 这个月又丢了一个包裹所以我们在考虑更换服务商。',2,['logistics','sentence_pattern'],'sentence_pattern'],
['The email flow is not triggering.','sentence_pattern','邮件流程没触发','email issue','Email / CRM','email marketing','report','The email flow is not triggering for customers who buy through the quick checkout button.','email flow 对于通过快速结账按钮购买的客户没有触发。',2,['email','sentence_pattern'],'sentence_pattern'],
['Backers are asking about refunds.','sentence_pattern','支持者开始问退款','backer concern','Backer Communication','post-campaign fulfillment','report','Backers are asking about refunds because the project is now two months past the estimated delivery date.','backer 开始问退款了因为项目已经超过预计交付日期两个月了。',2,['communication','sentence_pattern'],'sentence_pattern'],
['The product page needs more reviews.','sentence_pattern','产品页需要更多评价','review gap','Shopify / DTC Store','dtc store operation','identify','The product page needs more reviews to build trust before we scale the ad spend.','在我们放量广告支出之前 product page 需要更多评价来建立信任。',1,['dtc','sentence_pattern'],'sentence_pattern'],
['Can we extend the early bird window?','sentence_pattern','能延长早鸟窗口吗','promo proposal','Crowdfunding Campaign','campaign live','propose','Can we extend the early bird window by another 48 hours to capture the weekend traffic.','我们能把 early bird 窗口再延长 48 小时来获取周末流量吗。',1,['crowdfunding','sentence_pattern'],'sentence_pattern'],
['The factory is behind schedule.','sentence_pattern','工厂进度落后','production delay','Supplier / Foreign Trade','supplier communication','report','The factory is behind schedule because a key machine broke down and the repair took three days.','工厂进度落后的原因是一台关键机器坏了维修花了三天。',2,['supplier','sentence_pattern'],'sentence_pattern'],

// ===== MORE TERMS FOR REACHING 1000 =====
// Crowdfunding extra
['community engagement','noun_phrase','社群互动','community involvement','Crowdfunding Campaign','campaign live','build community','Community engagement in the comments section is the best organic growth channel we have.','评论区的 community engagement 是我们拥有的最好的有机增长渠道。',1,['crowdfunding','community'],'phrase'],
['campaign boost','noun_phrase','活动助推','campaign push','Crowdfunding Campaign','campaign live','gain momentum','We got a campaign boost after being featured in the projects we love section.','在被项目推荐栏目收录后我们获得了一波 campaign boost。',1,['crowdfunding','growth'],'phrase'],
['backer lead','noun_phrase','支持者线索','potential backer','Crowdfunding Campaign','pre-launch','collect contacts','We collected over 3000 backer leads from the pre-launch page in two months.','我们在两个月内从 pre-launch page 收集了超过 3000 个 backer lead。',1,['crowdfunding','marketing'],'phrase'],

// Shopify extra
['checkout flow','noun_phrase','结账流程','payment path','Shopify / DTC Store','dtc store operation','optimise','The checkout flow loses about forty percent of customers at the shipping cost step.','checkout flow 在运费步骤流失了大约百分之四十的客户。',2,['dtc','ux'],'phrase'],
['product carousel','noun_phrase','产品轮播','image slider','Shopify / DTC Store','dtc store operation','showcase','The product carousel on mobile is too fast and people miss the key features.','移动端上的 product carousel 太快了人们错过了关键功能。',1,['dtc','design'],'phrase'],
['payment method','noun_phrase','支付方式','way to pay','Shopify / DTC Store','dtc store operation','accept payment','We need to add more payment methods because many international customers prefer local options.','我们需要添加更多 payment method 因为许多国际客户更喜欢本地选项。',1,['dtc','technical'],'phrase'],
['gift card','noun_phrase','礼品卡','prepaid card','Shopify / DTC Store','dtc store operation','increase sales','Gift cards are popular during the holiday season and bring in new customers who might not buy otherwise.','gift card 在假日季很受欢迎，能带来本来不会购买的新客户。',1,['dtc','sales'],'phrase'],
['store credit','noun_phrase','店铺积分','in-store credit','Customer Support','customer support','compensate','We offered store credit instead of a cash refund and about half of customers accepted.','我们提供了 store credit 而不是现金退款，大约一半客户接受了。',1,['support','loyalty'],'phrase'],

// Ads extra
['ad performance','noun_phrase','广告表现','how ads do','Ads / Acquisition','paid acquisition','measure','Ad performance dipped after iOS 14 but we recovered by building better lookalike audiences.','iOS 14 之后 ad performance 下降了但我们通过创建更好的相似受众恢复了过来。',2,['ads','metrics'],'phrase'],
['interest targeting','noun_phrase','兴趣定向','interest-based','Ads / Acquisition','paid acquisition','define audience','Interest targeting used to work well but now broad targeting often performs better.','interest targeting 过去效果很好但现在广泛定向往往表现更好。',2,['ads','strategy'],'phrase'],
['lead magnet','noun_phrase','引流磁石','freebie for email','Email / CRM','email marketing','collect leads','We used a PDF guide as a lead magnet and collected over 2000 emails in a month.','我们用一份 PDF 指南作为 lead magnet 一个月内收集了超过 2000 个邮箱。',1,['email','growth'],'phrase'],

// Email extra
['email frequency','noun_phrase','邮件发送频率','how often','Email / CRM','email marketing','plan','The email frequency of twice a week seems to be the sweet spot without annoying subscribers.','每周两次的 email frequency 似乎是最佳频率，不会惹恼订阅者。',1,['email','strategy'],'phrase'],
['click-through rate','noun_phrase','点击率','percentage clicked','Email / CRM','email marketing','measure','The click-through rate on the product section is three times higher than the rest of the email.','产品区域的 click-through rate 是邮件其余部分的三倍。',1,['email','metrics'],'phrase'],

// Support extra
['support backlog','noun_phrase','积压工单','ticket pile','Customer Support','customer support','manage workload','The support backlog grew to over 200 tickets during the launch weekend.','上线周末期间 support backlog 增长到了超过 200 个工单。',2,['support','metrics'],'phrase'],
['self-service','noun','自助服务','help yourself','Customer Support','customer support','reduce tickets','Good self-service content reduces our ticket volume by about thirty percent.','好的 self-service 内容将我们的工单量减少了大约百分之三十。',1,['support','strategy'],'word'],

// Logistics extra
['shipping rate','noun_phrase','运费','delivery charge','Fulfillment / Logistics','logistics','manage cost','The shipping rate for international orders is based on weight and destination zone.','国际订单的 shipping rate 基于重量和目的地区域。',1,['logistics','finance'],'phrase'],
['warehouse location','noun_phrase','仓库位置','warehouse site','Fulfillment / Logistics','logistics','plan logistics','Having a warehouse location on the East Coast cut delivery times by two days for half our customers.','东海岸有一个 warehouse location 将我们一半客户的派送时间缩短了两天。',1,['logistics','strategy'],'phrase'],

// Supplier extra
['supplier relationship','noun_phrase','供应商关系','factory relationship','Supplier / Foreign Trade','supplier communication','maintain','A long-term supplier relationship is more valuable than squeezing the lowest price on every order.','长期的 supplier relationship 比在每笔订单上压到最低价更有价值。',2,['supplier','strategy'],'phrase'],
['import duty','noun_phrase','进口关税','import tax','Supplier / Foreign Trade','supplier communication','calculate cost','The import duty on consumer electronics into the EU can be as high as fourteen percent.','消费电子产品进入欧盟的 import duty 可能高达百分之十四。',3,['supplier','international'],'phrase'],
['shipment tracking','noun_phrase','货物追踪','cargo tracking','Fulfillment / Logistics','logistics','monitor','Shipment tracking for sea freight is less granular than for air freight.','海运的 shipment tracking 不如空运的精细化。',1,['logistics','operations'],'phrase'],
['production lead time','noun_phrase','生产交货期','manufacturing time','Supplier / Foreign Trade','supplier communication','plan','The production lead time is currently four weeks but it extends to six during peak season.','production lead time 目前是四周，但在旺季会延长到六周。',2,['supplier','planning'],'phrase'],
['brand awareness','noun_phrase','品牌知名度','brand recognition','Crowdfunding Campaign','campaign live','build','Brand awareness from the crowdfunding campaign helped us get into retail stores later.','众筹活动带来的 brand awareness 后来帮助我们进入了零售店。',1,['crowdfunding','brand'],'phrase'],
['AOV boost','noun_phrase','客单价提升','average order value increase','Shopify / DTC Store','dtc store operation','increase','The free shipping threshold gave us a twenty percent AOV boost across all orders.','免费送货门槛给我们带来了所有订单百分之二十的 AOV boost。',2,['dtc','metrics'],'phrase'],
['first purchase','noun_phrase','首次购买','initial buy','Shopify / DTC Store','dtc store operation','acquire','The first purchase is the hardest to get but once they buy they come back.','first purchase 最难获得但一旦他们买了就会再回来。',1,['dtc','conversion'],'phrase'],
];

// ===== PROCESS =====
let batchCount=0;
for(const item of items){
  const [term,pos,sm,sis,topic,bizStage,work,ex,ez,diff,tags,type,reg]=item;
  if(existing.has(term.toLowerCase())){skipped++;continue;}
  existing.add(term.toLowerCase());
  id++;
  const newItem={
    id:'foreign-trade-crowdfunding-dtc-operations-1000-'+String(id).padStart(4,'0'),
    packId:'foreign-trade-crowdfunding-dtc-operations-1000',term,
    type:type||'word',partOfSpeech:pos||'noun_phrase',topic,
    businessStage:bizStage||'',workIntent:work||'',
    shortMeaning:sm,shortMeaningInSentence:sis,
    example:ex,exampleZh:ez,
    register:reg||'neutral',difficulty:diff||2,
    sourceType:'foreign_trade_dtc_style_original',
    sourceTitle:'Original foreign trade DTC learning sentence',
    sourceUrl:'',sourceDate:'',isRealSourceSentence:false,
    tags:tags||['dtc'],fullForm:FF[term]||undefined
  };
  newItems.push(newItem);
  added++;batchCount++;
}
console.log('Added',batchCount,'items | Skipped:',skipped,'duplicates');
if(newItems.length>0){
  const updated=data.concat(newItems);
  fs.writeFileSync(file,JSON.stringify(updated));
  console.log('File total:',updated.length);
  if(updated.length<TARGET) console.log('Need',TARGET-updated.length,'more');
}

// Update packs.ts
const packsFile='src/data/packs.ts';
let pc=fs.readFileSync(packsFile,'utf-8');
pc=pc.replace(
  /('foreign-trade-crowdfunding-dtc-operations-1000'[\s\S]*?total:\s*)\d+/,
  (_,prefix)=>prefix+updated.length
);
fs.writeFileSync(packsFile,pc);
console.log('Updated packs.ts total to',updated.length);

// Update status
const stFile='docs/WORD_PACK_GENERATION_STATUS.json';
const st=JSON.parse(fs.readFileSync(stFile,'utf-8'));
if(st.packs['foreign-trade-crowdfunding-dtc-operations-1000']){
  st.packs['foreign-trade-crowdfunding-dtc-operations-1000'].current=updated.length;
  st.lastAction='Extended foreign trade pack with clean exampleZh items.';
}
fs.writeFileSync(stFile,JSON.stringify(st,null,2));
console.log('Done.');

