// DEPRECATED / DO NOT RUN
// This generator may produce low-quality or over-target items.
// Use only with a manually curated candidate pool.
const fs=require('fs');
const file='src/data/packs/smart-hardware-overseas-channel-sales-core.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));
const FF={MSRP:'Manufacturer Suggested Retail Price',FCC:'Federal Communications Commission',CE:'Conformité Européenne',RoHS:'Restriction of Hazardous Substances',WEEE:'Waste Electrical and Electronic Equipment',UKCA:'UK Conformity Assessed',B2B:'Business to Business',OEM:'Original Equipment Manufacturer',SKU:'Stock Keeping Unit',POS:'Point of Sale',TCO:'Total Cost of Ownership',RFQ:'Request for Quotation'};

const newItems=[];let id=data.length+1,added=0,skipped=0;

function add(t,sm,sis,topic,ss,ct,wi,ex,ez,diff,tg,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  newItems.push({id:'smart-hardware-overseas-channel-sales-core-'+String(id).padStart(4,'0'),packId:'smart-hardware-overseas-channel-sales-core',term:t,type:type||'word',topic,salesStage:ss||'',channelType:ct||'',workIntent:wi||'',shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'workplace',difficulty:diff||2,sourceType:'smart_hardware_channel_sales_style_original',sourceTitle:'Original smart hardware channel sales learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tg||['sales'],fullForm:FF[t]||undefined});
  id++;added++;return true;
}

const terms=[
// Product Positioning
['value proposition','价值主张','what makes you different','Product Positioning / Value Proposition','prospecting','direct sales','pitch product','Our value proposition is that the device lasts twice as long as the leading competitor at the same price.','我们的 value proposition 是在同样价格下这款设备的使用寿命是主要竞品的两倍。',2,['positioning','pitch']],
['selling point','卖点','key benefit','Product Positioning / Value Proposition','pitch','direct sales','highlight feature','The main selling point for retailers is the high margin and strong after-sales support.','对零售商来说主要的 selling point 是高利润和强大的售后支持。',1,['positioning','pitch']],
['product positioning','产品定位','market position','Product Positioning / Value Proposition','prospecting','direct sales','define strategy','We need to nail the product positioning before we approach distributors.','在接触分销商之前我们需要确定 product positioning。',2,['positioning','strategy']],
['target customer','目标客户','ideal buyer','Product Positioning / Value Proposition','prospecting','direct sales','define audience','Our target customer is a tech-savvy professional who values portability over raw power.','我们的 target customer 是重视便携性胜过原始性能的技术专业人士。',1,['positioning','strategy']],
['use case','使用场景','how it is used','Product Positioning / Value Proposition','demo','direct sales','show value','The best use case to demo is the outdoor scenario because that is where the battery life advantage shows.','最好的 demo use case 是户外场景因为那是电池寿命优势体现的地方。',1,['positioning','demo']],
['competitive advantage','竞争优势','edge over rivals','Product Positioning / Value Proposition','prospecting','direct sales','highlight strength','Our competitive advantage is the combination of waterproof design and a two-year warranty.','我们的 competitive advantage 是防水设计与两年保修的 combination。',2,['positioning','strategy']],

// Outbound Sales / Cold Call
['cold call','陌生拜访','unsolicited sales call','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','reach prospects','I made twenty cold calls this morning and got three follow-up meetings scheduled.','我今天早上打了二十个 cold call 预约了三次跟进会议。',2,['sales','outbound']],
['prospect','潜在客户','potential customer','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','find leads','We found this prospect through a trade show inquiry from last month.','我们通过上个月的一次展会询盘找到了这个 prospect。',1,['sales','outbound']],
['lead','线索','sales lead','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','build pipeline','Every lead from the website contact form gets a reply within four hours.','来自网站联系表单的每个 lead 都会在四小时内得到回复。',1,['sales','outbound']],
['decision maker','决策者','person who decides','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','reach authority','Can you connect me with the decision maker for hardware purchasing in your company?','你能帮我联系贵公司硬件采购的 decision maker 吗？',1,['sales','outbound']],
['gatekeeper','守门人','person blocking access','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','bypass barrier','The receptionist is the gatekeeper so be polite and ask for the person by name.','前台是 gatekeeper 所以要礼貌地直接叫出要找的人的名字。',2,['sales','outbound']],
['pitch','推销','sales talk','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','present offer','Keep the pitch under two minutes and focus on the one thing that makes your product different.','把 pitch 控制在两分钟以内专注于让你的产品与众不同的那一点。',1,['sales','outbound']],
['follow-up call','跟进电话','callback after contact','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','maintain contact','I sent the quotation yesterday and I will make a follow-up call on Thursday.','我昨天发了报价单周四会打一个 follow-up call。',1,['sales','outbound']],
['objection','异议','customer concern','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','handle resistance','The most common objection is about the price so we prepared a comparison chart with competitors.','最常见的 objection 是关于价格所以我们准备了与竞品的对比表。',2,['sales','outbound']],

// Distributor / Agent Development
['agent','代理商','sales representative','Distributor / Agent Development','partner negotiation','agent','find partner','We are looking for a local agent who already sells into retail chains in the region.','我们在寻找已经在当地销售到零售连锁店的 local agent。',1,['channel','agent']],
['distributor','分销商','wholesale partner','Distributor / Agent Development','partner negotiation','distributor','find partner','A good distributor will handle customs warehousing and local delivery for you.','一个好的 distributor 会为你处理海关、仓储和本地配送。',1,['channel','distributor']],
['dealer','经销商','retail seller','Distributor / Agent Development','partner negotiation','dealer','find partner','We need to recruit at least five dealers in each major city to get decent coverage.','我们需要在每个主要城市招募至少五个 dealer 才能获得像样的覆盖。',1,['channel','dealer']],
['reseller','转售商','authorised seller','Distributor / Agent Development','partner negotiation','reseller','find partner','The reseller programme includes training marketing materials and a dedicated account manager.','reseller programme 包括培训营销材料和专属客户经理。',2,['channel','reseller']],
['channel partner','渠道合作伙伴','distribution ally','Distributor / Agent Development','partner negotiation','distributor','build relationship','We treat every channel partner as an extension of our own sales team.','我们把每个 channel partner 都当作我们自己销售团队的延伸。',2,['channel','partner']],
['partner onboarding','合作伙伴入驻','bringing partner on board','Distributor / Agent Development','partner negotiation','distributor','integrate partner','The partner onboarding process takes about two weeks including product and sales training.','partner onboarding 过程大约需要两周包括产品和销售培训。',2,['channel','onboarding']],
['dealer training','经销商培训','educating resellers','Distributor / Agent Development','partner negotiation','dealer','enable partner','We run dealer training sessions every quarter to make sure partners can demo the products properly.','我们每季度进行 dealer training 以确保合作伙伴能够正确演示产品。',2,['channel','training']],

// Exclusive Agency / Territory
['exclusive distributor','独家分销','only distributor','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','negotiate rights','We offered them exclusive distributor status for the Nordic region with a minimum annual target.','我们给了他们北欧地区的 exclusive distributor 地位附有最低年度目标。',3,['channel','exclusive']],
['exclusive rights','独家权利','sole selling rights','Exclusive Agency / Territory / Channel Policy','partner negotiation','agent','negotiate rights','They want exclusive rights for the territory but we are not sure they can meet the volume.','他们想要该地区的 exclusive rights 但我们不确定他们是否能达到销量。',3,['channel','exclusive']],
['territory protection','区域保护','area exclusivity','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','define boundaries','Territory protection means we will not sell to another distributor in their assigned area.','territory protection 意味着我们不会卖给他们指定区域的另一个分销商。',3,['channel','policy']],
['sales territory','销售区域','geographic area','Exclusive Agency / Territory / Channel Policy','partner negotiation','agent','assign area','Each agent gets a defined sales territory with clear boundaries and a list of target cities.','每个 agent 都有一个明确的 sales territory 有清晰的边界和目标城市列表。',2,['channel','territory']],
['minimum sales target','最低销售目标','required sales volume','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','set expectations','The minimum sales target for the first year is 5000 units across the assigned territory.','第一年的 minimum sales target 是在指定区域内销售 5000 台。',2,['channel','target']],
['performance clause','业绩条款','target requirement','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','set expectations','The contract includes a performance clause that allows us to terminate if they miss the target two quarters in a row.','合同包含 performance clause 如果他们连续两个季度未达目标我们有权终止。',3,['channel','contract']],

// B2B Negotiation / Pricing
['wholesale price','批发价','bulk price','B2B Negotiation / Pricing / Payment','pricing negotiation','distributor','negotiate terms','The wholesale price depends on the order volume with better rates above 1000 units.','wholesale price 取决于订单量超过 1000 台有更好的价格。',2,['pricing','b2b']],
['dealer price','经销商价格','partner price','B2B Negotiation / Pricing / Payment','pricing negotiation','dealer','set pricing','The dealer price is set at 40 percent below MSRP to give partners a healthy margin.','dealer price 设定在 MSRP 以下百分之四十给合作伙伴留下 healthy margin。',2,['pricing','b2b']],
['MSRP','建议零售价','suggested retail price','B2B Negotiation / Pricing / Payment','pricing negotiation','retail chain','set pricing','The MSRP is ninety-nine dollars but retailers are free to set their own final price.','MSRP 是九十九美元但零售商可以自由设定最终价格。',1,['pricing','retail']],
['margin','利润空间','profit percentage','B2B Negotiation / Pricing / Payment','pricing negotiation','dealer','negotiate terms','The dealer margin is too low at twenty percent compared to competing brands that offer thirty.','dealer margin 太低了只有百分之二十而竞品提供百分之三十。',2,['pricing','margin']],
['volume discount','批量折扣','quantity price break','B2B Negotiation / Pricing / Payment','pricing negotiation','distributor','incentivise volume','We offer a volume discount of an extra five percent for orders over 2000 units.','我们为超过 2000 台的订单提供额外百分之五的 volume discount。',2,['pricing','discount']],
['quotation','报价','price offer','B2B Negotiation / Pricing / Payment','pricing negotiation','B2B customer','provide pricing','I will send you the quotation by the end of today including shipping costs to your warehouse.','我今天下班前会把 quotation 发给你包括到你仓库的运费。',1,['pricing','quote']],
['payment terms','付款条款','pay conditions','B2B Negotiation / Pricing / Payment','pricing negotiation','distributor','agree terms','Our standard payment terms are thirty percent deposit and seventy percent before shipment.','我们的标准 payment terms 是百分之三十订金和百分之七十发货前付清。',2,['payment','terms']],
['purchase order','采购订单','buy order','B2B Negotiation / Pricing / Payment','contracting','B2B customer','formalise order','We need a signed purchase order before we can schedule production for your batch.','我们需要 signed purchase order 才能为你的批次安排生产。',2,['order','contract']],
['proforma invoice','形式发票','preliminary invoice','B2B Negotiation / Pricing / Payment','pricing negotiation','B2B customer','document terms','The proforma invoice shows the unit price quantity and shipping terms before the final order.','proforma invoice 在最终订单之前显示了单价数量和运输条款。',2,['invoice','document']],

// Trade Show / Exhibition
['trade show','展会','industry exhibition','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','generate leads','We are exhibiting at the trade show in Berlin next month and need to prepare the booth and samples.','我们下个月在柏林的 trade show 参展需要准备展位和样机。',1,['exhibition','event']],
['exhibition','展览','large trade show','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','showcase products','The exhibition runs for three days and we expect about twenty thousand visitors.','exhibition 持续三天我们预计大约有两万参观者。',1,['exhibition','event']],
['booth','展位','stand','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','present brand','Our booth is in Hall 3 near the main entrance so we should get good foot traffic.','我们的 booth 在三号馆靠近主入口所以应该会有好的客流。',1,['exhibition','booth']],
['demo unit','演示机','display model','Trade Show / Exhibition / Follow-up','demo','trade show','showcase product','We shipped three demo units to the exhibition venue and they arrived with some scratches on the casing.','我们往展馆发了三台 demo unit 外壳有些划痕。',1,['exhibition','demo']],
['live demo','现场演示','real-time demo','Trade Show / Exhibition / Follow-up','demo','trade show','impress visitors','The live demo of the water-resistant feature drew a crowd at our booth every hour.','防水功能的 live demo 每小时都在我们的 booth 吸引一群人。',1,['exhibition','demo']],
['follow-up email','跟进邮件','after-event email','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','maintain contact','We sent a follow-up email to every lead we met at the exhibition within 48 hours.','我们在展会上遇到的每个 lead 都在 48 小时内发了 follow-up email。',1,['exhibition','follow-up']],
['meeting slot','会议时段','appointment','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','schedule meeting','All three meeting slots for tomorrow morning at the booth are already booked with distributors.','明天早上 booth 的三个 meeting slot 都已被分销商预订了。',1,['exhibition','meeting']],

// Retail / Supermarket
['retail buyer','零售采购','store purchaser','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','pitch to buyer','The retail buyer wants to test the product in ten pilot stores before committing to a chain-wide rollout.','retail buyer 想在承诺全连锁铺货前先在十家 pilot store 测试产品。',2,['retail','buyer']],
['category manager','品类经理','product category buyer','Retail / Supermarket / Channel Expansion','retail onboarding','supermarket','pitch category','The category manager for electronics decides which brands get shelf space in that aisle.','电子产品的 category manager 决定哪些品牌在那一排货架上获得 shelf space。',2,['retail','buyer']],
['shelf space','货架空间','display area','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','negotiate placement','Getting good shelf space at eye level can make or break a new brand in retail.','在视线高度获得好的 shelf space 可以决定一个新品牌在零售中的成败。',2,['retail','placement']],
['listing fee','上架费','slotting fee','Retail / Supermarket / Channel Expansion','retail onboarding','supermarket','pay for access','The listing fee for the electronics aisle was higher than we expected so we need to adjust the budget.','电子产品通道的 listing fee 比我们预期的要高所以我们需要调整预算。',2,['retail','fee']],
['sell-through','售罄率','actual retail sales','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','measure performance','The sell-through rate in the first month was over eighty percent which means the product is moving fast.','第一个月的 sell-through rate 超过百分之八十这意味着产品卖得很快。',2,['retail','metrics']],
['point of sale','销售点','checkout area','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','optimise placement','We placed a small display stand at the point of sale to catch impulse purchases.','我们在 point of sale 放了一个小展示架用来抓住冲动消费。',2,['retail','placement']],
['planogram','货架图','shelf layout','Retail / Supermarket / Channel Expansion','retail onboarding','supermarket','design layout','The planogram shows exactly where each product should sit on the shelf for maximum visibility.','planogram 精确显示了每个产品应该放在货架的哪个位置以获得最大可见度。',3,['retail','layout']],

// Certification / Compliance
['CE marking','CE 标志','EU safety mark','Certification / Market Access / Compliance','market access','B2B customer','comply with regulation','We need CE marking before we can ship to any country in the European Union.','我们需要 CE marking 才能发货到欧盟的任何国家。',3,['compliance','certification']],
['FCC certification','FCC 认证','US radio approval','Certification / Market Access / Compliance','market access','B2B customer','comply with regulation','The FCC certification took about six weeks and cost around fifteen thousand dollars.','FCC certification 花了大约六周费用约一万五千美元。',3,['compliance','certification']],
['RoHS','RoHS','hazardous substance rule','Certification / Market Access / Compliance','market access','B2B customer','comply with regulation','All components in the device must be RoHS compliant or we cannot sell in Europe.','设备中的所有组件都必须符合 RoHS 否则我们不能在欧洲销售。',3,['compliance','regulation']],
['declaration of conformity','符合性声明','compliance document','Certification / Market Access / Compliance','market access','B2B customer','document compliance','The declaration of conformity must be signed and kept on file for at least ten years.','declaration of conformity 必须签署并存档至少十年。',3,['compliance','document']],
['test report','测试报告','lab result','Certification / Market Access / Compliance','market access','B2B customer','prove compliance','The test report from the accredited lab confirms the device meets all safety requirements.','来自认证实验室的 test report 确认该设备符合所有安全要求。',3,['compliance','document']],
['user manual','用户手册','instruction book','Certification / Market Access / Compliance','market access','B2B customer','provide documentation','The user manual must be translated into the local language for each country we sell in.','user manual 必须翻译成我们销售的每个国家的当地语言。',1,['compliance','document']],
['importer','进口商','legal importer','Certification / Market Access / Compliance','market access','distributor','define responsibility','The importer of record is legally responsible for ensuring the product meets local regulations.','record 上的 importer 对确保产品符合当地法规负有法律责任。',3,['compliance','legal']],

// After-sales / Warranty
['warranty','保修','product guarantee','After-sales / Warranty / Training','after-sales support','B2B customer','provide assurance','The standard warranty is one year but we offer an extended three-year warranty for enterprise buyers.','标准 warranty 是一年但我们为企业买家提供延长的三年 warranty。',1,['aftersales','warranty']],
['warranty claim','保修索赔','repair request','After-sales / Warranty / Training','after-sales support','B2B customer','handle issues','The distributor wants a simpler process for handling warranty claims from their retail customers.','distributor 想要一个更简单的处理来自他们零售客户 warranty claim 的流程。',2,['aftersales','warranty']],
['spare parts','备件','replacement components','After-sales / Warranty / Training','after-sales support','distributor','support maintenance','We need to keep spare parts in the local warehouse so repairs do not take three weeks.','我们需要在本地仓库保留 spare parts 这样维修不会需要三周时间。',2,['aftersales','parts']],
['service center','服务中心','repair centre','After-sales / Warranty / Training','after-sales support','B2B customer','provide support','We are setting up a service center in the region to handle repairs and customer inquiries locally.','我们正在该地区建立一个 service center 以本地处理维修和客户咨询。',2,['aftersales','service']],
['installation guide','安装指南','setup instructions','After-sales / Warranty / Training','after-sales support','B2B customer','help customer','The installation guide has step-by-step pictures so that even a non-technical person can set up the device.','installation guide 有逐步图片这样即使非技术人员也能设置设备。',1,['aftersales','document']],
['return process','退货流程','return procedure','After-sales / Warranty / Training','after-sales support','B2B customer','handle returns','The return process for defective units must be clearly communicated to distributors at the start of the partnership.','缺陷产品的 return process 必须在 partnership 开始时清楚告知分销商。',2,['aftersales','process']],

// Channel Strategy
['channel sales','渠道销售','selling through partners','Channel Strategy / Sales Model','partner negotiation','distributor','define model','Channel sales now account for over sixty percent of our total international revenue.','channel sales 现在占我们国际总收入的百分之六十以上。',2,['channel','strategy']],
['direct sales','直销','selling directly','Channel Strategy / Sales Model','prospecting','direct sales','define model','Direct sales through our own website gives us higher margins but limits our reach.','通过我们自己网站的 direct sales 给我们更高的利润但限制了我们的覆盖范围。',1,['channel','strategy']],
['franchise','加盟','business licence','Channel Strategy / Sales Model','partner negotiation','franchise','expand network','The franchise model allows us to expand quickly without the capital cost of opening our own stores.','franchise 模式让我们能够快速扩张而无需自己开店的大量资金。',2,['channel','strategy']],
['hybrid channel','混合渠道','mixed sales model','Channel Strategy / Sales Model','partner negotiation','distributor','combine approaches','A hybrid channel approach lets us sell directly online while also building a dealer network.','hybrid channel 方式让我们在建立经销商网络的同时也能直接在线销售。',3,['channel','strategy']],
['channel strategy','渠道策略','go-to-market plan','Channel Strategy / Sales Model','partner negotiation','distributor','plan expansion','Our channel strategy for Europe is to start with one exclusive distributor and add resellers in year two.','我们在欧洲的 channel strategy 是从一个 exclusive distributor 开始第二年再增加 reseller。',2,['channel','strategy']],

// Trial / Pilot
['trial order','试单','test purchase','Trial / Pilot / First Order','partner negotiation','B2B customer','test product','Can we start with a trial order of 100 units before committing to a full container?','我们能不能先下一个 100 台的 trial order 再承诺整柜？',1,['order','trial']],
['pilot store','试点店','test retail location','Trial / Pilot / First Order','retail onboarding','retail chain','test in store','The retail chain agreed to test our product in five pilot stores for three months.','这家零售连锁同意在五家 pilot store 测试我们的产品三个月。',2,['retail','pilot']],
['sample unit','样机','demo product','Trial / Pilot / First Order','demo','B2B customer','showcase product','We can send you a sample unit at no cost so you can evaluate the build quality yourself.','我们可以免费寄给你一台 sample unit 让你自己评估做工质量。',1,['demo','sample']],
['first order','首单','initial purchase','Trial / Pilot / First Order','pricing negotiation','B2B customer','close deal','The first order is usually smaller while the buyer tests the market response.','首单通常较小 buyer 同时在 test 市场反应。',1,['order','first']],
['reorder','复购','repeat purchase','Trial / Pilot / First Order','after-sales support','B2B customer','build loyalty','If the sell-through is good the reorder will come within six to eight weeks.','如果 sell-through 好 reorder 会在六到八周内到来。',1,['order','repeat']],
// Batch 2
['price list','价格表','product price sheet','B2B Negotiation / Pricing / Payment','pricing negotiation','dealer','provide pricing','I will send you the updated price list with the new wholesale prices for Q3.','我会发给你更新后的 price list 包含 Q3 新的 wholesale price。',1,['pricing','document']],
['credit terms','账期','payment delay','B2B Negotiation / Pricing / Payment','pricing negotiation','distributor','negotiate terms','The distributor asked for net-60 credit terms but our standard is net-30.','分销商要求 net-60 credit terms 但我们的标准是 net-30。',3,['payment','terms']],
['deposit','订金','upfront payment','B2B Negotiation / Pricing / Payment','pricing negotiation','B2B customer','secure order','The deposit is thirty percent of the total order value payable before production starts.','deposit 是订单总金额的百分之三十在生产开始前支付。',1,['payment','terms']],
['balance payment','尾款','remaining amount','B2B Negotiation / Pricing / Payment','pricing negotiation','B2B customer','complete payment','The balance payment is due once the goods pass the final quality inspection.','balance payment 在货物通过最终质检时到期。',1,['payment','terms']],
['product brochure','产品手册','product catalogue','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','inform visitors','We printed 500 copies of the product brochure for the exhibition next week.','我们为下周的 exhibition 印了 500 份 product brochure。',1,['marketing','document']],
['business card','名片','contact card','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','exchange contacts','Always carry extra business cards because you will run out faster than you think at a trade show.','总是多带 business card 因为在 trade show 上用得比你想象的快。',1,['networking','basic']],
['lead form','线索表','contact form','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','capture information','We use a QR code on the booth for visitors to fill in the lead form on their phone.','我们在 booth 上使用 QR code 让参观者在手机上填写 lead form。',1,['exhibition','lead']],
['booth meeting','展位会议','stand appointment','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','schedule meeting','We have three booth meetings booked for tomorrow morning with distributors from France.','明天早上我们有三场 booth meeting 预定了与来自法国的 distributor。',1,['exhibition','meeting']],
['visitor badge','参观者证','entry pass','Trade Show / Exhibition / Follow-up','trade show follow-up','trade show','identify visitors','You need a visitor badge to enter the exhibition hall so register online before you come.','进入展馆需要 visitor badge 所以来之前先在线注册。',1,['exhibition','logistics']],
['showroom','展厅','display room','Trade Show / Exhibition / Follow-up','trade show follow-up','direct sales','demonstrate products','We set up a permanent showroom near the factory so distributors can bring their retail customers.','我们在工厂附近建了一个 permanent showroom 让 distributor 可以带他们的零售客户来看。',2,['exhibition','showroom']],
['retail chain','零售连锁','chain store','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','expand channel','Getting into a retail chain like MediaMarkt or Best Buy can increase your volume by five times.','进入像 MediaMarkt 或 Best Buy 这样的 retail chain 可以让你的销量增加五倍。',2,['retail','chain']],
['supermarket','超市','large grocery store','Retail / Supermarket / Channel Expansion','retail onboarding','supermarket','enter channel','The supermarket channel requires different packaging because the product sits on open shelves.','supermarket 渠道需要不同的 packaging 因为产品放在开放货架上。',1,['retail','supermarket']],
['electronics store','电子产品店','tech shop','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','enter channel','Electronics stores give us a better brand presence than general supermarkets.','electronics store 给我们比普通超市更好的品牌展示。',1,['retail','store']],
['store visit','门店拜访','retail check','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','check presence','I did a store visit yesterday and our product was not on the shelf because it was sold out.','我昨天做了一次 store visit 我们的产品不在货架上因为卖光了。',1,['retail','visit']],
['display stand','展示架','product display','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','optimise visibility','We provided a free display stand to the retailer so our product stands out from the shelf.','我们给零售商提供了一个免费的 display stand 让我们的产品从货架上脱颖而出。',1,['retail','display']],
['staff training','员工培训','team education','After-sales / Warranty / Training','after-sales support','dealer','enable partner','We did a two-hour staff training session with the retail team so they can explain the product to customers.','我们与零售团队进行了两小时的 staff training 让他们能够向客户解释产品。',1,['aftersales','training']],
['technical support','技术支持','tech help','After-sales / Warranty / Training','after-sales support','B2B customer','help customer','Technical support is available in English during European business hours via email and chat.','technical support 在欧洲工作时间以英文通过邮件和聊天提供。',1,['aftersales','support']],
['troubleshooting guide','故障排除指南','fix-it manual','After-sales / Warranty / Training','after-sales support','B2B customer','help customer','The troubleshooting guide covers the ten most common issues and takes about five minutes to read.','troubleshooting guide 涵盖了十个最常见的问题大约需要五分钟阅读。',1,['aftersales','document']],
['service fee','服务费','repair charge','After-sales / Warranty / Training','after-sales support','B2B customer','set pricing','Out-of-warranty repairs are subject to a service fee that depends on the type of damage.','保修期外的维修需要支付 service fee 根据损坏类型而定。',1,['aftersales','pricing']],
['maintenance plan','维护计划','service contract','After-sales / Warranty / Training','after-sales support','B2B customer','offer service','We offer a maintenance plan for enterprise customers that covers two on-site visits per year.','我们为企业客户提供 maintenance plan 每年包含两次现场服务。',2,['aftersales','service']],

// Certification extras
['UKCA marking','UKCA 标志','UK compliance mark','Certification / Market Access / Compliance','market access','B2B customer','comply with regulation','UKCA marking is now required for products sold in Great Britain after Brexit.','UKCA marking 现在是脱欧后在英国销售产品所必需的。',3,['compliance','certification']],
['compliance label','合规标签','regulation sticker','Certification / Market Access / Compliance','market access','B2B customer','meet requirements','The compliance label must include the model number manufacturer name and the CE mark.','compliance label 必须包含型号制造商名称和 CE 标志。',2,['compliance','label']],
['warning label','警告标签','safety notice','Certification / Market Access / Compliance','market access','B2B customer','meet requirements','The warning label about the rechargeable battery must be printed in the local language.','关于可充电电池的 warning label 必须用当地语言印刷。',2,['compliance','label']],
['local regulation','当地法规','country-specific rule','Certification / Market Access / Compliance','market access','B2B customer','research requirements','You need to check the local regulation for wireless devices before shipping to that country.','在发货到该国之前你需要检查无线设备的 local regulation。',3,['compliance','legal']],
['country approval','国家准入','market clearance','Certification / Market Access / Compliance','market access','B2B customer','obtain permission','Some countries require a separate country approval that takes four to six weeks.','一些国家需要一个单独的 country approval 需要四到六周。',3,['compliance','legal']],

// Sales extras
['sales rep','销售代表','salesperson','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','represent company','Each sales rep is responsible for a specific region and handles both new leads and existing accounts.','每个 sales rep 负责一个特定区域处理新 leads 和现有客户。',1,['sales','role']],
['store manager','店长','shop manager','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','pitch decision','The store manager has the authority to decide which new products to test on the shelves.','store manager 有权决定在货架上测试哪些新产品。',1,['retail','role']],
['retail placement','零售铺位','in-store position','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','optimise position','A good retail placement near the checkout counter can increase impulse purchases dramatically.','靠近收银台的好的 retail placement 可以大幅增加冲动购买。',2,['retail','placement']],
['counter display','柜台展示','small display','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','optimise visibility','The counter display holds six units and fits perfectly next to the cash register.','counter display 可放六台产品完美适配收银机旁边。',1,['retail','display']],
['sales script','销售话术','call guide','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','guide conversation','The sales script gives you a structure but do not sound like you are reading from a page.','sales script 给你一个结构但不要听起来像是在念稿。',1,['sales','tool']],
['opening line','开场白','first sentence','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','start strong','The opening line should be about them not about you and it should spark curiosity.','opening line 应该是关于他们的而不是关于你的并且应该引起好奇心。',1,['sales','pitch']],
['callback','回电','return call','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','follow up','I left a voicemail yesterday and will try a callback this afternoon.','我昨天留了语音邮件今天下午会试一次 callback。',1,['sales','follow-up']],
['meeting request','会议请求','ask for appointment','Outbound Sales / Cold Call / Email Outreach','cold call','direct sales','schedule meeting','The goal of the first call is not to sell but to get a meeting request accepted.','第一通电话的目标不是销售而是让 meeting request 被接受。',1,['sales','pitch']],

// Channel extras
['regional partner','区域伙伴','area partner','Distributor / Agent Development','partner negotiation','distributor','find partner','We are looking for a regional partner who already has relationships with electronics retailers.','我们在寻找已经与电子产品零售商有关系的 regional partner。',1,['channel','partner']],
['authorized distributor','授权分销商','official distributor','Distributor / Agent Development','partner negotiation','distributor','designate partner','Only an authorized distributor can use our brand name in their marketing materials.','只有 authorized distributor 可以在营销材料中使用我们的品牌名称。',2,['channel','distributor']],
['dealer network','经销商网络','reseller network','Distributor / Agent Development','partner negotiation','dealer','build coverage','Building a dealer network takes time but once it is in place the recurring orders are steady.','建立 dealer network 需要时间但一旦到位复购订单就会很稳定。',2,['channel','network']],
['distribution channel','分销渠道','sales channel','Distributor / Agent Development','partner negotiation','distributor','define strategy','We need to decide whether to use a single distribution channel or multiple channels in each country.','我们需要决定在各国是使用单一的 distribution channel 还是多渠道。',2,['channel','strategy']],
['partner agreement','合作协议','contract','Distributor / Agent Development','partner negotiation','agent','formalise relationship','The partner agreement covers territory sales targets pricing and the term of the relationship.','partner agreement 涵盖了区域销售目标定价和合作期限。',2,['channel','contract']],
['channel coverage','渠道覆盖率','market reach','Distributor / Agent Development','partner negotiation','distributor','assess reach','Our channel coverage in Germany is good but we have almost nothing in France yet.','我们在德国的 channel coverage 不错但在法国几乎还没有。',2,['channel','coverage']],
['renewal term','续约期限','contract extension','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','define contract','The renewal term is automatic for another year if both parties do not give notice within 90 days.','如果双方未在 90 天内通知 renewal term 自动延续一年。',3,['channel','contract']],
['termination clause','终止条款','end condition','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','define contract','The termination clause allows either party to end the agreement with six months written notice.','termination clause 允许任何一方以六个月书面通知终止协议。',3,['channel','contract']],
['channel conflict','渠道冲突','partner clash','Exclusive Agency / Territory / Channel Policy','partner negotiation','distributor','resolve issues','Selling directly on Amazon can create channel conflict with your retail partners.','直接在 Amazon 上销售可能与你的 retail partner 产生 channel conflict。',3,['channel','conflict']],

// Retail extras
['shelf listing','上架','product placement','Retail / Supermarket / Channel Expansion','retail onboarding','supermarket','get placement','The shelf listing process at a large supermarket chain can take three to six months.','在大型连锁超市的 shelf listing 过程可能需要三到六个月。',2,['retail','listing']],
['stock rotation','库存轮换','inventory turnover','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','manage stock','Good stock rotation means the oldest units sell first so nothing sits on the shelf past its best date.','好的 stock rotation 意味着最旧的货先卖出所以没有东西在货架上过期。',2,['retail','inventory']],
['in-store demo','店内演示','live demo in shop','Retail / Supermarket / Channel Expansion','retail onboarding','retail chain','promote product','We run an in-store demo every Saturday afternoon to show customers how the device works in real life.','我们每周六下午进行 in-store demo 向客户展示设备在真实生活中的使用效果。',1,['retail','demo']],
];for(const t of terms)add(t[0],t[1],t[2],t[3],t[4],t[5],t[6],t[7],t[8],t[9],t[10]);const updated=data.concat(newItems);fs.writeFileSync(file,JSON.stringify(updated));console.log('Smart HW: Added',added,'| Skipped:',skipped,'| Total:',updated.length);
