// DEPRECATED / DO NOT RUN
// This generator may produce low-quality or over-target items.
// Use only with a manually curated candidate pool.
const fs=require('fs');
const file='src/data/packs/ai-product-management-llm-products-1000.json';
const data=JSON.parse(fs.readFileSync(file,'utf-8'));
const existing=new Set(data.map(d=>d.term.toLowerCase()));

const FF={RAG:'Retrieval-Augmented Generation',PRD:'Product Requirements Document',MVP:'Minimum Viable Product',LLM:'Large Language Model',UX:'User Experience',UI:'User Interface',API:'Application Programming Interface',KPI:'Key Performance Indicator',ROI:'Return on Investment',SaaS:'Software as a Service',QA:'Quality Assurance',SDK:'Software Development Kit',ML:'Machine Learning',NLP:'Natural Language Processing',TTS:'Text to Speech',ASR:'Automatic Speech Recognition'};

const newItems=[];
let id=data.length+1,added=0,skipped=0;
const TARGET=300;

function add(t,sm,sis,topic,stage,work,ex,ez,diff,tags,type,reg){
  if(existing.has(t.toLowerCase())){skipped++;return false;}
  existing.add(t.toLowerCase());
  newItems.push({id:'ai-product-management-llm-products-1000-'+String(id).padStart(4,'0'),packId:'ai-product-management-llm-products-1000',term:t,type:type||'word',topic,productStage:stage||'',workIntent:work||'',shortMeaning:sm,shortMeaningInSentence:sis,example:ex,exampleZh:ez,register:reg||'workplace',difficulty:diff||2,sourceType:'ai_product_style_original',sourceTitle:'Original AI product management learning sentence',sourceUrl:'',sourceDate:'',isRealSourceSentence:false,tags:tags||['ai-pm'],fullForm:FF[t]||undefined});
  id++;added++;return true;
}

const terms=[
// AI Product Strategy
['problem space','问题空间','what problem to solve','AI Product Strategy / Use Case Discovery','discovery','define product scope','Before we touch any model, we need to map out the problem space clearly.','在我们接触任何模型之前需要先清楚地梳理 problem space。',2,['discovery','strategy']],
['user persona','用户画像','ideal user profile','User Research / Customer Feedback','discovery','understand users','We built three user personas for the assistant: the busy executive, the student, and the small business owner.','我们为助手建立了三个 user persona：忙碌的高管、学生和小企业主。',1,['user-research','design']],
['jobs to be done','待完成工作','user goal framework','AI Product Strategy / Use Case Discovery','discovery','define user goals','The jobs to be done framework helps us focus on what users actually need rather than what they say they want.','jobs to be done 框架帮助我们关注用户真正需要什么，而不是他们说想要什么。',3,['discovery','framework']],
['wedge strategy','楔入策略','narrow entry strategy','AI Product Strategy / Use Case Discovery','discovery','design go-to-market','Our wedge strategy is to start with a single high-value use case and expand from there.','我们的 wedge strategy 是从一个高价值用例开始，然后从那里扩展。',3,['strategy','gtm']],
['product-market fit','产品市场契合','does market want it','AI Product Strategy / Use Case Discovery','launch','validate demand','We know we have product-market fit when users start recommending the product without being prompted.','当用户开始主动推荐产品时我们就知道有 product-market fit 了。',3,['strategy','validation']],
['total addressable market','总可寻址市场','market size','AI Product Strategy / Use Case Discovery','discovery','estimate opportunity','The total addressable market for AI assistants in customer support is estimated at over twenty billion dollars.','客户支持领域 AI 助手的 total addressable market 估计超过二百亿美元。',3,['strategy','business']],

// LLM Basics
['context window','上下文窗口','max tokens at once','LLM Basics / Model Capabilities','design','understand constraints','The prompt fails on long conversations because it exceeds the context window limit.','提示在长对话中失败因为它超出了 context window 的限制。',3,['llm','constraints']],
['token limit','token 限制','max token count','LLM Basics / Model Capabilities','design','manage costs','We need to keep the system prompt short because every token counts against the token limit.','我们需要保持系统提示简短因为每个 token 都计入 token limit。',2,['llm','constraints']],
['model latency','模型延迟','response speed','LLM Basics / Model Capabilities','evaluation','measure performance','The model latency is under 800 milliseconds for most queries which is acceptable for a chat interface.','大多数查询的 model latency 在 800 毫秒以内这对聊天界面来说是可以接受的。',3,['llm','performance']],
['temperature','温度','randomness setting','LLM Basics / Model Capabilities','design','control output','We lowered the temperature to 0.2 for the billing assistant because accuracy is more important than creativity here.','我们把账单助手的 temperature 降到 0.2 因为在这里准确性比创造性更重要。',3,['llm','parameters']],
['top-p sampling','top-p 采样','nucleus sampling','LLM Basics / Model Capabilities','design','control diversity','Top-p sampling gives us more natural output than greedy decoding without going fully random.','top-p sampling 给我们比贪婪解码更自然的输出而不会完全随机。',4,['llm','parameters']],

// Prompt Engineering
['system prompt','系统提示','model behaviour instruction','Prompt / Context / Instruction Design','design','define behaviour','The system prompt should clearly state that the assistant must not give legal advice.','system prompt 应该明确说明助手不得提供法律建议。',2,['prompt','safety']],
['few-shot prompt','少样本提示','example-guided prompt','Prompt / Context / Instruction Design','implementation','improve accuracy','We added three examples to the few-shot prompt and the format adherence went up significantly.','我们在 few-shot prompt 中加入了三个例子格式遵循度显著提高。',3,['prompt','technique']],
['chain of thought','思维链','step-by-step reasoning','Prompt / Context / Instruction Design','implementation','improve reasoning','Adding chain of thought to the prompt improved the accuracy on multi-step math problems by over forty percent.','在 prompt 中加入 chain of thought 将多步骤数学问题的准确率提高了百分之四十以上。',4,['prompt','technique']],
['prompt template','提示模板','reusable prompt structure','Prompt / Context / Instruction Design','implementation','standardise prompts','We built a prompt template that injects the user query and conversation history automatically.','我们构建了一个 prompt template 自动注入用户查询和对话历史。',2,['prompt','engineering']],

// RAG / Knowledge Base
['chunking','分块','splitting documents','RAG / Knowledge Base / Retrieval','implementation','prepare data','The chunking strategy matters a lot because if chunks are too large the retrieval loses precision.','chunking 策略非常重要因为如果块太大检索就会失去精度。',3,['rag','data-prep']],
['embedding','嵌入','vector representation','RAG / Knowledge Base / Retrieval','implementation','encode documents','We are comparing the OpenAI embedding model with an open-source alternative for cost reasons.','出于成本考虑我们在比较 OpenAI embedding 模型和一个开源替代方案。',3,['rag','technical']],
['retrieval','检索','finding relevant docs','RAG / Knowledge Base / Retrieval','evaluation','fetch context','The retrieval step is the bottleneck because the search is too slow for real-time conversations.','retrieval 步骤是瓶颈因为搜索对于实时对话来说太慢了。',3,['rag','performance']],
['reranking','重排序','reorder results','RAG / Knowledge Base / Retrieval','implementation','improve relevance','We added a reranking step after retrieval and the quality of the top three results improved noticeably.','我们在检索后增加了 reranking 步骤前三名结果的质量有了明显提升。',4,['rag','technique']],
['hybrid search','混合搜索','keyword + vector','RAG / Knowledge Base / Retrieval','implementation','combine approaches','Hybrid search that combines keyword matching with vector similarity works much better for product documentation.','结合关键词匹配和向量相似度的 hybrid search 在产品文档中效果好得多。',3,['rag','technique']],

// Agent / Workflow
['agent workflow','智能体工作流','agent task sequence','Agent / Workflow / Automation','design','automate processes','The agent workflow needs a human approval step before sending any customer-facing email.','agent workflow 在发送面向客户的邮件之前需要有一个人工审批步骤。',3,['agent','design']],
['tool calling','工具调用','model uses external API','Agent / Workflow / Automation','implementation','integrate systems','The model needs tool calling to check order status from the database because that data is not in the knowledge base.','模型需要 tool calling 从数据库查询订单状态因为那些数据不在知识库中。',4,['agent','api']],
['multi-agent system','多智能体系统','multiple cooperating agents','Agent / Workflow / Automation','design','coordinate tasks','In our multi-agent system one agent handles retrieval while another handles the final response generation.','在我们的 multi-agent system 中一个 agent 处理检索另一个处理最终的回复生成。',4,['agent','architecture']],
['human in the loop','人机协同','human oversight','Agent / Workflow / Automation','design','ensure safety','For financial transactions we always keep a human in the loop to approve before execution.','对于金融交易我们始终保留 human in the loop 在执行前进行审批。',3,['agent','safety']],
['fallback response','兜底回复','backup answer','Agent / Workflow / Automation','design','handle failures','We need a polite fallback response when the agent cannot find a relevant answer in the knowledge base.','当 agent 在知识库中找不到相关答案时需要有一个礼貌的 fallback response。',2,['agent','ux']],

// Evaluation
['eval set','评估集','test question set','Evaluation / Quality / Benchmark','evaluation','measure quality','We built an eval set of 200 real user questions to track whether changes actually improve the model output.','我们建立了一个包含 200 个真实用户问题的 eval set 来追踪变更是否真的改进了模型输出。',3,['evaluation','testing']],
['ground truth','标准答案','correct reference','Evaluation / Quality / Benchmark','evaluation','define correctness','Without a reliable ground truth it is hard to tell if the model answer is actually correct.','没有可靠的 ground truth 很难判断模型答案是否真的正确。',3,['evaluation','data']],
['hallucination rate','幻觉率','wrong-answer ratio','Evaluation / Quality / Benchmark','evaluation','track accuracy','The hallucination rate dropped from eight percent to under two after we added RAG with proper chunking.','加入带有适当 chunking 的 RAG 后 hallucination rate 从百分之八降到了百分之二以下。',3,['evaluation','quality']],
['factuality score','事实性得分','truth measurement','Evaluation / Quality / Benchmark','evaluation','measure accuracy','We track the factuality score weekly because it is the metric that matters most to our enterprise customers.','我们每周追踪 factuality score 因为这是企业客户最关心的指标。',4,['evaluation','metrics']],
['user satisfaction score','用户满意度','happy-user metric','Evaluation / Quality / Benchmark','evaluation','measure UX','The user satisfaction score went up after we reduced the average response time to under two seconds.','在我们将平均响应时间降到两秒以下后 user satisfaction score 上升了。',2,['evaluation','ux']],

// Safety / Privacy
['guardrail','护栏','safety filter','Safety / Privacy / Compliance','risk review','prevent harm','The guardrail should block any output that contains personally identifiable information even if the user asks for it.','guardrail 应阻止任何包含个人身份信息的输出即使用户要求也不行。',3,['safety','privacy']],
['red teaming','红队测试','adversarial testing','Safety / Privacy / Compliance','risk review','find vulnerabilities','We ran a red teaming exercise and found that the model could be tricked into revealing system instructions.','我们进行了一次 red teaming 练习发现模型可以被诱导泄露系统指令。',4,['safety','testing']],
['prompt injection','提示注入','attack via prompt','Safety / Privacy / Compliance','risk review','prevent attacks','The security review found a prompt injection that could make the assistant completely ignore its safety rules.','安全审查发现了一个 prompt injection 能让助手完全忽略其安全规则。',4,['safety','security']],
['data residency','数据驻留','where data lives','Safety / Privacy / Compliance','enterprise deployment','comply with regulations','Our European customers require data residency in the EU so we deployed a separate instance in Frankfurt.','我们的欧洲客户要求数据在欧盟 data residency 所以我们在法兰克福部署了单独实例。',4,['privacy','enterprise']],
['PII redaction','PII 脱敏','hide personal info','Safety / Privacy / Compliance','implementation','protect privacy','We added automatic PII redaction to strip names phone numbers and email addresses from the chat logs.','我们添加了自动 PII redaction 从聊天日志中去除姓名电话号码和电子邮件地址。',3,['privacy','engineering']],

// Pricing / Token Cost
['token cost','token 成本','price per token','Pricing / Token Cost / Monetization','growth','control spending','The token cost will be a problem for free-tier users if the average conversation runs over ten thousand tokens.','如果平均对话超过一万个 token 那么 token cost 对免费用户来说会是一个问题。',2,['pricing','business']],
['cost per query','每次查询成本','query price','Pricing / Token Cost / Monetization','growth','track unit economics','We aim to keep the cost per query under half a cent to maintain a healthy margin on the pro plan.','我们的目标是保持 cost per query 在半美分以下以维持专业版计划的健康利润。',3,['pricing','finance']],
['usage-based pricing','按用量计费','pay per use','Pricing / Token Cost / Monetization','growth','design pricing','Usage-based pricing makes sense for our API product but the enterprise plan needs predictable monthly billing.','usage-based pricing 对我们的 API 产品有意义但企业版需要可预测的月度计费。',3,['pricing','strategy']],
['rate limit','速率限制','requests per minute','Pricing / Token Cost / Monetization','growth','prevent abuse','We set a rate limit of 60 requests per minute for the free tier to prevent abuse while keeping it usable.','我们将免费版的 rate limit 设为每分钟 60 个请求以防止滥用同时保持可用性。',2,['pricing','engineering']],

// UX / Conversation Design
['conversation design','对话设计','chat UX','UX / Conversation Design','design','craft user experience','Good conversation design means the assistant admits when it does not know something rather than guessing.','好的 conversation design 意味着助手在不知道某事时会承认而不是猜测。',2,['ux','design']],
['tone of voice','语气风格','brand voice','UX / Conversation Design','design','define personality','We defined the tone of voice as warm professional and concise with absolutely no marketing fluff.','我们把 tone of voice 定义为温暖专业简洁绝对没有营销废话。',2,['ux','brand']],
['error message','错误提示','failure response','UX / Conversation Design','design','handle gracefully','The error message should tell the user what went wrong in plain language and suggest a next step.','error message 应该用平实的语言告诉用户出了什么问题并建议下一步。',1,['ux','design']],
['onboarding flow','引导流程','first-time experience','UX / Conversation Design','launch','help new users','The onboarding flow walks new users through three sample queries to show what the assistant can do.','onboarding flow 引导新用户完成三个示例查询展示助手能做什么。',1,['ux','onboarding']],

// Engineering Collaboration
['latency budget','延迟预算','time allowance','Engineering Collaboration / Debugging','implementation','set constraints','We have a 200-millisecond latency budget for the retrieval step because the total response must be under two seconds.','我们为 retrieval 步骤设了 200 毫秒的 latency budget 因为总响应必须在两秒以内。',4,['engineering','performance']],
['error logging','错误日志','failure recording','Engineering Collaboration / Debugging','implementation','debug issues','The error logging shows that most timeouts happen during peak hours between 2 and 4 PM.','error logging 显示大多数超时发生在下午两到四点的高峰时段。',2,['engineering','debugging']],
['A/B test','A/B 测试','compare versions','Engineering Collaboration / Debugging','evaluation','compare approaches','We are running an A/B test comparing the current prompt with a new version that includes chain of thought.','我们正在运行一个 A/B test 比较当前 prompt 和包含 chain of thought 的新版本。',2,['engineering','experiment']],
['regression test','回归测试','check for breakage','Engineering Collaboration / Debugging','evaluation','prevent breakage','The regression test suite caught a drop in factuality after the last model update so we rolled it back.','regression test 套件在上次模型更新后捕捉到了事实性下降所以我们回滚了。',3,['engineering','testing']],
['canary deployment','金丝雀部署','gradual rollout','Engineering Collaboration / Debugging','launch','reduce risk','We use canary deployment to roll out new model versions to five percent of users first.','我们使用 canary deployment 先将新模型版本推送给百分之五的用户。',3,['engineering','deployment']],

// Launch / GTM
['beta programme','测试计划','early access','Launch / GTM / Customer Success','launch','gather feedback','The beta programme has 50 companies signed up and we are learning a lot about real-world usage patterns.','beta programme 有 50 家公司注册我们从中学到了很多关于实际使用模式的信息。',2,['launch','feedback']],
['customer onboarding','客户接入','getting started','Launch / GTM / Customer Success','customer success','ensure adoption','Enterprise customer onboarding takes about two weeks and includes a dedicated solutions engineer.','企业 customer onboarding 大约需要两周包括一名专属解决方案工程师。',2,['customer-success','enterprise']],
['churn rate','流失率','customer loss','Launch / GTM / Customer Success','growth','track retention','The monthly churn rate dropped after we introduced the onboarding flow for new users.','在引入面向新用户的 onboarding flow 后月度 churn rate 下降了。',2,['metrics','retention']],
['net promoter score','净推荐值','customer loyalty','Launch / GTM / Customer Success','growth','measure satisfaction','Our net promoter score improved from 32 to 48 after we shipped the RAG-powered knowledge base feature.','在发布 RAG 驱动的知识库功能后我们的 net promoter score 从 32 提高到 48。',3,['metrics','satisfaction']],

// Data / Analytics
['conversion funnel','转化漏斗','user journey steps','Data / Analytics / Product Metrics','growth','track user flow','The conversion funnel shows that most users drop off between the demo and the sign-up step.','conversion funnel 显示大多数用户在 demo 和注册步骤之间流失。',2,['analytics','metrics']],
['user retention','用户留存','staying users','Data / Analytics / Product Metrics','growth','measure stickiness','Day-seven user retention is the metric we care most about because it shows if people find real value.','第七天 user retention 是我们最关心的指标因为它显示人们是否找到了真正的价值。',2,['analytics','metrics']],
['feature adoption','功能采用','feature usage','Data / Analytics / Product Metrics','growth','track usage','The feature adoption rate for the knowledge base upload tool is lower than expected so we need to improve discoverability.','知识库上传工具的 feature adoption 率低于预期所以我们需要改进可发现性。',2,['analytics','product']],
['time to value','价值实现时间','how fast to see value','Data / Analytics / Product Metrics','growth','optimise onboarding','Our time to value is about three minutes because the user can upload a document and ask a question immediately.','我们的 time to value 大约三分钟因为用户可以立即上传文档并提问。',2,['analytics','ux']],

// Additional quality terms
['model fine-tuning','模型微调','custom training','LLM Basics / Model Capabilities','implementation','adapt model','We are fine-tuning the model on our customer support transcripts to improve domain-specific accuracy.','我们正在用客户支持对话记录 fine-tuning 模型以提高特定领域的准确性。',4,['llm','engineering']],
['vector database','向量数据库','embedding storage','RAG / Knowledge Base / Retrieval','implementation','store embeddings','We chose an open-source vector database to keep costs predictable as the knowledge base grows.','我们选择了一个开源的 vector database 以便在知识库增长时保持成本可预测。',3,['rag','infrastructure']],
['source citation','来源引用','show where from','RAG / Knowledge Base / Retrieval','implementation','build trust','Every answer should include a source citation so users can verify the information themselves.','每个答案都应该包括 source citation 这样用户可以自行核实信息。',2,['rag','trust']],
['context stuffing','上下文填充','overloading prompt','Prompt / Context / Instruction Design','implementation','optimise accuracy','Context stuffing can hurt more than help because the model loses focus when given too much irrelevant text.','context stuffing 可能弊大于利因为模型在获得过多无关文本时会失去焦点。',3,['prompt','technique']],
['streaming response','流式响应','real-time output','UX / Conversation Design','implementation','improve perceived speed','Streaming response makes the assistant feel much faster because users see the first words almost instantly.','streaming response 让助手感觉快得多因为用户几乎立即就能看到第一个词。',2,['ux','engineering']],
['caching layer','缓存层','stored responses','Engineering Collaboration / Debugging','implementation','reduce cost','We added a caching layer for common questions which cut our API costs by nearly thirty percent.','我们为常见问题添加了 caching layer 将 API 成本降低了近百分之三十。',3,['engineering','optimisation']],
['model selection','模型选择','choose which model','LLM Basics / Model Capabilities','design','make trade-offs','Model selection is always a trade-off between quality speed and cost for each specific use case.','model selection 总是在质量速度和成本之间为每个具体用例做权衡。',3,['llm','strategy']],
['toxicity filter','毒性过滤','harmful content block','Safety / Privacy / Compliance','implementation','prevent harm','The toxicity filter caught an edge case where the model was generating passive-aggressive responses to frustrated users.','toxicity filter 发现了一个边缘案例模型在对沮丧用户生成被动攻击性的回复。',3,['safety','engineering']],
['feedback loop','反馈循环','improvement cycle','Data / Analytics / Product Metrics','growth','improve continuously','We built a feedback loop where user ratings feed directly into the eval set for the next iteration.','我们建立了 feedback loop 用户评分直接输入到下一轮迭代的 eval set 中。',2,['analytics','improvement']],

// More quality terms
['model distillation','模型蒸馏','small model from big','LLM Basics / Model Capabilities','implementation','reduce cost','Model distillation lets us run a smaller faster model that retains most of the large model accuracy.','model distillation 让我们运行更小更快的模型同时保留大型模型的大部分准确性。',5,['llm','engineering']],
['RLHF','RLHF','human feedback training','LLM Basics / Model Capabilities','implementation','align model','RLHF was a key technique in making the model more helpful and less likely to produce harmful outputs.','RLHF 是使模型更有帮助且更少产生有害输出的关键技术。',5,['llm','technique']],
['structured output','结构化输出','JSON output','LLM Basics / Model Capabilities','implementation','enable automation','We need structured output from the model so we can parse the response and trigger the next workflow step.','我们需要模型输出 structured output 以便解析响应并触发下一个工作流步骤。',3,['llm','engineering']],
['function calling','函数调用','API trigger','Agent / Workflow / Automation','implementation','connect systems','Function calling allows the model to decide when to call an external API based on the user request.','function calling 允许模型根据用户请求决定何时调用外部 API。',3,['agent','api']],
['response format','回复格式','output structure','UX / Conversation Design','design','standardise output','We defined a response format that separates the main answer from optional follow-up suggestions.','我们定义了一个 response format 将主要答案与可选的后续建议分开。',2,['ux','design']],
['welcome message','欢迎消息','first greeting','UX / Conversation Design','launch','set expectations','The welcome message should set the tone and clearly tell users what the assistant can and cannot do.','welcome message 应该定下基调并清楚地告诉用户助手能做什么和不能做什么。',1,['ux','onboarding']],
['disambiguation','消歧','clarify intent','UX / Conversation Design','design','handle ambiguity','When the query is ambiguous the assistant should ask a disambiguation question instead of guessing.','当查询模糊时助手应该提出 disambiguation 问题而不是猜测。',3,['ux','design']],
['inference time','推理时间','model thinking time','Engineering Collaboration / Debugging','evaluation','measure speed','The inference time nearly doubled after we increased the max token output from 500 to 2000.','在把 max token output 从 500 增加到 2000 后 inference time 几乎翻了一倍。',3,['engineering','performance']],
['throughput','吞吐量','requests per second','Engineering Collaboration / Debugging','evaluation','measure capacity','Our current throughput is about 30 requests per second which will not be enough for the holiday traffic.','我们当前的 throughput 大约是每秒 30 个请求这对假期流量来说不够。',3,['engineering','performance']],
['uptime','在线时间','availability','Engineering Collaboration / Debugging','evaluation','track reliability','We target 99.9 percent uptime for the enterprise tier with a strict SLA for refunds if we miss it.','我们的目标是 enterprise tier 的 uptime 达到百分之 99.9 如果达不到则有严格的退款 SLA。',3,['engineering','reliability']],
['SLA','服务水平协议','service level agreement','Launch / GTM / Customer Success','enterprise deployment','commit to quality','The SLA guarantees a response time under 500 milliseconds for 99 percent of all API calls.','SLA 保证百分之 99 的 API 调用响应时间在 500 毫秒以内。',3,['enterprise','business']],
['SOC 2','SOC 2','security certification','Safety / Privacy / Compliance','enterprise deployment','prove security','We are working towards SOC 2 compliance because every enterprise customer asks for it during the sales process.','我们正在努力达到 SOC 2 合规因为每个企业客户在销售过程中都会要求它。',4,['security','enterprise']],
['GDPR','GDPR','data protection regulation','Safety / Privacy / Compliance','enterprise deployment','comply with law','GDPR compliance means European users can request deletion of all their conversation data at any time.','GDPR 合规意味着欧洲用户可以随时要求删除其所有对话数据。',3,['privacy','legal']],
['content moderation','内容审核','filter bad output','Safety / Privacy / Compliance','implementation','prevent harm','Content moderation is especially important when the assistant is exposed to user-generated input in a public setting.','当助手在公开环境中接触用户生成输入时 content moderation 尤为重要。',3,['safety','engineering']],
['version control','版本控制','track changes','Engineering Collaboration / Debugging','implementation','manage prompts','We keep all prompts under version control so we can track what changed and when.','我们把所有 prompt 都放在 version control 下以便追踪何时发生了什么变化。',2,['engineering','tooling']],
['playground','实验区','testing sandbox','Engineering Collaboration / Debugging','evaluation','experiment quickly','The internal playground lets the team test prompt changes against a fixed eval set before going live.','内部 playground 让团队可以在上线前针对固定的 eval set 测试 prompt 变更。',2,['engineering','tooling']],
['log analysis','日志分析','review records','Engineering Collaboration / Debugging','implementation','debug issues','Log analysis revealed that most errors happen during the retrieval step not during generation.','log analysis 显示大多数错误发生在 retrieval 步骤而不是 generation 步骤。',3,['engineering','debugging']],
['feature flag','功能开关','toggle on off','Engineering Collaboration / Debugging','launch','control rollout','We put the new RAG pipeline behind a feature flag so we can turn it off instantly if something goes wrong.','我们把新的 RAG pipeline 放在 feature flag 后面这样如果出问题可以立即关闭。',2,['engineering','deployment']],
['rollback','回滚','revert change','Engineering Collaboration / Debugging','launch','undo mistakes','We had to rollback the model update after the hallucination rate spiked in production.','在 hallucination rate 在生产环境中飙升后我们不得不 rollback 模型更新。',2,['engineering','deployment']],
['bottleneck','瓶颈','slowest step','Engineering Collaboration / Debugging','evaluation','find issues','The bottleneck is the embedding generation step which takes nearly 200 milliseconds per document.','bottleneck 是 embedding 生成步骤每个文档需要近 200 毫秒。',2,['engineering','performance']],
['load testing','负载测试','stress test','Engineering Collaboration / Debugging','evaluation','verify capacity','We ran a load testing session simulating Black Friday traffic and the system held up well.','我们进行了一次 load testing 模拟黑色星期五流量系统表现良好。',3,['engineering','testing']],
['observability','可观测性','monitoring','Engineering Collaboration / Debugging','evaluation','monitor systems','We need better observability into the retrieval pipeline to understand why some queries return irrelevant documents.','我们需要对 retrieval pipeline 有更好的 observability 以理解为什么有些查询返回无关文档。',4,['engineering','monitoring']],
['dashboard','仪表盘','visual metrics','Data / Analytics / Product Metrics','growth','visualise data','The dashboard shows real-time token usage cost per query and user satisfaction all on one screen.','dashboard 在一个屏幕上实时显示 token 使用量每次查询成本和用户满意度。',2,['analytics','tooling']],
['cohort analysis','同期群分析','group analysis','Data / Analytics / Product Metrics','growth','understand behaviour','A cohort analysis showed that users who upload documents in the first week are three times more likely to stay.','cohort analysis 显示第一周上传文档的用户留存率高出三倍。',4,['analytics','technique']],
['funnel drop-off','漏斗流失','where users leave','Data / Analytics / Product Metrics','growth','find leaks','The biggest funnel drop-off is between the free trial sign-up and the first actual query.','最大的 funnel drop-off 出现在免费试用注册和第一次实际查询之间。',2,['analytics','metrics']],
['power user','重度用户','heavy user','Data / Analytics / Product Metrics','growth','identify advocates','Power users who send over 50 queries per day account for nearly half of our total token consumption.','每天发送超过 50 次查询的 power user 占了我们总 token 消耗的近一半。',2,['analytics','users']],
['retention curve','留存曲线','keep rate over time','Data / Analytics / Product Metrics','growth','track loyalty','The retention curve flattens after day 14 which suggests that users who survive two weeks tend to stay long term.','retention curve 在第 14 天后趋于平稳表明坚持两周的用户往往会长期留下来。',3,['analytics','metrics']],
['North Star metric','北极星指标','key success measure','Data / Analytics / Product Metrics','growth','align team','Our North Star metric is the number of queries answered with a source citation per active user per week.','我们的 North Star metric 是每个活跃用户每周获得带 source citation 的查询数量。',3,['analytics','strategy']],

// Batch 2
['copilot','副驾驶','AI assistant','AI Product Strategy / Use Case Discovery','design','define product type','The copilot approach works better than full automation because users want to stay in control of the final decision.','copilot 方式比完全自动化效果更好因为用户希望保持对最终决策的控制。',2,['strategy','product-type']],
['AI-native','AI 原生','built around AI','AI Product Strategy / Use Case Discovery','design','define approach','An AI-native product is designed from the ground up around model capabilities rather than retrofitting AI into an existing workflow.','AI-native 产品是从头围绕模型能力设计的而不是把 AI 改装到现有工作流中。',3,['strategy','design']],
['model card','模型卡','model documentation','LLM Basics / Model Capabilities','launch','document model','Every model we release includes a model card that describes its intended use limitations and performance metrics.','我们发布的每个模型都包含 model card 描述其预期用途限制和性能指标。',3,['llm','documentation']],
['tokenizer','分词器','text splitter','LLM Basics / Model Capabilities','implementation','understand mechanics','The tokenizer treats common words as single tokens but rare words get split into multiple subword tokens.','tokenizer 将常见词视为单个 token 但罕见词会被拆分为多个子词 token。',4,['llm','technical']],
['max tokens','最大 token 数','output length limit','LLM Basics / Model Capabilities','design','control output','We set the max tokens to 500 for the chat interface because users do not want a wall of text.','我们把聊天界面的 max tokens 设为 500 因为用户不想要一堵文字墙。',2,['llm','parameters']],
['stop sequence','停止序列','when to stop','LLM Basics / Model Capabilities','implementation','control output','We added a stop sequence so the model knows when to end its turn in a multi-turn conversation.','我们添加了 stop sequence 这样模型就知道在多轮对话中何时结束自己的回合。',3,['llm','engineering']],
['benchmark suite','基准测试套件','eval tests','Evaluation / Quality / Benchmark','evaluation','measure quality','We run every model update through a benchmark suite of 500 questions covering factuality safety and instruction following.','我们把每次模型更新都通过包含 500 个问题的 benchmark suite 进行测试涵盖事实性安全性和指令遵循。',3,['evaluation','testing']],
['blind test','盲测','unbiased comparison','Evaluation / Quality / Benchmark','evaluation','compare fairly','In the blind test users preferred our model output over the competitor in seven out of ten cases.','在 blind test 中用户在十次中有七次更喜欢我们的模型输出而非竞争对手。',3,['evaluation','testing']],
['inter-rater reliability','评分者间信度','agreement between raters','Evaluation / Quality / Benchmark','evaluation','ensure consistency','We measure inter-rater reliability to make sure different evaluators are scoring the same output consistently.','我们测量 inter-rater reliability 以确保不同评估员对同一输出评分一致。',5,['evaluation','methodology']],
['context relevance','上下文相关性','how relevant is retrieved','RAG / Knowledge Base / Retrieval','evaluation','measure retrieval quality','Context relevance dropped when we switched to a smaller embedding model so we switched back.','当我们切换到较小的 embedding 模型时 context relevance 下降了所以又换了回来。',3,['rag','metrics']],
['answer grounding','答案有据','answer based on source','RAG / Knowledge Base / Retrieval','evaluation','measure faithfulness','Answer grounding measures whether each claim in the response can be traced back to a specific source document.','answer grounding 衡量回复中的每个陈述是否可以追溯到特定的源文档。',4,['rag','quality']],
['hybrid evaluation','混合评估','human + auto','Evaluation / Quality / Benchmark','evaluation','combine methods','We use hybrid evaluation with automated metrics for speed and human review for nuanced quality judgements.','我们使用 hybrid evaluation 用自动指标求速用人工审核做细微的质量判断。',3,['evaluation','methodology']],
['model switch','模型切换','change model','Engineering Collaboration / Debugging','implementation','update infrastructure','The model switch took about two hours of downtime which we scheduled for Sunday morning when traffic is lowest.','model switch 需要大约两小时的停机时间我们安排在周日早上流量最低的时候。',2,['engineering','operations']],
['deprecation notice','弃用通知','sunset warning','Launch / GTM / Customer Success','customer success','communicate changes','We sent a deprecation notice to all API users six weeks before shutting down the old endpoint.','我们在关闭旧端点六周前向所有 API 用户发送了 deprecation notice。',2,['customer-success','communication']],
['migration guide','迁移指南','upgrade instructions','Launch / GTM / Customer Success','customer success','help users upgrade','The migration guide walks users through upgrading from the old API format to the new one step by step.','migration guide 逐步引导用户从旧 API 格式升级到新格式。',2,['customer-success','documentation']],
['developer experience','开发者体验','DX','Engineering Collaboration / Debugging','implementation','make devs happy','Good developer experience means clear documentation fast onboarding and helpful error messages in the API.','好的 developer experience 意味着清晰的文档快速的入门和 API 中有帮助的错误消息。',2,['engineering','dx']],
['dark launch','暗发布','silent release','Launch / GTM / Customer Success','launch','test silently','We did a dark launch of the new model behind a feature flag and monitored quality for two weeks before the public announcement.','我们在 feature flag 后面做了 dark launch 新模型在公告前监控了两周的质量。',3,['launch','strategy']],
['self-serve onboarding','自助接入','DIY setup','Launch / GTM / Customer Success','launch','reduce friction','Self-serve onboarding lets users sign up and run their first query without talking to a salesperson.','self-serve onboarding 让用户无需与销售人员交流即可注册并运行第一次查询。',2,['launch','ux']],
['waitlist','等候名单','pre-registration','Launch / GTM / Customer Success','launch','control demand','We opened a waitlist to gauge demand before scaling up the inference infrastructure.','我们在扩展推理基础设施之前开放了 waitlist 以评估需求。',1,['launch','strategy']],
];

// Execute
for(const t of terms)add(t[0],t[1],t[2],t[3],t[4],t[5],t[6],t[7],t[8],t[9],t[10],t[11]);
const updated=data.concat(newItems);
fs.writeFileSync(file,JSON.stringify(updated));
console.log('AI PM: Added',added,'| Skipped:',skipped,'| Total:',updated.length);
if(updated.length>=TARGET)console.log('TARGET REACHED');else console.log('Need',TARGET-updated.length,'more');
